### ISSUE TITLE
Docs: appendix B example 9 fails deployment...missing servicePort

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-appsvcs-extension#10]
##### ISSUE TYPE
Documentation Report

##### AS3 BUILD/ VERSION
f5-appsvcs-3.1.0-4.noarch.rpm

##### BIGIP VERSION
13.1.0.7

##### SUMMARY
Example 9 declaration in appendix B is missing servicePort for gce_pool. As a result, the POST fails.

##### STEPS TO REPRODUCE
Run example 9 as is. It will fail.

##### EXPECTED RESULTS
Push example 9 declaration successfully

##### ACTUAL RESULTS
error in API response stating that servicePort is missing

Workaround
--snippet--
             "gce_pool": {
                 "class": "Pool",
                 "monitors": [
                     "http"
                 ],
                 "members": [
                     {
                         "servicePort": 80, <<<<<<<< add this line
                         "serverAddresses": [
                             "192.0.7.10",
                             "192.0.7.11"
                         ]
                     }

**Comment by JosephPJordan** [comment]
Thanks Jeff, closing this one as it has been updated in the docs with 3.2.0
