### ISSUE TITLE
Make latest schema version predictable and provide an accessible schema history

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-appsvcs-extension#100]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Feature Idea
 - Documentation Report

##### AS3 BUILD/ VERSION
```
any
```

##### BIGIP VERSION
```
any
```

##### SUMMARY
This is a feature / documentation idea for the organisation of this Github repository. Currently every new release renders previous links to the "latest" JSON schema invalid. Releases can be used to access any previous version so can commit ids, however this is not user friendly and doesn't help with future releases.
###### The problem
A good example: [clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html#to-validate-a-declaration
](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html#to-validate-a-declaration
) explains how the schema can be validated in VS Code. Here is the example code:
```json
{    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema-3.9.0-3.json",
```
At the time of opening this issue the latest version is 3.11 making the above link invalid. The current valid link is `https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema-3.11.0-3.json` which will be rendered invalid with the release of version 3.12 as `latest/as3-schema-3.11.0-3.json` is going to change to something like `latest/as3-schema-3.12.0-XYZ.json`.

A user would not either need to download the release zip/tar.gz file and extract the schema or search for the correct commit and reference it like so:
```json
{    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/99564f748886eeaf7dd2209039f1e82afa2fccfb/schema/latest/as3-schema-3.9.0-3.json"
```

This is not user friendly and probably not obvious to most users.

###### My (Feature/Documenation) request
1. Provide a permanently working `latest` schema link
2. Provide a permanently working schema links to any released version ("don't rewrite history")

###### Idea
There are many ways to organise Github repositories, here are two I think could work.

###### Using branches for versioning
Basically use branches for any AS3 version created. Always make sure a branch is available for any version released, at the same time the master branch equals to latest.
For version 3.11 the master branch and 3.11 branch would essentially be the same.
This would allow the following links to work:
```json
{  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/3.9.0/schema/as3-schema.json",
```
```json
{  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/3.11.0/schema/as3-schema.json",
```
```json
{  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/as3-schema.json",
```
Where the last two would return the same `as3-schema.json` as long as no new version is released.

Additionally a 'latest-lts' branch could be provided.

###### Provide all schemas in the master branch
As some users will not be familiar with git branches it might be easier to provide the full history in the master branch. The Repository already has subdirectories in the schema directory but currently this is only used to permanently provide the lts version (3.5.1).

Here would be a possible layout (example omits many earlier version for better readability):
```
f5-appsvcs-extension/schema/
                            latest
                            latest-lts
                            3.5.1 (same as latest-lts)
                            ...
                            3.9.0
                            3.10.0
                            3.11.0 (same as latest)
```
Obviously the directory contents must be predictable for future releases, so using the version in the `as3-schema.json` file name would not work.

This would allow a user to reference a specific version as well as always try to test declarations against latest + latest-lts.

##### STEPS TO REPRODUCE
Use the example from: [clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html#to-validate-a-declaration
](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html#to-validate-a-declaration
) 

##### EXPECTED RESULTS
```
predictable and avilable schema links (via raw.githubusercontent.com) for direct reference in VS Code and elsewhere.
```

##### ACTUAL RESULTS
```
schema links (via raw.githubusercontent.com) neither are reliable nor predictable.
```

**Comment by focrensh** [comment]
Tracked internally with AT-227

**Comment by simonkowallik** [comment]
Predictable json schema locations have been added to the repository starting with v3.12. closing issue
