### ISSUE TITLE
RFE: MRF Support

### ISSUE THREAD

**Issue by rduchez** [F5Networks/f5-appsvcs-extension#101]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### AS3 BUILD/ VERSION

```

```

##### BIGIP VERSION

```

```

##### SUMMARY

```

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by rduchez** [comment]
Please include a way to configure Message Routing Framework services via AS3.  These should include SIP, DIAMETER, and the Generic router profiles.  
This is mostly used by SP and related customers.  

I am most interested in the Generic Router functionality - 

Thank you -

romain

**Comment by focrensh** [comment]
AT-251 for tracking

**Comment by trinaths** [comment]
This option "MRF" is mandatory when we configure HTTP/2 profile for VS. 

From the docs, https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/big-ip-http2-full-proxy-configuration-14-1-0/01.html#concept-5982 

"Important: When you create the virtual server, make sure that you enable the HTTP MRF Router option. This is necessary for successful HTTP/2 full-proxy deployment."

**Comment by dstokesf5** [comment]
@trinaths That MRF option appears to be different than the message routing framework configuration requested in this ticket. Can you please create a new ticket to track your request?

**Comment by trinaths** [comment]
@dstokesf5 - Sure.

**Comment by dstokesf5** [comment]
We have decided to close this issue as out of scope for AS3. We do not have the resources at this time to address something that is, at best, only partially supported in iControl REST: https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-service-provider-generic-message-administration-13-1-0/1.html
