### ISSUE TITLE
AS3 does not support none persistence methods 

### ISSUE THREAD

**Issue by amsinha2** [F5Networks/f5-appsvcs-extension#107]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
3.11.0
```

##### BIGIP VERSION

```
13.1.0.2
```

##### SUMMARY

```
AS3 should not force persistence on Virtual Servers by removing a "none" option
```

##### STEPS TO REPRODUCE

```
[
    {
        "path": "/PartitionA/AppName/serviceMain/persistenceMethods",
        "op": "add",
        "value":[ 
				"none"
                ]}]
```

##### EXPECTED RESULTS

```
ltm virtual PartitionA/AppName/serviceMain {
 
 persist none
}


```

##### ACTUAL RESULTS

```
{
    "code": 422,
    "errors": [
        "/PartitionA/AppName/serviceMain/persistenceMethods/0: should be equal to one of the allowed values [\"cookie\",\"destination-address\",\"msrdp\",\"source-address\",\"tls-session-id\"]"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}

ltm virtual PartitionA/AppName/serviceMain {
    persist {
        Common/source_addr {
            default yes
        }
    }
}
```

**Comment by focrensh** [comment]
You should be able to use an empty array to accomplish this.

`"persistenceMethods":[]`
