### ISSUE TITLE
Feature request: Virtual Server Types

### ISSUE THREAD

**Issue by paulpaulini** [F5Networks/f5-appsvcs-extension#111]
##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
any

##### BIGIP VERSION
any

##### SUMMARY

Implement the possibility to deploy virtual Server Types
for example:
- L2-Forwarding
- L3 Forwarding
- etc

Expected result would be to get all properties set, as if you would use to GUI to deploy fi a layer2-forwarding server

**Comment by focrensh** [comment]
AS3 provides a layer of abstraction and is use-case based more than feature parity based. Are the configurations looking to be implemented something that would be managed as part of a service/app lifecycle or would they be more of a "set and forget"(global) config?

**Comment by paulpaulini** [comment]
In this case it would be to deploy a global config.
I think there should be the possibility to kinda have AS3 have the same feature set as the GUI.

At the moment theres no "easy" way to configure a L2 or L3 forwarind server as there isin the GUI

**Comment by mikeoleary** [comment]
+1 for this request. 
In my case I would like an AS3 declaration to create a Virtual Server of type "Forwarding (L3)", which will listen on 0.0.0.0/0 and forward IP traffic. It will act as a default GW for other instances to route through.

**Comment by focrensh** [comment]
AT-409 tracking internally.

**Comment by sorinboia** [comment]
Any update when we will have this available?

**Comment by dstokesf5** [comment]
It will likely be some time before we will be able to get around to this request. Could you make use of the include property to at least partially satisfy your use case?

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#using-the-include-property-to-reference-one-section-of-a-declaration-in-another-section

**Comment by sorinboia** [comment]
This did the Job
"Default_External_Route": {
    "class": "Application",
    "template": "l4",
    "serviceMain": {
        "class": "Service_L4",
        "layer4": "any",
        "virtualAddresses": [
           "0.0.0.0/0"
        ],
        "virtualPort": 0
    }
},

**Comment by grf5** [comment]
I believe there are use cases for a forwarding VS as the previous workaround uses a FastL4 VS, which is not ideal in every situation.

**Comment by dstokesf5** [comment]
This was resolved by release 3.18.0.
