### ISSUE TITLE
Feature Request: Allow WAF policies to reference existing parent policies

### ISSUE THREAD

**Issue by btully** [F5Networks/f5-appsvcs-extension#113]
Provide the ability for application configurations to reference parent ASM policies during deployment.  For example:

      "My_ASM_Policy": {
        "class": "WAF_Policy",
        "url": "https://example.com/asm-policy.xml",
        "ignoreChanges": true,
        **"parent" : {
        	"bigip": "/Common/baseline-policy"
        }**

**Comment by focrensh** [comment]
This is being considered for WAF Policy composition (not date currently) but not for the current implementation of referencing an XML policy.
