### ISSUE TITLE
Node prefixes as partition name being applied multiple times for node id

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#125]
##### ISSUE TYPE
 - Bug Report
 
##### AS3 BUILD/ VERSION
AS3 version 3.13 

##### BIGIP VERSION
BigIP v 13.1.1.3 

##### SUMMARY
We send a list of nodes to the service discovery endpoint of the type {"id": "10.10.10.10", "ip": "10.10.10.10"} to keep id and ip same. 
Now next time we read the node list from the endpoint it is of the form {"id" "/demopartition/10.10.10.10", "ip": "10.10.10.10"} so now if we send the list of nodes we just read ..
then service discovery again pre-pends it with partition name and the node entry becomes {"id" "/demopartition//demopartition/10.10.10.10", "ip": "10.10.10.10"}

This happens in the update path: Where we first read the list of nodes from the service discovery endpoint by doing GET on https://<BigIP Hostname>/mgmt/shared/service-discovery/task/~Part_Wed_1~App_Wed_1~web_pool/nodes for example, 
and then use that list and append a new node ip/id at the end of the list and POST again to the same endpoint

##### EXPECTED RESULTS
The node prefix should not be present in above case. 

##### ACTUAL RESULTS
The node id prefix is added every time in the id.

**Comment by dstokesf5** [comment]
In 3.14, the prefix will not be added if it already exists on the node ID. This should at least solve the issue of the prefix being added again when using the nodes from a GET request.

An issue for improving the results of a GET request to /node endpoints has been created internally as 621.

**Comment by dstokesf5** [comment]
The duplicate node prefixes were resolved in 3.14. Closing.
