### ISSUE TITLE
Consul Service Discovery needs more documentation

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#130]
##### ISSUE TYPE

 - Documentation Report

##### DESIRED RESULTS
All declaration examples in clouddocs refer to only a "/nodes" endpoint for consul, which is a really strange way to grab everything consul knows about and add it into a pool. What isnt documented is that you can pull the "/service/{name of service}" which is actually a logical grouping someone would use.

The documentation should highlight the available options

```
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html
```

**Comment by dstokesf5** [comment]
At the moment we do not recommend users to use Consul's service API because the "servicePort" property from that API is ignored by AS3's service discovery (see #117). We have an item in our backlog to improve support for Consul's service API, and I have added a comment there about making sure this documentation is added when we do that. Thank you for your feedback.

**Comment by jmcalalang** [comment]
is that needed though? only if you had different ports on the nodes across the pool member, otherwise you specify the ports in the pool class and it works.

is there a different method to no pull in literally every node in consul to a pool? like tag/label support?

**Comment by dstokesf5** [comment]
I was misunderstanding your use case. I agree now that we should document this use case, and it does not require the using the servicePort property. I have added this to our internal backlog as AT-692.

**Comment by aknot242** [comment]
Just watched the HashiCorp + F5 joint webinar wherein Consul was used with AS3 for service discovery. It would be nice if the documentation is updated soon, as this may cause confusion about Consul support.

**Comment by dstokesf5** [comment]
Documentation has been added for using the Consul service API: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#service-discovery-using-hashicorp-consul-for-a-specific-service

Closing this issue.
