### ISSUE TITLE
RFE: no log Policy action

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#131]
##### Do you already have an issue opened with F5 support?
NO
##### ISSUE TYPE
 - Feature Idea
##### AS3 BUILD/ VERSION
```
3.13.1
```

##### BIGIP VERSION
NA

##### SUMMARY

According to the documentation and https://github.com/F5Networks/f5-appsvcs-extension/blob/master/schema/3.13.1/as3-schema-3.13.1-1.json  there is no policy action to log a message which is a LTM policy feature

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal backlog as AT-693.

**Comment by dstokesf5** [comment]
This is resolved in the 3.34.0 release that is now available.
