### ISSUE TITLE
[DOC] tls-encryption.html#enabling-and-disabling-server-ssl-from-endpoint-policies

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#132]
##### Do you already have an issue opened with F5 support?
NA

##### ISSUE TYPE

 - Documentation Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.12.0-5.noarch
```

##### BIGIP VERSION
NA

##### SUMMARY

The link [tls-encryption.html#enabling-and-disabling-server-ssl-from-endpoint-policies](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#enabling-and-disabling-server-ssl-from-endpoint-policies) indicates the use of serverSsl when it really means the backend communication which in AS3 terms it is clientSsl. Moreover the option even doesn't exist. See next:

```
2019/08/23 10:57:39 [ERROR] - declaration.rules.1.actions.1.type: declaration.rules.1.actions.1.type must be one of the following: "http", "httpCookie", "httpHeader", "httpRedirect", "httpUri", "waf", "forward", "drop", "clientSsl"

```

##### STEPS TO REPRODUCE
configure a rule with this attribute

**Comment by dstokesf5** [comment]
The documentation was updated as part of the 3.14 release: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#enabling-and-disabling-clientssl-server-ssl-profile-from-endpoint-policies

Thank you for pointing this out.
