### ISSUE TITLE
Please add support for more attributes like "Description" to service discovery nodes

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#133]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
3.13

##### BIGIP VERSION
13.1.1.3

##### SUMMARY
Please add support for more attributes like "Description" to service discovery nodes.

##### STEPS TO REPRODUCE
When the nodes are added to BigIP using service discovery, it doesnt allow user to set "description" field for those nodes when they are created. Allowing such fields will enable different App users to add details to these nodes.

**Comment by dstokesf5** [comment]
Can you elaborate on the use cases you are trying to improve or enable with this feature request?

**Comment by dstokesf5** [comment]
Use case from out of band discussion:
>If the nodes which are dynamically learnt and added to bigIP - by this app - could be added with some description , users will have some data to differentiate between static and dynamic nodes and will be careful while changing config directly on BigIP.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter
