### ISSUE TITLE
When using bigip: /common/irulename within the iRule class, AS3 should not try to create the irule but use the reference.

### ISSUE THREAD

**Issue by johneudy** [F5Networks/f5-appsvcs-extension#135]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
3.12.1
```

##### BIGIP VERSION

```
13.1.1.2
```

##### SUMMARY

```
When using bigip: /common/irulename within the iRule class, AS3 attempts to create a new iRule instead of using the reference
```

##### STEPS TO REPRODUCE

```
{
    "class": "ADC",
    "schemaVersion": "3.12.0",
    "as3": {
        "class": "Tenant",
        "app1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "virtualPort": 80,
                "profileAnalytics": {
                    "use": "/as3/app1/Analytics_Profile"
                },
                "profileHTTP": {
                    "use": "/as3/app1/HTTP_Profile"
                },
                "virtualAddresses": [
                    "10.1.10.10"
                ],
                "pool": "/as3/app1/Pool",
                "enable": true,
                "iRules": [
                    "/as3/app1/log_http_request"
                ],
                "class": "Service_HTTP"
            },
            "Analytics_Profile": {
                "collectUserAgent": false,
                "collectClientSideStatistics": true,
                "collectGeo": false,
                "collectUrl": false,
                "collectPageLoadTime": false,
                "collectOsAndBrowser": false,
                "collectMethod": false,
                "collectResponseCode": true,
                "collectIp": false,
                "class": "Analytics_Profile"
            },
            "HTTP_Profile": {
                "fallbackRedirect": "https://www.example.com/404",
                "fallbackStatusCodes": [
                    404
                ],
                "class": "HTTP_Profile"
            },
            "Pool": {
                "members": [
                    {
                        "servicePort": 80,
                        "adminState": "enable",
                        "serverAddresses": [
                            "192.168.128.10"
                        ],
                        "monitors": [
                            "http"
                        ],
                        "shareNodes": true
                    }
                ],
                "class": "Pool",
                "monitors": [
                    "http"
                ]
            },
            "log_http_request": {
                "iRule": {
                    "bigip": "/Common/log_http_request"
                },
                "class": "iRule"
            }
        }
    },
    "id": "wOejBwmB-nCLA-nxLx-VoeC-JZdXeYhqTumH",
    "updateMode": "selective"
}
```

##### EXPECTED RESULTS

```
AS3 should have used the reference to the existing iRule on the BIG-IP
```

##### ACTUAL RESULTS

```
Failed to send declaration: status:422, body:{"results":[{"message":"declaration failed","response":"01020066:3: The requested iRule (/Common/log_http_request) already exists in partition Common.","code":422,"host":"localhost","tenant":"as3","runTime":902}],"declaration":{"class":"ADC","schemaVersion":"3.12.0","id":"wOejBwmB-nCLA-nxLx-VoeC-JZdXeYhqTumH","updateMode":"selective","controls":{"archiveTimestamp":"2019-08-29T14:43:09.249Z"}},"code":422}
```

**Comment by dstokesf5** [comment]
Instead of using an `iRule` object in AS3, you want to reference the iRule directly from your Service_HTTP object.

In other words, instead of this:
```json
                "iRules": [
                    "/as3/app1/log_http_request"
                ],
```

Try this:
```json
                "iRules": [
                    { "bigip": "/Common/log_http_request" }
                ],
```

And then get rid of `log_http_request` object in your declaration.

**Comment by xags** [comment]
I would like to reopen this. It should be possible to reference in existing iRule in the iRule class rather than attempt to create it.  Issue is still present in 3.16.0.

**Comment by dstokesf5** [comment]
Why do you need to reference an existing iRule in the iRule class instead of referencing the existing iRule directly in the Service_HTTP class?

**Comment by xags** [comment]
I am using a schema overlay (with a template created on BIQ) that only allows the use of the iRule class (the default and only option it appears?). The template expects a reference to the class, inputting an iRule from /Common/ fails with: "status: 422: /declare failed with status of 422, declaration is invalid /tenant_name/appname/serviceMain/iRules/0: contains invalid path (Tenant without application)"

**Comment by dstokesf5** [comment]
The supported way to reference an iRule that is already on the BIG-IP is as I described above. It sounds like this is a problem with BIG-IQ not allowing the supported method. Allowing the iRule class to reference iRules on the BIG-IP would make for some inconsistencies in the the API just to allow an extra layer of indirection.

**Comment by xags** [comment]
Very possible (and likely). Should the BIG-IQ not follow the updated schema that new versions of AS3 use? Meaning I would expect that if I upgrade AS3 (I have) on the BIG-IQ, I would expect any new template I create (manually for example) on the BIG-IQ to have any and all options available to it--this of course assumes that BIG-IQ dynamically creates the GUI from the schema...  If not, is it appropriate to file a bug like this on GitHub for something that is related to BIG-IQ?

**Comment by dstokesf5** [comment]
While the BIG-IQ GUI is dynamically created from the schema, the complexity of the AS3 schema has caused the GUI generation some problems. It sounds like this is a bug in that GUI generation code. This GitHub is for AS3 issues, and not BIG-IQ issues. I recommend going through the usual channels for BIG-IQ support.

**Comment by xags** [comment]
OK. It actually looks like the problem is with the built-in templates in BIG-IQ (https://github.com/f5devcentral/f5-big-iq) and using them as an overlay. The templates define the allowed value, string,array,etc. These don't appear being kept up to date or correct in some cases...

**Comment by rjouhann** [comment]
The templates are fine. We have known limitation with the 7.0 release regarding AS3 UI template. Please see [BIG-IQ 7.1 RN 808697](https://techdocs.f5.com/kb/en-us/products/big-iq-centralized-mgmt/releasenotes/related/relnote-supplement-big-iq-central-mgmt-7-0-0.html#A808697).
We are fixing this particular limitation in the next BIG-IQ release 7.1.
Regarding issue on BIG-IQ, like Daniel mentioned, I recommend going through the usual channels for [BIG-IQ support](https://www.f5.com/services/support).
