### ISSUE TITLE
When AS3 declaration used in CloudInit "config verify file /config/bigip.conf" fails

### ISSUE THREAD

**Issue by zhurvla** [F5Networks/f5-appsvcs-extension#138]
install rpms via BIG-IP GUI https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/installation.html

cat /var/tmp/123.json
{"remark": "CLOUDINIT_VS1", "schemaVersion": "3.0.0", "label": "CLOUDINIT_VS1", "class": "ADC", "cloudinit_01": {"HTTP_Service": {"class": "Application", "template": "http", "serviceMain": {"class": "Service_HTTP", "virtualAddresses": ["192.168.80.51"]}}, "class": "Tenant"}}

curl -u admin: -sk --retry 20 -m 10 -X POST -d @/var/tmp/123.json https://localhost:8443/mgmt/shared/appsvcs/declare | jq .

[admin@localhost:Active:Standalone] ~ # tmsh load sys config verify file /config/bigip.conf
Validating system configuration...
  /defaults/asm_base.conf
  /defaults/config_base.conf
  /defaults/ipfix_ie_base.conf
  /defaults/ipfix_ie_f5base.conf
  /defaults/low_profile_base.conf
  /defaults/low_security_base.conf
  /defaults/policy_base.conf
  /defaults/wam_base.conf
  /defaults/analytics_base.conf
  /defaults/apm_base.conf
  /defaults/apm_oauth_base.conf
  /defaults/apm_saml_base.conf
  /defaults/app_template_base.conf
  /defaults/classification_base.conf
  /var/libdata/dpi/conf/classification_update.conf
  /defaults/ips_base.conf
  /var/libdata/ips/ips_update.conf
  /defaults/daemon.conf
  /defaults/pem_base.conf
  /defaults/profile_base.conf
  /defaults/sandbox_base.conf
  /defaults/security_base.conf
  /defaults/urldb_base.conf
  /usr/share/monitors/base_monitors.conf
  /defaults/cipher.conf
  /defaults/ilx_base.conf
  /usr/local/gtm/include/gtm_base_region_isp.conf
  /usr/share/monitors/gtm_base_monitors.conf
Validating configuration...
  /config/bigip.conf
01070734:3: Configuration error: Can't associate value list (/Common/appsvcs/dataStore) folder does not exist

 - "https://github.com/F5Networks/f5-appsvcs-extension/raw/master/dist/lts/3.13.1/f5-appsvcs-3.13.1-1.noarch.rpm"

**Comment by dstokesf5** [comment]
This is being tracked in the internal product backlog as AT-658.

**Comment by dstokesf5** [comment]
It looks like tmsh is saving the folders from the running configuration into bigip_base.conf, and some of the items in those folders in bigip.conf. If I run the command `tmsh load sys config verify` to load and verify all files at once, I do not get an error.

This looks like an issue with tmsh, and not AS3. I am closing this issue. Feel free to reopen it or file a new issue if you believe this is incorrect or you are still experiencing an issue.
