### ISSUE TITLE
Known Issue: Browser access blocked by blank screen with gray bar

### ISSUE THREAD

**Issue by JosephPJordan** [F5Networks/f5-appsvcs-extension#14]
##### ISSUE TYPE

 - Known Issue

##### AS3 BUILD/ VERSION

```
All versions
```

##### BIGIP VERSION

```
All supported versions
```

##### SUMMARY

After using the DELETE method to remove an AS3 configuration, you are unable to access the BIG-IP configuration utility. In your browser window, you see only a gray screen with a dark gray bar.

##### WORKAROUND
Use one of the following workarounds:

 1) Return to your API client and re-deploy the tenant that was previously configured. This should unlock the web interface.
2) Login to the BIG-IP CLI shell and restart the tomcat daemon by typing ```bigstart restart tomcat```.

**Comment by m-kratochvil** [comment]
We're running into this quite often, it looks like it's not affecting just AS3 but also lbaasv2 configurations.
As this issue was created over a year ago, I wonder if there are any plans for a fix..
