### ISSUE TITLE
Getting 422 error with service discovery with 3.13.1

### ISSUE THREAD

**Issue by scshitole** [F5Networks/f5-appsvcs-extension#143]
##### ISSUE TYPE

 - Bug Report
 
When we try to POST the service discovery JSON we get 422 error

![image](https://user-images.githubusercontent.com/13858248/64358379-3960f400-cfbb-11e9-982f-02618884f5f6.png)

![image](https://user-images.githubusercontent.com/13858248/64358422-4c73c400-cfbb-11e9-9a45-45ef7f82df5b.png)

##### AS3 BUILD/ VERSION

```

```

##### BIGIP VERSION

```

```

##### SUMMARY
When we initiate a POST with the above JSON we get 422 error, the same JSON works fine for RPM 3.7 as3 image
```

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by dstokesf5** [comment]
I believe you are seeing that error because the updateInterval property is set too low. Try using a value of 10. I suspect at some point the limits specified in AS3's schema and the limits in the system that AS3 uses for service discovery diverged.

**Comment by dstokesf5** [comment]
It looks like this was resolved in 3.16.0, closing this issue. If you are still experiencing a problem, please reopen this issue or create a new one.
