### ISSUE TITLE
Notification/Response of AS3 change to take place on destination BIG-IP

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#147]
##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
```
NA
```

##### BIGIP VERSION
```
All TMOS versions that are supported by AS3
```

##### SUMMARY
```
Customer request to see the changes that will be posted to the destination BIG-IP after the parser/audit engine runs. This would allow logging from pipelines and endpoint testing to pass after a validation. This could be done in the "dry-run" option as it's primarily for testing.

Deeper logic like this can be thought of in a Terraform example. We want to place configuration and know that the configuration is actually on the destination, AS3 accepts the declaration processes thru the parser/auditor and hands back a success/process and then an example of the declaration done. Having a response of the deltas would provide endpoints that can then be checked around AS3 on the destination for validity. 
```
##### ENGINEERS FOLLOWING
@aknot242, @mjmenger, @yossi-r

**Comment by markchart** [comment]
Try `"action": "dry-run"` plus `"trace": "true"` (in the `"class": "AS3"` object) then inspect the trace files left in `/tmp/myTenant_*` such as `/tmp/myTenant_script.cli`.  You can also trace while deploying.

Note, however, that "checking the deltas for validity" would require you to re-implement AS3's logic, which seems like a lot of work for little benefit.  The main reason to use AS3 is to get away from making (or "checking") a long list of tiny changes which must be presented in a particular order to work.

**Comment by dstokesf5** [comment]
As @markchart mentioned, you could enable trace files and then inspect those files on the BIG-IP. I have added AT-752 to our internal product backlog to look into adding those trace files to the body of the HTTP response.

**Comment by dstokesf5** [comment]
In AS3 v3.18.0, you can now use the traceResponse control property to include the AS3 trace files in the response: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html?highlight=traceresponse#using-traceresponse-to-enable-traces-in-as3-responses
