### ISSUE TITLE
Event-Driven SD: does not perform save sys config (write to disk)

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-extension#152]
##### ISSUE TYPE

 - Bug Report
 

##### AS3 BUILD/ VERSION

```
{"version":"3.14.0","release":"4","schemaCurrent":"3.14.0","schemaMinimum":"3.0.0"}
{
  "release": "4",
  "schemaCurrent": "3.14.0",
  "schemaMinimum": "3.0.0",
  "version": "3.14.0"
}
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Thu Oct 11 15:32:21 PDT 2018
```

##### SUMMARY

event-driven SD does not do a "sys sys config" to write the change to disk.

##### STEPS TO REPRODUCE

Declaration 1

```
{
    "schemaVersion": "3.9.0",
    "class": "ADC",
    "Tenant": {
        "class": "Tenant",
        "Application": {
            "class": "Application",
            "template": "generic",
            "pool": {
                "class": "Pool",
                "monitors": ["http"],
                "members": [
                    {
                        "addressDiscovery": "event",
                        "servicePort": 80
                    }
                ]
            }
        }
    }
}
```
Update to SD task
```
[
    {
        "id": "newNode1",
        "ip": "192.0.2.3"
    },
    {
        "id": "NewNode2",
        "ip": "192.0.2.4"
    }
]
```
TMSH output
```
ltm pool Application/pool {
    members {
        NewNode2:80 {
            address 192.0.2.4
            session monitor-enabled
            state down
        }
        newNode1:80 {
            address 192.0.2.3
            session monitor-enabled
            state down
        }
    }
    min-active-members 1
    monitor min 1 of { /Common/http }
    partition Tenant
}
```
Contents of bigip.conf
```
# cat /config/partitions/Tenant/bigip.conf
#TMSH-VERSION: 13.1.1.2

ltm pool /Tenant/Application/pool {
    min-active-members 1
    monitor min 1 of { /Common/http }
}
```

##### EXPECTED RESULTS

pool member saved to disk (or have an option to specify)

##### ACTUAL RESULTS

not written to disk

**Comment by walterk82** [comment]
Have you tried forcing ` "persist": true,` ?

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have created internal product backlog item AUTOTOOL-970 to track this issue.

**Comment by dstokesf5** [comment]
Do you think that persisting to disk on an interval (e.g. every 5 minutes) would be sufficient? I am worried that persisting on any event driven update could have an impact on performance.

**Comment by chen23** [comment]
that gets a little bit confusing. What do the other SD mechanisms do?  Having an additional parameter to specify the interval when creating the event SD pool member would be one possibility to introduce it without “breaking” existing behavior. Some might consider the current implementation a “feature”.

**Comment by dstokesf5** [comment]
The other SD mechanisms will just rediscover the nodes, so they do not really need to persist the nodes. Similarly, if a user was frequently posting to the event driven nodes, they would not really need persistence either. I think a persistInterval setting on event driven service discovery would make sense.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
