### ISSUE TITLE
Double quoting of variable values with spaces when ?show=expanded

### ISSUE THREAD

**Issue by writemike** [F5Networks/f5-appsvcs-extension#154]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

No F5 support issue was filed as workaround exists.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.12.0-5.noarch
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.3
  Build       0.0.1
  Edition     Point Release 3
  Date        Wed Nov 28 18:50:45 PST 2018
```

##### SUMMARY

We are using Ansible to deploy AS3 declaration updates for BIG-IP Applications. We are first collecting the current AS3 JSON declaration using a GET request with the ?show=expanded option and saving the output. In the event of failure anywhere else in the Ansible Playbook, the AS3 configuration is rolled back to the previous declaration using the AS3 JSON declaration collected at the beginning of the playbook. When rollback occurs, the previous AS3 JSON declaration version contains additional double quotes around values which contain spaces, even when they already are double quoted.

##### STEPS TO REPRODUCE

POST the following declaration, paying attention to the securityLogProfile name

```
{
	"class": "AS3",
	"declaration": {
		"class": "ADC",
		"schemaVersion": "3.10.0",
		"remark": "HTTP with existing log profile",
		"Sample_http_01": {
			"class": "Tenant",
			"A1": {
				"class": "Application",
				"template": "http",
				"serviceMain": {
					"class": "Service_HTTP",
					"virtualAddresses": [
						"10.0.6.10"
					],
					"securityLogProfiles": [{
						"bigip": "/Common/Log all requests"
					}]
				}
			}
		}
	}
}
```

##### EXPECTED RESULTS

Now do a GET request on the new partition with ?show=expanded and see how the securityLogProfile name has changed.

```
{
    "class": "ADC",
    "schemaVersion": "3.10.0",
    "remark": "HTTP with existing log profile",
    "Sample_http_01": {
        "class": "Tenant",
        "A1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "10.0.6.10"
                ],
                "securityLogProfiles": [
                    {
                        "bigip": "/Common/Log all requests"
                    }
                ],
                "virtualPort": 80,
                "persistenceMethods": [
                    "cookie"
                ],
                "profileHTTP": "basic",
                "layer4": "tcp",
                "profileTCP": "normal",
                "enable": true,
                "maxConnections": 0,
                "snat": "auto",
                "addressStatus": true,
                "mirroring": "none",
                "lastHop": "default",
                "translateClientPort": false,
                "translateServerAddress": true,
                "translateServerPort": true
            },
            "enable": true
        },
        "enable": true,
        "defaultRouteDomain": 0,
        "optimisticLockKey": ""
    },
    "id": "autogen_05cbdeb6-7b68-48b8-8e15-74651981c9e4",
    "updateMode": "selective",
    "controls": {
        "archiveTimestamp": "2019-09-27T01:55:56.301Z",
        "class": "Controls",
        "logLevel": "error",
        "trace": false
    }
}
```

##### ACTUAL RESULTS

See how the securityLogProfile name has changed. This declaration is now not usable.

```
{
    "class": "ADC",
    "schemaVersion": "3.10.0",
    "remark": "HTTP with existing log profile",
    "Sample_http_01": {
        "class": "Tenant",
        "A1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "10.0.6.10"
                ],
                "securityLogProfiles": [
                    {
                        "bigip": "\"/Common/Log all requests\""
                    }
                ],
                "virtualPort": 80,
                "persistenceMethods": [
                    "cookie"
                ],
                "profileHTTP": "basic",
                "layer4": "tcp",
                "profileTCP": "normal",
                "enable": true,
                "maxConnections": 0,
                "snat": "auto",
                "addressStatus": true,
                "mirroring": "none",
                "lastHop": "default",
                "translateClientPort": false,
                "translateServerAddress": true,
                "translateServerPort": true
            },
            "enable": true
        },
        "enable": true,
        "defaultRouteDomain": 0,
        "optimisticLockKey": ""
    },
    "id": "autogen_05cbdeb6-7b68-48b8-8e15-74651981c9e4",
    "updateMode": "selective",
    "controls": {
        "archiveTimestamp": "2019-09-27T01:55:56.301Z",
        "class": "Controls",
        "logLevel": "error",
        "trace": false
    }
}
```
##### Workaround
Feed the collected AS3 JSON declaration through the jinja2 
```
|regex_replace('\"')
``` 
filter to remove all the extra escaped quotes.

**Comment by markchart** [comment]
I think you have discovered a real bug which the F5 team ought to fix.

However, I also think you should _not_ fetch (and later resubmit) the *expanded* form of the declaration-- that is intended for analysis/debugging, _not_ for re-submittal.  Just fetch the normal form of the declaration, because some stuff that takes place during expansion really _should_ run right at the time a declaration is applied.

**Comment by dstokesf5** [comment]
Thank you for reporting this. While I agree with @markchart that you might not want to use the expanded declaration, it should still be a valid declaration. I have added this bug to our internal product backlog as AUTOTOOL-974.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
