### ISSUE TITLE
Add geoip condition for ltm policies

### ISSUE THREAD

**Issue by rs232p** [F5Networks/f5-appsvcs-extension#156]
**Do you already have an issue opened with F5 support?**
no

**ISSUE TYPE**
 - Feature Idea

**AS3 BUILD/ VERSION**
3.14.0

**BIGIP VERSION**
14.1.x

**SUMMARY**
Some features of LTM Policy features are not usable with AS3 (conditions):
TCP address/port for source ip matching (should work with datagroups)
Geo IP
This would help restricting access to specific resources

**Comment by dstokesf5** [comment]
Can you please provide some tmsh output of the desired configuration? That will really help us make sure we expose the right functionality for your use case.

**Comment by rs232p** [comment]
Hello Daniel,

Here are some examples from tmsh:

create ltm policy Drafts/testpolicy2 create-draft strategy first-match
rules add { testrule1 { conditions add { 0 { tcp address matches values  { "
1.1.1.1/32" } } } } }
create ltm policy Drafts/testpolicy3 create-draft strategy first-match
rules add { testrule1 { conditions add { 0 { tcp address matches datagroup
private_net } } }
create ltm policy Drafts/testpolicy4 create-draft strategy first-match
rules add { testrule1 { conditions add { 0 { geoip country-code equals
values  { AT } } } } }

Thanks and regards
Ronald

Am Do., 14. Nov. 2019 um 19:09 Uhr schrieb Daniel Stokes <
notifications@github.com>:

**Comment by dstokesf5** [comment]
Thank you, that helps a lot. I have created internal product backlog item AUTOOL-975 for this request.

**Comment by walterk82** [comment]
Is this duplicated by #211  ?

**Comment by dstokesf5** [comment]
Good catch, and thank you. These requests are certainly very similar. However, this one includes the geoip condition, while #211 is for the tcp condition. I will modify AUTOTOOL-975 to focus on geoip specifically.

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com

**Comment by sunitharonan** [comment]
This has been resolved in the 3.42.0 release of AS3.
