### ISSUE TITLE
file load from an external server fails when using self signed certificate

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-appsvcs-extension#170]
##### Do you already have an issue opened with F5 support?
No.

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION

f5-appsvcs-3.13.2-1.noarch
```
1
```

##### BIGIP VERSION

```
13.1.0.8
```

##### SUMMARY

```
My AS3 json file include a clause to load an irule from a github repository.
The github server is an internal one and the SSL certificate used is signed by a private CA.
We use ansible to send the AS3 declaration file to the f5 box.

```

##### STEPS TO REPRODUCE

create a simple declaration that include below code.
Host an irule on a private github using an internally signed certificate.

```
		"externalIrule": {
                    "class": "iRule",
                    "iRule": {
                        "url": "https://raw.git.private.net/master/F5/irule.tcl"
                    }
                },

```

##### EXPECTED RESULTS

```
I'm expecting the irule to be read from the github repo and loaded correctly.

```

##### ACTUAL RESULTS

Ansible fails and error are seen on the f5 box.

```
from  /var/log/restnoded/restnoded.log

Mon, 14 Oct 2019 11:58:11 GMT - severe: [appsvcs] {"message":"Unable to fetch value. GET https://raw.git.private.net/master/F5/irule.tcl for /xx/xx/externalIrule/iRule failed (self signed certificate in certificate chain)","level":"error"}
Mon, 14 Oct 2019 11:58:11 GMT - warning: [appsvcs] {"message":"unable to digest declaration. Error: Unable to fetch value. GET https://raw.git.private.net/master/F5/irule.tcl for /xx/xx/externalIrule/iRule failed (self signed certificate in certificate chain)","level":"warning"}

```

**Comment by tizianorosato-gr** [comment]
oh yes, I did that as a workaround

**Comment by dstokesf5** [comment]
You can add additional certificates to the restnoded process (the process that runs AS3) by modifying `/etc/bigstart/scripts/restnoded` to set the [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable for the node process. Below is an example of this.

```bash
#!/bin/sh

service=restnoded

# First argument passed to these scripts is the number of starts
start_cnt=$1

# load common functions and clear down indicators
. /usr/lib/bigstart/functions
clear_down ${service}
...
export NODE_PATH=/usr/lib/node_modules
export NODE_EXTRA_CA_CERTS=/config/ssl/ssl.crt/ca-bundle.crt
...
```

Alternatively, we have an internal product backlog item (AUTOTOOL-444) to disable certificate checking on certain URLs. That feature should be available in the 3.16 release.

**Comment by dstokesf5** [comment]
The ability to disable certificate checking on URL fetches has been added in version 3.16.0. Here is an example of how to use the feature: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#ignoring-validation-of-certificates-when-retrieving-uri-data

**Comment by m-kratochvil** [comment]
Hi @dstokesf5 I just found this issue as I'm running into exactly the same problem with irule fetched from GitHub. I don't want to open new issue just yet, hoping you'll have a chance to take a look and perhaps point out some simple mistake I'm making.

The `"skipCertificateCheck": true` is not working for me on AS3 version 3.36.1, the declaration fails due to schema validation error:
```
"{'code': 422, 'errors': ['/tenant_test/lb_test/irule_test/iRule: should NOT have more than 1 properties'], 'declarationFullId': '', 'message': 'declaration is invalid'}"}
```
The VSCode validator reports:
```
Object has more properties than limit of 1.
Property skipCertificateCheck is not allowed.
```
My declaration piece looks like this:
```
                "irule_test": {
                    "class": "iRule",
                    "label": "proxy protocol irule",
                    "iRule": {
                        "url": "https://github.redacted",
                        "skipCertificateCheck": true
                    }
                }
```

**Comment by RobCupples** [comment]
It looks like the skipCertificateCheck property is mislocated.  This section of the AS3 documentation provides an example that should help you.

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html?highlight=skipcertificatecheck#using-ignorechanges-on-resources-referenced-by-url

***@***.***<https://f5.com/>
 Rob Cupples  | Software Engineer III
 M +1 (425) 232-1791
