### ISSUE TITLE
Allow declaration of Availability Calculation in AS3

### ISSUE THREAD

**Issue by rgarcia89** [F5Networks/f5-appsvcs-extension#176]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
3.11.0
```

##### BIGIP VERSION

```
14.1.2.1
```

##### SUMMARY

```
Per AS3 declaration it is not possible currently to define the Availability Calculation of a Virtual Server Address. This however, is needed in case your declaration creates a class Service_HTTPS. When using this class AS3 creates two virtual servers. One listening on port 443 and the other on port 80. The port 80 virtual server uses an iRule for forwarding and stays in unknown health. Here comes the problem: When setting Availability Calculation to - When any virtual server(s) are available - the route continues to be advertised, even if the virtual server that listens on port 443 goes offline. Not sure if this is a bug. Anyway setting the Availability Calculation to - When all virtual server.... - solves the issue.
```

##### STEPS TO REPRODUCE

```
Create a service of class - Service_HTTPS - and advertise the routes selective
![image](https://user-images.githubusercontent.com/4134730/67261304-546ec100-f4a0-11e9-9ca0-fa7bf4a9e11f.png)
```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by dstokesf5** [comment]
Thank you for your input. I have created issue AT-858 in our internal product backlog for this feature request.

**Comment by rgarcia89** [comment]
@dstokesf5 where are we with this request? 
This case is causing really big trouble for us.

**Comment by rgarcia89** [comment]
@JosephPJordan can you maybe provide an update on that request?
I would appreciate it a lot

**Comment by RobCupples** [comment]
In order to use the Availability Calculation for Route Advertisement the value of Route Advertisement needs to be Selective or the deprecated value of Enabled according to the KB below.

https://support.f5.com/csp/article/K85543242

Does it work if you set Route Advertisement to All?  This setting is currently available in the AS3 Service_Address class.

**Comment by rgarcia89** [comment]
@RobCupples thats exactly what I needed. Many thanks. Really confusing to see that you can overwrite the availability calculation setting with that one... Looks like there are some settings double

**Comment by dstokesf5** [comment]
@rgarcia89 Can this issue be closed?
