### ISSUE TITLE
Class Pool Monitor not changeable after initial set

### ISSUE THREAD

**Issue by rgarcia89** [F5Networks/f5-appsvcs-extension#177]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
3.11.0
```

##### BIGIP VERSION

```
14.1.2.1
```

##### SUMMARY

```
Class Pool monitoring type cannot be changed afterwards. When deploying with http on initial changed for this parameter are not taking any effect.
```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by dstokesf5** [comment]
There is a bug in the BIG-IP GUI that shows the incorrect pool monitor after it is changed by AS3. Is the correct monitor listed when you check the pool via tmsh (`tmsh list ltm pool <insert pool name>`)?

**Comment by rgarcia89** [comment]
Good to know. Do you know when it will be fixed?

**Comment by dstokesf5** [comment]
I do not know when, or if, that BIG-IP bug will be fixed.

**Comment by dstokesf5** [comment]
Closing since this is not an AS3 bug.
