### ISSUE TITLE
Support for DataSafe

### ISSUE THREAD

**Issue by ab-gmbh** [F5Networks/f5-appsvcs-extension#182]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```

```

##### BIGIP VERSION

```

```

##### SUMMARY

It is confirmed that AS3 currently lacks support for DataSafe. The ask is to add DataSafe to AS3.

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by dstokesf5** [comment]
Can you please elaborate on the service you want AS3 to support and how you see that support looking?

**Comment by ab-gmbh** [comment]
The AS3 does not support attaching Anti-Fraud (DataSafe) Profile. This is part of AWAF and has its own profile outside of ASM. To create an anti-fraud profile, go to Security -> Data Protection -> BIG-IP Data Safe. Support for this feature would allow such a profile to be configured and attached.

**Comment by dstokesf5** [comment]
AS3 is able to attach anti-fraud profiles: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/application-security.html#using-an-anti-fraud-fps-profile-in-a-declaration

Is this different than the profiles you are trying to attach?

**Comment by dstokesf5** [comment]
@ab-gmbh can we close this issue?
