### ISSUE TITLE
Add iFiles support

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-appsvcs-extension#184]
##### Do you already have an issue opened with F5 support?
No.

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```
3.13.1 (LTS)
```

##### BIGIP VERSION

```
BIG-IP 13.1.1.4 Build 0.0.4 Point Release 4
```

##### SUMMARY

```
Currently, it seems that iFiles are not supported in AS3, or at least, I can't find any reference on CloudDocs (https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html).

iFiles Documentation
- https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-system-irules-concepts-11-6-0/7.html
- https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/ltm-implementations-11-6-0/29.html
- https://clouddocs.f5.com/cli/tmsh-reference/latest/modules/sys/sys-file-ifile.html

```

##### STEPS TO REPRODUCE

```
N/A
```

##### EXPECTED RESULTS

```
N/A
```

##### ACTUAL RESULTS

```
N/A
```

**Comment by dstokesf5** [comment]
I would like to better understand the use case you are trying to achieve here with iFile support. Are you looking for ways to add iFiles to the BIG-IP so you can use them with iRules? Is there anywhere else that you might be wanting to use iFiles?

**Comment by erjac77** [comment]
@dstokesf5 
Exactly. Our primary use case is to be able to add/download iFiles to the BIG-IP and use them in iRules.

**Comment by dstokesf5** [comment]
Added this feature request to our internal product backlog as AUTOTOOL-1054.

**Comment by tkam8** [comment]
any update on this? Want to host static maintenance pages (not fallbackredirect) and use them in an iRule. If there's a better way please advise.

**Comment by dstokesf5** [comment]
There are no updates on this request at this time. I have added the additional information on iFile profiles to the internal product backlog item.

**Comment by tizianorosato-gr** [comment]
I'm interested too on iFiles.
use case: use the ifiles via iRules

**Comment by Bob-VT** [comment]
any update on this feature request? I'm  also interested in iFile support.

**Comment by dstokesf5** [comment]
This feature request has been prioritized for the 3.29.0 release.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 3.29.0 release.

**Comment by walterk82** [comment]
We don't see a way to upload the iFile itself, only a way to reference an iFile object to be used in the iRule.  iFiles require a two-part configuration change.  What improvement did this feature accomplish?

**Comment by walterk82** [comment]
I think that I see the issue now, the schema docs at https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#ifile don't explain how to reference the content.  I had to read the change log: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/revision-history.html to find a link to how to use this option: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#ifile
