### ISSUE TITLE
AS3 Service Discovery : Constants update/delete not working

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#190]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report
 
##### AS3 BUILD/ VERSION
3.14
##### BIGIP VERSION
13.1
##### SUMMARY
As per the current AS3 behavior, AS3 does not consider constants update or delete as a change in declaration and hence does not process it. So,for now the workaround is to delete and recreate the AS3 application. 

Steps :
- Post Service discovery configuration 
- POST the AS3 configuration with only constants updated

**Comment by dstokesf5** [comment]
This is tracked in the internal product backlog as AUTOTOOL-715. It has already been completed and should be available in the 3.16 release.

**Comment by kedargslab** [comment]
This issue has been verified with AS3 v 3.16 and can be closed.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter
