### ISSUE TITLE
[AS3 Service Discovery]: Need support for AS3 Service Discovery append mode

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#191]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

  - Feature Idea

##### AS3 BUILD/ VERSION
3.14

##### BIGIP VERSION
13.1
##### SUMMARY
Recently opened github issue #188 where Service discovery doesnt allow 70+ endpoints to be POSTed to service discovery EP in same go.
Service discovery endpoint always requires the entire final list of nodes to be sent to it. So it works in replace mode rather than append mode, where we cant send it a list of node ips to add or remove (append mode) from original list.

**Comment by dstokesf5** [comment]
Supporting PATCH requests on the service discovery node endpoints is being tracked in our internal product backlog as AUTOTOOL-621.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter
