### ISSUE TITLE
AS3 application update does not work when "enable" set to false

### ISSUE THREAD

**Issue by manuwelakanade-GSLAB** [F5Networks/f5-appsvcs-extension#192]
ISSUE TYPE
Bug Report
AS3 BUILD/ VERSION
3.14

BIGIP VERSION
13.1

SUMMARY
As per the current AS3 behavior, if AS3 application has property "enable" set to false, any update to that AS3 application in the AS3 declaration does not work. As soon as "enable" is set to true the changes to other properties in that AS3 application also start working. 

Steps :
1. POST AS3 declaration with Partition/Application which has "enable": false
2. Update some other values like serverAddresses or virtualAddresses in the same application and repost. The update will not work.

**Comment by dstokesf5** [comment]
This is tracked in the internal product backlog as AUTOTOOL-715. It has already been completed and should be available in the 3.16 release.

**Comment by thomsonjames** [comment]
Verified working now in 3.15.   Be aware that the default version packaged in Azure images is older an needs to be updated after deployment.
OK to close
