### ISSUE TITLE
Event Driven Service Discovery: Enhancement to allow bulk updates

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-extension#194]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently event driven service discovery can only update a single pool at a time.  Ideally one could batch multiple updates into a single POST call.

**Comment by dstokesf5** [comment]
What issues are you currently encountering with the unbatched calls? Are you seeing a performance problem at a certain scale? If so, at what point do you begin seeing performance problems?

**Comment by chen23** [comment]
There's not an issue that I know of.  More of use case of being able to batch multiple updates into a single API call.

**Comment by dstokesf5** [comment]
We do not currently see a strong enough reason to implement and maintain this functionality. Closing this issue.
