### ISSUE TITLE
Cannot create iRule with line continutations

### ISSUE THREAD

**Issue by drennalls** [F5Networks/f5-appsvcs-extension#197]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
3.15.0

##### BIGIP VERSION

14.1.0.2 Build 0.0.4 Point Release 2

##### SUMMARY
Trying to create a Virtual Server that includes an iRule where lines are broken up using "\" fails unless the line continuations are removed first. The same iRule can be created using the REST API without issues.

##### STEPS TO REPRODUCE
A [as3_bug.py](https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e#file-as3_bug-py) script that tries to create the same iRule using the REST API and AS3. The attempt using AS3 fails unless the line continuations are removed.

```
12:08 $ ./as3_bug.py
AS3 version is  3.15.0
1) Creating HSSR iRule using REST API.. result=OK
2) Creating VS + HSSR iRule using AS3.. result=FAILED
422 Client Error: Unprocessable Entity for url: https://hod-staging-f5-k8s/mgmt/shared/appsvcs/declare
{"results":[{"code":422,"message":"declaration failed","response":"01070151:3: Rule [/Sample_01/as3_test/hssr_using_AS3] error: /Sample_01/as3_test/hssr_using_AS3:279: error: [undefined procedure: method][method nocache ns passwd proxy rbody rcookies ]\n/Sample_01/as3_test/hssr_using_AS3:280: error: [undefined procedure: rformat][rformat rheaders state tag type uri userid virt]\n/Sample_01/as3_test/hssr_using_AS3:283: error: [undefined procedure: redir][redir sniff timeout wait]\n/Sample_01/as3_test/hssr_using_AS3:286: error: [undefined procedure: accept-language][accept-language content-length content-type host ]\n/Sample_01/as3_test/hssr_using_AS3:287: error: [undefined procedure: user-agent][user-agent x-hssr-helper]\n","host":"localhost","tenant":"Sample_01","runTime":2299}],"declaration":{"class":"ADC","schemaVersion":"3.11.0","id":"test124","updateMode":"selective","controls":{"archiveTimestamp":"2019-11-19T17:08:01.503Z"}},"code":422}
3) Creating VS + HSSR iRule using AS3.. result=OK
```
[2] contains the following
* [as3_bug.py](https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e#file-as3_bug-py) for reproducing the issue
* [AS3 template](https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e#file-as3_vs_with_hssr-json) being used with a placeholder for the iRule definition
* [A copy of `HSSR.tcl`](https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e#file-hssr-tcl)  (the iRule used when encountering this, copied from [1])

References:
1. https://clouddocs.f5.com/api/irules/HTTP-Super-SIDEBAND-Requestor-Client-Handles-Redirects-Cookies-Chunked-Transfer-APM-Access-etc.html)
2. https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e

##### EXPECTED RESULTS
VS creation would be successful without the need to modify the iRule payload

##### ACTUAL RESULTS
iRule creation fails because it seems AS3 gets confused by the line continuations. For e.g. they're a bunch of "undefined procedure X" errors, which orignate from the list definitions found at https://gist.github.com/drennalls/9b4695bd6c8a71f455f90e2aea948f8e#file-hssr-tcl-L288 where they're broken into multiple lines
```
{
  "results": [
    {
      "code": 422,
      "message": "declaration failed",
      "response": "01070151:3: Rule [/Sample_01/as3_test/hssr_using_AS3] error: 
/Sample_01/as3_test/hssr_using_AS3:279: error: [undefined procedure: method][method nocache ns passwd proxy rbody rcookies ]\n
/Sample_01/as3_test/hssr_using_AS3:280: error: [undefined procedure: rformat][rformat rheaders state tag type uri userid virt]\n
/Sample_01/as3_test/hssr_using_AS3:283: error: [undefined procedure: redir][redir sniff timeout wait]\n
/Sample_01/as3_test/hssr_using_AS3:286: error: [undefined procedure: accept-language][accept-language content-length content-type host ]\n
/Sample_01/as3_test/hssr_using_AS3:287: error: [undefined procedure: user-agent][user-agent x-hssr-helper]\n",
      "host": "localhost",
      "tenant": "Sample_01",
      "runTime": 2299
    }
  ],
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.11.0",
    "id": "test124",
    "updateMode": "selective",
    "controls": {
      "archiveTimestamp": "2019-11-19T17:08:01.503Z"
    }
  },
  "code": 422
}
```

**Comment by simonkowallik** [comment]
Hi @drennalls,

I would recommend you to base64 encode iRules in declarations to avoid escaping issues.

Based on your example:
```json
"hssr_using_AS3": {
  "class": "iRule",
    "iRule": {
      "base64": "<base64 encoded irule>"
    }
  }
}
```

**Comment by drennalls** [comment]
@simonkowallik Thanks for the tip I didn't know that was an option. I tried your suggestion however I still have the same issue unless I remove the line continuations before base64 encoding the irule.

**Comment by drennalls** [comment]
Another thing I've noticed with both AS3 and iControl REST is that  some of the comment lines (like the header + footer for the HSSR.tcl used in in the reproduction scenario) seem to be removed in the end. For e.g. HSSR.tcl includes these lines..
```
#== Mark's HTTP Super SIDEBAND Requestor! (v2.1) =====================
..etc.
#== End of Mark's HTTP Super SIDEBAND Requestor! (v2.1) ==============
```
..both of which end up being removed. The f5 python sdk seems to have a similar issue except it removes less. For e.g. I attempt to configure this iRule..
```
#== comment 1 
when HTTP_REQUEST {
#==  comment 2 
# comment 3 
    if {[HTTP::uri] contains "/health"} {
    # comment 4
    HTTP::respond 200
    }
}
# comment 5 
#== comment 6
```
 Using AS3 this is what ends up being configured..
```
when HTTP_REQUEST {
#==  comment 2
# comment 3
    if {[HTTP::uri] contains "/health"} {
    # comment 4
    HTTP::respond 200
    }
}

```
Using REST/python F5 sdk this is what ends up being configured...
```
#== comment 1 
when HTTP_REQUEST {
#==  comment 2 
# comment 3 
    if {[HTTP::uri] contains "/health"} {
    # comment 4
    HTTP::respond 200
    }
}

```

**Comment by dstokesf5** [comment]
Thank you for reporting this issue. I have confirmed that there is a bug even with base64 encoded strings. I have added this issue to our internal product backlog as AUTOTOOL-1247.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
