### ISSUE TITLE
predictable schema files missing for AS3 release 3.14.1 and 3.16.0

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-appsvcs-extension#200]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
```
3.14.1
3.16.0
```

##### BIGIP VERSION
```
N/A
```

##### SUMMARY
The GitHub repository is missing predictable schema files for AS3 release 3.16.0 and 3.14.1.

Related issue and motivation: https://github.com/F5Networks/f5-appsvcs-extension/issues/100

##### STEPS TO REPRODUCE
Check [`schema/3.14.1`](https://github.com/F5Networks/f5-appsvcs-extension/tree/5aea66a5e2d42391fd99c94e907a292bf6b48194/schema/3.14.1
) and [`schema/3.16.0`](https://github.com/F5Networks/f5-appsvcs-extension/tree/5aea66a5e2d42391fd99c94e907a292bf6b48194/schema/3.16.0
) for `as3-schema.json`.

##### EXPECTED RESULTS
[`schema/3.14.1`](https://github.com/F5Networks/f5-appsvcs-extension/tree/5aea66a5e2d42391fd99c94e907a292bf6b48194/schema/3.14.1
) directory contains `as3-schema-3.14.1-1.json` and `as3-schema.json` (files have same content)
[`schema/3.16.0`](https://github.com/F5Networks/f5-appsvcs-extension/tree/5aea66a5e2d42391fd99c94e907a292bf6b48194/schema/3.16.0
) directory contains `as3-schema-3.16.0-6.json` and `as3-schema.json` (files have same content)

##### ACTUAL RESULTS
`schema/3.14.1` directory only contains `as3-schema-3.14.1-1.json` 
`schema/3.16.0` directory only contains `as3-schema-3.16.0-6.json`

`as3-schema.json` is missing for both directories

**Comment by JosephPJordan** [comment]
Thank you @simonkowallik for bringing this to our attention.  Both schema files have been added.
