### ISSUE TITLE
AS3 Extension is not idempotent

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-appsvcs-extension#207]
### Environment
 * Application Services Version: `3.13.1`
 * BIG-IP Version: `BIG-IP 13.1.1.4 Build 0.0.4 Point Release 4`

### Summary
Sending an AS3 declaration triggers a "Changes Pending" even if there's "no change".

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "label": "Sample 01",
    "remark": "Simple HTTP application with round robin pool",
    "sample01": {
      "class": "Tenant",
      "defaultRouteDomain": 0,
      "Application_1": {
        "class": "Application",
        "template": "http",
        "serviceMain": {
          "class": "Service_HTTP",
          "virtualAddresses": ["10.0.1.11"],
          "pool": "web_pool"
        },
        "web_pool": {
          "class": "Pool",
          "monitors": ["http"],
          "members": [
            {
              "servicePort": 80,
              "serverAddresses": ["10.1.2.101", "10.1.2.102"]
            }
          ]
        }
      }
    }
  }
}
```

2. Sync the devices.

3. Re-submit the declaration.

4. Observe the following response:
```json
        {
            "message": "no change",
            "host": "localhost",
            "tenant": "sample01",
            "runTime": 557,
            "code": 200
        }
```
5. Observe the sync status on the BIG-IP: `Changes Pending`

### Expected Behavior
When there's no change, sending an AS3 declaration should not trigger a "Changes Pending".

### Actual Behavior
A "Changes Pending" is triggered on the BIG-IP, even if the AS3 response message says "no change".

**Comment by dstokesf5** [comment]
While AS3 may not have changed any application related configuration, it may have updated something in it's internal data store. That data store is persisted to ltm data groups. There are valid cases for the data store to update in "no change" cases.

**Comment by erjac77** [comment]
@dstokesf5 Thank you for the response.

However, can you enlighten me about the valid cases of a data store update with a "no changes" ? Cause this behaviour seems counterintuitive to me. The declaration above is really simple and I can't see what internal data AS3 needed to change...

The problem in our case is that we manage configuration synchronization separately from AS3, and it become difficult to detect a change when AS3 reports none. Unless of course, we manually call the 'cm/sync-status' endpoint each time we send a declaration, but I think it defeats the purpose of a declarative approach like AS3.

Maybe a solution would be to return a status message for the application service, and an other one for the data store?

**Comment by dstokesf5** [comment]
I believe the internal data store is used to keep track of things like declaration history. Any declaration that is posted will affect that history, and therefore would likely cause a change in the internal data store. Are you seeing any cases were an AS3 post does not affect the sync status?

**Comment by erjac77** [comment]
You're right, I see no cases were AS3 does not affect the sync status. Moreover, I looked at the "Local Traffic  ››  iRules : Data Group List" section and now see some entries like `____appsvcs_declaration-1579883764992`. They contain a date that seems to be changed each time a declaration is deployed, even with "no changes".

But two things puzzle me:
1) Even if I use the `syncToGroup` option, the "Changes pending" still occur on the BIG-IP. Maybe because AS3 reports "no changes". If that so, this is a serious bug.
2) The `dry-run` action also triggers a "Changes Pending". Is it the desired behaviour?

Thanks again for your support.

**Comment by dstokesf5** [comment]
Now those two things do sound like bugs. Could you please file new issues for those two so we can keep the issues separate for easier handling and tracking?

**Comment by dstokesf5** [comment]
Thank you for creating the new issues. I am going to close this one out. If you feel there is something else that is not covered by #221 or #222, please reopen this ticket or create a new one.
