### ISSUE TITLE
policyEndpoint needs to support "use" syntax

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#208]
### Is your feature request related to a problem? Please describe.
The "policyEndpoint" element does not support "use":"<pointer>" syntax.  This is in consistent with other "use" style syntax.

### Describe the solution you'd like
Make "use" and "bigip" valid with "policyEndpoint" declarations.

### Describe alternatives you've considered
There are no alternatives.  Users must drop "use" and simply reference the pointer directly.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this feature request to our internal product backlog as AUTOTOOL-1077.

**Comment by dstokesf5** [comment]
This should be resolved in the 3.17.0 release. If you are still experiencing a problem, please re-open this issue or create a new one.
