### ISSUE TITLE
Where is the adc-schema.json file?

### ISSUE THREAD

**Issue by kshanafelt** [F5Networks/f5-appsvcs-extension#21]
##### ISSUE TYPE
 - Documentation Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs (f5-appsvcs-3.2.0-7.noarch) | 3.2.0 | 7
```

##### BIGIP VERSION

```
Version | BIG-IP 12.1.2 Build 2.0.276 Hotfix HF2
```

##### SUMMARY

The F5 AS3 documentation indicates there is a json schema available:
For example: 
1. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/userguide/components.html#as3-json-schema

   > The JSON Schema document prescribes the syntax of an AS3 declaration (found in the file **adc-schema.json** in the **/src/schema** directory of the GitHub repository).
   > (**Emphasis** in original)

   The Bolded filename and directory are not helpfully when I cannot find **the** GitHub repository that contains them. I have search F5Network Org in github, all of github, and google, and cannot find this schema file.

1. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/as3-api.html

   > The request document may be a proper request (see **as3-request-schema.json**) or a ADC-only declaration (see **adc-schema.json**).
   > (**Emphasis** added)

   Where can I find these files?

##### STEPS TO REPRODUCE
Click on the above links.

##### EXPECTED RESULTS
The documents linked above provide direct links to the json schema files, or are more descriptive of where to find them.

##### ACTUAL RESULTS
An unsatisfied F5 customer spends most of the day on a worthless Easter Egg hunt.

**Comment by jmcalalang** [comment]
@kshanafelt I'm sending Tyler a message for us to chat about this; totally agree on the open issue, looking to provide you some support while it gets worked out.

**Comment by delgadillo22** [comment]
I've raised visibility of this issue with engineering. Thanks for your patience.

**Comment by mdditt2000** [comment]
@jmcalalang i sent the schema to Tyler

**Comment by JosephPJordan** [comment]
The schema files are now published on GitHub in this repo: https://github.com/F5Networks/f5-appsvcs-extension/tree/master/schema.  Closing this issue.
