### ISSUE TITLE
Policy_Action tcl set-variable

### ISSUE THREAD

**Issue by zivvel** [F5Networks/f5-appsvcs-extension#210]
### Is your feature request related to a problem?
During iRule execution, need to be able to detect when a Policy_Condition was matched.  Prior to AS3, we use a TCL set-variable action to accomplish this.

In the current case, we are inserting a prefix on HTTP::uri; we would normally do this:
```
actions {
  0 {
    http-uri
    replace
    path /
    value "tcl:[string replace [HTTP::uri] 0 0 /new_prefix/]"
  }
  1 {
    tcl
    set-variable
    expression 1
    name http_uri_rewritten
  }
}
```

### Describe the solution you'd like
Implement TCL set-variable as a Policy_Action in AS3.

### Describe alternatives you've considered
I don't know if this will work, and it's definitely not the way we want to do it, but we are playing with something like this:
```
"actions": [{
  "type": httpUri",
  "replace": {
    "value": "tcl:[string replace [HTTP::uri] 0 0 [set http_uri_rewritten /new_prefix/]]",
  }
}]
```

### Additional context
We also need a Policy_Condition like `http-uri not starts-with /new_prefix`, but I see there are already 2 requests for that.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have copied your feature request to our internal product backlog as AUTOTOOL-1151.

**Comment by walterk82** [comment]
Is there any updated on this request?

**Comment by walterk82** [comment]
Any news here?

**Comment by delgadillo22** [comment]
We've create a ticket in our internal backlog for sizing and prioritization against existing commitments.
