### ISSUE TITLE
Endpoint policy condition - missing possibility to match against TCP ip/port

### ISSUE THREAD

**Issue by Eken92** [F5Networks/f5-appsvcs-extension#211]
### Is your feature request related to a problem? Please describe.
Using "regular" big-ip, it is possible to create ltm policies with conditions matching against client ip address or destination port. Using as3 it seems like it's only possible to match against port specified in the URL ( = not sufficient)

### Describe the solution you'd like
Ability to add conditions based on TCP parameters such as client ip or destination port.

### Describe alternatives you've considered
It's possible to do it using iRules of course, but since it is possible using GUI version, I don't see why it shouldn't work using as3.

### Additional context
Feature in GUI:
![image](https://user-images.githubusercontent.com/11943081/71925770-15dcce80-3192-11ea-966d-4173470e4725.png)

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have copied this feature request to our internal product backlog as AUTOTOOL-1152.

**Comment by j-zehnder** [comment]
This issue is one I am facing as well, would it be possible to get an update?

**Comment by dstokesf5** [comment]
I have bumped up the priority on this issue in our internal backlog. However, our backlog is quite full at this time, and it may still take a while to get to this feature request.

**Comment by mgaliulin** [comment]
Raising my hand for implementation of this functionality too.
Use case: ltm policy for pool selection based on IP addresses.  
Implementing this using iRule is possible but makes the configuration less "uniform" and requires iRule/TCL programming skills.

**Comment by trinaths** [comment]
@dstokesf5  any update on this ?

**Comment by dstokesf5** [comment]
This will be available in the 3.20 release.
