### ISSUE TITLE
External Monitor definition results in truncated file

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-appsvcs-extension#214]
#132 # Environment
 * Application Services Version: 3.16
 * BIG-IP Version: BIG-IP 15.0.1 Build 0.0.11 Final

### Summary
I'm looking to build a configuration which has an external monitor. The monitor is stored on github. When I use the AS3 declaration attached, the monitor gets created on the BIG-IP with an added "-script" added to the end of the object name.
When I then look at the file, some sort of text wrap has been added to the script at 65 characters and it mangles the script.

Attached
dns-eav.txt - Good monitor file
broken-eav.txt - What it looks like once it is uploaded to the BIG-IP via AS3
addeav.json - the AS3 declaration I'm using

### Steps To Reproduce
1) Use the attached json to push to BIG-IP, go look at the EAV after it is uploaded either in the GUI under System - File Management - External File Management
or in the CLI in the filestore in /config/filestore/files_d/azurevmss_d/external_monitor_d

### Expected Behavior
I expect the monitor to be in it's original state

### Actual Behavior
See attached broken-eav.txt to see what happens to it.

This was on one line originally
# these arguments supplied automatically for all external monito
rs:

same thing here

# Additional command line arguments ($3 and higher) may be speci
fied in the monitor template

**Comment by thomsonjames** [comment]
[addeav.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/4074451/addeav.json.txt)
[broken-eav.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/4074452/broken-eav.txt)
[dns-eav.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/4074453/dns-eav.txt)

**Comment by thomsonjames** [comment]
Truncated may not be the correct word, but I seems to get artificially word wrapped at the 65 character length

**Comment by dstokesf5** [comment]
Confirmed the bug, added to our internal product backlog as AUTOTOOL-1164.

**Comment by dstokesf5** [comment]
This was resolved in the 3.18.0 release.
