### ISSUE TITLE
No synchronization when AS3 reports "no change"

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-appsvcs-extension#222]
### Environment
 * Application Services Version: `3.13.1`
 * BIG-IP Version: `BIG-IP 13.1.1.4 Build 0.0.4 Point Release 4`

### Summary
When AS3 reports "no change", the devices won't sync and a "Changes Pending" is triggered, even if the `syncToGroup` option is set. See issue #207.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "syncToGroup": "/Common/MyDeviceGroup",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "label": "Sample 01",
    "remark": "Simple HTTP application with round robin pool",
    "sample01": {
      "class": "Tenant",
      "defaultRouteDomain": 0,
      "Application_1": {
        "class": "Application",
        "template": "http",
        "serviceMain": {
          "class": "Service_HTTP",
          "virtualAddresses": ["10.0.1.11"],
          "pool": "web_pool"
        },
        "web_pool": {
          "class": "Pool",
          "monitors": ["http"],
          "members": [
            {
              "servicePort": 80,
              "serverAddresses": ["10.1.2.101", "10.1.2.102"]
            }
          ]
        }
      }
    }
  }
}
```

2. Observe the following response:
```json
        {
            "message": "no change",
            "host": "localhost",
            "tenant": "sample01",
            "runTime": 557,
            "code": 200
        }
```
3. Observe the sync status on the BIG-IP: `Changes Pending`

### Expected Behavior
The devices should sync, even if AS3 reports "no change", cause some internal data are changed and stored in data groups.

### Actual Behavior
Devices won't sync and a "Changes Pending" is triggered.

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have added it to our internal product backlog as AUTOTOOL-1393.

**Comment by Ahmedmagddi** [comment]
Is there any update on this?

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
