### ISSUE TITLE
Support creation and association of HTML Content Profiles

### ISSUE THREAD

**Issue by aknot242** [F5Networks/f5-appsvcs-extension#226]
### Is your feature request related to a problem? Please describe.
There is currently no support for creating or attaching HTML Content Profiles in AS3. 

### Describe the solution you'd like
Please provide the ability to manage HTML Content Profiles in AS3. Also please create the ability to attach HTML Content Profiles to a Virtual Server. 

### Describe alternatives you've considered
A possible workaround is to use iControlREST to send TMSH commands to manage an HTML Content Profile, but a better solution is that AS3 should be managing these objects rather than being managed imperatively on an individual basis.

### Additional context
HTML Content profiles are needed for the Shape Security integration, and I would like to use an AS3 template for this rather than a series of TMSH commands as outlined here:  https://support.f5.com/csp/article/K37712232

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have created AUTOTOOL-1240 in our internal product backlog to track this request.

**Comment by walterk82** [comment]
Maybe step 1 for this request would be the ability to reference a pre-existing HTML content profile in /Common

step 2 would be the ability to declare the HTML objects in AS3. 

A two step approach would minimize development for quick onboarding for new VIPs while the JSON schema for HTML content profiles is fully defined.

**Comment by walterk82** [comment]
What is the priority of this request? Would it be feasible to deliver this in two parts so that we can at least associate HTML profiles to a VS?

The complications comes where we have adopted AS3 for an initial deployment, and now we need to add HTML profiles in a subsequent requirement.  We now have to remove this App from AS3 and re-build it outside to add HTML profile support.  Or manually change in the GUI and hope that no one re-runs the AS3 POST for this tenant.

**Comment by walterk82** [comment]
Are we any closer to having a solution to this problem?

**Comment by j-zehnder** [comment]
Is it possible to receive an update on the progress of this request?

**Comment by dstokesf5** [comment]
Unfortunately there are no significant updates on this issue as it is regularly preempted by higher priority tasks.

**Comment by grf5** [comment]
I have an immediate need for this feature as well.

**Comment by walterk82** [comment]
@dstokesf5 has a BZ ID been assigned to this?  I can open a support ticket RFE for enhanced visibility.

**Comment by dstokesf5** [comment]
Fortunately, this item is already being worked on for the 3.31.0 release. We are initially exposing the `tag-append-html` rule. If you require other rules, please create new tickets for those specific rules, and I will see what I can do about getting those tickets prioritized for the 3.31.0 release.

**Comment by grf5** [comment]
I have a need for this to enable F5's Shape Integrated Bot Defense iApp to work in conjunction with AS3 deployed applications. I need to attach two existing iRules, an existing OneConnect profile and an existing HTML profile to the virtual server using AS3 so I do not have a source of truth conflict. 

Example virtual server configuration with Shape profiles and iRules attached:

```console
ltm virtual fragglerock.com {
    destination 192.0.2.143:https
    ip-protocol tcp
    mask 255.255.255.255
    pool doozer_pool
    profiles {
        clientssl-secure {
            context clientside
        }
        f5-tcp-progressive { }
        http { }
        serverssl-secure {
            context serverside
        }
        testing_Shape_JsHtml { } <- HTML profile (Content Rewrite)
        testing_Shape_oneconnect { }
    }
    rules {
        testing_Shape_TLSFP_iRule__Common_fragglerock.com
        testing_Shape_iRule__Common_fragglerock.com
    }
    serverssl-use-sni disabled
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
```
