### ISSUE TITLE
Need "HTTP Host" parameter in Policy_Condition

### ISSUE THREAD

**Issue by subbuv26** [F5Networks/f5-appsvcs-extension#229]
### Is your feature request related to a problem? Please describe.
Yes. Unable to frame a Policy Condition with "HTTP Host" parameter in HTTP request. 

### Describe the solution you'd like
I would like to configure the below configuration using AS3
![Screenshot 2020-02-11 at 5 54 52 PM](https://user-images.githubusercontent.com/12125694/74237204-01dc3d80-4cf9-11ea-99ed-8e58c39d4692.png)

### Describe alternatives you've considered
As an alternative, "Host" in "HTTP Header" was considered
 
![Screenshot 2020-02-11 at 5 54 00 PM](https://user-images.githubusercontent.com/12125694/74237267-2506ed00-4cf9-11ea-88d7-79f521531fc3.png)

**Comment by dstokesf5** [comment]
Why did inspecting the Host header not work for you? As far as I know, that is exactly what the HTTP Host option is checking. From the tmsh help page on "http-host":
```
Match against an HTTP request's Host: header
```

**Comment by subbuv26** [comment]
We are able to get it work for us, but with an issue.
By overriding the header in the request, ltm policies can be tricked. 

Eg:
if a policy is configured for host "foo.com"
# curl --resolve bar.com:443:172.16.3.14 --header "HOST:foo.com" https://bar.com -k
by using the above command we can reach the server using "bar.com"

**Comment by dstokesf5** [comment]
@subbuv26 Have you confirmed that the host condition does not have the same behavior? The documentation says that it just checks to the "Host" header, so it should have the same behavior and limitations as just using the header condition.

**Comment by agupta49** [comment]
One more use case for the need of "HTTP Host" parameter: To specify a port number in a policy condition "HTTP Host" is required. Currently, we do not have an alternative solution.

**Comment by dstokesf5** [comment]
@agupta49 can you use the http-uri condition for port checking?
```json
{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "Tenant": {
        "class": "Tenant",
        "Application": {
            "class": "Application",
            "template": "generic",
            "policy": {
                "class": "Endpoint_Policy",
                "rules": [
                    {
                    	"name": "sample",
                        "conditions": [
                            {
                            	"type": "httpUri",
                            	"host": {
                            		"values": ["foo.com"]
                            	}
                            },
                            {
                            	"type": "httpUri",
                            	"port": {
                            		"values": [8100]
                            	}
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by m-kratochvil** [comment]
Hi,
We're in a process of migration from the old lbaasv2 to AS3 and all our LTM policies that used `http-host` stopped working because AS3 switched to `httpUri`, causing downtime of the listeners. As soon as we reconfigured the failing policy back to use `http-host`, it was working as intended.

I would thus still very much vote for implementing the `http-host` in AS3.
The port checking example above from @dstokesf5 would fail to match the host `foo.com`, at least on our systems.

**Comment by dstokesf5** [comment]
@m-kratochvil Does the http-header condition work for you? As far as I can tell from the documentation, it should be doing the same thing as http-host.

```json
{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "Tenant": {
        "class": "Tenant",
        "Application": {
            "class": "Application",
            "template": "generic",
            "policy": {
                "class": "Endpoint_Policy",
                "rules": [
                    {
                        "name": "sample",
                        "conditions": [
                            {
                                "type": "httpHeader",
                                "all": {
                                    "values": ["foo.com"]
                                },
                                "name": "Host"
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by m-kratochvil** [comment]
@dstokesf5 Yes, we switched to httpHeader for host matching and the policies work fine so far, so I think we're good here..
Thanks for the response!
