### ISSUE TITLE
Enable sharing user-agent metadata with TEEMS

### ISSUE THREAD

**Issue by trinaths** [F5Networks/f5-appsvcs-extension#230]
**Problem:**

AS3 doesn't send full declaration to avoid sending any sensitive info to TEEMS. But this limits user_agent metadata being sent to TEEMS which doesn't contain any sensitive info.

**Solution:**

AS3 should send user-agent info along with platform info to TEEMS.

user-agent metadata, be

```
ltm virtual /k8s/default_demo-app {
    destination /k8s/10.1.20.201%0:80
    ip-protocol tcp
    mask 255.255.255.255
    metadata {
        user_agent {
            value k8s-bigip-ctlr-1.12.0-n2050-623590021
        }
    }
 
```

**Comment by dstokesf5** [comment]
We have a similar request in our internal product backlog as AUTOTOOL-1201. The way we intend to implement this is by allowing a user to specify a user agent in the controls class. I believe that will work better than relying on the metadata fields of virtual servers.

**Comment by dstokesf5** [comment]
This was added in v3.18.0: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html?highlight=useragent#using-the-useragent-controls-property
