### ISSUE TITLE
BigIP Services restart after adding IPv6 node to service discovery endpoint.

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#235]
### Environment
 * Application Services Version: 3.17.1
 * BIG-IP Version: 15.1

### Summary
BigIP Services restart after adding IPv6 node to service discovery endpoint.This was observed on Physical standalone BigIP with said versions deployed on it.

### Steps To Reproduce

Steps :

1. Configure Service discovery for BigIP

2. Service discovery endpoint : https://<BigIP IP>/mgmt/shared/service-discovery/task/~<Partition-Name>~<App Name>~<Pool Name>/nodes

post below json payload to the given endpoint :

Json :  {'ip': '12.12.1.3', 'id': '/newpart1/12.12.1.3'}, {'ip': '12.12.1.1', 'id': '/newpart1/12.12.1.1'}, {'ip': '12.12.1.5', 'id': '/newpart1/12.12.1.5'}, {'ip': '12.12.1.10', 'id': '/newpart1/12.12.1.10'}, {'ip': '12.12.1.2', 'id': '/newpart1/12.12.1.2'}, {'ip': '12.12.1.6', 'id': '/newpart1/12.12.1.6'}, {'ip': '12.12.1.8', 'id': '/newpart1/12.12.1.8'}, {'ip': '12.12.1.7', 'id': '/newpart1/12.12.1.7'}, {'ip': '12.12.1.9', 'id': '/newpart1/12.12.1.9'}, {'ip': '12.12.1.4', 'id': '/newpart1/12.12.1.4'}, {'id': '172.18.1.1', 'ip': '172.18.1.1'}, {'id': '2001:db8::ff00:42:8329', 'ip': '2001:db8::ff00:42:8329'}, {'id': '2001:db8::ff00:42:8330', 'ip': '2001:db8::ff00:42:8330'}

Port number for pool members was : 9090 in this case.

After posting the json, it was observed that the 2 ipv6 nodes were created under the partition on BigIP. However, it failed to add them as  pool members.

It seems that its not able to differentiate between ipv6 format and ipv4 along with port added. 

Please take a look at below log from restnoded.log file for the operation :

Fri, 06 Mar 2020 08:47:35 GMT - info: [f5-service-discovery: Task.js] Task ~newpart1~Test2~svc_pool failed: Command failed: tmsh -a modify ltm pool /newpart1/Test2/svc_pool members replace-all-with { 12.12.1.3:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.1:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.5:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.10:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.2:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.6:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.8:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.7:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.9:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.4:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 172.18.1.1:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 2001:db8::ff00:42:8329:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 2001:db8::ff00:42:8330:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
Syntax Error: A port number or service name is missing for "2001:db8::ff00:42:8329:9090". Please specify a port number or service name using the syntax "2001:db8::ff00:42:8329:9090.<port>".

Fri, 06 Mar 2020 08:47:35 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a modify ltm pool /newpart1/Test2/svc_pool members replace-all-with { 12.12.1.3:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.1:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.5:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.10:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.2:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.6:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.8:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.7:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.9:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 12.12.1.4:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 172.18.1.1:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 2001:db8::ff00:42:8329:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } 2001:db8::ff00:42:8330:9090 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
Syntax Error: A port number or service name is missing for "2001:db8::ff00:42:8329:9090". Please specify a port number or service name using the syntax "2001:db8::ff00:42:8329:9090.<port>".

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

### Expected Behavior
It should be able to add the pool member with appropriate port and services should not be restarted for this operation. 

### Actual Behavior
If the json contains ipv6 ip , AS3 fails to add all these members to the pool. BigIP services get restarted.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have added it to our internal product backlog as AUTOTOOL-1389.

It looks like this only occurs when you specify an IPv6 address for the id. If you give your nodes an id that is not an IP address, IPv6 nodes seem to work just fine.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
