### ISSUE TITLE
Bot Defense Log Profile should be aligned with new BIG-IP versions

### ISSUE THREAD

**Issue by michal-malec** [F5Networks/f5-appsvcs-extension#239]
### Is your feature request related to a problem? Please describe.
Current configuration of Security_Log_Profile_Bot_Defense doesn't work for newer BIG-IP version. For example it doesn't work on BIG-IP 15.0.1.1 Build 0.0.3. Similar issue exists for DOS Log Profile. 

### Describe the solution you'd like
I would Security Log Profiles settings to be aligned with those required on newer BIG-IP.

### Describe alternatives you've considered
Currently I can configure it using iControl REST.

### Additional context
I would like to use only one tool to setup BIG-IP and this feature is required to do so.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal backlog as AUTOTOOL-1383. This will likely take us a while to sort out as we try to find information on what changed and how to migrate old settings to these new settings.
