### ISSUE TITLE
Getting "2 unexpected results" during selftest

### ISSUE THREAD

**Issue by russellmilliner** [F5Networks/f5-appsvcs-extension#24]
##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION

```6```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.3
  Build       0.3.1
  Edition     Engineering Hotfix
  Date        Wed Mar 21 12:47:00 PDT 2018

Hotfix List
ID708653-3
```

##### SUMMARY

```
When running the selftest from cURL, I get the the message "2 unexpected results"
```

##### STEPS TO REPRODUCE

```
curl -s -k --user admin:xxxxx --data '{}' -X POST "https://<hostname>/mgmt/shared/appsvcs/selftest"
```

##### ACTUAL RESULTS

```
[
  {
    "message": "2 unexpected results",
    "selfTestRunTime": 43459
  },
  {
    "name": "AS3_Basics_01",
    "message": "Warning: test result did not match expected configuration",
    "hash": "7231eca15c383cf212b5793ed00552d13e78471f95f6e2d880a229214526371c"
  },
  {
    "name": "AS3_Basics_02",
    "message": "Warning: test result did not match expected configuration",
    "hash": "8a8d5228c4efe00a992026199495cc313f01f6359ec8ee4e1aa26218d018224b"
  }
]
```

**Comment by mdditt2000** [comment]
@russellmilliner can you please check a few things

Add the following to the body of the JSON payload

[
    {
        "message": "all tests passed",
        "selfTestRunTime": 9006
    }
]

Also what version of AS3 are you validating?

**Comment by russellmilliner** [comment]
The version of AS3 is 3.3.0 build 6.  Currently, I am having problems syncing after upgrading to 13.1.1, so once that is resolved, I'll post the results requested.

**Comment by russellmilliner** [comment]
curl -s -k --user admin:xxxx --data '[ { "message": "all tests passed", "selfTestRunTime": 9006 } ]' -X POST "https://xxxx/mgmt/shared/appsvcs/selftest"

[{"message":"2 unexpected results","selfTestRunTime":44259},{"name":"AS3_Basics_01","message":"Warning: test result did not match expected configuration","hash":"627ece748636ebddc3c167f24e86bae85f75fc873db1256c4b6133cd727d8f23"},{"name":"AS3_Basics_02","message":"Warning: test result did not match expected configuration","hash":"8a8d5228c4efe00a992026199495cc313f01f6359ec8ee4e1aa26218d018224b"

**Comment by kaustriaf5** [comment]
This seems to be an obsolete issue that hasn't updated in a while..
Please note that selftest feature is going to be deprecated (774).
To verify that AS3 is up and running, please perform a GET `https://{{host}}/mgmt/shared/appsvcs/info`
