### ISSUE TITLE
OAuth2 Support when retriving objects from a URL

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-appsvcs-extension#240]
### Is your feature request related to a problem? Please describe.
Need OAuth2 support to download WAF policies from Azure DevOps and GitHub repositories: https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-5.1#security

### Describe the solution you'd like
With OAuth2 support, we would be able to leverage Azure DevOps(ADO) with F5 AS3 automation. ADO does not support basic authentication, only OAuth v2.  The ideal solution would be for AS3 to support OAuth to pull the WAF policy from a secure GIt repository inside ADO. 

GitHub will also deprecate password-based authentication in favor of OAuth by 11/13/2020: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

### Describe alternatives you've considered
The only current alternative is to make the WAF policy publically viewable, which is against security best practices.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-1382.

**Comment by tizianorosato** [comment]
Quite interested on this enhancement.
We use to store irules and datagroups and an private git repo.

**Comment by dstokesf5** [comment]
@codygreen and @tizianorosato, could either of you provide examples of what you expect this to look like in AS3? Would you expect to provide a token to AS3, or provide credentials for AS3 to use for a log in request to get the token?

**Comment by codygreen** [comment]
I would expect the user would supply a token to access the repository.  I
don't think it is necessary for AS3 to request the token on the user's
behalf.

For example, the user can follow the GitHub documentation to create a
personal access token and then supply this token to AS3:
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

**Comment by dstokesf5** [comment]
@codygreen It looks like for GitHub the personal access token from the link you provided is used as the password in basic auth requests: https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens

**Comment by codygreen** [comment]
Yes, but that's just one example of a personal access token used for
authentication.  GitHub Apps are the preferred method which required OAuth2
support:
https://docs.github.com/en/developers/apps
https://docs.github.com/en/developers/apps/authorizing-oauth-apps

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 3.28.0 release.

**Comment by DahlPatric** [comment]
Need little help to understand how to authenticate with my created personal access token (classic)
Got access token but how to use it? Saw example and got confused.

"authentication": {
                        "method": "basic",
                        "username": "testUser",
                        "passphrase": {
                            "ciphertext": "ZjVmNQ==",
                            "protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0"
                        }
                    }
