### ISSUE TITLE
Unable to remove AS3 partition when DNS resolver is present under the AS3 Partition

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#241]
### Environment
 * Application Services Version: v3.17
 * BIG-IP Version: v15

### Summary
Unable to remove AS3 partition when DNS resolver is present under a partition. The BigIP doesnt show error properly about what object to delete. It just shows "All objects must be removed from a partition (PART-XX) before the partition may be removed"

### Steps To Reproduce
- Partition/App created using AS3.
- We had a DNS Resolver present on the BigIP under this partition.
- Tried to perform AS3 delete operation for this partition. 
- Observed error "All objects must be removed from a partition ( ) before the partition may be removed"

### Expected Behavior
If there is any dependency on any object for Partition/App delete operation, AS3 should respond appropriately for this.

### Actual Behavior
AS3 shows generic message "All objects must be removed from a partition (PART-XX) before the partition may be removed" but its difficult to figure out which object is causing this issue.
As a workaround, user needs to check "partitions/<Part Name>/bigip.conf" to check which object is causing issues. In our case it was observed to be DNS resolver.

[root@localhost:Active:Standalone] config # cat partitions/newpart1/bigip.conf
#TMSH-VERSION: 15.1.0

net dns-resolver /newpart1/DNS_Server {
    route-domain /Common/0
}

So removed this from the partition and then the AS3 delete operation went fine.

**Comment by dstokesf5** [comment]
This is expected behavior when AS3 is mixed with other configuration methods. In this case, AS3 does not understand DNS resolvers, and does not know how to delete them.
