### ISSUE TITLE
HTTP MRF Router param is not supported for Virtual.

### ISSUE THREAD

**Issue by trinaths** [F5Networks/f5-appsvcs-extension#242]
Using AS3, when a Virtual is configured with HTTP/2 profile, HTTP MRF Router option must be enabled. 
Currently AS3 doesn't support enable for HTTP MRF Router.

From the docs, 

https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/big-ip-http2-full-proxy-configuration-14-1-0/01.html#concept-5982

"Important: When you create the virtual server, make sure that you enable the HTTP MRF Router option. This is necessary for successful HTTP/2 full-proxy deployment."

Can we have MRF option in AS3 upcoming release ?

**Comment by dstokesf5** [comment]
Added to our internal product backlog as AUTOTOOL-1391.

**Comment by dstokesf5** [comment]
This was resolved in the 3.24.0 release.
