### ISSUE TITLE
API to manage individual certificates in a CA bundle

### ISSUE THREAD

**Issue by andrewjohnston54** [F5Networks/f5-appsvcs-extension#243]
### Is your feature request related to a problem? Please describe.
We struggle to maintain a CA bundle, an encoded set of certificates, as a bundle.  Over time, we are adding and removing certificates from this bundle, which is an awkward, manual, error-prone process.

### Describe the solution you'd like
We'd like to see an API (and a GUI wouldn't hurt either) to enable us to add and remove individual certificates from a bundle.  We would do this in response to upcoming certificate expiry dates (new certificates added), and after certificate expiry dates (old certificates removed).

### Describe alternatives you've considered
We have considered developing our own tools (scripts backed by databases) to manage bundles, to automate and validate the creation of CA bundles.

### Additional context
We might do this more than the average customer.

**Comment by dstokesf5** [comment]
This level of certificate management is outside of the scope of AS3.
