### ISSUE TITLE
Add filterClass support for Application Class

### ISSUE THREAD

**Issue by boeboe** [F5Networks/f5-appsvcs-extension#250]
**Current status:** filterClass supports to filter on VirtualServer classes like Service_HTTP, Service_HTTPS, etc... (the documentation mentions)

**Request:** It would be nice to have the ability to filter in class Application as well, so CICD pipelines only need to parse on the Application they are deploying and use that as a verification step to see if creation/update/delete has worked on this specific Application.

Example:

    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
           "class": "ADC",
           "schemaVersion": "3.0.0",
           "id": "fghijkl7890",
           "label": "Sample 6",
           "remark": "HTTP two applications",
           "Sample_http_06": {
              "class": "Tenant",
              "A1": {
                 "class": "Application",
                 "template": "http",
                 "serviceMain": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                       "10.0.6.100"
                    ],
                    "pool": "web_pool"
                 },
                 "web_pool": {
                    "class": "Pool",
                    "monitors": [
                       "http"
                    ],
                    "members": [{
                       "servicePort": 80,
                       "serverAddresses": [
                          "192.0.6.10",
                          "192.0.6.11"
                       ]
                    }]
                 }
              },
              "A2": {
                 "class": "Application",
                 "template": "generic",
                 "AnyName": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                       "10.0.6.111"
                    ],
                    "pool": "web_pool2",
                    "virtualPort": 80
                 },
                 "web_pool2": {
                    "class": "Pool",
                    "monitors": [
                       "http"
                    ],
                    "members": [{
                       "servicePort": 80,
                       "serverAddresses": [
                          "192.0.6.111",
                          "192.0.6.121"
                       ]
                    }]
                 }
              },
              "A3": {
                "class": "Application",
                "template": "generic",
                "AnotherName": {
                   "class": "Service_TCP",
                   "virtualAddresses": [
                      "10.0.6.14"
                   ],
                   "pool": "web_pool3",
                   "virtualPort": 80
                },
                "web_pool3": {
                   "class": "Pool",
                   "monitors": [
                      "tcp"
                   ],
                   "members": [{
                      "servicePort": 21,
                      "serverAddresses": [
                         "192.0.6.141",
                         "192.0.6.142"
                      ]
                   }]
                }
             }
           }
        }
    }

GET /mgmt/shared/appsvcs/declare/Team_A?filterClass=A3

    "Sample_http_06": {
       "A3": {
         "class": "Application",
         "template": "generic",
         "AnotherName": {
            "class": "Service_TCP",
            "virtualAddresses": [
               "10.0.6.14"
            ],
            "pool": "web_pool3",
            "virtualPort": 80
         },
         "web_pool3": {
            "class": "Pool",
            "monitors": [
               "tcp"
            ],
            "members": [{
               "servicePort": 21,
               "serverAddresses": [
                  "192.0.6.141",
                  "192.0.6.142"
               ]
            }]
         }
      }
    }

**Comment by dstokesf5** [comment]
I believe this is better handled by an application level API similar to what you described in #253. Therefore I am closing this one as a duplicate.
