### ISSUE TITLE
Officially deprecate application templates in favor of "template": "generic"

### ISSUE THREAD

**Issue by j-zehnder** [F5Networks/f5-appsvcs-extension#251]
### Is your feature request related to a problem? Please describe.
Documentation does not accurately reflect the current expected use of application templates.

### Describe the solution you'd like
Documentation should be updated to reflect the statement
>"...and we have since decided that [application templates] are not worth developing further. At this point they are unofficially deprecated, and we recommend all users to use the generic template." _From a thread in the f5-appsvcs-extension Slack channel_

Example declarations should be converted from "template": "http" etc. to "template": "generic". 

Documentation piece:
> ##Do all of my application services need to be named “ServiceMain”?##
> No, if you want to name your service something other than serviceMain, use “template:”generic” in the application service of your declaration. You can still use the class property in the application service to specify Service_HTTP or Service_TCP for example, but for each application service in a tenant that uses one of the templates (http, https, tcp, udp, l4), you must use the name serviceMain for your application service. See Example 20 in the AS3 documentation for an illustrative declaration.

should be replaced with a statement of why the templates existed and why the generic template is now the recommended approach

### Additional context
This was a major source of confusion for me when starting into AS3, and I commonly see other users with similar issues in the f5-appsvcs-extension Slack channel.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This is already being tracked in our internal product backlog as AUTOTOOL-978.

**Comment by dstokesf5** [comment]
This has been resolved as part of the 3.20.0 release.
