### ISSUE TITLE
Add support to update a single application within the same Tenant

### ISSUE THREAD

**Issue by boeboe** [F5Networks/f5-appsvcs-extension#253]
Related to #250 

**Current state:**

Currently, the AS3 model is _Tenant_ based, with one _Tenant_ being responsible for one or more _Applications_. We have the option to have AS3 separation of _Tenant_ concerns, by the option to add one or more _Tenants_ to the AS3 URI endpoint, as documented [here](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/as3-api.html#posting-to-a-specific-tenant).

     POSTING to the URI /mgmt/shared/appsvcs/declare/tenant1,tenant2

**Possible improvement:**

Add the option to also have a separation of concern on _Application_ level

     POSTING to the URI /mgmt/shared/appsvcs/declare/tenant1/application1

**Scenario:**
From a DevOps perspective, I would like a clean separation of concern between _Applications_. This means:

- _Application_ code is stored in separate git repo's
- Ansible provision scripts are stored in the same (or a different) repo, per _Application_
- My service delivery (AS3) is stored per _Application_ as well

Given the current capabilities of AS3, you have no choice other than to store AS3 blobs per _Tenant_. 

**Workarounds:**

There are a few ways to get around this today:

- Use 1 _Application_ per _Tenant_ only
- Have a separate system (eg a CICD pipeline) to fetch split per _Application_ AS3 deployments and recombine them into one per _Tenant_ based AS3 
- Use PATCH instead of POST, which has different disadvantages (and or risks)

The second work around however, violates the principle that a CICD pipeline is responsible for 1 _Application_ only. This might have both security and instability implications (like an application development team making mistakes in their _Application_ specific blob).

**Comment by dstokesf5** [comment]
While I agree that this could be useful, it will likely be a while before we make a larger change or update to the API like this one. If and when we do get to a point where we are able to work on an API update like this, we will certainly keep this feedback in mind. Especially since this is not the first time it has come up.

In the meantime I have added AUTOTOOL-1502 to our internal product backlog to begin tracking this feature.

**Comment by boeboe** [comment]
Thanks for the update @dstokesf5 . It would avoid a whole lot of boilerplate verification and recomposition code for about everyone make the move to our ATC toolchain.

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com
