### ISSUE TITLE
Add the possibility to specify ingress egress for http2 profiles

### ISSUE THREAD

**Issue by rdalbenzio** [F5Networks/f5-appsvcs-extension#255]
In https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html the only profile which can be specified as ingress or egress is the TCP profile.

F5 configuration has more profiles which can be different on client and server side. In particular http2 profiles are needed.

Solution would be to add the possibility to specify ingress vs egress on http2 profile.

This is the snapshot of the Big-IP WebUI showing different http profiles possible on client and server side.

<img width="524" alt="Screenshot 2020-04-15 at 10 38 50" src="https://user-images.githubusercontent.com/36187251/79319875-34790100-7f09-11ea-849b-f836e8a7857d.png">

**Comment by joebride** [comment]
Prioritize issue#255 over #254.
Firstly I require http2-profile on ingress.
Next onboarding of customer starts at 4th-May.

**Comment by dstokesf5** [comment]
In your example you have both items set to the same value, which can be achieved today. I tried changing one of the values and received an error: `01070734:3: Configuration error: Found disallowed profile on /Common/test: Not HTTP2 Profile (Only on serverside)`.

In order to help us create an appropriate user experience, can you elaborate on the configuration you are trying to achieve?

**Comment by joebride** [comment]
These are the profiles required to achieve VS the normal function including HTTP/2-Gateway function:
profiles {
/Common/PROF_ANALYTICS_HTTP_CUSTOMIZED { }
/Common/PROF_HTTP_REDIRECT_HSTS_XFF { }
/Common/PROF_TCP_LANOPTIMIZED_KEEPALIVE_120 {
context serverside
}
/Common/PROF_TCP_WANOPTIMIZED_KEEPALIVE_120_NONAGLE {
context clientside
}
/Common/PROF_WAF_BOT_DEFENSE_RELAXED { }
/Common/PROF_WAF_DOS_BA_TLSFP_BLOCKING { }
/Common/bot_defense_asm_aggregated { }
/Common/websecurity { }
RD_000_VS_STD_APPAOTEL1_443_tls_server {
context clientside
}

/Common/http2 {
context clientside
}
+++
It means http-profile on client- and server-side.
http2-profile on client-side only!
No httprouter-profile!

**Comment by joebride** [comment]
This should be the expected target AS3-syntax (ingress=client-side):

"profileHTTP2": {
                "ingress": {
                  "bigip": "/Common/http2"
                }
              },

**Comment by dstokesf5** [comment]
Thank you for your feedback. This has been added to our internal product backlog as AUTOTOOL-1512.

**Comment by dstokesf5** [comment]
This has been resolved as part of the 3.20.0 release.
