### ISSUE TITLE
Add support for monitorType external in GSLB_Monitor

### ISSUE THREAD

**Issue by DaanOlbrechts** [F5Networks/f5-appsvcs-extension#259]
### Is your feature request related to a problem? Please describe.
To enable HTTPS SNI-enabled healthchecks for AS3 GSLB pools I want to use the "external" monitor type for GSLB monitors but this option does not exist.

### Describe the solution you'd like
Add monitorType external for GSLB_Monitor, similar to how the LTM "Monitor" has a more specific "Monitor_External".

**Comment by dstokesf5** [comment]
Closing as duplicate of #160.

**Comment by dstokesf5** [comment]
Actually, keeping this open. I misunderstood the request. This is actually to create an external GSLB monitor with AS3 instead of just referencing one, right?

**Comment by DaanOlbrechts** [comment]
Exactly!

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this to our internal product backlog as AUTOTOOL-1571.

**Comment by dstokesf5** [comment]
This issue has been resolved with the 3.30.0 release of AS3.
