### ISSUE TITLE
Error after upgrading from AS3 3.2.0 to 3.3.0 when modifying an existing pool

### ISSUE THREAD

**Issue by JosephPJordan** [F5Networks/f5-appsvcs-extension#26]
##### ISSUE TYPE

 - Known Issue

##### AS3 BUILD/ VERSION

```
AS3 v3.3.0
```

##### BIGIP VERSION

```
All supported BIG-IP versions
```

##### SUMMARY

When sending a POST request to the declare endpoint using a declaration that results in modifications to an existing pool, AS3 attempts to create the pool instead of applying the modification. Upgrading from 3.2.0 to 3.3.0 triggers a modification to pools to add auto-discovery related metadata.

##### SYMPTOM

A POST request to the declare endpoint results in a 422 status code response containing a message about a pool already existing. Example message: “The requested Pool (/AS3/https_waf/pool) already exists in partition AS3”.

##### WORKAROUND

Delete the tenant through the declare endpoint, and retry the POST request that generated the error.

**Comment by mdditt2000** [comment]
Hi @JosephPJordan 

Issues resolved in upcoming AS3.4 release scheduled for early September
