### ISSUE TITLE
Unable to set Unclean Shutdown or Secure Renegotiation v3.18.0

### ISSUE THREAD

**Issue by hedrickbt** [F5Networks/f5-appsvcs-extension#262]
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#nat-source-translation-portblockallocation

Neither the SSL Profile | Server (TLS_Server) nor the SSL Profile | Client (TLS_Client) appears to include options for Unclean Shutdown or Secure Renegotiation.

For Unclean Shutdown, I know historically this was necessary for IE.  IIRC, it was still needed for IE11.
RE: K14783: Overview of the Client SSL profile (11.x - 15.x)
https://support.f5.com/csp/article/K14783

**Comment by dstokesf5** [comment]
It looks like `secure-renegotiation` is an option on `ltm profile client-ssl` and `ltm-profile-server-ssl` tmsh objects. While `unclean-shutdown` is only available on `ltm profile client-ssl`. Do you just need these two objects exposed for `ltm profile client-ssl` objects? Or do you also need `secure-renegotiation` on `ltm profile server-ssl` objects?
