### ISSUE TITLE
support for building shared object port lists

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-appsvcs-extension#269]
### Is your feature request related to a problem? Please describe.
Was attempting to automate deployment of services where multiple service ports are associated with a single virtual server.

### Describe the solution you'd like
create AS3 objects for shared port lists.
TMSH example: 
`tmsh create ltm traffic-matching-criteria alpha_ftpse_tmc_obj { destination-address-inline 10.0.0.10/32 destination-port-list ftp_ftpse_ports protocol tcp source-address-inline 0.0.0.0 }`

### Describe alternatives you've considered
I was forced to use TMSH to build the configurations as I'd need to build shared port list manually.

**Comment by dstokesf5** [comment]
How many ports do you want to use with a single virtual server? Would defining multiple applications with a shared IP work for your use case?
```json
{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "Tenant": {
        "class": "Tenant",
        "ApplicationOne": {
            "class": "Application",
            "template": "generic",
            "VipOne": {
                "class": "Service_HTTP",
                "virtualPort": 80,
                "virtualAddresses": [
                   "192.0.2.1"
                ]
            },
            "VipTwo": {
                "class": "Service_HTTP",
                "virtualPort": 8080,
                "virtualAddresses": [
                   "192.0.2.1"
                ]
            }
        }
    }
}
```

**Comment by ajgerace** [comment]
Sorry I thought I had included the port configuration.  In the example above the request was for  ~ 100 ports 
`tmsh create net port-list ftp_ftpse_ports ports add { 21 39000-39100 }
tmsh create net port-list ftpsi_ports ports add { 990 39101-39200 }
`

**Comment by dstokesf5** [comment]
Thank you, that port list configuration is very helpful. It also makes it clear that the solution I proposed does not work well for your use case.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This has been added to our internal product backlog as AUTOTOOL-1573.

**Comment by LeonardosGitHub** [comment]
+1 for this request

**Comment by raZorTT** [comment]
+ 1

**Comment by dstokesf5** [comment]
Unfortunately, there are still several BIG-IP bugs that prevent AS3 from configuring address lists and port lists. We cannot provide a robust user experience for this feature until the following bugs are resolved:
* 931797
* 872981
* 934133

**Comment by antonywm** [comment]
voted up.

Creating shared address and port lists (like the 'Shared Objects' section in the GUI, and being able to attach to a virtual server.

**Comment by grf5** [comment]
I have an immediate need for this feature as well.

**Comment by poly68** [comment]
Good day - This feature would be very Valuable, I have multiple use cases for this now.

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com

**Comment by 21buckets** [comment]
@mdditt2000 Can this issue be re-opened and looked into again?

**Comment by thepowercoders** [comment]
@21buckets - you can do this in AS3 if you have AFM (F5 Firewall) enabled. If you do, you can use the classes: Firewall_Address_List and Firewall_Port_List. Both of these allow you to define IP address lists and port lists which, when added, are actually are placed in the Shared Objects part of the config - so can also be used for virtual servers.

Example:
```
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.43.0",
        "Test01": {
            "class": "Tenant",
            "App01": {
                "class": "Application",
                "template": "shared",
                "shared-port-list": {
                    "class": "Firewall_Port_List",
                    "ports": [
                        80,
                        443
                    ]
                }
            }
        }
    }
}
```

Creates this:
![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/32461620/18c33563-a5c8-431f-8a44-a19c72c07560)

which can then be used in a VS:
![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/32461620/3bb6b088-dfb7-49d5-81c1-da90eebb55ff)

**Comment by mdditt2000** [comment]
@21buckets @thepowercoders no need to reopen this issue. AS3 can already create those objects, you just can't refer to them from a virtual yet. However referring the virtual is coming in AUTOTOOL-3821 Hopefully AS3-46

**Comment by 21buckets** [comment]
> @21buckets - you can do this in AS3 if you have AFM (F5 Firewall) enabled. If you do, you can use the classes: [Firewall_Address_List](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#firewall-address-list) and [Firewall_Port_List](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#firewall-port-list). Both of these allow you to define IP address lists and port lists which, when added, are actually are placed in the Shared Objects part of the config - so can also be used for virtual servers.
> 
> Example:
> 
> ```
> {
>     "class": "AS3",
>     "action": "deploy",
>     "persist": true,
>     "declaration": {
>         "class": "ADC",
>         "schemaVersion": "3.43.0",
>         "Test01": {
>             "class": "Tenant",
>             "App01": {
>                 "class": "Application",
>                 "template": "shared",
>                 "shared-port-list": {
>                     "class": "Firewall_Port_List",
>                     "ports": [
>                         80,
>                         443
>                     ]
>                 }
>             }
>         }
>     }
> }
> ```
> 
> Creates this: ![image](https://user-images.githubusercontent.com/32461620/241162885-18c33563-a5c8-431f-8a44-a19c72c07560.png)
> 
> which can then be used in a VS: ![image](https://user-images.githubusercontent.com/32461620/241163091-3bb6b088-dfb7-49d5-81c1-da90eebb55ff.png)

@thepowercoders - appreciate this info... Is there any reason for the requirement for AFM? Shared Objects can be consumed via an LTM only virtual server. My lab environment doesn't have AFM provisioned yet the `Shared Objects` menu is available.

![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/39548246/e3af9012-5fb5-4344-bb83-00d46b5c55d8)

![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/39548246/185dc261-fe31-42b9-80ac-fddb3b613081)

**Comment by 21buckets** [comment]
I've answered my own question on this one..

I can see AS3 is using the `security firewall port-list` tmsh command to create the object, rather than the `net port-list` command that is compatible with LTM, which is why the AFM module is required.

@mdditt2000 - Would it be possible to implement the functionality using this command?

`tmsh create net port-list myPortList ports add { 80 443}`

https://clouddocs.f5.com/cli/tmsh-reference/v15/modules/net/net_port-list.html

**Comment by mdditt2000** [comment]
@21buckets you right net port-list is current NOT in AS3. I will create a new JIRA task for this.

**Comment by mdditt2000** [comment]
@21buckets @thepowercoders Created AUTOTOOL-3881 "Add support for Net Port-list when no AFM is provisioned" - Added to the next sprint.

**Comment by petliura** [comment]
@mdditt2000, any updates on the port list functionality? you adding the same functionality for address lists? when is the ability to reference shared objects in virtual server declarations coming?

**Comment by nickamon** [comment]
Why is this closed w/o any comment on the resolution status?  Is this being tracked in another ticket?  I am trying to use this functionality to no avail.  Please provide an update.

**Comment by mrudel** [comment]
@mdditt2000 @21buckets @thepowercoders any updates on this? we are also trying to use this functionality

**Comment by LeonardosGitHub** [comment]
I believe as of AS3 version 3.46 it can create lists of IP address and ports and apply those to a virtual server.  Here’s an example declaration:
 
 
{
    "class": "ADC",
    "schemaVersion": "3.46.0",
    "id": "Service_Generic",
    "controls": {
      "dryRun": true
    },
    "Sample_misc_02": {
        "class": "Tenant",
        "Application": {
            "class": "Application",
            "generic_virtual": {
                "class":"Service_Generic",
                "sourceAddress": {
                    "use": "sourceList"
                },
                "virtualAddresses": [
                    "192.0.2.100"
                ],
                "virtualPort": {
                        "use": "portList"
                    }
            },
            "sourceList": {
                "class": "Net_Address_List",
                "addresses": [
                    "10.3.10.10-10.9.10.10",
                    "192.0.2.0/24",
                    "198.51.100.0/24"                ]
            },
            "portList": {
                "class": "Net_Port_List",
                "ports": [
                    "1-999"
                ]
            }
        }
    }
}
