### ISSUE TITLE
service_generic class ClientSSL Profile

### ISSUE THREAD

**Issue by roefe** [F5Networks/f5-appsvcs-extension#272]
we would like to use just one AS3 class for defining services, no matter if they are http(s) or tcp. this supports the automation approach.
Right now we have the issue, that we can not assign a ClientSSL profile to a class which uses the service_generic class.

### Describe the solution you'd like
there should be a feature partity for service configuration in TMSH and AS3

### Describe alternatives you've considered
We considered to use misc. templates, but this makes the automation approach more complex.

### Additional context
-

**Comment by daniesch** [comment]
@dstokesf5

**Comment by dstokesf5** [comment]
The Service_Generic class is actually meant for configuring ip-other virtual servers. In hindsight, that name is misleading. I think this is a useful idea and I have added it to our internal product backlog as AUTOTOOL-1683.

Thank you for your feedback.

**Comment by daniesch** [comment]
Thanks @dstokesf5 for the feedback.
