### ISSUE TITLE
Add TLS_Server option to enable/disable "default profile for SNI"

### ISSUE THREAD

**Issue by fustilarian01** [F5Networks/f5-appsvcs-extension#274]
### Is your feature request related to a problem? Please describe.
TLS_Server declarations don't have an option to enable or disable using a client SSL profile as the SNI default, however that option is set to "true" by default and there is no way to disable it.

### Describe the solution you'd like
Add an option to enable/disable the "default profile for SNI" client SSL profile option

### Describe alternatives you've considered
I don't have one, other than manually changing the setting in the GUI, which is not a good option.

### Additional context
Out of our ~100 client SSL profiles we created manually, we have only enabled that option on one or two profiles. Having that enabled by default with no way to disable it is less than ideal and won't work for our declarations.

**Comment by dstokesf5** [comment]
I believe that setting is mostly used when attaching multiple certificates to a virtual server. This is done in AS3 by attaching multiple certificates to a TLS_Server objec, and attaching that single object to a servicet: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#using-multiple-ssl-tls-certificates-in-a-single-profile

Behind the scenes, AS3 will generate an ssl profile for each certificate and handle attaching the multiple profiles to a virtual server. The first certificate is used as the SNI default, all the other generated profiles have the tmsh property `sni-default` set to false.

Do you have a use case that is not handled by this behavior?

**Comment by fustilarian01** [comment]
@dstokesf5 I do: making app-specific changes to SSL profiles used for SNI on a virtual server. Even if that isn't considered a valid use case, is there a reason to enable it by default? Is there a reason for not including it as a property that can be changed?

**Comment by dstokesf5** [comment]
I am still having a difficult time understanding your use case. Do you have some example tmsh configuration for the virtual server, ssl profile, and certificates? It is my understanding that if you only have one certificate attached to a virtual server, then it should not matter what the `sni-default` property is set to. If you have multiple certificates, then AS3 should be able to manage this property for you.

**Comment by mdditt2000** [comment]
Default SNI should be false in AS3 simular to BIG-IP. This is a bug. Changing the default SNI to default AUTOTOOL-3606 using the sni-default property in AS3-44
