### ISSUE TITLE
Unable to edit the pool member port number when the member is added using service discovery

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#276]
### Environment
 * Application Services Version: 3.19.1
 * BIG-IP Version:15.1

### Summary
Unable to edit the pool member port number when the member is added using service discovery using update AS3 operation.

### Steps To Reproduce
1. Submit the following declaration to configure service discovery endpoint :
```json
{
  "class": "ADC",
  "schemaVersion": "3.19.0",
  "Part1": {
    "App1": {
      "class": "Application",
      "template": "udp",
      "serviceMain": {
        "class": "Service_UDP",
        "virtualPort": 1234,
        "virtualAddresses": [
          "1.2.3.4"
        ],
        "pool": "Pool1"
      },
      "Pool1": {
        "class": "Pool",
        "monitors": [
          "icmp"
        ],
        "members": [
          {
            "servicePort": 8080,
            "serverAddresses": []
          },
          {
            "addressDiscovery": "event",
            "servicePort": 8080
          }
        ]
      },
      "constants": {
        "class": "Constants",
        "serviceCenterEPG": {
          "Pool1": {
            "tenant": "Demo",
            "application": "AppProfile",
            "epg": "EPG-Internal1"
          }
        },
        "appsvcsFormData": {
          "virtual_port::integer": 1234,
          "virtual_address": "1.2.3.4",
          "server_port::integer": 8080,
          "server_addresses::array": [],
          "template_name": "simple_udp"
        }
      }
    },
    "class": "Tenant"
  },
  "id": "22323668-c652-4689-81ee-ded9dffd0c5c",
  "controls": {
    "class": "Controls",
    "userAgent": "ServiceCenter/2.4 ACI/4.2(3l)"
  }
}
```
2. Submit the list of endpoint to service discovery ep : https://BIGIP/mgmt/shared/service-discovery/task/~Part1~App1~Pool1/nodes
List : [{'ip': '10.11.10.20', 'id': '10.11.10.20'}, {'ip': '10.11.10.15', 'id': '10.11.10.15'}, {'ip': '10.11.10.19', 'id': '10.11.10.19'}, {'ip': '10.11.10.21', 'id': '10.11.10.21'}, {'ip': '10.11.10.13', 'id': '10.11.10.13'}, {'ip': '10.11.10.16', 'id': '10.11.10.16'}, {'ip': '10.11.10.18', 'id': '10.11.10.18'}, {'ip': '10.11.10.14', 'id': '10.11.10.14'}, {'ip': '10.11.10.100', 'id': '10.11.10.100'}, {'ip': '10.11.10.12', 'id': '10.11.10.12'}, {'ip': '10.11.10.17', 'id': '10.11.10.17'}]

Verify the endpoints are learnt and added as pool members with port 8080.

3. Edit the AS3 config to change the port number to 8099
```json
{
  "class": "ADC",
  "schemaVersion": "3.19.0",
  "Part1": {
    "App1": {
      "class": "Application",
      "template": "udp",
      "serviceMain": {
        "class": "Service_UDP",
        "virtualPort": 1234,
        "virtualAddresses": [
          "1.2.3.4"
        ],
        "pool": "Pool1"
      },
      "Pool1": {
        "class": "Pool",
        "monitors": [
          "icmp"
        ],
        "members": [
          {
            "servicePort": 8080,
            "serverAddresses": []
          },
          {
            "addressDiscovery": "event",
            "servicePort": 8099
          }
        ]
      },
      "constants": {
        "class": "Constants",
        "serviceCenterEPG": {
          "Pool1": {
            "tenant": "Demo",
            "application": "AppProfile",
            "epg": "EPG-Internal1"
          }
        },
        "appsvcsFormData": {
          "virtual_port::integer": 1234,
          "virtual_address": "1.2.3.4",
          "server_port::integer": 8080,
          "server_addresses::array": [],
          "template_name": "simple_udp"
        }
      }
    },
    "class": "Tenant",
    "optimisticLockKey": "lrasNEqMAszgQX3HTyHsYzSHRUinBB/sKKmrTcU08vE="
  },
  "id": "253229be-f2a7-4103-957a-1797536766c1",
  "controls": {
    "class": "Controls",
    "userAgent": "ServiceCenter/2.4 ACI/4.2(3l)"
  }
}
```
Post this change, when submitted same list of endpoints again, it returns 200 as response but the pool members port is not changed to 8099.

Note : Verified above steps on As3 3.17.1 and observed it to be working fine with pool members ports getting updated to 8099.

### Expected Behavior
After the last step, old pool member should have got deleted and new pool members with port 8099 should have got added.

### Actual Behavior
Pool members port is not changed to 8099

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by dstokesf5** [comment]
Thank you for reporting this bug. I have confirmed it and added it to our internal product backlog as AUTOTOOL-1666.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
