### ISSUE TITLE
Bug in AS3: impossible to configure "ltm profile server-ssl" with options 'none'

### ISSUE THREAD

**Issue by p-semenov-f5** [F5Networks/f5-appsvcs-extension#277]
Hello!
 
Found another problem in AS3.
 
Right now we have about 14 options in field options of client-ssl and server-ssl profiles.
But only part of them are covered by AS3.
 
Setting options to ‘none’ means enable part of them in AS3, because some AS3 values are inverted.
 
None =   "tls1_0Enabled": true,
                "tls1_1Enabled": true,
                "tls1_2Enabled": true,
                **"tls1_3Enabled": true,**                                              <--
                "singleUseDhEnabled": false,
                **"insertEmptyFragmentsEnabled": true**                   <--

Right now it is impossible to use both selected options in AS3 in true state.
 
There will be an error.
 
No such error in “ltm profile client-ssl”

### Environment
 * Application Services Version: AS 3.20
 * BIG-IP Version: 15.0.1.3

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "ADC",
    "schemaVersion": "3.17.0",
    "id": "urn:uuid:ab7f4832-2a95-49c2-a41c-9365bf615d82",
    "label": "Converted Declaration",
    "remark": "Auto-generated by Project Charon",
    "AS3_Tenant": {
        "class": "Tenant",
        "AS3_Application": {
            "class": "Application",
            "template": "generic",
            "customCipherGroup_1": {
                "allowCipherRules": [
                    {
                        "bigip": "/Common/f5-secure"
                    }
                ],
                "class": "Cipher_Group"
            },
            "certificate_default": {
                "class": "Certificate",
                "certificate": {
                    "bigip": "/Common/default.crt"
                },
                "privateKey": {
                    "bigip": "/Common/default.key"
                }
            },
            "test_serverssl_3": {
                "trustCA": "generic",
                "clientCertificate": "certificate_default",
                "cipherGroup": {
                    "use": "/AS3_Tenant/AS3_Application/customCipherGroup_1"
                },
                "class": "TLS_Client",
                "tls1_0Enabled": true,
                "tls1_1Enabled": true,
                "tls1_2Enabled": true,
                "tls1_3Enabled": true,
                "singleUseDhEnabled": false,
                "insertEmptyFragmentsEnabled": true
            }
        }
    }
}
 

```

2. Observe the following error response:
```json

    "results": [
        {
            "code": 422,
            "message": "declaration failed",
            "response": "\\\"peer-cert-mode\\\" unexpected argument",
            "host": "localhost",
            "tenant": "AS3_Tenant",
            "runTime": 2082
        }
    ],

```

### Expected Behavior
AS3 should be applied. Because config works well.
```
#TMSH-VERSION: 15.0.1.3

ltm cipher group /AS3_Tenant/AS3_Application/customCipherGroup_1 {
    allow {
        /Common/f5-secure { }
    }
}
ltm profile server-ssl /AS3_Tenant/AS3_Application/test_serverssl_3 {
    app-service none
    ca-file /Common/ca-bundle.crt
    cert /Common/default.crt
    chain none
    cipher-group /AS3_Tenant/AS3_Application/customCipherGroup_1
    ciphers none
    key /Common/default.key
    options none
}
```

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by dstokesf5** [comment]
Thank you for reporting this bug, it looks like we are incorrectly generating the tmsh cli script in this case. I have added AUTOTOOL-1629 to our internal backlog to fix this issue.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
