### ISSUE TITLE
Dynamic EP discovery doesnt work if Duplicate IP exists under pre-existing AS3 configuration.

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-extension#287]
### Environment
 * Application Services Version: 3.19.1
 * BIG-IP Version:15.1

### Summary
In case when user posts duplicate IPs to service discovery endpoint for 2 different BigIP Partitions/Apps, one of them succeeds and the other operations ends up with the duplicate IP staying absent in pool.
This is acceptable as BigIP doesn't support duplicate IP. However, after this, even if a valid and unique IP is posted to service discovery endpoint, that doesn't work. It only gets added as a node but fails to make it to desired pool as a pool member.

### Steps To Reproduce

1.On BigIP, submit the list of endpoints to service discovery endpoint under a partition/App/Pool PK02/A1/web_pool: https://BIGIP/mgmt/shared/service-discovery/task/~PK_02~A1~web_pool
[{"id":"/PK_02/28.28.2.3","ip":"28.28.2.3"},{"id":"/PK_02/28.28.2.2","ip":"28.28.2.2"},{"id":"/PK_02/28.28.2.1","ip":"28.28.2.1"},{"id":"/PK_02/13.14.15.17","ip":"13.14.15.17"},{"id":"/PK_02/13.14.15.18","ip":"13.14.15.18"},{"id":"/PK_02/13.14.16.19","ip":"13.14.16.19"},{"id":"/PK_02/13.14.15.22","ip":"13.14.15.22"}]}

2.On same BigIP,submit one more list of endpoints - but containing a duplicate IP 13.14.15.22 -  to service discovery ep on second partition/App/pool PK_04/A1/web_pool: https://BIGIP/mgmt/shared/service-discovery/task/~PK_04~A1~web_pool
[{"ip":"30.30.2.3","id":"/PK_04/30.30.2.3"},{"ip":"30.30.2.2","id":"/PK_04/30.30.2.2"},{"ip":"13.14.15.20","id":"/PK_04/13.14.15.20"},{"ip":"13.14.15.19","id":"/PK_04/13.14.15.19"},{"ip":"30.30.2.1","id":"/PK_04/30.30.2.1"},{"id":"/PK_04/13.14.15.21","ip":"13.14.15.21"},{"id":"/PK_04//PK_02/13.14.15.22","ip":"13.14.15.22"},{"id":"/PK_04/13.14.15.23","ip":"13.14.15.23"},{"id":"/PK_04/33.34.45.67","ip":"33.34.45.67"}]}

3. After step 2, any new ip - unique IP - when added to partition/App/pool PK_04/A1/web_pool resulted only in a corresponding node creation but failed to create pool member.
This issue persisted till the duplicate entry was present.

4. After removing the duplicate IP entry from service discovery endpoint and the partition, the subsequent Attach/Detach operations worked properly.

Additional Observation-
Similar behavior is observed when instead of duplicate IP,, a non-supported IP format like 1.2.3.4/24 exists in the node list.

Submit the list of endpoints as below:
[{"id":"/PK_02/28.28.2.3","ip":"28.28.2.3"},{"id":"/PK_02/28.28.2.2","ip":"28.28.2.2"},{"id":"/PK_02/28.28.2.1","ip":"28.28.2.1"},{"id":"/PK_02/13.14.15.17","ip":"13.14.15.17"},{"id":"/PK_02/13.14.15.18","ip":"13.14.15.18"},{"id":"/PK_02/13.14.16.19","ip":"13.14.16.19"},{"id":"/PK_02/13.14.15.22/24","ip":"13.14.15.22/24"}]

### Expected Behavior
-AS3 to allow all unique IPs to get added to configured pool except the duplicate IP.

### Actual Behavior
Unique IPs - as endpoint list - added after duplicate ip event are added only as node however not as pool members in respective partition

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by dstokesf5** [comment]
I have confirmed this bug and added it to our internal product backlog as AUTOTOOL-1677.

As a work-around, you can add `"shareNodes": true` to your member declarations.
