### ISSUE TITLE
AS3 accepts Common tenant with no class keyword

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-appsvcs-extension#291]
### Environment
 * Application Services Version: 3.20
 * BIG-IP Version: 15.1

### Summary
I have a declaration that consists of /Common/Shared items and tenant items. I post the declaration and it works great. All items are created. I can GET /declare and see all items. However, when I delete the tenant, then my GET no longer shows the Shared items as it seems be tied to declaration. But...the BIG-IP objects and Shared tenant still remain. 

### Steps To Reproduce
1. Submit the following declaration for Shared AND tenant all in one declaration:
```json
{
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.20.0",
    "id": "123abc",
    "label": "Sample 1",
    "remark": "An HTTPS sample application",
    "controls": {
      "trace": true
    },
    "Common": {
      "Shared": {
        "class": "Application",
        "template": "shared",
        "monitor_respond_200": {
          "class": "iRule",
          "iRule": "when HTTP_REQUEST {\n   HTTP::respond 200 System Responding \n}\n"
        },
        "lb_external_probe": {
          "class": "Service_HTTP",
          "remark": "LB Health Probe for External Forwarding Rule",
          "virtualPort": 40000,
          "virtualAddresses": [
            "34.10.12.3"
          ],
          "shareAddresses": true,
          "iRules": ["monitor_respond_200"]
        }
      }
    },
    "Sample_01": {
      "class": "Tenant",
      "A1": {
        "class": "Application",
        "template": "http",
        "serviceMain": {
          "class": "Service_HTTP",
          "virtualAddresses": [
            "34.10.12.3"
          ],
          "shareAddresses": true,
          "pool": "web_pool"
        },
        "web_pool": {
          "class": "Pool",
          "monitors": [
            "tcp"
          ],
          "members": [{
            "servicePort": 80,
            "addressDiscovery": "fqdn",
            "autoPopulate": true,
            "hostname": "httpbin.org"
          }]
        }
      }
    }
  }
}
```
2. Do a GET /declare and you will see Shared AND tenant items
3. Do a DELETE /declare (do not specify tenant and do not provide payload)
4. Do a GET /declare and all items are gone even the Shared. But...shared items remain if you look in the GUI or on tmsh CLI. In fact, shared never shows up when you look at GET /declare UNLESS you posted shared stuff in same declaration as tenant.
5. If you want to delete /Shared, then see https://github.com/F5Networks/f5-appsvcs-extension/issues/290

### Expected Behavior
Since Shared items are not actually being deleted via DELETE /declare, they should be visible via GET /declare. I have tried to view shared with /declare, /declare/Common, /declare/Common/Shared, /declare/Shared...but blank.

### Actual Behavior
I delete tenant with DELETE /declare and the Shared items no longer return in payload json. However, they are indeed in the BIG-IP configs.

Other questions:
1. How do you view Shared items?

Other behavior:
If you post a declaration for Shared separately and do a GET /declare...nothing. Then you post with the tenant and do GET /declare...you see only tenant. So...separating the declaration of Shared items into separate request no longer shows you Shared items when you GET /declare.

**Comment by JeffGiroux** [comment]
After testing and talking internally, a DELETE to /declare should delete all...even Shared items. That is not the case for me in my testing. This seems to be directly related to my declaration and classes within. 

BAD -- this will post successfully, but not show in GET. Items in the big-ip are created and remain even with a DELETE /declare.
```
{
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.20.0",
    "id": "123abc",
    "label": "Sample 1",
    "remark": "An HTTPS sample application",
    "controls": {
      "trace": true
    },
    "Common": {
      "Shared": {
        "class": "Application",
        "template": "shared",
        "monitor_respond_200": {
          "class": "iRule",
          "iRule": "when HTTP_REQUEST {\n   HTTP::respond 200 System Responding \n}\n"
        },
        "lb_external_probe": {
          "class": "Service_HTTP",
          "remark": "LB Health Probe for External Forwarding Rule",
          "virtualPort": 40000,
          "virtualAddresses": [
            "34.10.12.1"
          ],
          "iRules": ["monitor_respond_200"]
        },
        "lb_internal_probe": {
          "class": "Service_TCP",
          "remark": "LB Health Probe for Internal Forwarding Rule",
          "virtualPort": 40000,
          "virtualAddresses": [
            "10.1.10.106"
          ]
        }
      }
    }
  }
}
```

Good -- this POSTS successfully, it does show as GET, items on BIG-IP are created, and when you DELETE, items on BIG-IP are also deleted
```
{
    "class": "ADC",
    "schemaVersion": "3.13.0",
    "controls": {
        "logLevel": "debug"
    },
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "service": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "192.0.2.1"
                ]
            }
        }
    }
}
```

**Comment by JeffGiroux** [comment]
Ok, quick troubleshooting. Added class tenant and it worked. Schema validation should have failed without this. It did not, took my POST, and declared. 

```
    "Common": {
        "class": "Tenant",
```

**Comment by dstokesf5** [comment]
Added the fixing of the validation to our internal product backlog as AUTOTOOL-1660.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
