### ISSUE TITLE
Pool members deleted directly from BIG-IP dont get added automatically when synced on AS3 service discovery endpoint

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-extension#293]
### Environment
 * Application Services Version: 3.19.1
 * BIG-IP Version:15.1

### Summary
Pool members deleted directly from BIG-IP dont get added automatically when synced on AS3 service discovery endpoint

### Steps To Reproduce
1.Configured As3 service discovery endpoint and added nodes to it-

[{"ip":"12.12.1.4","id":"/lcc_partition2/12.12.1.4"},{"ip":"12.12.1.1","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.8","id":"/lcc_partition2/12.12.1.8"},{"ip":"12.12.1.5","id":"/lcc_partition2/12.12.1.5"},{"ip":"12.12.1.3","id":"/lcc_partition2/12.12.1.3"},{"ip":"12.12.1.2","id":"/lcc_partition2/12.12.1.2"},{"ip":"12.12.1.10","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.9","id":"/lcc_partition2/12.12.1.9"},{"ip":"12.12.1.7","id":"/lcc_partition2/12.12.1.7"},{"ip":"12.12.1.6","id":"/lcc_partition2/12.12.1.6"}]

2.Delete the pool members and node directly from BIGIP  for e.g:

12.12.1.1:9090
12.12.1.3::9090
12.12.1.5:9090

3.Post the same endpoints as step 1 to sync on service discovery endpoints-

[{"ip":"12.12.1.4","id":"/lcc_partition2/12.12.1.4"},{"ip":"12.12.1.1","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.8","id":"/lcc_partition2/12.12.1.8"},{"ip":"12.12.1.5","id":"/lcc_partition2/12.12.1.5"},{"ip":"12.12.1.3","id":"/lcc_partition2/12.12.1.3"},{"ip":"12.12.1.2","id":"/lcc_partition2/12.12.1.2"},{"ip":"12.12.1.10","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.9","id":"/lcc_partition2/12.12.1.9"},{"ip":"12.12.1.7","id":"/lcc_partition2/12.12.1.7"},{"ip":"12.12.1.6","id":"/lcc_partition2/12.12.1.6"}]

4. Observation - After step 3 the deleted nodes/pool members from step 2 are not added on BIGIP pool member 

### Expected Behavior
Pool members deleted directly from BIG-IP should get added automatically when synced on AS3 service discovery endpoint

### Actual Behavior
Pool members deleted directly from BIG-IP do not get added automatically when synced on AS3 service discovery endpoint

**Comment by vishwajeetgslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by vishwajeetgslab** [comment]
Adding one more observation, Endpoints added directly on BIGIP should get deleted once the AS3 sync data for that pool is posted on As3 service discovery endpoint


Steps-
Steps to reproduce the behavior:
1.Configured As3 service discovery endpoint and added nodes to it-

[{"ip":"12.12.1.4","id":"/lcc_partition2/12.12.1.4"},{"ip":"12.12.1.1","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.8","id":"/lcc_partition2/12.12.1.8"},{"ip":"12.12.1.5","id":"/lcc_partition2/12.12.1.5"},{"ip":"12.12.1.3","id":"/lcc_partition2/12.12.1.3"},{"ip":"12.12.1.2","id":"/lcc_partition2/12.12.1.2"},{"ip":"12.12.1.10","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.9","id":"/lcc_partition2/12.12.1.9"},{"ip":"12.12.1.7","id":"/lcc_partition2/12.12.1.7"},{"ip":"12.12.1.6","id":"/lcc_partition2/12.12.1.6"}]


2.Added 2 more nodes on BIGIP to same pool-
12.12.1.19:9090
12.12.1.20:9090

3.Posted the same endpoints as step 1 to sync on service discovery endpoints-
[{"ip":"12.12.1.4","id":"/lcc_partition2/12.12.1.4"},{"ip":"12.12.1.1","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.8","id":"/lcc_partition2/12.12.1.8"},{"ip":"12.12.1.5","id":"/lcc_partition2/12.12.1.5"},{"ip":"12.12.1.3","id":"/lcc_partition2/12.12.1.3"},{"ip":"12.12.1.2","id":"/lcc_partition2/12.12.1.2"},{"ip":"12.12.1.10","id":"/lcc_partition2/12.12.1.10"},{"ip":"12.12.1.9","id":"/lcc_partition2/12.12.1.9"},{"ip":"12.12.1.7","id":"/lcc_partition2/12.12.1.7"},{"ip":"12.12.1.6","id":"/lcc_partition2/12.12.1.6"}]

4.Observation- nodes/pool members added in step 2 are not getting deleted from BIGIP pool after sync data in step 3 is posted on service discovery endpoint.

Expected Behavior-

As3 should overwrite the synced endpoints and remove manually added endpoints 

Actual Behavior-

AS3 is not deleting the manually added endpoints on BIGIP upon As3 sync data posted on As3 service discovery endpoint

**Comment by dstokesf5** [comment]
Thank you for reporting this bug. I have confirmed it and added it to our internal product backlog as AUTOTOOL-1667.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
