### ISSUE TITLE
Support for permanent Service_Address objects

### ISSUE THREAD

**Issue by jussisjostrom** [F5Networks/f5-appsvcs-extension#294]
### Is your feature request related to a problem? Please describe.
When deploying forwarding virtual servers, a Service_Address object for some prefix (example 0.0.0.0/0) must be created separately, so that ARP and ICMP-echo can be disabled for that object. When such an object will be used by multiple tenants, the Service_Address object is first created in /Common/Shared declaration, and can then be referenced from the other tenants' Service declarations using pointers.

Problem is that in this scenario, when the last tenant Service (vs) referencing to that Service_Address is deleted, also the Service_Address in /Common/Shared is deleted.

This causes subsequent posts of new tenants' declarations referring to this Service_Address object to fail, because the object is no longer in /Common/Shared.

Example declarations:
In tenant /Common:
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
               "vaAny_ipv4": {
                    "class": "Service_Address",
                    "arpEnabled": false,
                    "icmpEcho": "disable",
                    "routeAdvertisement": "disable",
                    "virtualAddress": "0.0.0.0/0"
                },
...
Then in a tenant:
        "APN01": {
            "class": "Tenant",
            "defaultRouteDomain": 0,
            "GiLAN": {
                "class": "Application",
                "template": "generic",
                "vsANY_out": {
                    "class": "Service_L4",
                    "label": "Default VS for any",
                    "layer4": "any",
                    "translateServerAddress": false,
                    "translateServerPort": false,
                    "virtualAddresses": [
                        **{"bigip": "/Common/Shared/vaAny_ipv4"}**
                    ],
                    "shareAddresses": true,
                    "allowVlans": [
                        { "bigip":"/Common/VLANNAME" }
                    ],
                    "virtualPort": 0,
                    "profileL4": { "bigip": "/Common/Shared/fastL4any" },
                    "snat": "none",
                    "policyNAT": {"use": "cgnat_policy"},
                    "persistenceMethods": []
                },

Later, when the APN01 tenant is deleted for whatever reason, the Service_Address /Common/Shared/vaAny_ipv4 is also deleted as side-effect, even if declared in different tenant and shareAddresses is true in the Services (tested on 3.20). 
After this, when either the deleted tenant is recreated using same declaration, or a new tenant also using the vaAny_ipv4 is posted, the declaration fails due to the object missing from /Common/Shared.

Workarounds exists, like using dummy vs with a Virtual_Address containing that Service_Address, or instructing ops team to always re-apply the /Common declaration before posting new tenants, but neither are very elegant.

### Describe the solution you'd like
I would like to have an option to mark  Service_Address objects as permanent, ie they would not be deleted even if the last virtual server referencing that Service_Address is deleted. I think it would be useful especially when using AS3 to create forwarding virtual servers for different tenants, who very often need to have destination any (either IPv4 or IPv6) and having ARP and ICMP echo disabled for correct function.
This feature would improve the idempotency for AS3 when you split the configuration over multiple AS3-files (one for Common, one for the tenant(s)), so that there is no need to re-apply the Common declaration if you have deleted the last non-common tenants from the device.

### Describe alternatives you've considered
Using a dummy Service that "holds" the Service_Address in /Common to prevent it from being deleted. 
Also considered to instruct operators to always first re-apply existing /Common declaration before posting new tenants.

**Comment by dstokesf5** [comment]
We have AUTOTOOL-1657 in our internal product backlog to look into disabling this auto-delete behavior for virtual-address objects.
