### ISSUE TITLE
AS3 v3.5 - Declaration fails with duplicate values in members

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-appsvcs-extension#30]
##### ISSUE TYPE

 - Bug Report
 

##### AS3 BUILD/ VERSION
```
Build 3 / version 3.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.8
  Build       0.0.3
  Edition     Point Release 8
  Date        Sat Jun 16 00:03:03 PDT 2018


```

##### SUMMARY

```
Attempting to deploy declaration containing a single application that has 2 pool members.  When I deploy I receive an error 'declaration has duplicate values in members'.  If I remove a single member the declaration deploys.  I have tried different IPs for the pool members and receive same error. This declaration worked using version 3.4.

```

##### STEPS TO REPRODUCE

POST a declaration that contains a pool with more than 1 member

```
{
    "action": "deploy", 
    "class": "AS3", 
    "declaration": {
        "as3_lab": {
            "class": "Tenant", 
                "bodgeit": {
                "class": "Application", 
                "template": "generic", 
                "vs_bodgeit_443": {
                    "class": "Service_HTTPS", 
                    "clientTLS": {
                        "bigip": "/Common/f5demo-serverssl"
                    }, 
                    "iRules": [
                        {
                            "bigip": "/Common/bodgeit-irule"
                        }
                    ], 
                    "persistenceMethods": [
                        {
                            "bigip": "/Common/f5demo-persist-cookie"
                        }
                    ], 
                    "policyWAF": {
                        "bigip": "/Common/bodgeit"
                    }, 
                    "pool": "vs_bodgeit_pool", 
                    "profileHTTP": {
                        "bigip": "/Common/f5demo-http"
                    }, 
                    "profileMultiplex": {
                        "bigip": "/Common/f5demo-oneconnect"
                    }, 
                    "profileTCP": {
                        "egress": {
                            "bigip": "/Common/f5demo-tcp-wan"
                        }, 
                        "ingress": {
                            "bigip": "/Common/f5demo-tcp-lan"
                        }
                    }, 
                    "redirect80": true, 
                    "serverTLS": {
                        "bigip": "/Common/san_cert"
                    }, 
                    "snat": "auto", 
                    "virtualAddresses": [
                        "10.0.1.214"
                    ], 
                    "virtualPort": 443
                }, 
                "vs_bodgeit_pool": { 
                    "class": "Pool", 
                    "monitors":[
                    	{ "bigip": "/Common/f5demo-http-head"}
                    	],
                    "members": [{
                    	"servicePort": 8080,
                    	"serverAddresses": [
                        	"10.128.20.12",
                        	"10.128.20.11"
                    ]
                }]          
                }
            }
        }, 
        "class": "ADC", 
        "id": "as3_lab", 
        "label": "as3_lab", 
        "remark": "This is a sample remark ", 
        "schemaVersion": "3.5.0"
    }, 
    "persist": true
}
```

##### EXPECTED RESULTS

Declaration should deploy successfully

##### ACTUAL RESULTS

Receive 500 error back.

```
{
    "code": 500,
    "declarationFullId": "",
    "message": "declaration has duplicate values in members"
}
```

**Comment by mdditt2000** [comment]
please look at the following example

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/additional-examples.html#example-10-two-applications-sharing-a-pool

You need to add shared to the tenant and then just reference the second pool "pool": "/Sample_10/Shared/dual_pool" - make sure the the path is correct. 

`
"Sample_10": {
      "class": "Tenant",
      "Shared": {
`

**Comment by ajgerace** [comment]
Thanks, but I'm not trying to add a second pool. I'm trying to create a pool with more than one pool member.

**Comment by kaustriaf5** [comment]
@ajgerace do you get the same error using a more basic declaration ( without the non-required props that reference existing /Common objects)?:

```
{
    "action": "deploy", 
    "class": "AS3", 
    "declaration": {
        "as3_lab": {
            "class": "Tenant", 
                "bodgeit": {
                "class": "Application", 
                "template": "generic", 
                "vs_bodgeit_443": {
                    "class": "Service_HTTPS", 


                    "pool": "vs_bodgeit_pool", 

                    "redirect80": true, 
                    "serverTLS": {
                        "bigip": "/Common/san_cert"
                    }, 
                    "snat": "auto", 
                    "virtualAddresses": [
                        "10.0.1.214"
                    ], 
                    "virtualPort": 443
                }, 
                "vs_bodgeit_pool": { 
                    "class": "Pool", 
                    "members": [
                    	{
                    	"servicePort": 8080,
                    	"serverAddresses": [
                        	"10.128.20.12",
                        	"10.128.20.11"
                    ]
                }]          
                }
            }
        }, 
        "class": "ADC", 
        "id": "as3_lab", 
        "label": "as3_lab", 
        "remark": "This is a sample remark ", 
        "schemaVersion": "3.5.0"
    }, 
    "persist": true
}
```

**Comment by ajgerace** [comment]
@kaustria this happens when I try to use 1 or more nodes that reside in the Common partition. If I only want to use 1 node that node can exist in either Common or the tenant partition.  

`root@(vadc06)(cfg-sync Standalone)(Active)(/as3_lab)(tmos)# list ltm  node 
ltm node 10.128.20.17 {
    address 10.128.20.17
    partition as3_lab
}
ltm node 10.128.20.18 {
    address 10.128.20.18
    partition as3_lab
}
ltm node 10.128.20.19 {
    address 10.128.20.19
    partition as3_lab
}
root@(vadc06)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm  node
ltm node server1 {
    address 10.128.20.11
}
ltm node server2 {
    address 10.128.20.12
}
ltm node server3 {
    address 10.128.20.13
}
ltm node server4 {
    address 10.128.20.14
}
ltm node server5 {
    address 10.128.20.15
}
ltm node server6 {
    address 10.128.20.16
}

{
    "action": "deploy", 
    "class": "AS3", 
    "declaration": {
        "as3_lab": {
            "class": "Tenant", 
                "bodgeit": {
                "class": "Application", 
                "template": "generic", 
                "vs_bodgeit2_pool": { 
                    "class": "Pool", 
                    "monitors":[
                    	{ "bigip": "/Common/f5demo-http-head"}
                    	],
                    "members": [{
                    	"servicePort": 8080,
                    	"serverAddresses": [
                        	"10.128.20.11",
                        	"10.128.20.18"
                    ]
                }]          
                }
            }
        }, 
        "class": "ADC", 
        "id": "as3_lab", 
        "label": "as3_lab", 
        "remark": "This is a sample remark ", 
        "schemaVersion": "3.5.0"
    }, 
    "persist": true
}
`
This declaration fails:
`{
    "action": "deploy", 
    "class": "AS3", 
    "declaration": {
        "as3_lab": {
            "class": "Tenant", 
                "bodgeit": {
                "class": "Application", 
                "template": "generic", 
                "vs_bodgeit2_pool": { 
                    "class": "Pool", 
                    "monitors":[
                    	{ "bigip": "/Common/f5demo-http-head"}
                    	],
                    "members": [{
                    	"servicePort": 8080,
                    	"serverAddresses": [
                        	"10.128.20.11",
                        	"10.128.20.18"
                    ]
                }]          
                }
            }
        }, 
        "class": "ADC", 
        "id": "as3_lab", 
        "label": "as3_lab", 
        "remark": "This is a sample remark ", 
        "schemaVersion": "3.5.0"
    }, 
    "persist": true
}`

This one works:
`{
    "action": "deploy", 
    "class": "AS3", 
    "declaration": {
        "as3_lab": {
            "class": "Tenant", 
                "bodgeit": {
                "class": "Application", 
                "template": "generic", 
                "vs_bodgeit2_pool": { 
                    "class": "Pool", 
                    "monitors":[
                    	{ "bigip": "/Common/f5demo-http-head"}
                    	],
                    "members": [{
                    	"servicePort": 8080,
                    	"serverAddresses": [
                        	"10.128.20.17",
                        	"10.128.20.18"
                    ]
                }]          
                }
            }
        }, 
        "class": "ADC", 
        "id": "as3_lab", 
        "label": "as3_lab", 
        "remark": "This is a sample remark ", 
        "schemaVersion": "3.5.0"
    }, 
    "persist": true
}`

**Comment by kaustriaf5** [comment]
@ajgerace [3.6] (https://github.com/F5Networks/f5-appsvcs-extension/tree/v3.6.0) has been released.
Closing this issue - if you run into something else, please open a new one. Thanks!
