### ISSUE TITLE
Add support for ping access profiles

### ISSUE THREAD

**Issue by jamesjrwood** [F5Networks/f5-appsvcs-extension#303]
### Is your feature request related to a problem? Please describe.
I have quite a few configurations that leverage the APM / pingAccess integration.  I am not able to see a solution in the AS3 schema for attaching a pingAccess profile to a virtual server.  

### Describe the solution you'd like
It would be great if support for attaching existing pingAccess profiles to virtual servers could be added to the AS3 schema.

### Describe alternatives you've considered
Since the integration for pingAccess profiles does not exist in AS3 today I would need to add this configuration after the fact by hand or abandon AS3 for pingAccess enabled VIPs all together.

Please reach out to me if additional information is needed for this RFE.

**Comment by dstokesf5** [comment]
Thank you for your feedback, I have added this feature request to our internal product backlog as AUTOTOOL-1896.
