### ISSUE TITLE
Service_HTTPS redirect virtual server doesn't use HTTPS virtual address range

### ISSUE THREAD

**Issue by fustilarian01** [F5Networks/f5-appsvcs-extension#305]
### Environment
 * Application Services Version: 3.20.0.3
 * BIG-IP Version: 15.1.0.2

### Summary
When I use the Service_HTTPS class to create a virtual server with a /32 address range, the redirect virtual server that is automatically created is assigned the first IP address in the range instead of the /32 IP address range.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "ADC",
    "schemaVersion": "3.20.0",
    "id": "Initial_deployment",
    "Common": {
        "class": "Tenant",
        "label": "commonTenant",
        "remark": "Declaration Common tenant",
        "enable": true,
        "Shared": {
            "class": "Application",
            "template": "shared",
            "main_https": {
                "class": "Service_HTTPS",
                "profileHTTP": {
                    "bigip": "/Common/http"
                },
                "profileTCP": {
                    "bigip": "/Common/tcp"
                },
                "virtualAddresses": [
                    "10.156.160.80/32"
                ],
                "virtualPort": 443,
                "snat": "auto",
                "translateClientPort": true,
                "translateServerAddress": true,
                "serverTLS": {"bigip": "/Common/clientssl"},
                "clientTLS": {"bigip": "/Common/serverssl"}
            }
        }
    }
}
```

2. Observe the following response:
```json
{
    "code": 200,
    "message": "success",
    "lineCount": 16,
    "host": "localhost",
    "tenant": "Common",
    "runTime": 1547
},
{
    "code": 200,
    "message": "success",
    "lineCount": 21,
    "host": "localhost",
    "tenant": "Common",
    "runTime": 1669
}
```

### Expected Behavior
Two virtual servers should be created:
- main_https: 10.156.160.80/32:443
- main_http-Redirect: 10.156.160.80/32:80

### Actual Behavior
Two virtual servers should be created:
- main_https: 10.156.160.80/32:443
- main_https-Redirect-: 10.156.160.80:80

Also, the redirect virtual server appends "-Redirect-" to the end of the name, with the extra hyphen at the end. Couldn't it be just "-redirect"?

**Comment by JeffGiroux** [comment]
Maybe related to https://github.com/F5Networks/f5-appsvcs-extension/issues/292

**Comment by fustilarian01** [comment]
opened 16 days ago and still untriaged. might as well close it.

**Comment by dstokesf5** [comment]
Looks like this was a duplicate of #292, which is tracked in our internal product backlog as AUTOTOOL-1662.
