### ISSUE TITLE
Support for keep-alive-interval under fastl4 profile

### ISSUE THREAD

**Issue by nitzan-tz** [F5Networks/f5-appsvcs-extension#307]
### Describe the solution you'd like
I would like to have option to define idle-timeout under fastl4 profile 

### Describe alternatives you've considered
The other options is to change the default fastl4 profile but it is not allow full automation

**Comment by delgadillo22** [comment]
Thank you for the request: I've created AUTOTOOL-1734 for prioritization

**Comment by nmenant** [comment]
Hi,

this is available today: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#l4-profile 


`

idleTimeout (integer) | 300 | [-infinity, infinity] | Number of seconds (default 300; may not be 0) connection may remain idle before it becomes eligible for deletion. Value -1 (not recommended) means infinite
-- | -- | -- | --


`

Have you tested this ? Have you faced any issue ? 

Thanks for your feedback

**Comment by nitzan-tz** [comment]
Hi,

Sorry for the confusion we mean keep-alive-interval 
This is available only under tcp profile but not under fastl4 profile 

Thanks

Nitzan

**Comment by dstokesf5** [comment]
This was resolved in the 3.23.0 release.
