### ISSUE TITLE
AS3 container v3.5.0 - "delete single tennants" feature missing

### ISSUE THREAD

**Issue by net47** [F5Networks/f5-appsvcs-extension#31]
##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
```
Docker Container - v3.5.0
```

##### BIGIP VERSION
```
BIG-IP 14.0.0 Build 0.0.2187 Final
```

##### SUMMARY
```
Using guide https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/as3-api.html#delete-ref, I'm missing a "delete single tennants" function using the Docker container. 

I can delete all AS3 applications on a specific host using a POST request to "https://as3-container:8443/mgmt/shared/appsvcs/declare", but I cannot POST to "https://as3-container:8443/mgmt/shared/appsvcs/declare/<tennant>".
```

##### STEPS TO REPRODUCE
example declaration:
POST https://as3-container:8443/mgmt/shared/appsvcs/declare
```
{

    "class": "AS3",
    "action": "deploy",
    "targetHost": "192.168.100.31",
    "targetUsername": "as3-admin",
    "targetPassphrase": "as3-admin",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "container",
        "label": "Sample 1 in a container",
        "remark": "Simple HTTP application with RR pool",
        "AS3_App_01": {
            "class": "Tenant",
            "VS_App01": {
                "class": "Application",
                "template": "http",
                "serviceMain": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "192.168.110.190"
                ],
                "pool": "Pool_App01"
                },
                "Pool_App01": {
                "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                "members": [{
                    "servicePort": 80,
                    "serverAddresses": [
                        "192.168.120.71",
                        "192.168.120.72",
                        "192.168.120.73"
                    ]
                }]
                }
            }
        }
    }
}
```
Deleting this tennant could be done the following way:
POST https://as3-container:8443/mgmt/shared/appsvcs/declare/AS3_App_01
```
{

    "class": "AS3",
    "action": "remove",
    "targetHost": "192.168.100.31",
    "targetUsername": "as3-admin",
    "targetPassphrase": "as3-admin"
    
}
```

##### EXPECTED RESULTS
Get a success message, which indicates the tennant has been removed.

##### ACTUAL RESULTS
Error message:
```
{
    "code": 400,
    "message": "method \"Post\" is currently not allowed on path /AS3_App_01"
}
```

**Comment by lephubui** [comment]
Hi @net47 ,
I am sorry to hear that issue happened to you, and thank you for raising up .
I  have created an internal issue, and I am going to check and look at the issue, and meantime if you have any more concerns, feel free to let me know (or direct ping me **Le** in our slack channel #f5-appsvcs-extension) for any AS3 container questions.

Thanks,
-Le

**Comment by lephubui** [comment]
Hi @net47 
After I have talked with the team, I have some updates that with AS3 container, you can remove the specific tenant is do a POST with tenant body empty. In your case, you can try this declaration 
POST https://as3-container:8443/mgmt/shared/appsvcs/declare
{
    "class": "AS3",
    "action": "deploy",
    "targetHost": "192.168.100.31",
    "targetUsername": "as3-admin",
    "targetPassphrase": "as3-admin",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "container",
        "label": "Sample 1 in a container",
        "remark": "Simple HTTP application with RR pool",
        "AS3_App_01": {
            "class": "Tenant"
            
        }
    }
}

**FYI:**
AS3 has no POST on tenant path currently supported, but I'm opening an issue and will prioritized it. Stay tuned. 

Please let me know if you have other questions.

Thanks,

-Le

**Comment by net47** [comment]
Hi Le,

sorry for the late response, I just tried that and it's working.

Response:
```
{
    "results": [
        {
            "message": "success",
            "lineCount": 23,
            "code": 200,
            "host": "192.168.100.31",
            "tenant": "AS3_App_01",
            "runTime": 22892
        }
    ],
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "container",
        "label": "Sample 1 in a container",
        "remark": "Simple HTTP application with RR pool",
        "controls": {
            "archiveTimestamp": "2018-11-12T15:00:16.649Z"
        }
    }
}
```
Thanks for your help!
br
Daniel

**Comment by lephubui** [comment]
No problem @net47 Daniel. 
I'm glad it wok and always happy to help. 
Please let us know if there are other issues or you can find us through the Slack chance **f5-appsvcs-extention.**

**Comment by kaustriaf5** [comment]
Closing this issue as the workaround verified works.  We are tracking the feature enhancement part internally. 
Please keep an eye out for new releases. Thanks!
