### ISSUE TITLE
save sys ucs is very long after installing AS3

### ISSUE THREAD

**Issue by emmanuelgirard** [F5Networks/f5-appsvcs-extension#311]
### Environment
 * Application Services Version: 3.19.1-1, 3.20.0-3, 3.21.0-4
 * BIG-IP Version: 15.1.0.4-0.0.6

### Summary
On a freshly deployed new BIG-IP with only LTM and no virtual server.
save sys ucs works fine until we Install AS3
As soon the packages is deployed along the f5-service-discovery package
It then takes very long time to create the UCS Archive but finally finished with success.

### Steps To Reproduce

1. Deploy BIG-IP VE latest version
2. save sys ucs (30 seconds)
3. Install Application Services AS3 RPM
4. save sys ucs (2 minutes)

2. Observe the following error response:

```
Jul 27 18:34:22 localhost.localdomain info iAppsLX_save_pre[6752]: Exporting: f5-service-discovery - /var/config/rest/iapps/f5-service-discovery
Jul 27 18:35:25 localhost.localdomain err iAppsLX_save_pre[6752]: Failed to get task response within timeout for: /shared/iapp/build-package/17923de5-2c62-4c49-9c60-16210a76d33b
Jul 27 18:35:26 localhost.localdomain err iAppsLX_save_pre[6752]: Failed to get getRPM build response within timeout for f5-service-discovery
```

### Expected Behavior
System archive should not take that long to be created when installing AS3.

### Actual Behavior
f5-service-discovery RPM build task launch by ucs archive creation failed all the time.

I've added this line the **iAppsLX_save_pre** file as a work-around in order to keep the backup under a minute.
But it just skip the task...wich is probably not what we want ?

```
if iapp == "f5-service-discovery": continue
```

**Comment by dstokesf5** [comment]
Thank you for reporting this issue. I have confirmed it and added it to our internal product backlog as AUTOTOOL-1838.

**Comment by walterk82** [comment]
Where is `iAppsLX_save_pre` located?

**Comment by dstokesf5** [comment]
@walterk82 It looks like it is located on the BIG-IP at `/usr/libexec/iAppsLX_save_pre`.

**Comment by walterk82** [comment]
I have case C3434268 which I believe is related to this issue.  

@emmanuelgirard Can you see if /shared/tmp/ is having leftover tmp files from service discovery?

**Comment by dstokesf5** [comment]
After some investigation into this issue, we determined that the underlying framework does not handle saving iControlLX extensions well. There is an internal bug report related to these underlying issues (985329).

**Comment by walterk82** [comment]
@dstokesf5 I had filed RFE 995173 to improve service-discovery installation which I believe is contributing to the side-effects of 985329
I'm hoping that one of these IDs can be looked at to address this reported issue.
