### ISSUE TITLE
[SCA] RFE: auto-discover virtual server address

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-extension#315]
### Is your feature request related to a problem? Please describe.
currently it is challenging to determine the correct IP address to use for a virtualAddress when deploying in a cloud environment

### Describe the solution you'd like
Ideally AS3 should have a placeholder syntax to grab an IP address for the virtualServer address.  i.e. in AWS you should be able to say "grab eth1 second private address" and it will populate 10.1.10.2 based on the meta-data service.  something like 
```
"virtualAddresses:" [{"aws":"eth1:1"}] 
```
this would also be similar to service discovery where you could also have an API to fetch this from a generic IPAM solution.
```
"virtualAddresses:" [{"generic_ipam":"unique_ipam_identifier"}] 
```

### Describe alternatives you've considered
Currently you have to use automation tools to determine this information (i.e. Ansible)

**Comment by dstokesf5** [comment]
Thank you for your feedback. Unfortunately, we have decided that this feature request is outside of the scope of AS3 and I am closing this issue.
