### ISSUE TITLE
Make a best effort attempt to provide the declaration ID on a "declaration invalid" task

### ISSUE THREAD

**Issue by mstokes-f5** [F5Networks/f5-appsvcs-extension#322]
### Is your feature request related to a problem? Please describe.
I have an application (FAST) that is inserting metadata into the declaration ID to be able to filter tasks (gathered using a `GET` to the `/task` endpoint) such that only tasks generated by the application are left. This can be done for most tasks since they include the declaration in the task information, which retains the `id` property.

However, on a "declaration invalid" task (i.e., the declaration failed schema validation) the declaration is not available in the task. When this happens FAST has to use other, less reliable means to re-associate the task with a FAST action.

### Describe the solution you'd like
Ideally, "declaration invalid" tasks would still have the bad declaration available for review, but that could be problematic if the declaration has JSON issue or something else that could break the response object from the GET request.

At the very least, it would be nice to attempt to salvage the ID from the declaration and have it in the task object. Whether that is only having the `id` property in the `declaration` object or a separate `declarationId` property of some sort works for me.

### Describe alternatives you've considered
Currently FAST uses task IDs to try to re-associate tasks with FAST actions when the declaration ID is not available. However, this relies on FAST keeping a list of task IDs that have to be persisted (which can be slow with a BIG-IP iApps LX extension) or this association is lost when FAST is restarted.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this to our internal product backlog as AUTOTOOL-1960.
