### ISSUE TITLE
Snat list Creation

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/f5-appsvcs-extension#331]
Hello,
Until the recent AS3 3.21, looks like there is still no schema to create a snat list. We only see snatpool shcema. Snat list is created in LTM, if we want to map a snatpool to a vlan. This can be done via BIGIP GUI or tmsh but not available via AS3. Will it be available in future releases?

Thanks
Prabhat

**Comment by dstokesf5** [comment]
Please resubmit this issue using one of our issue templates: https://github.com/F5Networks/f5-appsvcs-extension/issues/new/choose
