### ISSUE TITLE
Add Service_Discovery_NSXT

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#337]
### Is your feature request related to a problem? Please describe.

NSX-T provides additional grouping mechanisms on top of VM discovery mechanism that vCenter provides. These mechanisms are more network oriented than vCenter VM oriented grouping mechanisms.

More precisely, the native NSX-T LB makes use of the [Group](https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.0/administration/GUID-9DFF6EE2-2E00-4097-A412-B72472596E4D.html) construct for this purpose. This can be seen in the attached screenshot.

<img width="1694" alt="Screenshot 2020-09-10 at 09 12 31" src="https://user-images.githubusercontent.com/16683733/92693589-1a234200-f346-11ea-9c8c-a3f2812cef96.png">

### Describe the solution you'd like

Implement Service_Discovery_NSXT backend for NSX-T's Inventory Group facility.

### Additional context

Find the corresponding documentation in [this link](https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.0/administration/GUID-9DFF6EE2-2E00-4097-A412-B72472596E4D.html)

**Comment by dstokesf5** [comment]
AS3 relies on the [f5-cloud-libs](https://github.com/F5Networks/f5-cloud-libs) project for service discovery. We do not have the resources at this time to implement this functionality into f5-cloud-libs. I have created AUTOTOOL-1887 as a low priority product backlog item. This is unlikely to be worked on any time soon. If this feature is critical for a customer deployment, I recommend escalating it through F5 support as the [readme](https://github.com/F5Networks/f5-appsvcs-extension#filing-issues-and-getting-help) suggests.

**Comment by alonsocamaro** [comment]
AVI (aka NSX-T Advance Load Balancer) has incorporated this feature as of release 20.x.

**Comment by dstokesf5** [comment]
Closing this issue as there is insufficient interest from product management to support it.
