### ISSUE TITLE
Unable to create pool in /Common/Shared containing node/s created in other tenants already

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#340]
### Environment
 * Application Services Version: 3.22.0
 * BIG-IP Version: 15.1

### Summary
We are unable to submit our AS3 declaration if it contains a pool with members that are already created in another tenant.
For example. If I create tenant "test_tenant" and add a pool with the member "10.1.1.1" in it, and then tries to submit the Common declaration with a pool that also contains the member "10.1.1.1" it gives me the error message: 01020066:3: The requested Node (/Common/10.1.1.1%2) already exists in partition Common.

The "shareNodes" directive is set to true in all partitions as nothing works without it. (Since multiple tenants has references to the same backend servers).

### Steps To Reproduce (issue 1)
1. Submit the following declaration:
```
{
  "class": "ADC",
  "updateMode": "selective",
  "schemaVersion": "3.22.0",
  "id": "autogen_162c3001-7654-4f05-b478-689c702681e9",
  "controls": {
    "archiveTimestamp": "2020-09-14T12:33:46.468Z"
  },
  "int_as3-test-v1": {
    "class": "Tenant",
    "defaultRouteDomain": 2,
    "int_as3-test-v1_app": {
      "class": "Application",
      "template": "generic",
      "int_as3-test-v1_service": {
        "class": "Service_HTTPS",
        "virtualAddresses": [
          "172.10.10.10"
        ],
        "virtualPort": 443,
        "redirect80": true,
        "snat": "auto",
        "translateClientPort": true,
        "allowVlans": [
          "/Common/vlan_ingress"
        ],
        "profileHTTP": {
          "bigip": "/Common/http_ssl_rewrite"
        },
        "profileTCP": {
          "ingress": "normal",
          "egress": "lan"
        },
        "pool": "int_as3-test-v1_pool"
      },
      "int_as3-test-v1_pool": {
        "class": "Pool",
        "loadBalancingMode": "round-robin",
        "serviceDownAction": "none",
        "monitors": [
          {
            "bigip": "/Common/tcp"
          }
        ],
        "minimumMonitors": 1,
        "members": [
          {
            "servicePort": 8080,
            "serverAddresses": [
              "10.1.1.1%2"
            ],
            "priorityGroup": 0,
            "shareNodes": true
          }
        ]
      }
    }
  }
}

```
2. Then submit the following declaration (issue 1)
```
{
  "class": "ADC",
  "updateMode": "selective",
  "schemaVersion": "3.22.0",
  "id": "autogen_162c3001-7654-4f05-b478-689c702681e9",
  "controls": {
    "archiveTimestamp": "2020-09-14T12:33:46.468Z"
  },
  "Common": {
    "class": "Tenant",
    "enable": true,
    "Shared": {
      "class": "Application",
      "template": "shared",
      "enable": true,
      "all_nodes_pool": {
        "class": "Pool",
        "loadBalancingMode": "round-robin",
        "serviceDownAction": "none",
        "members": [
          {
            "servicePort": 54321,
            "serverAddresses": [
              "10.1.1.1%2"
            ],
            "priorityGroup": 0,
            "shareNodes": true
          }
        ]
      }
    }
  }
}

```
3. Observe the following error response (issue 1)
```
[
  {
    code: 422,
    message: 'declaration failed',
    response: '01020066:3: The requested Node (/Common/10.1.1.1%2) already exists in partition Common.',
    host: 'localhost',
    tenant: 'Common',
    runTime: 35014
    },
  {
    code: 422,
    message: 'declaration failed',
    response: '01020066:3: The requested Node (/Common/10.1.1.1%2) already exists in partition Common.',
    host: 'localhost',
    tenant: 'Common',
    runTime: 34489
  }
]
```

### Expected Behavior
The Common partition should be created, re-using the nodes that already exists in common.
To me it sounds like an extremely bad implementation if I need to declare all partitions at all times in order to be sure to not end up with these kind of issues.

As3 should be modular and allow us to send declarations for tenants independently of each other, especially if we have have declared the nodes to be "shared". 

### Actual Behavior
The Common partition declaration fails.

### A similar issue
A similar issue (with the same origin) happens if I first create the Common partition with the node, then create the "test_tenant". This will work to create it, but when I then try to delete the test_tenant partition it fails since it thinks that "Common" has references to the node (which it does). That one fails with (issue 2):

```
{
  "code": 422,
  "message": "declaration failed",
  "response": "01070110:3: Node address '/Common/10.1.1.1%2' is referenced by a member of pool 
  '/Common/Shared/all_nodes_80_pool'.",
  "host": "localhost",
  "tenant": "test_tenant",
  "runTime": 8370
 }
```

### Reflections
I really don't know how much problems we've had with cross-reference issues. But shouldn't AS3 be able to keep track of it's own state/deployed tenants without needing the entire declaration which could consist of several MBs?

**Comment by dstokesf5** [comment]
I have confirmed this bug and I have added it to our internal product backlog as AUTOTOOL-1884.

**Comment by sunitharonan** [comment]
Fixed
