### ISSUE TITLE
websocket profile created but not attached to virtual server

### ISSUE THREAD

**Issue by nielsvanderbeke** [F5Networks/f5-appsvcs-extension#341]
### Environment
 * Application Services Version: f5-appsvcs-3.22.1-1.noarch
 * BIG-IP Version: BIG-IP 15.1.0 Build 0.0.31 Final

### Summary
When we create a HTTP_Profile to enable websocket support on a virtual server and add this http profile to the Service_HTTPS we can see that after applying the AS3 config a websocket profile is created "f5_appsvcs_selective" but it is not applied to the virtual server

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "TEST": {
        "Shared": {
            "enable": true,
            "template": "shared",
            "testWebsocket": {
                "proxyType": "reverse",
                "multiplexTransformations": true,
                "responseChunking": "selective",
                "xForwardedFor": true,
                "trustXFF": false,
                "truncatedRedirects": false,
                "knownMethods": [
                    "CONNECT",
                    "DELETE",
                    "GET",
                    "HEAD",
                    "LOCK",
                    "OPTIONS",
                    "POST",
                    "PROPFIND",
                    "PUT",
                    "TRACE",
                    "UNLOCK"
                ],
                "webSocketsEnabled": true,
                "hstsPreload": false,
                "unknownMethodAction": "allow",
                "hstsInsert": false,
                "pipelineAction": "allow",
                "hstsPeriod": 7862400,
                "viaResponse": "remove",
                "maxHeaderSize": 32768,
                "viaRequest": "remove",
                "webSocketMasking": "selective",
                "maxHeaderCount": 64,
                "class": "HTTP_Profile",
                "maxRequests": 0,
                "serverHeaderValue": "BigIP",
                "requestChunking": "preserve",
                "hstsIncludeSubdomains": true,
                "rewriteRedirects": "none"
            },
            "class": "Application"
        },
        "defaultRouteDomain": 1101,
        "class": "Tenant",
        "EH": {
            "testvip_443": {
                "persistenceMethods": [
                    "cookie"
                ],
                "mirroring": "none",
                "serverTLS": "/TEST/Shared/serverTLSprofile",
                "profileTCP": "normal",
                "translateServerAddress": true,
                "clientTLS": [
                    {
                        "bigip": "/Common/serverssl-insecure-compatible"
                    }
                ],
                "lastHop": "default",
                "virtualAddresses": [
                    {
                        "use": "testvip"
                    }
                ],
                "snat": {
                    "use": "/EH/Shared/testvip"
                },
                "enable": true,
                "shareAddresses": false,
                "profileHTTP": {
                    "use": "/EH/Shared/testWebsocket"
                },
                "translateClientPort": false,
                "virtualPort": 443,
                "addressStatus": true,
                "class": "Service_HTTPS",
                "pool": "",
                "layer4": "tcp",
                "virtualType": "standard",
                "nat64Enabled": false,
                "translateServerPort": true,
                "maxConnections": 0
            },
            "enable": true,
            "template": "generic",
            "class": "Application"
        }
    },
    "remark": "test-remark",
    "id": "testid",
    "schemaVersion": "3.21.0",
    "class": "ADC",
    "updateMode": "selective",
    "controls": {
        "archiveTimestamp": "2020-09-15T09:54:34.352Z"
    }
}
```

2. Observe the following error response:

profile created but no applied to the virtualserver

**Comment by dstokesf5** [comment]
The declaration  you provided appears to be missing some pieces:
```json
{
    "code": 422,
    "errors": [
        "/TEST/EH/testvip_443/profileHTTP/use: contains path to non-existent object EH"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

**Comment by nielsvanderbeke** [comment]
Hi @dstokesf5 I corrected the example, this should be a valid example that still has the issue.

`{
    "TEST": {
        "Shared": {
            "enable": true,
            "template": "shared",
            "testWebsocket": {
                "proxyType": "reverse",
                "multiplexTransformations": true,
                "responseChunking": "selective",
                "xForwardedFor": true,
                "trustXFF": false,
                "truncatedRedirects": false,
                "knownMethods": [
                    "CONNECT",
                    "DELETE",
                    "GET",
                    "HEAD",
                    "LOCK",
                    "OPTIONS",
                    "POST",
                    "PROPFIND",
                    "PUT",
                    "TRACE",
                    "UNLOCK"
                ],
                "webSocketsEnabled": true,
                "hstsPreload": false,
                "unknownMethodAction": "allow",
                "hstsInsert": false,
                "pipelineAction": "allow",
                "hstsPeriod": 7862400,
                "viaResponse": "remove",
                "maxHeaderSize": 32768,
                "viaRequest": "remove",
                "webSocketMasking": "selective",
                "maxHeaderCount": 64,
                "class": "HTTP_Profile",
                "maxRequests": 0,
                "serverHeaderValue": "BigIP",
                "requestChunking": "preserve",
                "hstsIncludeSubdomains": true,
                "rewriteRedirects": "none"
            },
            "class": "Application"
        },
        "class": "Tenant",
        "EH": {
            "testvip_443": {
                "persistenceMethods": [
                    "cookie"
                ],
                "mirroring": "none",
                "profileTCP": "normal",
                "translateServerAddress": true,
                "serverTLS": [
                    {
                        "bigip": "/Common/clientssl-insecure-compatible"
                    }
                ],
                "clientTLS": [
                    {
                        "bigip": "/Common/serverssl-insecure-compatible"
                    }
                ],
                "lastHop": "default",
                "virtualAddresses": [
                    "::"
                ],
                "enable": true,
                "shareAddresses": false,
                "profileHTTP": {
                    "use": "/TEST/Shared/testWebsocket"
                },
                "translateClientPort": false,
                "virtualPort": 443,
                "addressStatus": true,
                "class": "Service_HTTPS",
                "pool": "",
                "layer4": "tcp",
                "virtualType": "standard",
                "nat64Enabled": false,
                "translateServerPort": true,
                "maxConnections": 0
            },
            "enable": true,
            "template": "generic",
            "class": "Application"
        }
    },
    "remark": "test-remark",
    "id": "testid",
    "schemaVersion": "3.20.0",
    "class": "ADC",
    "updateMode": "selective",
    "controls": {
        "archiveTimestamp": "2020-09-15T09:54:34.352Z"
    }
}`

**Comment by dstokesf5** [comment]
I have reproduced the issue and added it to our internal product backlog as AUTOTOOL-1901.

I noticed this behavior occurs when the http profile is in a shared application. That shared application can be in the same tenant or Common. The websocket profile was correctly configured when the http profile and the virtual server were in the same application.

**Comment by dstokesf5** [comment]
This issues appears to have been resolved in a previous release. Are you still experiencing this issue with the latest AS3 release?
