### ISSUE TITLE
Implement GSLB_Monitor_External 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#344]
### Is your feature request related to a problem? Please describe.

Please implement External monitor type for GSLB.

### Describe the solution you'd like

Just like Monitor_External but for GSLB_Monitor_External.

### Describe alternatives you've considered

There are none

### Additional context

External monitors solve many customer corner cases but in this case it also would help solving a very relevant problem: the HTTPS monitor for GSLB doesn't support SNI and the only workaround is to use curl through an external monitor.

**Comment by s-archer** [comment]
+1
I have a customer in the UK that needs this feature to provide GSLB for apps deployed across multiple k8s clusters, that use a shared ingress model.

**Comment by chen23** [comment]
This looks to be a duplicate of https://github.com/F5Networks/f5-appsvcs-extension/issues/259

**Comment by dstokesf5** [comment]
Closing as duplicate of #259.
