### ISSUE TITLE
Possibility to match against host+path in endpoint policy

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#347]
### Is your feature request related to a problem? Please describe.
This is probably more of a F5 specific issue as this is how it's configured when doing it in the GUI as well, but I think this is somewhat weird. Anyway. When configuring an endpoint policy you have the option to match against "all" on HTTP_URI level. This is where it gets interesting as the concept "URI" is somewhat confusing, some believe it to be "https://blabla.domain.com/my/path?myquery=string" whereas F5 see it as /my/path?myquery=string. However, in the UTTP_URI section you have the possibility to select "host" (which makes one think that "full string" or "all" should be the entire url with atleast host+path+qs and not only path+qs).

This is not only confusing but does also become an issue when you want to match a host+path in a single endpoint policy rule instead of creating 235798237389 different rules to do this. (Alternative is creating an iRule + datagroup - which I would like to avoid too).

I suppose this is how F5 interprets it:
https://clouddocs.f5.com/api/irules/HTTP__uri.html

But both of these documentations are misleading:
Here's scheme, host, path, qs mentioned as what "http uri" consists of and it says: "full string. Matches a specified full text string.".
https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/local-traffic-policies-getting-started-12-1-0/1.html

Here's also scheme etc mentioned, and all is mentioned such as "all (Policy_Compare_String) |  Match on the full URI"
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#policy-condition-http-uri

One could think that all the sub-options that there's to choose from actually exists in the full string/all version. So, full string should be changed or another option that distinguishes the actual full uri from the "full path+qs" should be created.

### Describe the solution you'd like
I think there should be a way to actually match against the entire URI, as in host+path+qs in an endpoint policy condition rule, not only full string as in "path+qs".

### Describe alternatives you've considered
As mentioned earlier, an option is to use iRules or multiple LTM rules but I would like to avoid both of these rules as a single endpoint policy rule would be way(!) more clean to do this.

**Comment by dstokesf5** [comment]
I have confirmed that the "all" parameter maps to the appropriate options in tmsh. This sound like it is ultimately an issue with `ltm policy` objects. AS3 provides a thin wrapper for functionality that already exists in `ltm policy` objects, and it would be difficult for AS3 to extend `ltm policy` objects to provide more options.

I suggest opening a request with F5 support on how to configure an `ltm policy` object to suite your use case.
