### ISSUE TITLE
Customize persistence profile

### ISSUE THREAD

**Issue by danpacheco1** [F5Networks/f5-appsvcs-extension#349]
### Environment
* Application Services Version: 3.22.1
* BIG-IP Version:14.1.2.6

### Summary
With the Service_HTTPS template, I am unable to apply a custom cookie persistence profile. Only the parent profiles seem to be available

### Steps To Reproduce
1. Submit the following declaration:
```json
create a custom cookie profile
                "as3-persist": {
                "class": "Persist",
                "persistenceMethod": "cookie",
                "cookieMethod": "insert",
                "cookieName": "as3"
                },

Apply it to HTTPS_service
              "as3-vs": {
                  "class": "Service_HTTPS",
                  "virtualAddresses": [
                     "7.7.7.7/32"
                   ],
                  "virtualPort": 8443,
                  "persistenceMethods": [
                      "as3-persist"
                  ],
                  "profileHTTP": {
                       "use": "as3-http"
                   },
                   "iRules": [
                       {
                       "bigip": "/Common/hoc_errorpage_ir"
                       }
                   ],
                   "allowVlans": [
                       {
                       "bigip": "/Common/lab-legacy-dc_vlan"
                       }
                   ],
                   "snat": {
                       "bigip": "/Common/SNAT-DCLB-Legacy"
                   },
                  "serverTLS": "as3-client-ssl",    
                  "clientTLS": "as3-server-ssl",
                  "pool": "as3_pool"
               },

```

2. Observe the following error response:
```json
{
    "code": 422,
    "errors": [
        "/as3-partition/as3-app-folder/as3-vs/persistenceMethods/0: should be equal to one of the allowed values [\"cookie\",\"destination-address\",\"msrdp\",\"source-address\",\"tls-session-id\"]"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

### Expected Behavior
Virtual accept the custom persistence profile.

### Actual Behavior
produces this error
{
    "code": 422,
    "errors": [
        "/as3-partition/as3-app-folder/as3-vs/persistenceMethods/0: should be equal to one of the allowed values [\"cookie\",\"destination-address\",\"msrdp\",\"source-address\",\"tls-session-id\"]"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}

**Comment by RobCupples** [comment]
Try using the "use" keyword like this

          "persistenceMethods": [{
            "use": "as3-persist"
          }]

**Comment by danpacheco1** [comment]
@RobCupples Yes, of course that is the solution. So obvious now now that I see it. Thanks for the help.
