### ISSUE TITLE
Error in documentation for Docker usage

### ISSUE THREAD

**Issue by Sakorah** [F5Networks/f5-appsvcs-extension#35]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/userguide/as3-container.html

```
{

     "class": "AS3",
     "action": "deploy",
     "targetHost": "192.0.2.76",
     "targetPort": "8443"
     "targetUsername": "admin",
     "targetPassphrase": "admin",
     "declaration": {
         "class": "ADC",
         "schemaVersion": "3.0.0",
         ...
     }
}
```

AS3 Docker container reports that "targetPort" should be integer. Defined as string in documentation.

##### STEPS TO REPRODUCE
Use example config from documentation

##### EXPECTED RESULTS
Fix documentation to be integer, also a semi-colon is missing.

##### ACTUAL RESULTS
```
~$ curl -sku admin:admin -H "Content-Type: application/json" -X POST https://localhost:8443/mgmt/shared/appsvcs/declare --data-binary "@as3.json";
{"code":422,"message":"/targetPort: should be integer"}
```

**Comment by lephubui** [comment]
Hi @Sakorah, thank you for the feedback.
I'm opening an internal issue for the documented improvement, and we will change for the coming release. (which will go live next week).

**Comment by JosephPJordan** [comment]
Sakorah, in the short term, if you have not already, you can remove the quotes around the port, so the correct line would read: "targetPort": 8443.  As Le mentioned, this will be correct in the next documentation release.  Thanks again.

**Comment by JosephPJordan** [comment]
Hello, this is corrected in the latest version of the documentation, thank you for bringing it to our attention. 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/as3-container.html
