### ISSUE TITLE
Extremely poor deployment performance - what's considered to be normal?

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#350]
We are trying to migrate to using AS3 for all of our configuration, but we are experiencing issues with extremely slow deploy times.

If I deploy the /Common/Shared partition with around 10 pools and 3 irules it takes approximately 2-3 minutes to deploy it. Other partitions takes maybe 60 seconds to complete.

Our existing F5 configuration (not in AS3) is rather large (100-200 of each pools/vips/ltm/asm policies) but I don't see why this should mean that the AS3 deployments are taking so extremely long time.

This becomes quite problematic already when the declaration is tiny(!) as this, but I can't even imagine when we have migrated everything into AS3. Will it even work?

We have raised our MGMT provisioning to high, we have also provisioned extra memory to the mgmt db value (don't remember the exact name but was recommended on one of your troubleshooting guides).

Either way. 30-180 seconds works when you have a declaration that you want to deploy in order to create an entire application from scratch, but when you have a configuration where you want to do changes, and you got several different people and components working at the same time to modify things, it will be unworkable as you can't even send two declarations simultaneously (yes, I know about the burst thing, but that's only a queue functionality that doesn't change much if every change takes minutes to deploy - not even for different tenants...)

Imagine if you are working on an irule locally and you want to test it, after some changes you want to test it out in increments, just to realize that it takes minutes, or maybe even more if the deploy queue is somewhat flooded ("flooded" as in a few declarations waiting to be deployed).

This all boils down to one question. How long deployment time is considered normal? 3 seconds? 50? 180? 

Very thankful for any kind of help of feedback/help with this.

**Comment by oakh1** [comment]
Right now we have 1 tenant deployed in our production environment and we have unfortunately already started receiving issues such as:

results: [
  {
    code: 500,
    declarationFullId: '',
    message: 'connection to http://admin:XXXXXX@localhost:8100/mgmt/tm/asm/policies timed out'
  }
]

-------------

 {
   "code": 422,
   "message": "declaration failed",
   "response": "connection to http://admin:XXXXXX@localhost:8100/mgmt/tm/task/cli/script run cli script timed out",
   "host": "localhost",
   "tenant": "xxxxxx",
   "runTime": 87322
 }

The declaration consists of a virtual server, three pools with 1 member in each, 4 irules and a datagroup with few hundred records.

**Comment by mdditt2000** [comment]
Good morning @oakh1 thank you for reaching out. I would like to understand your migration and help with some best practices etc. Could we set up sometime via Zoom to discuss this issue in more details. Thanks

**Comment by oakh1** [comment]
Thank you, I think that would be great. I should mention that we have a case open with F5 support regarding our management performance (since months) but nothing seems to happen there... We have tweaked everything possible and even extended the management memory to 10gb+ but it makes no real difference.

Would be great to have a session, how do we proceed with that?

**Comment by mdditt2000** [comment]
Resolved. Recommended AS3 best practices. Closing issue
