### ISSUE TITLE
How to use fasthttp profile in as3 configmap ?

### ISSUE THREAD

**Issue by k8s-multicloud** [F5Networks/f5-appsvcs-extension#353]
Application Services Version: 3.20
BIG-IP Version: 14.1.2.6

I would like to use "Performance HTTP virtual server" type. ( https://support.f5.com/csp/article/K8082#perf )
I found a document about "Fast HTTP profile" at https://support.f5.com/csp/article/K8024.

So I tested below as3 configmap.( 
Actually I modified two things from successful as3 configmap.
1. add profileHTTP
2. replace monitors from http to below. - maybe this is not necessary. )

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: tenant-filtering-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.20.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "Sample 1",
            "remark": "Simple HTTP application with RR pool",
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "iningress": {
                        "class": "Service_HTTP",
                        "profileHTTP": {
                          "bigip": "/Common/fasthttp"
                        },
                        "virtualAddresses": [
                            "10.107.40.1"
                        ],
                        "remark":"ingress: f5demo",
                        "virtualPort": 80,
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            {
                              "bigip": "/Common/http"
                            } 
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
```

CIS pod logs : 
2020/09/28 06:48:48 [ERROR] [AS3] Big-IP Responded with code: 422
2020/09/28 06:48:48 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find /Common/fasthttp for /AS3/A1/iningress/profileHTTP]

Could anyone let me know how to use "Performance HTTP virtual server" or how to use "fasthttp profile"?

**Comment by dstokesf5** [comment]
Thank you for your feedback. This is actually a feature request since it appears AS3 cannot reference `ltm profile fasthttp` objects. I have added AUTOTOOL-1951 to our internal product backlog for that feature request.

**Comment by k8s-multicloud** [comment]
Could you let me know current status for this issue? ( use fasthttp profile at as3 configmap )

**Comment by dstokesf5** [comment]
This item is still in our product backlog, but not assigned to any release.
