### ISSUE TITLE
Ability to create DNS_Logging_Profile from AS3

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#357]
### Is your feature request related to a problem? Please describe.
Feature Request

### Describe the solution you'd like
AS3 has the ability to reference DNS_Logging_Profile as a pre-created item, we would like the ability to create it. I don't see an option in the schema to create one.

```    "Pointer_DNS_Logging_Profile": {
      "description": "Reference to a DNS logging profile",
      "type": "object",
      "properties": {
        "bigip": {
          "description": "Pathname of existing BIG-IP DNS logging profile",
          "type": "string",
          "format": "f5bigip"
        }
      },
```

### Describe alternatives you've considered
There isn't an Ansible module for this either, it would require imperative calls to create the object.

REST endpoint: **/mgmt/tm/ltm/profile/dns-logging**

Options:

```
appService:
description:
enableQueryLogging:
enableResponseLogging:
includeCompleteAnswer:
includeQueryId:
includeSource:
includeTimestamp:
includeView:
logPublisher:
name:
```

### Additional context

Object in question:
![image](https://user-images.githubusercontent.com/20847865/95265115-66e32700-07e5-11eb-836f-0d3a6641585c.png)

**Comment by dstokesf5** [comment]
Thank you for your feedback. Due to the age of this feature request, I would like to know if this is still something you need or are interested in.
