### ISSUE TITLE
Consul - use service health in a passing state and discover service port

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-appsvcs-extension#360]
#338 # Is your feature request related to a problem?
If I used `/v1/catalog/service/my-service` in AS3 Declaration, all nodes registered for service my-service are returned, regardless of their service state
I should used `/v1/health/service/my-service?passing`... but response from Consul is not understand by BIG-IP.

### Describe the solution you'd like
Need an attribute in class `Service_Discovery_Consul` to use either `Service Catalog` (current) or `Service Health` (new need)
`Service Health` could populate pool member address and port based on:
- Discovered port (service.port in Consul response `/v1/health/service/my-service?passing`)
- Discovered IP (node.address in Consul response `/v1/health/service/my-service?passing`)

### Additional context
Use Case: delegate a full service definition to Consul (IP+port+monitor), as NGINX does with DNS SRV.

### Example of responses
- `/v1/catalog/service/totalapp3-arcadia-all-in-one`: consul_catalog_service.json
- `/v1/health/service/totalapp3-arcadia-all-in-one?passing`: consul_service_health-passing_state_only.json
- `/v1/health/service/totalapp3-arcadia-all-in-one`: consul_service_health-all_state.json

[consul_service_health-all_state.json.TXT](https://github.com/F5Networks/f5-appsvcs-extension/files/5362332/consul_service_health-all_state.json.TXT)
[consul_service_health-passing_state_only.json.TXT](https://github.com/F5Networks/f5-appsvcs-extension/files/5362333/consul_service_health-passing_state_only.json.TXT)
[consul_catalog_service.json.TXT](https://github.com/F5Networks/f5-appsvcs-extension/files/5362334/consul_catalog_service.json.TXT)

**Comment by chen23** [comment]
related issue: https://github.com/F5Networks/f5-appsvcs-extension/issues/117 internally tracked at: AT-576

**Comment by chen23** [comment]
This is now possible in AS3 3.24 using a custom jmespathquery. 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#using-service-discovery-with-the-consul-health-api
