### ISSUE TITLE
f5-service-discovery not included with f5-appsvcs-extension?

### ISSUE THREAD

**Issue by jahawkns** [F5Networks/f5-appsvcs-extension#363]
### Environment
 * Application Services Version:
 * BIG-IP Version:

### Summary
According to documentation f5-appsvcs-extension 3.4 began including f5-service-discovery. I've installed versions 3.19.1 - 3.23.0 but none include f5-service-discovery. F5 is running 14.1.2.6. 

### Steps To Reproduce
Import .rpm
f5-appsvcs-extension appears to install normally. 

2. Observe the following error response:
following can be found in /var/log/restnoded after the install. 

Tue, 13 Oct 2020 13:37:13 GMT - severe: [RestWorker] [RestWorker] worker failed to load state: [object Object]:shared/appsvcs
Tue, 13 Oct 2020 13:43:05 GMT - severe: [ErrorHandlingModule] RestOperation failed: "/odata-registry/types/available". {"code":404,"message":"","referer":"restnoded","originalRequestBody":"","errorStack":[]}
Tue, 13 Oct 2020 13:44:38 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:44:48 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:44:58 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:08 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:18 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:28 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:38 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:48 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:45:58 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:46:08 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:46:18 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:46:28 GMT - warning: [appsvcs] {"message":"Dependencies Check failed, retrying.","level":"warning"}
Tue, 13 Oct 2020 13:46:38 GMT - severe: [appsvcs] {"message":"Failed to complete startup. Error: Unable to verify additional dependencies: Dependencies Check failed: Timed out waiting for dependencies to load}\n    at getHostInfo.then.then (/var/config/rest/iapps/f5-appsvcs/lib/context/hostContext.js:74:23)\n    at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"error"}
Tue, 13 Oct 2020 13:46:38 GMT - severe: [RestWorker] [RestWorker] worker failed to load state: [object Object]:shared/appsvcs

**Comment by dstokesf5** [comment]
@jahawkns, the f5-service-discovery extension is still being included with the f5-appsvcs extension. It is unclear to me how you reached the conclusion of the f5-service-discovery extension not being included from that error message. While cryptic, that error message is indicating that the `/mgmt/tm/util/available` endpoint did not respond with a successful response. This means the BIG-IP was not in a state where AS3 could run. I recommend checking that restjavad and restnoded are running `bigstart status restjavad restnoded` on the BIG-IP.

**Comment by dstokesf5** [comment]
AS3 is unable to start up, and unable to install the f5-service-discovery extension, because of that error message.

**Comment by jahawkns** [comment]
Mystery solved. Due to security/compliance requirements we disable default admin. I went back and re-enabled the admin account on the LTMs where the install was failing and both the appsvcs and service-discovery packages appear. 

Thanks for feedback @dstokesf5.
