### ISSUE TITLE
GSLB: valid AS3 declaration fails if there is a previous declaration 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#366]
## Environment
 * Application Services Version: 3.21.0
 * BIG-IP Version: 15.1.0.2

### Summary
Hi

From initial state with an empty declaration, POSTing the valid attached declaration state.0.json.txt succeeds.
From initial state with an empty declaration, POSTing the valid attached declaration state.1.json.txt succeeds too.

On the other hand

From initial state with state.0.json declaration, POSTing the valid attached declaration state.1.json FAILS.

The error message can be found in the attached file result-0-1.json.txt

### Steps To Reproduce

0. Create two DCs: onprem and minikube. Initially there is no AS3 declaration.
1. Submit the declaration state.0.json.txt. This succeeds.
2. Submit the declaration state.1.json.txt. This fails.
3. Observe the error in result-0-1.json.txt

### Expected Behavior

Step #2 should succeed.

### Actual Behavior

Step #2 fails unexpectedly.

[state.0.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/5421685/state.0.json.txt)
[state.1.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/5421687/state.1.json.txt)
[result-0-1.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/5421689/result-0-1.json.txt)

**Comment by dstokesf5** [comment]
I have confirmed that there is a bug when renaming GSLB server objects. There are a couple of ways to work around this issue until it is fixed:
1. POST the second declaration again (for some reason this seems to work).
1. Send a DELETE request to clear the configuration before POSTing the second declaration so that you are creating a new GSLB server instead of renaming it.

I have added this bug to our internal product backlog as AUTOTOOL-2036.

**Comment by dstokesf5** [comment]
Due to some technical issues when working in Common, properly supporting renames of GSLB servers in the Common partition is difficult. This will likely not be resolved for quite some time. In the meantime, I recommend using the work-arounds mentioned above.

**Comment by alonsocamaro** [comment]
Hi @dstokesf5 

Please note that I'm not doing renames.

**Comment by dstokesf5** [comment]
The GSLB_Server containing a device with the IP address of 10.105.217.30 is called minikube_default in `state.0.json` and minikube_az1 in `state.1.json`. There are some ordering requirements to handle corss-tenant referencing when configuring the Common tenant that results in a create command for minikube_az1 before the delete command of minikube_default. This causes the IP conflict described by the error message.

**Comment by alonsocamaro** [comment]
@dstokesf5 Thanks for the clarification.
