### ISSUE TITLE
WAF policy enforcement mode not honored in JSON security policy

### ISSUE THREAD

**Issue by mikeshimkus** [F5Networks/f5-appsvcs-extension#367]
### Environment
 * Application Services Version: 3.23.0
 * BIG-IP Version: 15.1.0.4

### Summary
When using this JSON security policy and enforcementMode set to "blocking", the policy is deployed in transparent mode: https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-templates/v1.1/owasp_ready_template/owasp_policy_v1.0.json

### Steps To Reproduce
1. Submit the following declaration:
```json
"My_ASM_Policy": {
  "class": "WAF_Policy",
  "ignoreChanges": false,
  "enforcementMode": "blocking",
  "url": "https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-templates/v1.1/owasp_ready_template/owasp_policy_v1.0.json"
}
```
enforcementMode is honored when using an XML policy, such as:

https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-templates/master/generic_ready_template/Rapid_Depolyment_Policy_13_1.xml

2. Observe the following error response:
No error response.

### Expected Behavior
The policy should be deployed in blocking mode.

### Actual Behavior
The policy is deployed in transparent mode.

**Comment by dstokesf5** [comment]
AS3 does not support overriding DWAF policy settings. Instead, the adjustments section of a DWAF policy should be used instead.

I have added AUTOTOOL-2004 to make this more clear to users with errors and documentation updates.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
