### ISSUE TITLE
serverssl SNI supports for default ssl and require peer options

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-appsvcs-extension#368]
### Is your feature request related to a problem? Please describe.
Looks like is a new feature, below server-ssl profile options are not covered atm by AS3

Default SSL Profile for SNI
Require Peer SNI support 

The "SNI Server Name" option is already supported by AS3.

### Describe the solution you'd like
Both params are simply on| off 

### Describe alternatives you've considered
none

### Additional context
none

**Comment by dstokesf5** [comment]
Thank you for your feedback. Due to the age of this feature request, I would like to know if this is still something you need or are interested in.

**Comment by tizianorosato-gr** [comment]
still interested, thanks

**Comment by sunitharonan** [comment]
If you still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com
