### ISSUE TITLE
AS3 is missing User-Defined Storage Format in schema

### ISSUE THREAD

**Issue by lasseh** [F5Networks/f5-appsvcs-extension#372]
### Is your feature request related to a problem? Please describe.
AS3 is missing support for User-Defined Storage Format in Log profile.
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#security-log-profile-application-storageformat

### Describe the solution you'd like
"storageFormat": {
	"user-defined": "f5_asm=Splunk-F5-ASM,<snip>"
}

### Additional context
Now i have to add it manualy here:
Security  ››  Event Logs : Logging Profiles  ››  Edit Logging Profile
But this then gets overwritten when i run the AS3 again.

**Comment by dstokesf5** [comment]
This has been added to our internal product backlog as AUTOTOOL-2044.

**Comment by walterk82** [comment]
I'm voting for this issue as well. Thank-You.

**Comment by walterk82** [comment]
What does closing this issue mean/do?
