### ISSUE TITLE
Embedding JSON/XML WAF policies in AS3 declaration 

### ISSUE THREAD

**Issue by nashkenazi** [F5Networks/f5-appsvcs-extension#375]
### Is your feature request related to a problem? Please describe.
No option to embed the WAF policy as part of the AS3 request

### Describe the solution you'd like
The ability that the mBIP management plane will able to push WAF policies to mBIPs as part of the AS3 declaration.

### Describe alternatives you've considered
generate download link and require the user to specify credentials only to use an existing configuration on the management layer.

### Additional context
Please contact E.Agami@f5.com for more technical details

**Comment by delgadillo22** [comment]
Added to internal backlog as AUTOTOOL-2055

**Comment by dstokesf5** [comment]
This was resolved in the 3.26.0 release.

**Comment by fpieressa** [comment]
Hi! I'm seeing this feature request was added in 3.26.0, can you please confirm how can I send an ASM xml policy without the "url" parameter? Is there any way to send it attached in the AS3 JSON Request?

Thanks!

**Comment by RobCupples** [comment]
Check out this section of the AS3 documentation.

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/application-security.html?highlight=waf_policy#embedding-a-waf-policy-in-a-declaration

**Comment by bwearp** [comment]
Sorry to post this here, especially as it is so old. 
For the url: 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/application-security.html?highlight=waf_policy#urlex

How does the policy get uploaded to the BIG-IP.

For the base64 and text it is clear - it is part of the declaration, but for the uri it is not obvious.

Does the AS3 software download the policy referenced in the uri and then make it part of the AS3 declaration, or does the BIG-IP on receiving the uri in the AS3 declaration, download the policy from that remote location?
