### ISSUE TITLE
Post status to a webhook

### ISSUE THREAD

**Issue by lasseh** [F5Networks/f5-appsvcs-extension#377]
### Is your feature request related to a problem? Please describe.
Is it possible to get the status from the AS3 posted as a webhook the same way Declarative Onboarding does?
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/schema-reference.html#device

### Describe the solution you'd like
```
{
    "class": "AS3",
    "action": "deploy",
    "webhook": "http://example.com/webhook",
    .....
```

**Comment by dstokesf5** [comment]
Thank you for your feedback. Unfortunately, we have decided that this functionality is not as valuable for AS3, and we are not interested in investing resources into it at this time. I am closing this issue.
