### ISSUE TITLE
Add Endpoint_Policy matching rules for HTTP Basic Auth username

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#379]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Please add support for Endpoint_Policy conditions to support HTTP Basic Auth username criteria.  Supporting Basic Auth conditions will allow for feature parity with the out-of-box LTM matching rules.

### Describe alternatives you've considered
iRules is an option, however, LTM policies are more performant than iRules and this is required for efficiency purposes.

**Comment by dstokesf5** [comment]
Thank you for your feedback. Due to the age of this feature request, I would like to know if this is still something you need or are interested in.

**Comment by walterk82** [comment]
Yes, we have a deployment where we perform some basic checks on the username presented to know which direction an HTTP request should flow.  This does not affect the security of the application but does make it easier to handle application-to-application connectivity using VIP targeting.

**Comment by j-zehnder** [comment]
Is it possible to get an update on this issue?

**Comment by sunitharonan** [comment]
If you still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com
