### ISSUE TITLE
make as3 validator available in a container 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-appsvcs-extension#38]
Please make AS3 validator available as a container. either independent or within the AS3 container. 
that will make it a lot easier to use
Thanks

**Comment by JosephPJordan** [comment]
Hello Yossi, 
This is currently on our roadmap and we hope to have it complete in a upcoming release.  Will update this issue when it is available.

**Comment by kaustriaf5** [comment]
Latest update: we will no longer be doing additional/feature enhancement for this specific tool. We are currently exploring a new approach/implementation to provide improved validation capabilities to users (776). Please keep an eye out for our new releases for more information.

**Comment by simonkowallik** [comment]
Hi, I created an AS3 Schema Validator docker image, you can find it on Docker Hub till we get to the future implementation.
[https://hub.docker.com/r/simonkowallik/f5-as3sv](https://hub.docker.com/r/simonkowallik/f5-as3sv)

**Comment by delgadillo22** [comment]
We are no longer enhancing the AS3 Validator tool, and will soon be providing documentation for a better and more efficient way to validate AS3 declarations directly within VSCode.
