### ISSUE TITLE
AS3 is missing http2 monitor 

### ISSUE THREAD

**Issue by joebride** [F5Networks/f5-appsvcs-extension#380]
### Is your feature request related to a problem? Please describe.
No AS3-declaration for http2 monitor available.

### Describe the solution you'd like
AS3-declaration should be cover the following http2 monitor-parameters:
    interval 
    recv-string
    recv-disable-string
    send-string
    time-until-up 
    timeout 
}

### Describe alternatives you've considered
No

### Additional context
AdvWAF in http2 full-proxy mode requires http2-monitors.
F5-requirement is to have only http2-webservers within single pool.
This monitor ensures that no "fallback" to http1.x occurs and take pool-member down, when not http2-compatible.
See also Service Request #C3356850.

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-2103.
