### ISSUE TITLE
AS3 is missing server-ssl profile parameters for renegotiation and retain-certificate

### ISSUE THREAD

**Issue by joebride** [F5Networks/f5-appsvcs-extension#381]
### Is your feature request related to a problem? Please describe.
No AS3-declaration available for server-ssl profile parameter "renegotiation" and "retain-certificate".

### Describe the solution you'd like
AS3-declaration should be cover the following server-ssl profile parameters:
renegotiation 
retain-certificate

### Describe alternatives you've considered
-

### Additional context
The server-ssl profile parameter "renegotiation" is mandatory for usage of http2 on server-side.
retain-certificate set to false optimize memory consumption of BIG-IP (F5 best-practice).

**Comment by mdditt2000** [comment]
@joebride are you looking to enabling or disabling either renegotiation/retain-certificate as shown below? Both are enabled by default on BIG-IP

![image](https://user-images.githubusercontent.com/12733938/100676776-6915bd80-331e-11eb-9fcc-9de300b2abd1.png)

**Comment by joebride** [comment]
@mdditt2000: I would like to disable it.

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-2102.

**Comment by mdditt2000** [comment]
@joebride - AUTOTOOL-2102: (GitHub Issue 381): Add renegotiationEnabled and retainCertificateEnabled properties to TLS_Client and TLS_Server classes is resolved in AS3 25 coming shortly. I have requested CIS 2.2.2 support this new schema.

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 3.25.0 release.
