### ISSUE TITLE
Unable to change virtual address in declaration

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#383]
### Environment
 * Application Services Version: 3.22
 * BIG-IP Version: 15.1

### Summary
Unable to change virtual address in an existing deployed declaration.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "schemaVersion": "3.22.0",
    "class": "ADC",
    "Tenant": {
        "class": "Tenant",
        "defaultRouteDomain": "2",
        "Application": {
            "template": "generic",
            "vip": {
                "class": "Service_HTTPS",
                "pool": "web_pool",
                "virtualAddresses": [
                   { "use": "vaddr" }
                ]
            },
           "vaddr": {
             "class": "Service_Address",
             "virtualAddress": "172.21.1.10",
             "trafficGroup": "custom-tg"         
           }
        }
    }
}
```

2. Observe the following error response:
```json
results: [
 {
  code: 422,
  message: 'declaration failed',
  response: '0107176a:3: Invalid Virtual Address modification. An address change from 172.21.1.20%2 to 172.21.1.10%2 is not supported',
  host: 'localhost',
  tenant: 'Tenant',
  runTime: 28160
 }
]

```

### Expected Behavior
Declaration to deploy successfully.

### Actual Behavior
The declaration fails to deploy as it's a non-supported address change.

**Comment by mdditt2000** [comment]
@oakh1 i am getting the same error when changing the Virtual IP referenced by the { "use": "vaddr" }. Why don't you specify the address instead of using a pointer/reference? Specifying the IP address and posting a update works good.

**Comment by oakh1** [comment]
If you mean why I am using a service address instead of simply specifying the IP? Well, the reason why I have to use a service_address is because I have to use a custom traffic-group for that IP address. The reason for that is because the APM module is bound to one specific traffic group, and that traffic group is not the default one that's assigned when using a normal virtual address.

In other words, if I don't use a Virtual_Address with our custom traffic group, I am not able to bind any APM/access policy to that service.

**Comment by dstokesf5** [comment]
I have confirmed the bug. I suspect that the transaction is combining a delete and create into a modify when it should not be. I have added this to our internal product backlog as AUTOTOOL-2076.

**Comment by oakh1** [comment]
Yea, there's something weird with it, at some point (don't know when and why), I can't update the declarations using virtual addresses either, they fail with: "01070344:3: Cannot delete referenced virtual address /tenant/10.10.10.1%2." **even when the virtual addresses are still existing in the declaration**. When that happens I have to delete the entire partition + service addresses and then deploy it again.

**Comment by dstokesf5** [comment]
It looks like tmsh does not allow modifying of the virtual-address address property. Since this will require additional work for AS3 to track users, break those connections, delete the object, recreate it with the new address, and then restore the connections all in a robust way, I am changing this to a feature request.

It appears that the Ansible module also does not allow modifying the address of a virtual-address object: https://docs.ansible.com/ansible/2.5/modules/bigip_virtual_address_module.html

**Comment by oakh1** [comment]
Interesting & good finding.. In that case, I suppose we will try to migrate away from using specific traffic-groups and instead just use a single one (and thus being able to use APM on all virtual servers without having to use the somewhat buggy virtual addresses.

Thank you for getting back.

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com
