### ISSUE TITLE
HA sync fails for a few seconds after posting AS3 declaration on HA device

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-extension#384]
### Environment
 * Application Services Version: 3.24
 * BIG-IP Version: 14.1

### Summary
HA sync is broken for a few seconds after posting AS3 declaration on HA device.

### Steps To Reproduce
1.Configured AS3 service discovery endpoint and added nodes on one of the BIG-IP devices in HA.
```json
[
    {
        "ip": "45.43.2.2",
        "id": "/AS3.24/45.43.2.2"
    },
    {
        "ip": "89.3.2.2",
        "id": "/AS3.24/89.3.2.2"
    },
    {
        "ip": "56.3.3.2",
        "id": "/AS3.24/56.3.3.2"
    }
]
```

### Expected Behavior
Node/Pool member update on both devices should happen without breaking the HA sync of the BIG-IP devices.

### Actual Behavior
As soon as the above dictionary is Posted to service discovery endpoint,  the sync between two HA devices is broken with the sync message “Not all devices are synced” and reformed after a few seconds.

**Comment by vishwajeetgslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by dstokesf5** [comment]
How is this any different than an expected sync after a configuration change?

**Comment by vishwajeetgslab** [comment]
For Configuration change in case of default Gateway and floating IP sync between two devices we never observed the sync fail for few seconds. Is this an expected behavior while configuration change for Service discovery endpoint on HA devices? And is this behavior also expected in other config change scenarios?

**Comment by dstokesf5** [comment]
If AS3 makes changes to the configuration, then there will be configuration changes that will need to be synchronized between devices in an HA cluster. AS3 will not make changes to both devices at the same time to keep them in sync.

I tested this scenario on the latest version of AS3 and saw no unexpected behavior. Are you still seeing this problem with the latest version of AS3?
