### ISSUE TITLE
Node/pool Members are not synced on AS3 service discovery REST API for HA devices

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-extension#385]
### Environment
 * Application Services Version: 3.24
 * BIG-IP Version: 14.1

### Summary
Node/pool Members are not synced on AS3 service discovery REST API for HA devices. Although nodes do get synced between the two BIG-IP devices, it is just the REST API on two devices which are not in sync.

### Steps To Reproduce
1.Configured AS3 service discovery endpoint and added nodes on one of the devices in HA.
```json
[
    {
        "ip": "45.43.2.2",
        "id": "/AS3.24/45.43.2.2"
    },
    {
        "ip": "89.3.2.2",
        "id": "/AS3.24/89.3.2.2"
    },
    {
        "ip": "56.3.3.2",
        "id": "/AS3.24/56.3.3.2"
    }
]
```
2.Verified the service discovery REST API for BIG-IP1-  https://BIG-IP1/mgmt/shared/service-discovery/task/~AS3.24~AP1~Pool1

REST API Response on BIG-IP1-
```json
{
    "code": 200,
    "result": {
        "id": "~AS3.24~AP1~Pool1",
        "updateInterval": 0,
        "provider": "event",
        "providerOptions": {
            "type": "event",
            "nodeList": [
                {
                    "ip": "45.43.2.2",
                    "id": "/AS3.24/45.43.2.2"
                },
                {
                    "ip": "89.3.2.2",
                    "id": "/AS3.24/89.3.2.2"
                },
                {
                    "ip": "56.3.3.2",
                    "id": "/AS3.24/56.3.3.2"
                }
            ]
        },
        "resources": [
            {
                "type": "pool",
                "path": "/AS3.24/AP1/Pool1",
                "options": {
                    "servicePort": 8080,
                    "connectionLimit": 0,
                    "rateLimit": "disabled",
                    "dynamicRatio": 1,
                    "ratio": 1,
                    "priorityGroup": 0,
                    "monitor": "default"
                },
                "requiresNodes": true
            }
        ],
        "kind": "shared:service-discovery:taskstate",
        "lastRun": "2020-11-30T13:01:05.902Z",
        "nodePrefix": "/AS3.24/"
    }
}
```

3.Verified the service discovery REST API for BIG-IP2-  https://BIG-IP2/mgmt/shared/service-discovery/task/~AS3.24~AP1~Pool1

REST API Response on BIG-IP2-
```json
{
    "code": 404,
    "message": "",
    "referer": "10.107.0.5",
    "originalRequestBody": "",
    "errorStack": []
}
```

### Expected Behavior
Dictionary with node IP entries should be same on both HA device's service discovery REST API endpoints

### Actual Behavior
Node/pool members are not synced to peer device’s service discovery REST API. Although nodes do get synced between the two BIG-IP devices, it is just the REST API on two devices which are not in sync.

**Comment by vishwajeetgslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by payalsin** [comment]
@dstokesf5 - any update on this issue.

**Comment by dstokesf5** [comment]
Thank you for reporting this issue. I have added it to our internal product backlog as AUTOTOOL-2083.

**Comment by sunitharonan** [comment]
In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com
