### ISSUE TITLE
severe: [RestOperationDispatcher] 'shared/service-discovery/task' not found.

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#387]
### Environment
 * Application Services Version: 3.24.0
 * BIG-IP Version: 15.1.2

### Summary
_/var/log/restnoded/restnoded.log_ has numerous **severe** and **warning** outputs as follows:

Tue, 01 Dec 2020 20:09:38 GMT - severe: [RestOperationDispatcher] 'shared/service-discovery/task' not found.
Tue, 01 Dec 2020 20:09:38 GMT - severe: [ErrorHandlingModule] RestOperation failed: "/shared/service-discovery/task?$filter=partition+eq+App1PA". {"code":404,"message":"","referer":"Unknown","originalRequestBody":"","errorStack":[]}
Tue, 01 Dec 2020 20:09:38 GMT - warning: [appsvcs] {"message":"Unable to fetch state from /mgmt/shared/service-discovery/task","level":"warning"}

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "class": "ADC",
  "schemaVersion": "3.24.0",
  "App1PA": {
    "class": "Tenant",
    "Shared": {
      "class": "Application",
      "template": "shared",
      "App1_pa_cookie_persist": {
        "class": "Persist",
        "persistenceMethod": "cookie",
        "cookieName": "LB"
      },
      "probe_https_monitor": {
        "class": "Monitor",
        "monitorType": "https",
        "send": "GET /probe.aspx \r\nConnection: Close\r\n\r\n",
        "receive": "App1 online.*"
      }
    },
    "DEV": {
      "class": "Application",
      "template": "generic",
      "App1_pa_dev0_443_vs": {
        "class": "Service_HTTPS",
        "virtualAddresses": [
          "10.7.45.223"
        ],
        "virtualPort": 443,
        "redirect80": false,
        "profileTCP": {
          "bigip": "/Common/Default-TCP"
        },
        "profileHTTP": {
          "bigip": "/Common/Default-HTTP"
        },
        "snat": {
          "bigip": "/Common/Default-SNATPool"
        },
        "serverTLS": {
          "bigip": "/Common/wildcard-ClientSSL"
        },
        "clientTLS": {
          "bigip": "/Common/RootCA-ServerSSL"
        },
        "pool": "App1_pa_dev0_443_pool",
        "persistenceMethods": [
          {
            "use": "/@/Shared/App1_pa_cookie_persist"
          }
        ]
      },
      "App1_pa_dev0_443_pool": {
        "class": "Pool",
        "monitors": [
          {
            "use": "/@/Shared/probe_https_monitor"
          }
        ],
        "members": [
          {
            "servicePort": 443,
            "serverAddresses": [
              "10.1.1.1",
              "10.1.1.2"
            ]
          }
        ]
      }
    }
  }
}
```

2. Observe the following error response:
There is no error response, but there are messages on the backend node logs.

### Expected Behavior
restnoded.log should be clear of error and warning messages on declaration posts.

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by dstokesf5** [comment]
I believe there is something wrong with your BIG-IP that is causing problems with service discovery. What do you get from GET requests to /mgmt/shared/service-discovery/info and /mgmt/shared/service-discovery/task?

**Comment by walterk82** [comment]
Right, both result in an HTTP 404 error

**Comment by walterk82** [comment]
Is there a way to manually install service-discovery RPM outside of the AS3 RPM?

**Comment by dstokesf5** [comment]
Does f5-service-discovery show up in the list of LX packages in the GUI? If you uninstall  f5-service-discovery, that will force AS3 to reinstall it.

Yes, you could pull the service discovery RPM from the AS3 RPM to force a manual reinstall.

**Comment by walterk82** [comment]
Yes, it shows.  It was built from the auto-install process.  But I have been having an issue with diskspace under /var because of this auto installation process.

**Comment by walterk82** [comment]
I performed a manual install of service-discovery and those end-points are working now.  However, the RPM didn't auto-install on the other device group members like usual.

**Comment by m-kratochvil** [comment]
I found we have the same issue on our Big-IPs. Although we're not using service discovery, the above mentioned endpoints `info`
 and `task` were returning 404 response until I uninstalled service discovery package which resulted in its re-install and now the endpoints work correctly. And in my case this action was auto replicated on the standby Big-IP.

Why is that happening, any idea what causes service discovery to require re-install?
Is there any adverse effect on the AS3/Big-IP environment with this non-working service discovery state, even if the service discovery itself is not used?

We're on TMOS v13.1.3.4 and v15.1.2; AS3 v3.22, same behavior on both TMOS versions

Before:
```
restcurl -u admin:xxxxx /mgmt/shared/service-discovery/info
{
  "code": 404,
  "message": "",
  "referer": "Unknown",
  "originalRequestBody": "",
  "errorStack": []
}
restcurl -u admin:xxxxx /mgmt/shared/service-discovery/task
{
  "code": 404,
  "message": "",
  "referer": "Unknown",
  "originalRequestBody": "",
  "errorStack": []
}
```
After
```
restcurl -u admin:xxxxx /mgmt/shared/service-discovery/info
{
  "version": "1.3.0-1"
}
restcurl -u admin:xxxxx /mgmt/shared/service-discovery/task
{
  "code": 200,
  "items": []
}
```

**Comment by dstokesf5** [comment]
It is unclear to me at this time why service discovery would enter into this bad state. Are either of you seeing any message in restnoded about service discovery rest workers failing to start?

Based on the log snippet provided in the original post, I believe AS3 should still be able to function normally if service discovery is not being used. The severe level log messages are from the framework generating 404 responses. The AS3 (appsvcs) log message is at a warning level, which means AS3 should continue processing without the service discovery information.

**Comment by walterk82** [comment]
Yes, AS3 base operations seem to be unaffected by this particular error.  I don't remember the timing if this was triggered by any device upgrades.  However, I have noticed that sometimes AS3 will not persist thru a software upgrade and that the package must be re-installed as a post process upgrade item even thought the GUI still lists the RPM as installed.

I usually perform this action by a full package removal, then re-deployments.

**Comment by dstokesf5** [comment]
There are known issues with the iControl LX extension framework where most extensions are lost on an upgrade. One example is this one: https://cdn.f5.com/product/bugtracker/ID929213.html. Fortunately, your AS3 data should be fine.

**Comment by walterk82** [comment]
I'm wondering if ID995173 and https://github.com/F5Networks/f5-appsvcs-extension/issues/311 are related to that bug since UCS save will not complete correctly which is key to having the upgrade complete.

**Comment by walterk82** [comment]
@dstokesf5 Can you escalate internally to see if these are related or should I open a support case?

**Comment by dstokesf5** [comment]
Any extension that reaches a certain size threshold encounters timeouts that cause it to be excluded from a UCS. Reviewing the internal discussion on 929213, it appears this is suspected to be the root cause of the packages disappearing on an upgrade.

The long time to save an extension during the UCS process (985329) is related to those extensions timing out.

995173 should help AS3 users that are not using service discovery work around these framework problems.
