### ISSUE TITLE
endpoint_policy http method check implementation

### ISSUE THREAD

**Issue by roefe** [F5Networks/f5-appsvcs-extension#390]
### Is your feature request related to a problem? Please describe.
We need to create a L7 Policy, which checks the http Method. The L7 Policy shall be implemented using AS3

### Describe the solution you'd like
Creating a condition match type httpMethod

### Describe alternatives you've considered
Manual Integration of the L7 Policy (no AS3 Automation)
Creating an iRule using AS3 and reference it

**Comment by dstokesf5** [comment]
This has been added to our internal product backlog as AUTOTOOL-2440.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 3.28.0 release.
