### ISSUE TITLE
Ability to Attach APM Profiles to Service_TCP Virtual Servers

### ISSUE THREAD

**Issue by rayterrill** [F5Networks/f5-appsvcs-extension#398]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
This appears to be supported from the F5 GUI. Allow us to attach APM profiles with profileAccess to Service_TCP Virtual Servers.

### Describe alternatives you've considered
Could use Service_HTTP/S

**Comment by walterk82** [comment]
How do you get this apply in the GUI?  APM Requires HTTP enabled VIPs.  Under 15.1.2 the GUI displays a JavaScript pop-up warning of this condition.
