### ISSUE TITLE
restnoded should use forward proxy

### ISSUE THREAD

**Issue by thomas-rd21** [F5Networks/f5-appsvcs-extension#404]
### Is your feature request related to a problem? Please describe.

AS3 respectively  restnoded does not use forward-proxy settings.
I've tried the FAST template for ADFS and it tried to download the ADFS_eav_monitor script from raw.githubusercontent.com directly, without using the forward proxy settings.
The F5 system has no direct access to the internet.

/var/log/restnoded/restnoded.log:
`Thu, 07 Jan 2021 12:41:17 GMT - severe: [appsvcs] {"message":"GET https://raw.githubusercontent.com/f5devcentral/f5-bd-FASTexample/master/ADFS/eav_scripts/adfs_eav.sh for /TENANT1/ADFS/ADFS_eav_monitor/script failed (connect ECONNREFUSED 151.101.12.133:443)","level":"error"}
`

### Describe the solution you'd like

restnoded should use the proxy settings configured with tmsh

```# tmsh list /sys db proxy*
sys db proxy.host {
    value "10.23.4.5"
}
sys db proxy.password {
    value "<null>"
}
sys db proxy.port {
    value "8080"
}
...
````

### Describe alternatives you've considered

Alternate options to download content from internet for a system without access (no route nor ACL) to the internet.

### Additional context

TMOS: 15.1.0.4
AS3: 3.24.0-5
FAST Templates: 1.5.0-1

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this feature request to our internal product backlog as AUTOTOOL-2749.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
