### ISSUE TITLE
AS3 / DO incompatibility for GSLB objects

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-appsvcs-extension#405]
### Environment
 * Application Services Version: 3.25
 * Declarative Onboarding Version: 1.18
 * BIG-IP Version: 15.1.2

### Summary
If a Datacenter is created with DO (or manually), it is not available in Common AS3 declaration. and AS3 deny creating this object as it already exists.

So when I try to create a new gslbServer, If the Datacenter is not in current declaration, I add a GSLB_Data_Center object....

### Steps To Reproduce

1. Submit the following DO declaration:
```json
{
    "schemaVersion": "1.15.0",
    "class": "Device",
    "async": true,
    "label": "Onboarding from Ansible Tower",
    "Common": {
        "class": "Tenant",
        "System": {
            "cliInactivityTimeout": 1200,
            "consoleInactivityTimeout": 1200,
            "autoPhonehome": false
        },
        "hostname": "gtm1.demo.local",
        "myProvisioning": {
            "class": "Provision",
            "gtm": "nominal"
        },
...
        "gslbGlobals": {
            "class": "GSLBGlobals",
            "general": {
                "synchronizationEnabled": true,
                "synchronizationGroupName": "GSLB_Sync_Group"
            }
        },
        "DC2": {
            "class": "GSLBDataCenter",
            "enabled": true
        },
        "DC2_GTM": {
            "class": "GSLBServer",
            "label": "Example of all GSLB server properties",
            "remark": "GSLB server description",
            "devices": [
                {
                    "address": "fd00:0:f5::130",
                    "remark": "DC2_GTM"
                }
            ],
            "dataCenter": "/Common/DC2",
            "virtualServerDiscoveryMode": "disabled",
            "exposeRouteDomainsEnabled": true
        }
    }
}
```
2. Get the Common Tenant Configuration

URL: https://<bigip>/mgmt/shared/appsvcs/declare/Common
Method: GET

When the device is just onboarded, the server respond with 404 status code... 

So to create the new gslbServer and include it is DC2 with "use" property, I have to create it in AS3.

3. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.18.0",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "LTM2": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "DC2"
                    },
                    "devices": [
                        {
                            "address": "fd00:0:f5::132",
                            "label": "ltm2.demo.local",
                            "name": "ltm2.demo.local"
                        }
                    ],
                    "virtualServers": [],
                    "exposeRouteDomainsEnabled": true
                },
                "DC2": {
                    "class": "GSLB_Data_Center"
                }
            }
        }
    }
}
```

2. Observe the following error response:
```json
{
    "code": 422,
    "message": "declaration failed",
    "response": "01020037:3: The requested Datacenter (/Common/DC2) already exists.",
    "host": "localhost",
    "tenant": "Common",
    "runTime": 2491
}
```

### Expected Behavior
DO and AS3 may share objects which can be configured in both API.

### Actual Behavior
both gslbServer and Datacenter can be created in AS3 and DO, but AS3 is not aware of such objects... so it create an issue when trying to create it again.

**Comment by dstokesf5** [comment]
A use-pointer is meant for referencing other AS3 configuration. If you want to reference something managed outside of AS3, I recommend using a bigip-pointer:
```json
                    "dataCenter": {
                        "bigip": "/Common/DC2"
                    },
```

Does updating your declaration to a bigip-pointer resolve your issue?

**Comment by stanislaspiron** [comment]
So you mean we must not use Datacenter object in DO if we want to manage the GSLB configuration with AS3...

**Comment by dstokesf5** [comment]
If you create the Datacenter in DO, use a bigip-pointer like the one I mentioned previously.
If you create the Datacenter in AS3, use a use-pointer like the one you have in your declaration.

**Comment by stanislaspiron** [comment]
That's what I knew... I was expecting that if both DO and AS3 can create this kind of objects, DO can share this part of declaration with AS3. 
when building a AS3 declaration with automation tools, it's better to build all Datacenter objects with the same type of pointers...

So if we want to manage datacenters with AS3, it's recommended to not use Datacenter objects in DO.

you can close this issue.
