### ISSUE TITLE
receiveDown string added to "Receive String" within BIG-IP instead of "Receive Disable String"

### ISSUE THREAD

**Issue by Harm4432** [F5Networks/f5-appsvcs-extension#408]
### Environment
 * Application Services Version: 3.23.0 Build 5
 * BIG-IP Version: 15.1.0.2

### Summary
When making the following declaration the receiveDown ends up being placed in the "Receive String" on the BIG-IP.  In the example below, the BIG-IP then shows Receive String of "Status\\:0 recv-disable Status\\:1" basically concatenating the AS3 Attributes of "receive" and "receiveDown".

        "epic_bca2": {
            "bca2": {
                "send": "GET /maintenance/status.json HTTP/1.0\\r\\n\\r\\n",
                "class": "Monitor",
                "label": "EpicMaintenance_HealthRDS_HTTPS",
                "ciphers": "DEFAULT:+SHA:+3DES:+kEDH",
                "receive": "Status\\\":0",
                "timeout": 16,
                "interval": 5,
                "monitorType": "https",
                **"receiveDown": "Status\\\":1"**
            }, 

### Expected Behavior
It is expected that attribute receive should be placed in the "Receive String" and the receiveDown attribute would be placed in the "Receive Disable String" of the BIG-IP.  

### Actual Behavior
Attribute receive and receiveDown are concatenated in the "Receive String"

**Comment by dstokesf5** [comment]
I have added this to our internal product backlog as AUTOTOOL-2214. Thank you for reporting it.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
