### ISSUE TITLE
AS3 Add support for "exists" and "does not exist" to Policy_Compare_String

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#411]
### Is your feature request related to a problem? Please describe.
Per https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#policy-compare-string

The comparison operator should allow for _exists_ and _does not exist_ as these features are present in at least TMOS level 15.1

### Describe the solution you'd like
Policy_Compare_String _operand_ should support clauses for _exist_ and _does not exist_ to match TMOS support.

### Describe alternatives you've considered
The only option is to build LTM policy outside of AS3 and attach to Virtual thru the use of a "bigip" semantic.

**Comment by walterk82** [comment]
@dstokesf5 Can this issue be be addressed?  Thanks.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This issue has been added to our internal product backlog as     AUTOTOOL-2483.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 3.29.0 release.
