### ISSUE TITLE
add possibility to use IP Pool in AS3 templates.

### ISSUE THREAD

**Issue by jlindr** [F5Networks/f5-appsvcs-extension#414]
Hi,
Inside BIG-IQ you could create "IP Pools" and then use them when creating applications with the "old" Service Catalog Templates.
Could you please add this option when using AS3 templates as well?

**Comment by dstokesf5** [comment]
IPAM is currently outside of AS3's scope. If you feel that this something important to have on BIG-IQ, please create a Service Request ticket on the BIG-IQ product. I am closing this issue since it does not follow the required template for AS3 feature requests.
