### ISSUE TITLE
Authorization failed  for user with the Administrator Role

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/f5-appsvcs-extension#420]
### Environment
 * Application Services Version: f5-appsvcs-3.26.0-5.noarch
 * BIG-IP Version:  BIG-IP 15.1.1 Build 0.0.6 Point Release 0 

### Summary
Installed AppSvc plugin which was successful. When calling the appsvc REST endpoint using an external user with the Administrator role it returns a Authorization failed but does work if I call a different endpoint such as the virtual services one. If I try it with the out of box admin user the appsvcs endpoint returns successfully. 

#### Installed Plugins

![Screen Shot 2021-03-02 at 11 41 35 AM](https://user-images.githubusercontent.com/4107699/109690747-49c04380-7b4c-11eb-810f-0d05ea7fd955.png)

#### User I am testing with

![Screen Shot 2021-03-02 at 11 09 28 AM](https://user-images.githubusercontent.com/4107699/109686364-d3214700-7b47-11eb-865f-30e95a0aab66.png)

### Steps To Reproduce

1. Cannot call appsvc info endpoint using above user or other users with Administrator role
```
$ curl -X GET "https://asc-stg-f504.ascendlearning.com/mgmt/shared/appsvcs/info" -H "Content-Type: application/json" -k -u 'mmaler-admin:REDACTED'
{"code":401,"message":"Authorization failed: user=https://localhost/mgmt/shared/authz/users/mmaler-admin resource=/mgmt/shared/appsvcs/info verb=GET uri:http://localhost:8100/mgmt/shared/appsvcs/info referrer:REDACTED sender:REDACTED","referer":"REDACTED","restOperationId":166951379,"kind":":resterrorresponse"}⏎
```

2. Can call different non-appsvc endpoint using above user
```
$ curl -X GET "https://server.ascendlearning.com/mgmt/tm/ltm/virtual/" -H "Content-Type: application/json" -k -u 'mmaler-admin:REDACTED'
{"kind":"tm:ltm:virtual:virtualcollectionstate","selfLink":"https://localhost/mgmt/tm/ltm/virtual?ver=15.1.1","items":[{"kind":"tm:ltm:virtual:virtualstate","name":"test","partition":"Common","fullPath":"/Common/test","generation":1,"selfLink":"https://localhost/mgmt/tm/ltm/virtual/~Common~test?ver=15.1.1","addressStatus":"yes","autoLasthop":"default","cmpEnabled":"yes","connectionLimit":0,"creationTime":"2020-11-13T17:54:17Z","destination":"/Common/REDACTED:443","enabled":true,"evictionProtected":"disabled","gtmScore":0,"ipProtocol":"tcp","lastModifiedTime":"2020-11-13T18:47:23Z","mask":"255.255.255.255","mirror":"disabled","mobileAppTunnel":"disabled","nat64":"disabled","pool":"/Common/test","poolReference":{"link":"https://localhost/mgmt/tm/ltm/pool/~Common~test?ver=15.1.1"},"rateLimit":"disabled","rateLimitDstMask":0,"rateLimitMode":"object","rateLimitSrcMask":0,"serversslUseSni":"disabled","serviceDownImmediateAction":"none","source":"0.0.0.0/0","sourceAddressTranslation":{"type":"automap"},"sourcePort":"preserve","synCookieStatus":"not-activated","translateAddress":"enabled","translatePort":"enabled","vlansDisabled":true,"vsIndex":2,"rules":["/Common/X-Forwarded-Proto","/Common/X-Request-Start","/Common/Strip_Server_Name"],"rulesReference":[{"link":"https://localhost/mgmt/tm/ltm/rule/~Common~X-Forwarded-Proto?ver=15.1.1"},{"link":"https://localhost/mgmt/tm/ltm/rule/~Common~X-Request-Start?ver=15.1.1"},{"link":"https://localhost/mgmt/tm/ltm/rule/~Common~Strip_Server_Name?ver=15.1.1"}],"policiesReference":{"link":"https://localhost/mgmt/tm/ltm/virtual/~Common~test/policies?ver=15.1.1","isSubcollection":true},"profilesReference":{"link":"https://localhost/mgmt/tm/ltm/virtual/~Common~test/profiles?ver=15.1.1","isSubcollection":true}}]
```

3. Can call appsvc info endpoint using built in admin account
```
$ curl -X GET "https://asc-stg-f503.ascendlearning.com/mgmt/shared/appsvcs/info" -H "Content-Type: application/json" -k -u 'admin:REDACTED'
{"version":"3.26.0","release":"5","schemaCurrent":"3.26.0","schemaMinimum":"3.0.0"}
```

### Expected Behavior
Able to call the appsvc endpoint using a external user with the Administrator or Resource Administrator role so we can use the big-ip cis controller

### Actual Behavior
Returns Auth Failed 401 when using one of these users other than the built in admin account.

I have also logged the SR #C3502290 which explains the same detail above.

**Comment by dstokesf5** [comment]
I believe you are encountering an iControl REST bug that was resolved in BIG-IP version 15.1.2: https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/related/relnote-supplement-bigip-15-1-2.html#A958281-1

**Comment by mitchellmaler** [comment]
@dstokesf5 Ah that looks like exactly my issue! Ill start the process of upgrading my VEs to 15.1.2.

**Comment by mitchellmaler** [comment]
@dstokesf5 Updating to BIG-IP 15.1.2 Build 0.0.9 Final fixed my issue. Thanks for the quick response.
/close
