### ISSUE TITLE
Bind configurations

### ISSUE THREAD

**Issue by mahdymo** [F5Networks/f5-appsvcs-extension#424]
Environment
Application Services Version: 3.26.0-5
BIG-IP Version: 14.1.2.6

```
"dnsCache": {
   "class": "DNS_Cache",
   "type": "transparent",
   "localZones": {
      "zone_x": {
         "type": "transparent",
         "records": [
```

It only supports A, AAAA records but local bind configurations for PTR, SOA, NS are required, thanks to provide support for the full range of local bind. 

Also, cache resolver with forwarded zones, it exists in DO templates, but not in AS3

**Comment by dstokesf5** [comment]
Please resubmit this issue using one of the available issue templates.
