### ISSUE TITLE
Schema docs for Policy_Action_disable and Policy_Action_Persist_disable are missing

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#426]
### Environment
 * Application Services Version: 3.25
 * BIG-IP Version: 15.1.2

### Summary
Per https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html?highlight=persistencemethods#policy-action-persist

There is no documentation for schema elements `Policy_Action_disable` or `Policy_Action_Persist_disable` also, the actual schema does not seem to contain the values necessary for auto-completion within VS.Code.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "Endpoint_Policy",
    "strategy": "first-match",
    "rules": [
		{
            "name": "appx_rule",
            "conditions": [
                {
                    "type": "httpUri",
                    "pathSegment": {"values": ["appx"]},
                    "index": 1,
                    "event": "request"
                }
            ],
            "actions": [
                {
                    "type": "persist",
                    "disable": {},
                    "event": "request"
                },
                {
                    "type": "forward",
                    "select": {"pool": {"use": "appx_pool"}},
                    "event": "request"
                }
            ]
        }
```

2. Observe the following error response:

### Expected Behavior
Please provide the language construct for the "disable" actions.

**Comment by dstokesf5** [comment]
Confirmed that there is an issue with the schema reference. Added to our internal product backlog as AUTOTOOL-2324.

**Comment by walterk82** [comment]
Support case C3507515 filed for this issue as well.

**Comment by walterk82** [comment]
Buried in https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3.19/declarations/all-properties.html

the syntax is simply  

"disable": {},

**Comment by dstokesf5** [comment]
I believe the schema here is actually incorrect. I believe it was intended to be a boolean value.

**Comment by walterk82** [comment]
Yes, that would make more sense, but at least I can get this deployed and I have confirmation that it addresses our need.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
