### ISSUE TITLE
CloudDocs 'Declaration using All AS3 Properties' page no longer shows the JSON declaration body

### ISSUE THREAD

**Issue by 6a6d** [F5Networks/f5-appsvcs-extension#428]
### Environment
 * Application Services Version: N/A
 * BIG-IP Version: N/A

### Summary
The following AS3 documentation page no longer shows the JSON AS3 declaration for v3.26.0.  
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/all-properties.html

Documentation for AS3 v3.19.1 (LTS) does show this declaration.

**Comment by RobCupples** [comment]
Hi.  We have been tracking this internally with AUTOTOOL-2296.

**Comment by RobCupples** [comment]
This should be fixed now.  If you still see the same declaration you might have to refresh.

**Comment by gaetanquentin** [comment]
hi,

we cannot see previous versions of all "AS3 properties" content page. 

Current version is 3.30, we can see well the page.

But for previous ones, 3.26 for example, content  do not exist anymore. And we need previous versions.

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3.26/declarations/all-properties.html#all-properties


Regards

**Comment by tpitkinf5** [comment]
Hi @gaetanquentin,

thank you for pointing out that the all-properties example was still missing from our 3.26 documentation.
The example should now be available at the link you provided in your most recent comment.
