### ISSUE TITLE
AS3 To Support Creating PTR, NS, SOA records in local bind

### ISSUE THREAD

**Issue by tstanley93** [F5Networks/f5-appsvcs-extension#429]
We have a very large customer with VNF Manager that is deploying our DNS Solution.  However there are some features of DNS that AS3 currently cannot create/modify.

The customer needs to deploy our DNS solution and create PTR, NS, and SOA records in the local bind.  Currently only A and AAAA records types are supported.

**Comment by dstokesf5** [comment]
Please resubmit this issue following one of our issue templates. That will allow us to better track and handle your request.
