### ISSUE TITLE
AS3 To Support creating DNS Logging Profiles

### ISSUE THREAD

**Issue by tstanley93** [F5Networks/f5-appsvcs-extension#430]
### Is your feature request related to a problem? Please describe.
We have a very large customer with VNF Manager that is deploying our DNS Solution.  However there are some features of DNS that AS3 currently cannot create/modify.

### Describe the solution you'd like
Would like AS3 to support creating/modifying DNS Logging profiles like it does for traffic, and security logging profiles.

**Comment by dstokesf5** [comment]
Can you please provide an example of the tmsh configuration you would like to achieve?

**Comment by 21buckets** [comment]
@dstokesf5 Is it possible to have this re-opened? 

An example tmsh command would look like this:

`tmsh create ltm profile dns-logging {{ name }} log-publisher {{ publisher_name }} description "{{ description }} enable-query-logging {{ enable_query_logging }} enable-response-logging {{ enable_response_logging }} include-complete-answer {{ include_complete_answer }} include-query-id {{ include_query_id }} include-timestamp {{ include_timestamp }} include-view {{ include_view }}`

i.e.

`tmsh create ltm profile dns-logging MyLoggingProfile log-publisher local-syslog-publisher description "My First Logging Profile" enable-query-logging yes enable-response-logging yes include-complete-answer yes include-query-id yes include-timestamp yes include-view yes`

As per tmsh, the only mandatory fields should be:
* name,
* log-publisher

Default values for other fields:
* enable-response-logging: no
* enable-query-logging: yes
* include-complete-answer: yes
* include-query-id: no
* include-timestamp: yes
* include-view: yes

![image](https://user-images.githubusercontent.com/39548246/187799432-6c7cf88f-a662-492c-94b1-604db07f71e0.png)

**Comment by 21buckets** [comment]
Hi Team,

Any progress on this issue?

Thanks

**Comment by sunitharonan** [comment]
Please contact us at  automation_toolchain_pm@f5.com so we can prioritize.

**Comment by mdditt2000** [comment]
Jira created AUTOTOOL-3489 and prioritized

**Comment by sunitharonan** [comment]
This has been resolved in the 3.41.0 release of AS3.
