### ISSUE TITLE
AS3 To Support Creating PTR, NS, SOA records in local bind

### ISSUE THREAD

**Issue by tstanley93** [F5Networks/f5-appsvcs-extension#431]
### Is your feature request related to a problem? Please describe.
We have a very large customer with VNF Manager that is deploying our DNS Solution.  However there are some features of DNS that AS3 currently cannot create/modify.

### Describe the solution you'd like
Would like AS3 to support creating these 3 additional record types.

**Comment by dstokesf5** [comment]
Can you please provide an example of the tmsh configuration you would like to achieve?
