### ISSUE TITLE
Unchecked mode example documentation typo

### ISSUE THREAD

**Issue by mjmenger** [F5Networks/f5-appsvcs-extension#433]
In the documentation for the experimental unchecked mode feature, the [given example](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/unchecked-mode.html#example-of-unchecked-mode) has a typo.

The example is 

```https://192.0.2.35/mgmt/shared/appsvcs/declare?unchecked="true"```

which failed when used with BIG-IP 15.1.2.1 and AS3 3.26.0.5

```https://192.0.2.35/mgmt/shared/appsvcs/declare?unchecked=true```

worked as expected

**Comment by dstokesf5** [comment]
Thank you for pointing this out. I have added this to our internal product backlog as AUTOTOOL-2348 and getting it resolved now. The documentation update should go live as part of the next release.

**Comment by dstokesf5** [comment]
This issue was resolved in the 3.27.0 release.
