### ISSUE TITLE
Using the patch (add) method and adding configuration to /common also deletes all other configuration

### ISSUE THREAD

**Issue by nickdebom** [F5Networks/f5-appsvcs-extension#434]
### Environment
 * Application Services Version: 3.26.0
 * BIG-IP Version: BIGIP 14.1.2 

### Summary

Using the patch (add) method and adding configuration to /common also deletes all other configuration from your /Common directory that was not provided, even if it was declared using AS3.

### Steps To Reproduce

case number: **C3516651** you can view the json, not going to provide them here. ( more details there)

Because AS3 manages topology records globally in /Common, it is required that records only be managed through AS3, as it will treat the records declaratively. If a record is added outside of AS3, it will be removed if it is not included in the next AS3 declaration for topology records (AS3 completely overwrites non-AS3 topologies when a declaration is submitted).
We declared everything using AS3, but still notice that if we use the patch method, it does delete everything that is in /common when we try to add configuration in the /common directory. 

While that is not how the patch method is described:
Use PATCH to modify an existing declaration without having to resend the entire declaration. For detailed information on JSON PATCH

Source: AS3 API Reference (f5.com)

### Expected Behavior
That provided configuration gets added to the /common

### Actual Behavior
That it provided configuration gets replaced in the /common

**Comment by dstokesf5** [comment]
This issue was resolved through the F5 support case mentioned above.

The PATCH request was using the add operation with a path that added a duplicate application that overwrote the first one. The solution was to break up the PATCH into multiple operations that did more targeted updates to avoid the duplicate application.
