### ISSUE TITLE
add possibility to use more Pool members inside BIG-IQ AS3 templates.

### ISSUE THREAD

**Issue by jlindr** [F5Networks/f5-appsvcs-extension#441]
Hi,
When creating AS3 templates inside of BIG-IQ there's no option to set more than one specific pool member in the Pool Class.

You can of course add more members when you're deploying an app with this template.
But, when creating a template for an already existing Application Hotel you want to have the servers for that Hotel already defined in the template, and not let the customer be able to change it.

Is this something that could be added?

**Comment by dstokesf5** [comment]
This issue should be filed as a BIG-IQ request for enhancement. Please file a request through F5 support, or contact your sales representative to do so on your behalf.
