### ISSUE TITLE
RFE: Ability to specify / generate CSR / key-pair (FIPS) for Certificate attributes

### ISSUE THREAD

**Issue by Mikej81** [F5Networks/f5-appsvcs-extension#444]
There is currently no simple way to integrate AS3 with customers that require FIPS certificate management.  In #417 I requested the ability to specify storage for importing FIPS key-pairs, but this RFE is more along the lines of allowing the specification of allowing the onboard HSM (if-exist) to generate CSR / key-pair as needed based on attributes submit in the declaration.

This would also be applicable to non-FIPS-based certificate management.

Example Solution:

```json
"webcert": {
          "class": "[CertificateSigningRequest || GenerateCertificateKeyPair]",
          "securitytype": "fips",
          "subjectNames" "virtualserver.domain.com",
          "email": "johnsnow@f5company.com"
          "organization": "f5",
          "unit": "f5",
          "city": "Seattle",
          "state": "WA",
          "country": "US",
          "provider": "rsa",
          "bitlength": "2048"
        }
```

For the US Government's adoption of AS3, we need better options for certificate management.

Considered imperative solution to use bash to create FIPS key and CSR, generate key-pair, then import to client/server SSL profiles. This defeats the purpose of using AS3.

[FIPS Administrator Guide](https://techdocs.f5.com/content/kb/en-us/products/big-ip_ltm/manuals/product/f5-platforms-fips-administration-13-0-0/_jcr_content/pdfAttach/download/file.res/F5_Platforms__FIPS_Administration.pdf)

- this does not account for CSR generation that would need to be passed to a 3rd Party CA, this is just one use-case.

**Comment by dstokesf5** [comment]
Please set up an internal call to discuss use cases and requirements for this feature request.
