### ISSUE TITLE
AS3.26 failed installation on 12.1.x

### ISSUE THREAD

**Issue by delgadillo22** [F5Networks/f5-appsvcs-extension#446]
### Environment
 * Application Services Version: AS3.26 Build 5
 * BIG-IP Version: BIG-IP 12.1.5.2 Build 0.0.10 Point Release 2

### Summary
AS3.26 fails to install on BIG-IP running 12.1.5.2

Error claims MD5 sum mismatch

Same issue seen with AS3.27 (not supported on 12.1.x)

### Steps To Reproduce

Install AS3.26-5 on BIG-IP 12.1.5.2

2. Observe the following error response:

![image](https://user-images.githubusercontent.com/23509342/115584602-c1bf0600-a27f-11eb-94e8-1b28cba75350.png)

### Expected Behavior
AS3.26 should install and run on 12.1.x.

### Actual Behavior
AS3.26 fails to load on 12.1.x

**Comment by dstokesf5** [comment]
Confirmed and added to the internal product backlog as AUTOTOOL-2454. This will require a 3.26.1 release to resolve.
