### ISSUE TITLE
Service Discovery Troubleshooting Enhancements

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-appsvcs-extension#448]
1) Need to better document API reachability requirement for Service Discovery here:

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#requirements-for-using-service-discovery

Service Discovery requires reaching Cloud APIs which by default are on the Internet. As production environments have Internet access restricted, document that API access is required (wether via outbound service (ex. FW, SNAT, etc.) or Native Services like 
AWS: VPC endpoints (https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html)
Azure: Private endpoints (https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#connecting-to-private-endpoints 
etc.
GCP: Private Endpoints
https://cloud.google.com/vpc/docs/private-access-options

Similar to documented here:
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/isolated-env.html

2) Increased and user friendly debug output.  

In troubleshooting deployment where APIs were unreachable but w/ Debug enabled 

```json
  "controls": {
    "class": "Controls",
    "logLevel": "debug"
  },
```
There was very little output when tailing the logs and/or restarting restnoded.  

However, we did find old messages that resembled the problem:

 [f5-service-discovery: getNodes.js] error code: NetworkingError message: connect ECONNREFUSED 52.94.48.63:443

```
# egrep f5-service-discovery /var/log/restnoded/restnoded.log
....
Mon, 26 Apr 2021 20:38:13 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Mon, 26 Apr 2021 20:38:13 GMT - fine: [f5-service-discovery: restWorkerTask.js] Got service discovery task request
Mon, 26 Apr 2021 20:38:13 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Tue, 27 Apr 2021 18:56:06 GMT - severe: [f5-service-discovery: getNodes.js] error code: NetworkingError message: connect ECONNREFUSED 52.94.48.63:443
Tue, 27 Apr 2021 18:56:06 GMT - info: [f5-service-discovery: Task.js] Task ~Common~jvRw3D failed: connect ECONNREFUSED 52.94.48.63:443
Tue, 27 Apr 2021 18:56:06 GMT - fine: [f5-service-discovery: Task.js] Error: connect ECONNREFUSED 52.94.48.63:443
Tue, 27 Apr 2021 20:10:34 GMT - fine: [f5-service-discovery: restWorkerTask.js] Got service discovery task request
Tue, 27 Apr 2021 20:10:34 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Tue, 27 Apr 2021 20:17:31 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-service-discovery/nodejs/restWorkerEncryption.js
Tue, 27 Apr 2021 20:17:31 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-service-discovery/nodejs/restWorkerInfo.js
Tue, 27 Apr 2021 20:17:31 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-service-discovery/nodejs/restWorkerRpc.js
Tue, 27 Apr 2021 20:17:31 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-service-discovery/nodejs/restWorkerTask.js
Tue, 27 Apr 2021 20:17:32 GMT - config: [RestWorker] /shared/service-discovery/encryption has started. Name:RestWorkerEncryption
Tue, 27 Apr 2021 20:17:32 GMT - info: starting /shared/service-discovery/encryption
Tue, 27 Apr 2021 20:17:32 GMT - config: [RestWorker] /shared/service-discovery/info has started. Name:RestWorkerInfo
Tue, 27 Apr 2021 20:17:32 GMT - info: starting /shared/service-discovery/info
Tue, 27 Apr 2021 20:17:32 GMT - config: [RestWorker] /shared/service-discovery/rpc has started. Name:RestWorkerRpc
Tue, 27 Apr 2021 20:17:32 GMT - info: starting /shared/service-discovery/rpc
Tue, 27 Apr 2021 20:17:32 GMT - info: starting /shared/service-discovery/task
Tue, 27 Apr 2021 20:17:33 GMT - config: [RestWorker] /shared/service-discovery/task has started. Name:RestWorkerTask

```
Notice delta between 18:56 (long before troubleshooting session at 20:17. Nothing logging after a restnoded restart or actively erroring on probes.   

In *Debug*, would expect to see some more activity, individual failed requests, empty data structures, etc.  
In *Notice*, a more user friendly error message like: 

"Unable to reach Cloud API, please check your connectivity" 

would be more helpful.

**Comment by dstokesf5** [comment]
If you query the endpoint `mgmt/shared/service-discovery/task` you should be able to see additional information about the running service discovery tasks. This includes a `lastRun` and `lastDiscoveryResult` property that provide additional information about the last attempt service discovery made to find nodes. Is this additional information sufficient for your needs?
