### ISSUE TITLE
Service Discovery - Enforce Pool Member consistency w/ Query Results

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-appsvcs-extension#452]
Currently, if you manually delete a pool member in BIG-IP, Service Discovery not does update the pool to reflect the query results. This is because from Service Discovery's perspective, nothing has changed. Service Discovery apparently caches previous query and only updates the config if there is a change. However, this is unintuitive as many implementations will continually update the pool to match the results on each polling interval. I believe this is even how the BIG-IP's fqdn service discovery behavior is.

Feature Request: 
Service Discovery should have option to enforce consistency

```
enforce: true
```

So that Service Discovery compares query results with current pool members or just updates pool members (replace-all vs. caching) or whatever is most efficient to ensure the BIG-IP pool always reflects current environment (source of truth).

**Comment by dstokesf5** [comment]
Manipulating an application manually and with AS3 is not a recommended use case. Adding additional protections for a use case that we recommend against is not currently in our scope.
