### ISSUE TITLE
Embedding YAML Swagger file from ASM Policy AS3 declaration 

### ISSUE THREAD

**Issue by fpieressa** [F5Networks/f5-appsvcs-extension#454]
### Is your feature request related to a problem? Please describe.
When ASM Policy type POLICY_TEMPLATE_API_SECURITY is configured, no option to embed the Swagger file as part of the AS3 request.

### Describe the solution you'd like
Add "base64" as alternative to the actual "link" option to "open-api-files"

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by dstokesf5** [comment]
Can you please provide some additional context? I cannot find anywhere in AS3 where an `open-api-files` property is being configured. Is this something related to Declarative WAF Policies (https://clouddocs.f5.com/products/waf-declarative-policy/)?

**Comment by fpieressa** [comment]
Hi! We are using the example available on https://devcentral.f5.com/s/articles/Declarative-Advanced-WAF-policy-lifecycle-in-a-CI-CD-pipeline, as you can see it's using the _open-api-files_ property inside the ASM policy, and the _link_ to upload the swagger file.  We want to be able to upload the swagger file embeding it in the AS3 request (probably with the _base64_ property, like we are using to upload the ASM policy).

Thanks!

**Comment by dstokesf5** [comment]
@fpieressa That open-api-files property is part of the Declarative WAF API, which is separate from the AS3 API. AS3 simply passes the JSON payload along to the Declarative WAF API. You will need to file an F5 support ticket to request improvements to the Declarative WAF API.

**Comment by fpieressa** [comment]
Hi! Thanks @dstokesf5 for your help, I will open the support case!
