### ISSUE TITLE
Order of returned tasks changed with 3.26.0

### ISSUE THREAD

**Issue by mstokes-f5** [F5Networks/f5-appsvcs-extension#456]
### Environment
 * Application Services Version: 3.26.0 and 3.27.0
 * BIG-IP Version: 15.1.2.1

### Summary
Prior to AS 3.26.0, tasks from the `/task` endpoint were returned in reverse chronological order based on when they were submitted. This meant the last task submitted was always conveniently at index 0, but this is no longer the case.

It appears that tasks are now always added to the end of the task list, but when AS3 restarts, the task list gets reversed.

### Steps To Reproduce
1. Submit multiple tasks
2. Check the order of tasks returned by `/task` (should be in chronological order)
3. Restart AS3/restnoded
4. Check the order of tasks returned by the `/task` (should be in reverse chronological order)
5. Submit another task
6. Check the order of task returned by the `/task` (should be reverse chronological for old tasks with new ones in chronological order at the bottom)

### Expected Behavior
Tasks returned by the `/task` endpoint should always be in reverse chronological order such that task 0 is the last submitted task. Barring that, the `/task` endpoint should at least remain consistent.

### Actual Behavior
Inlined with repro steps

**Comment by dstokesf5** [comment]
Thank you for reporting this. It has been added to our internal product backlog as AUTOTOOL-2498.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 3.29.0 release.
