### ISSUE TITLE
SSL profile vs TLS object: Terminology alignment between BIG-IP Cfg and AS3 declaration

### ISSUE THREAD

**Issue by lisonlp** [F5Networks/f5-appsvcs-extension#459]
### Environment
 * Application Services Version: 3.26.1
 * BIG-IP Version: 15.1.2.1 

### Summary
When declaring a  **Client** SSL profile, it get applied as a **server**  SSL profile and conversely.
Example taken from [F5 documentation example](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#configuring-additional-tls-options-on-a-virtual)

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "persist": false,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "TLS_Client",
        "TEST_TLS_Client": {
            "class": "Tenant",
            "TLS_App": {
                "class": "Application",
                "test.item-foo": {
                    "class": "TLS_Client",
                    "insertEmptyFragmentsEnabled": true,
                    "singleUseDhEnabled": true,
                    "tls1_3Enabled": false,
                    "tls1_2Enabled": false,
                    "tls1_1Enabled": true,
                    "tls1_0Enabled": false,
                    "cipherGroup": {
                        "bigip": "/Common/f5-aes"
                    },
                    "clientCertificate": "defaultCert"
                },
                "defaultCert": {
                    "class": "Certificate",
                    "certificate": {
                        "bigip": "/Common/default.crt"
                    },
                    "privateKey": {
                        "bigip": "/Common/default.key"
                    }
                }
            }
        }
    }
}
```

2. Observe the profile being created a **server** ssl profile :

ltm profile server-ssl test.item-foo {
    alert-timeout indefinite
    allow-expired-crl disabled
    app-service none
    authenticate once
    authenticate-name none
    c3d-ca-cert none
    c3d-ca-key none
    c3d-cert-extension-includes { basic-constraints extended-key-usage key-usage subject-alternative-name }
    c3d-cert-lifespan 24
    ca-file /Common/ca-bundle.crt
    cache-timeout 3600
    cert /Common/default.crt
    chain none
    cipher-group /Common/f5-aes
    ciphers none
    crl-file none
    description none
    expire-cert-response-control drop
    key /Common/default.key
    options { no-tlsv1.3 no-tlsv1.2 single-dh-use no-tlsv1 }
    peer-cert-mode ignore
    renegotiation enabled
    retain-certificate true
    server-name none
    session-ticket disabled
    ssl-c3d disabled
    ssl-forward-proxy disabled
    ssl-forward-proxy-bypass disabled
    untrusted-cert-response-control drop
}

### Actual Behavior
The AS3 object with Class "TLS-Client" is configured as **Server** SSL profile in BIG_IP. It is VERY CONFUSING
Similarly, an AS3 object with Class "TLS-Server" is configured as **Client** SSL profile in BIG_IP.
in AS3, A TLS CLient refers to "connections leaving ADC"
in BIG-IP, a Client profile is a type of traffic profile that enables BIG-IP to **accept and terminate** any
client requests.

### Expected Behavior
Make the terminology to match between BIG-IP and AS3, please. 
Details like this will help improving the adoption of AS3.

**Comment by dstokesf5** [comment]
Please see the FAQ entry titled "I used a TLS_Server object in my AS3 declaration, why did it create a Client SSL profile on the BIG-IP?": https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html

This is not something we can change without breaking existing deployments.
