### ISSUE TITLE
AS3 support for rate limit on the virtualservice 

### ISSUE THREAD

**Issue by arturbarczewski** [F5Networks/f5-appsvcs-extension#462]
Hello

AS3 support already TCP-Session rate limit on the members in a pool. I ask for the support of the TCP rate-limiter on the VIP.

### Is your feature request related to a problem? Please describe.
We want to protect the F5 and the backend from a flood of requests, in our case SSL-Requests. In our case the F5-CPU went up   to 75%.

### Describe the solution you'd like
The value may have a similar format  like maxConnections.

Regards Artur Barczewski

**Comment by dstokesf5** [comment]
@arturbarczewski, do you have an example of the desired tmsh configuration?

**Comment by arturbarczewski** [comment]
hi please the see the example configuration below:
ltm virtual /example_applications_production/vip_production.example.sctv.ch_8883/service_production.example.sctv.ch_8883 {  │[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # 
    creation-time 2021-03-15:11:28:59                                                                                    │[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # 
    destination /example_applications_production/bgpadvertise_example.sctv.ch:secure-mqtt                       │[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # 
    ip-protocol tcp                                                                                                      │[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # 
    last-modified-time 2021-05-25:13:43:12                                                                               │[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # nc -v   10.63.25.31 8080
    mask 255.255.255.255                                                                                                 │Ncat: Version 6.40 ( http://nmap.org/ncat )
    partition exampleapplications_production                                                                             │Ncat: No route to host.
    pool /example_applications_production/vip_production.example.sctv.ch_8883/pool_mqtt_8883_vernemq_production.example.sctv│[tzhbaar4@tvosmc1-vlbs002:Active:Changes Pending] ~ # 
.ch                                                                                                                      │
    profiles {                                                                                                           │
        /example_applications_production/vip_production.example.sctv.ch_8883/clientssl_ecc_production.example.sctv.ch {     │
            context clientside                                                                                           │
        }                                                                                                                │
        tcp { }                                                                                                          │
    }                                                                                                                    │
    rate-limit 3000     <<<<<<<<<<<

Regards Artur Barczewski

**Comment by dstokesf5** [comment]
@arturbarczewski Thank you, that is exactly what I needed.

**Comment by arturbarczewski** [comment]
Hi Daniel
do you have update?

Regards Artur Barczewski

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2729.

**Comment by arturbarczewski** [comment]
Hello
do you have any information about the release version  when this feature may get implemented?
Kind regards Artur

**Comment by dstokesf5** [comment]
This has been resolved in the 3.33.0 release.
