### ISSUE TITLE
Add the ability to reference additional SIP profile types

### ISSUE THREAD

**Issue by dgarrisonf5** [F5Networks/f5-appsvcs-extension#463]
### Describe the solution you'd like
Currently, AS3 3.28 support the ability to reference an existing SIP profile.  However, there are two additional SIP profile types that aren't reference-able in an AS3 declaration.

Please add the ability to reference "**sip session**" and "**sip router**" profiles in AS3.

### Additional context
Oracle needs this in order to be able to offer BIG-IP as a SIP load balancer option to their customers that are leveraging the Oracle OCCAS SIP gateway that runs on Kubernetes.

Thanks

**Comment by zinkem** [comment]
Fix it yourself.

**Comment by dstokesf5** [comment]
Awaiting on internal feedback.
