### ISSUE TITLE
AS3 declaration fails when Pool members does not include "bigip"

### ISSUE THREAD

**Issue by MitchellMahan** [F5Networks/f5-appsvcs-extension#466]
fatal: [10.240.72.161]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "content": {
                "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
                "action": "deploy",
                "class": "AS3",
                "declaration": {
                    "class": "ADC",
                    "default": {
                        "class": "Tenant",
                        "web": {
                            "class": "Application",
                            "http_mon": {
                                "class": "Monitor",
                                "monitorType": "http",
                                "receive": "I AM UP"
                            },
                            "web": {
                                "class": "Service_HTTP",
                                "pool": "web_pool",
                                "virtualAddresses": [
                                    "10.39.2.1"
                                ],
                                "virtualPort": 80
                            },
                            "web_pool": {
                                "class": "Pool",
                                "members": [
                                    {
                                        "serverAddresses": [
                                            "10.39.2.2",
                                            "10.39.2.3",
                                            "10.39.2.4",
                                            "{'name': 'api', 'vsip': '10.39.3.1', 'vsport': 3000, 'memberport': 3000, 'poolname': 'api_pool', 'members': ['10.39.3.2', '10.39.3.3', '10.39.3.4']}"
                                        ],
                                        "servicePort": 8080
                                    }
                                ],
                                "monitors": [
                                    {
                                        "use": "http_mon"
                                    }
                                ]
                            }
                        }
                    },
                    "id": "id",
                    "label": "WebApp",
                    "schemaVersion": "3.28.0"
                },
                "persist": true
            },
            "state": "present",
            "tenant": null,
            "timeout": 300
        }
    },
    "msg": "{u'message': u'declaration is invalid', u'code': 422L, u'errors': [u\"/default/web/web_pool/members/0: should have required property 'bigip'\"], u'declarationFullId': u''}"
}

**Comment by dstokesf5** [comment]
Please refile this issue following the appropriate issue template.
