### ISSUE TITLE
K8S services with same port but different protocols should not cause an AS3 error

### ISSUE THREAD

**Issue by dgarrisonf5** [F5Networks/f5-appsvcs-extension#467]
### Environment
 * CIS 2.4
 * BIG-IP Version: 14.1
 * AS3 3.28

### Summary
A K8S service with the same port but different protocols exposed causes an AS3 error.  

Example service snippet:

ports:
  - name: sips
    port: 8080
    protocol: **TCP**
    targetPort: 8080
  - name: sip
    port: 8080
    protocol: **UDP**
    targetPort: 8080
  selector:
    app: f5-hello-world-web1

2. Observe the following error response:

2021/06/08 17:37:03 [ERROR] **[AS3] Template is not valid. see errors**
2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared: Must validate "then" as "if" was valid

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared: Must validate "then" as "if" was valid

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0: Must validate "then" as "if" was valid

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0: Must validate one and only one schema (oneOf)

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0.serverAddresses: array items[0,1] must be unique

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0.serverAddresses: array items[2,3] must be unique

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0: Must validate all the schemas (allOf)

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared.members.0: Must validate all the schemas (allOf)

2021/06/08 17:37:03 [ERROR] - declaration.Common.Shared: Must validate all the schemas (allOf)

### Expected Behavior

A K8S service with the same port but different protocols should not cause an AS3 error

**Comment by dstokesf5** [comment]
Can you please provide the AS3 input and output?

**Comment by dgarrisonf5** [comment]
Hi Daniel.  Below is the configmap used.  The only AS3 output are the error messages.

kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-david
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "Common": {
                "class": "Tenant",
                "Shared": {
                    "class": "Application",
                    "template": "shared",
                    "POOL1": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": [],
                                "shareNodes": true
                            }
                        ]
                        }
                      }
                        }
                    }
                }

Thanks

**Comment by dstokesf5** [comment]
I tried applying the AS3 declaration from data section of the configuration, but it was successful. Can you provide the declaration that is actually sent to AS3 that reproduces the issue you are seeing?
