### ISSUE TITLE
Removing AS3 deployment does not remove app folder

### ISSUE THREAD

**Issue by MitchellMahan** [F5Networks/f5-appsvcs-extension#469]
### Environment
 * Application Services Version: 3.28.0
 * BIG-IP Version: 15.1.3

### Summary
When deplying an APP via AS3 and then removing the application the associated folder are not removed from the partition.

Example;
Deploy "/part2/web-api" app via AS3
Remove "/part2/web-api" all via AS3

Delete partition:
tmsh delete auth partition part2
010713f9:3: The folder /part2 cannot be deleted because it contains configuration item (folder /part2/web-api)

### Steps To Reproduce
1. Submit the following declaration:
https://github.com/f5devcentral/f5-ansible-bigip/blob/devel/docs/examples/f5_modules-f5_bigip-comparison/declarations/as3_templ.json

Then remove the deployment and attempt to delete the partition.

2. Observe the following error response:
```bash
tmsh delete auth partition part2
010713f9:3: The folder /part2 cannot be deleted because it contains configuration item (folder /part2/web-api)
```

### Expected Behavior

When removing an application the associated folder should also be removed.

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

When removing an application (via AS3) the application folder remains.

**Comment by dstokesf5** [comment]
I am unable to reproduce this issue, and we have not seen anything like this in our testing. Can you please provide:
1. A sample declaration generated from the provided template.
2. The steps you used to delete the tenant. For example, did you use a DELETE request to the /declare endpoint?
