### ISSUE TITLE
sha256 file check fails

### ISSUE THREAD

**Issue by aknot242** [F5Networks/f5-appsvcs-extension#47]
##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
3.7.0-7
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.0.0.3
  Build       0.0.4
  Edition     Point Release 3
  Date        Mon Oct 22 15:08:29 PDT 2018
```

##### SUMMARY

```
A line feed character (decimal 10, hex 0A) in the .sha256 file causes the sha256sum check to fail.
```

##### STEPS TO REPRODUCE

```
sha256sum -c f5-appsvcs-3.7.0-7.noarch.rpm.sha256
```

##### EXPECTED RESULTS

Deleting the trailing line feed from the .sha256 file produces the correct result:
```
f5-appsvcs-3.7.0-7.noarch.rpm: OK
```
##### ACTUAL RESULTS

```
: No such file or directory-7.noarch.rpm
: FAILED open or readarch.rpm
sha256sum: WARNING: 1 of 1 listed file could not be read
```

**Comment by lephubui** [comment]
Hi @aknot242 , Thanks for reporting, and we have opened an internal issue #791 for it.

**Comment by aknot242** [comment]
Yes, this is probably what happened. I am now unable to reproduce it when I clone the repo and upload to bib-ip and run the command on the big-ip. Working fine. Thanks!
