### ISSUE TITLE
AS3 Authenticate Name TLS_client

### ISSUE THREAD

**Issue by KoviPK** [F5Networks/f5-appsvcs-extension#477]
**Environment**
Application Services Version: 3.28.0

Hello,

Im trying to create **TLS_client** via AS3 and I would like to use **"AuthenticateName"**, but I cant find how to declare it (define it). I tried to look for it on clouddocs f5 AS3, but there is no property for it.

Now Im using RESTAPI for it. Something like this:
curl -sSk -u xxx:xxx -H "Content-Type: application/json" -X POST https://x.x.x.x/mgmt/tm/ltm/profile/server-ssl -d '{"name":"foo","partition":"Common","defaultsFrom":"bar","authenticateName":"foobar"}'

Is there a way I cant find to define "AutheticateName" or is it not in AS3 yet or not posible?

Thank you
Kovi

**Comment by dstokesf5** [comment]
Can you please provide an example of the tmsh configuration you would like to achieve?

**Comment by markchart** [comment]
Just set `"serverName"` in your TLS_Client object.  That corresponds to "authenticatename" in BIG-IP configuration (tmsh) for the serverssl profile.

**Comment by dstokesf5** [comment]
Reopening this issue.

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com in order to prioritize.
