### ISSUE TITLE
Route Domain support for service discovery

### ISSUE THREAD

**Issue by ab-gmbh** [F5Networks/f5-appsvcs-extension#479]
### Is your feature request related to a problem? Please describe.
Currently there is no way to place discovered services into a route domain. We need the route domain to match on the VIP and the discovered backends.

### Describe the solution you'd like
Add 'route domain' as an attribute to Pool_Member

**Comment by codecowboydotio** [comment]
The intention here is that a new attribute be added to service discovery for each cloud provider such that a route domain can be added to the schema for:

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-discovery-aws

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-discovery-azure

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-discovery-gce

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-discovery-consul

Note that this can be achieved with Consul already in the following way:

`                 "members": [
                     {
                       "servicePort": 80,
                       "addressDiscovery": "consul",
                       "updateInterval": 10,
                       "uri": "http://10.200.1.74:8500/v1/catalog/service/web?passing",
                       "jmesPathQuery": "[*].{id:ID||Node,ip:{private:join('',[Address,ServiceMeta.RD]),public:Address},port:ServicePort}",
                       "credentialUpdate": false
                     }
                 ]
             },`

Using the jmes path query in consul allows the query to pull back specific metadata from consul. If we store the route domain in consul, then this can be passed through as "10.1.1.1%10" which is accepted as a node IP address.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this feature request to our internal product backlog as AUTOTOOL-2667.

**Comment by dstokesf5** [comment]
This was resolved with the 3.31.0 release of AS3.
