### ISSUE TITLE
Assign the device name when creating a server

### ISSUE THREAD

**Issue by MMarco1977** [F5Networks/f5-appsvcs-extension#480]
Environment

    Application Services Version: 3.28.0
    BIG-IP Version: 15.1.3-0.0.11

### Summary
From the Bigip, under DNS >> GSLB:Server: ServerList >> Devices: "XXX" it is not possible to assign the name.
Each declaration that is executed assigns a name of 0

Steps To Reproduce
1. Submit the following declaration:
```json
[
  { 
    "op": "add",
    "path": "/Common/Shared/ACME-NICOLA",
    "value": { 
                "class": "GSLB_Server",
                "serverType": "generic-host",
                "monitors": [
                        
                    ],
                "dataCenter": { 
                    "use": "marco"
                },
                "devices":[
                    {
                        "label": "ACME-NICOLA",
                        "address": "1.2.4.8"
                    } 
                ],
                "virtualServers": [
                    {
                        "name": "ACME-NICOLA_VS",
                        "address": "1.2.4.8",
                        "port": 0
                    }
                ]
            }
    },
    { 
    "op": "add",
    "path": "/Gsv/Application/pool_NICOLA",
    "value": { 
                "class": "GSLB_Pool",
                "resourceRecordType": "A", 
                "lbModeFallback": "none",
                "lbModeAlternate": "none",
                "verifyMemberEnabled": false,
                "members": [
                    {
                        "server": {
                            "use": "/Common/Shared/ACME-NICOLA" 
                        },
                        "virtualServer": "ACME-NICOLA_VS",
                        "enabled": true
                    }
                ]
            }
    }
]
```
2. Expected Behavior:
(a Server created without AS3 is shown)
<img width="754" alt="Screenshot 2021-07-15 at 12 32 13" src="https://user-images.githubusercontent.com/85392708/125774353-897419eb-e413-4338-9e40-33657cc14999.png">

3. Observe the following result:
<img width="761" alt="Screenshot 2021-07-15 at 12 31 48" src="https://user-images.githubusercontent.com/85392708/125774496-b321248c-f7e5-4686-9c87-23b0eb65e830.png">

**Comment by dstokesf5** [comment]
The name value comes from the name of the virtual server being referenced. Please see the following documentation on how to override the generated index-based name of a virtual server: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/gslb.html#specifying-a-gslb-virtual-server-name-in-a-declaration.

**Comment by MMarco1977** [comment]
The one indicated in the documentation, refers to how to name the Virtual Server. 
What I need, however, is to name the 'Devices'. The device name should be the same as the Server and not 0

**Comment by dstokesf5** [comment]
@MMarco1977 You are right, it looks like the devices property needs to be updated to accept a name property like virtual servers. I am changing this into a feature request to allow for a GSLB_Server declaration similar to the one below:
```json
{
    "class": "GSLB_Server",
    "serverType": "generic-host",
    "monitors": [],
    "dataCenter": {
        "use": "marco"
    },
    "devices": [
        {
            "name": "ACME-NICOLA",
            "address": "1.2.4.8"
        }
    ],
    "virtualServers": [
        {
            "name": "ACME-NICOLA_VS",
            "address": "1.2.4.8",
            "port": 0
        }
    ]
}
```

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-2636.

**Comment by MMarco1977** [comment]
I tried to send the declaration that you have indicated but the name always remains at 0. Below is the declaration used:

[
  { 
    "op": "add",
    "path": "/Common/Shared/ACME-NICOLA",
    "value": { 
                "class": "GSLB_Server",
                "serverType": "generic-host",
                "monitors": [
                        
                    ],
                "dataCenter": { 
                    "use": "marco"
                },
                "devices":[
                    {
                        "name": "ACME-NICOLA",
                        "address": "1.2.4.8"
                    } 
                ],
                "virtualServers": [
                    {
                        "name": "ACME-NICOLA_VS",
                        "address": "1.2.4.8",
                        "port": 0
                    }
                ]
            }
    },
    { 
    "op": "add",
    "path": "/Gsv/Application/pool_NICOLA",
    "value": { 
                "class": "GSLB_Pool",
                "resourceRecordType": "A", 
                "lbModeFallback": "none",
                "lbModeAlternate": "none",
                "verifyMemberEnabled": false,
                "members": [
                    {
                        "server": {
                            "use": "/Common/Shared/ACME-NICOLA" 
                        },
                        "virtualServer": "ACME-NICOLA_VS",
                        "enabled": true
                    }
                ]
            }
    }
]

tks
/MMarco1977

**Comment by dstokesf5** [comment]
That was meant as an example of how the feature will look when it is implemented.

**Comment by MMarco1977** [comment]
I supposed,but I wanted to try it anyway ;-)

**Comment by MMarco1977** [comment]
Hi @dstokesf5  for info, this issue, do you know when it will be fixed?

**Comment by sunitharonan** [comment]
If you are still looking for this feature, please reach out to us at automation_toolchain_pm@f5.com in order to prioritize.
