### ISSUE TITLE
Add HTML Tag Raise Event support

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#485]
### Describe the solution you'd like
Similar to https://github.com/F5Networks/f5-appsvcs-extension/issues/226#issuecomment-889956361 please add AS3 support for the HTML tag raise configuration object.

### Describe alternatives you've considered
HTML Tag Raise must be created outside of AS3 and attached thru "bigip" declaration semantics.

### Additional context
HTML Tag raise is required so that custom iRules can be developed with the HTML_TAG_RAISED event.

**Comment by walterk82** [comment]
@dstokesf5 Per your request, if this can be bundled with 3.31.  Thanks for the attention.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2678.

**Comment by dstokesf5** [comment]
This was resolved with the 3.31.0 release of AS3.
