### ISSUE TITLE
BOT profile is not attached when DOS profile is created on /Common/Shared

### ISSUE THREAD

**Issue by jeremy-py** [F5Networks/f5-appsvcs-extension#486]
### Environment
 * Application Services Version: v3.29
 * BIG-IP Version: v15.1

### Summary
When DOS profile (which includes the BOT protection) is created inside /Common/Shared, AS3 creates well both profiles (BOT & DOS).
Then, all deployed applications use a pointer to the DOS Profile but only the DOS profile is attached. BOT profile is not attached to the VS.
The expected behavior works when DOS Profile are located inside the same partition/application as the service.

### Steps To Reproduce

First, create a DOS profile inside /Common/Shared.  
AS3 should create DOS & BOT profiles

Then, deploy an application using the local reference:  

```
{
   ...
  "profileDOS": {
            "bigip": "/Common/Shared/DOS_Profile"
   }
   ...
}
```

### Expected Behavior
BOT & DOS profiles should be attached to the VS

### Actual Behavior
Only DOS profile is attached to the VS

**Comment by dstokesf5** [comment]
Does this work as expected if you use a use-pointer instead?
```json
{
   ...
  "profileDOS": {
            "use": "/Common/Shared/DOS_Profile"
   }
   ...
}
```

**Comment by jeremy-py** [comment]
By using "use", it works as expected.  

- Should we conclude that use-pointers are fully supported for external partition, like /Common/Shared ?  
- Second question, can we expect an improvement for "bigip" reference to include the BOT Protection ? As all our existing AS3 declarations use "bigip" reference.   

Thank you.

**Comment by dstokesf5** [comment]
You should use use-pointers anytime you reference configuration managed by AS3. You should only use bigip-pointers to point to items configured outside of AS3.

AS3 does no inspection of items pointed to with a bigip-pointer. This means AS3 will not know that a DOS profile referenced with a bigip-pointer will also require a bot defense profile.

**Comment by jeremy-py** [comment]
Ok thanks a lot for all clarifications.
