### ISSUE TITLE
Add timeout controls for SNAT_Pool class

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-appsvcs-extension#487]
### Describe the solution you'd like
SNAT_Pool class does not support configuring TCP/UDP/IP timeout values.  These then use the BIG-IP default "indefinite".

See https://support.f5.com/csp/article/K7606

> Important: Using an indefinite idle timeout can lead to resource exhaustion if connections are not shut down gracefully. This is especially true for TCP-based communication. In most cases, F5 recommends that you set the idle timeout to a small-as-possible finite value.

### Describe alternatives you've considered
SNAT must be configured outside of AS3

### Additional context
Timeout values need to be configurable so that tmm resource exhaustion does not occur.

**Comment by dstokesf5** [comment]
Can you please provide an example of the tmsh configuration you want?

**Comment by walterk82** [comment]
sorry, I missed that last comment:

modify ltm snat-translation 10.255.100.87 tcp-idle-timeout 
modify ltm snat-translation 10.255.100.87 udp-idle-timeout 
modify ltm snat-translation 10.255.100.87 ip-idle-timeout

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com in order to prioritize.

**Comment by sunitharonan** [comment]
Re-opened as there is an equivalent escalation

**Comment by sunitharonan** [comment]
This is added in AS3 3.42.0 which will be releasing in January. Thanks.

**Comment by sunitharonan** [comment]
This has been resolved in the 3.42.0 release of AS3.
