### ISSUE TITLE
Add  DNS ›› GSLB : Topology : Records for POOL (refer Issue #475) 

### ISSUE THREAD

**Issue by MMarco1977** [F5Networks/f5-appsvcs-extension#488]
Environment

Application Services Version: 3.30.0
BIG-IP Version: 15.1.3-0.0.11

Summary

Topology record per pool it does not work

Steps To Reproduce:

I upgraded to AS3 version 3.30 and downloaded the example.collection.json.
It seems to me that the problem of implementing a Topology record per pool still exists.

this is the JSONPatch I try to implement:
```json
{
    "class": "ADC",
    "schemaVersion": "3.23.0",
    "id": "GSLB_Domain",
    "label": "GSLB Configuration",
    "remark": "A Sample Configuration of GSLB Regions",
    "Common": {
        "class": "Tenant",
        "label": "The main GSLB tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "marco": {
                "class": "GSLB_Topology_Records",
                "records": [
                    {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.216.18/32"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": "pool_MARCO"
                        }
                    }
                ]
            }
        }
    }
}
```
** I try to change the field "matchValue" with path (/Gsv/Application/pool_MARCO) but it does not work.

The error is:
```json
{
    "code": 422,
    "errors": [
        "/Common/Shared/marco/records/0/destination/matchValue: should be object"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

If I try to send a declaration for Topology record per subnet,this work.
```json
{
    "class": "ADC",
    "schemaVersion": "3.23.0",
    "id": "GSLB_Domain",
    "label": "GSLB Configuration",
    "remark": "A Sample Configuration of GSLB Regions",
    "Common": {
        "class": "Tenant",
        "label": "The main GSLB tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "marco": {
                "class": "GSLB_Topology_Records",
                "records": [
                    {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.216.18/32"
                        },
                        "destination": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "1.1.1.0/25"
                        }
                    }
                ]
            }
        }
    }
}
```
That I expect is the one shown in the image

<img width="347" alt="Screenshot 2021-08-10 at 11 31 56" src="https://user-images.githubusercontent.com/85392708/128844764-0e223f3a-cb4e-4760-9401-6d67c751968f.png">

**Comment by dstokesf5** [comment]
If the `matchType` is `pool` then the `matchValue` needs to be an AS3 pointer to a GSLB pool. I think you are looking for something like this:
```json
{
    "class": "ADC",
    "schemaVersion": "3.23.0",
    "id": "GSLB_Domain",
    "label": "GSLB Configuration",
    "remark": "A Sample Configuration of GSLB Regions",
    "Common": {
        "class": "Tenant",
        "label": "The main GSLB tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "marco": {
                "class": "GSLB_Topology_Records",
                "records": [
                    {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.216.18/32"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": {
                                "use": "/Gsv/Application/pool_MARCO"
                            }
                        }
                    }
                ]
            }
        }
    }
}
```

**Comment by MMarco1977** [comment]
In the Issue I indicated that I had also tried to use:
                    
                    "matchValue": {
                                "use": "/Gsv/Application/pool_MARCO"
                            }

But it does not work.

I have tried other solutions too, but without success
Tks
/MMarco1977

**Comment by dstokesf5** [comment]
The following declaration was successful for me. What error are you seeing?
```json
{
    "class": "ADC",
    "schemaVersion": "3.23.0",
    "id": "GSLB_Domain",
    "label": "GSLB Configuration",
    "remark": "A Sample Configuration of GSLB Regions",
    "Common": {
        "class": "Tenant",
        "label": "The main GSLB tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "pool_MARCO": {
                "class": "GSLB_Pool",
                "resourceRecordType": "A"
            },
            "marco": {
                "class": "GSLB_Topology_Records",
                "records": [
                    {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.216.18/32"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": {
                                "use": "/Common/Shared/pool_MARCO"
                            }
                        }
                    }
                ]
            }
        }
    }
}
```

**Comment by dstokesf5** [comment]
In my above example matchValue is an object and it is working. Are you sure you have all pool references changed from basic strings to objects?

**Comment by MMarco1977** [comment]
great! you are right! it works...
I did not notice that you need to reference the pool under the class:

"Shared": {
            "class": "Application",
            "template": "shared",
            "pool_MARCO": {

give me time to run some more tests, then we can close this issue
thank you again
/MMarco1977

**Comment by MMarco1977** [comment]
From the tests I am running, I see that the declaration is successful, but since a POST is performed, it deletes all the rest of the configuration. In my opinion, a PATCH should be performed by specifying the array. 
For example, making a declaration of this type:

[
    { 
    "op": "add"
    "path": 
etc...etc...etc...

correct? I'm working on finding the exact declaration. Do you have any idea how to do it?

**Comment by dstokesf5** [comment]
@MMarco1977, I am not sure what you are asking for. However, I can confirm that you can submit an array of operations with an AS3 PATCH request.

**Comment by MMarco1977** [comment]
@dstokesf5 What I mean, is that in normal condition, where for the DNS GSLB there are Server, pool, virtual server, WideIP, DataCenter ... when a POST is performed with the declaration indicated by you, the topology record is correctly implemented per pool, but the rest of the configuration is cleared.
I think instead of making a declaration in POST, a declaration in PATCH should be used.
I'm working on it, and as soon as I find the correct syntax I'll share it with you. If in the meantime, you find it, share it
;-)

**Comment by MMarco1977** [comment]
Hi Guys,
I continued testing with the declaration you posted to me. The declaration works correctly, but I have noticed some things that are not correct.
If on F5 there is a complete configuration about GSLB-DNS, such as WideIP, DataCenter, Pools, Server ... when the declaration is sent, this will correctly configure the Topology for records with pool, but overwrite all the rest of the configuration.

I think this is due to the fact that in the declaration, under Common / Shared it is said to create the pool_Marco and then to use it in the destination of the GSLB_Topology_Records:

"Common": {
        "class": "Tenant",
        "label": "The main GSLB tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "pool_MARCO": {
                "class": "GSLB_Pool",
                "resourceRecordType": "A"
            },

**N.B. The same result also occurs if you change partitions, such as Marco / Application

By executing a PATCH instead, using the declaration indicated below, the existing configuration is not deleted, and the record in the topology is correctly configured:

[
  { 
    "op": "add",
    "path": "/Common/Shared/topology",
    "value": { 
                "class": "GSLB_Topology_Records",
                
                    "records": [
                            {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.217.0/24"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": {
                                "use": "pool_MARCO"
                            }   
                            },
                            "weight": 5
                            }
                        ]       
                }
        }
]

However, I noticed that by always executing a PATCH of the same declaration, and varying both the source and the destination, this overwrites all the other records.

And trying to send a PATCH with the declaration indicated below, only the last one remains configured, it is as if the other records are overwritten by the last one:

[
  { 
    "op": "add",
    "path": "/Common/Shared/topology",
    "value": { 
                "class": "GSLB_Topology_Records",
                
                    "records": [
                            {
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.217.0/24"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": {
                                "use": "pool_MARCO"
                            }   
                            },
                            "weight": 5
                            }
                    ]
            }
    },
    {
    "op": "add",
    "path": "/Common/Shared/topology",
    "value": { 
                "class": "GSLB_Topology_Records",
                    "records": [
                            {                        
                        "source": {
                            "matchType": "subnet",
                            "matchOperator": "equals",
                            "matchValue": "10.103.218.0/24"
                        },
                        "destination": {
                            "matchType": "pool",
                            "matchOperator": "equals",
                            "matchValue": {
                                "use": "pool_GIANM"
                            }   
                            },
                            "weight": 4
                            }
                        ]       
                }
        }
]


Any ideas or clarifications are welcome
See you

**Comment by MMarco1977** [comment]
Oh yes, this was the idea ... but I didn't get there! :-( 
I got the path wrong and obviously ... it didn't work! You're great!
and thanks again for your help ...

**Comment by MMarco1977** [comment]
Since what is indicated in the issue has been resolved, I close the issue.
If I find other anomalies, I will proceed with the opening of a new issue
Thanks again

**Comment by MMarco1977** [comment]
Since what is indicated in the issue has been resolved, I close the issue.
If I find other anomalies, I will proceed with the opening of a new issue
Thanks again
