### ISSUE TITLE
add skipCertificateCheck on monitorType external

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-appsvcs-extension#491]
### Is your feature request related to a problem? Please describe.
Feature Request:
In the context of an AS3 external monitor definition, when using an untrusted HTTPS based  link to a repo , the deployment will fail because is unable to fetch the content 

### Describe the solution you'd like
add the skipCertificateCheck parameter similar to what has been done for iRule.

### Describe alternatives you've considered
NONE

**Comment by dstokesf5** [comment]
It may not be well demonstrated in the examples, but skipCertificateCheck is already supported for external monitors:
```json
{
    "class": "ADC",
    "schemaVersion": "3.6.0",
    "tenant": {
        "class": "Tenant",
        "application": {
            "class": "Application",
            "mNewExternalMonitorFile": {
                "class": "Monitor",
                "monitorType": "external",
                "interval": 5,
                "upInterval": 0,
                "timeUntilUp": 0,
                "timeout": 16,
                "expand": false,
                "script": {
                    "url": {
                        "url": "https://192.0.2.0:8000/monitor.sh",
                        "skipCertificateCheck": true
                    }
                },
                "environmentVariables": {
                    "USER": "example"
                }
            }
        }
    }
}
```

Is this sufficient for your use case?

**Comment by tizianorosato-gr** [comment]
Thanks @dstokesf5 , while comparing with your example I've just found that the issue was the missing >> "expand": false<<
