### ISSUE TITLE
PEM certificate URL reference

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-appsvcs-extension#492]
### Is your feature request related to a problem? Please describe.
P12 certificates with keys can use url reference in declaration. PEM certificate cannot be referenced with URL.
CA bundle encoding format is PEM only, so customers with CA bundle must include it in AS3 declaration.

### Describe the solution you'd like
add url reference support in "certificate" field for Certificate Class.
This feature must support ignoreChanges field as well to prevent file download for every declaration POST.

**Comment by dstokesf5** [comment]
AS3 already supports specifying a URL for the certificate property of the Certificate class. However, there appears to be a bug with it. I have filed #506 to track that bug. I am closing out this feature request.
