### ISSUE TITLE
Service_HTTP drops profileL4

### ISSUE THREAD

**Issue by frslater** [F5Networks/f5-appsvcs-extension#494]
### Environment
 * Application Services Version: 3.23.0
 * BIG-IP Version: any

### Summary
Specifying "profileL4" inside a service of class "Service_HTTP" is accepted without error, but the profile is not attached.  There are 2 problems: (1) AS3 should throw an error, and (2) online documentation (clouddocs) should be corrected, because an example of profileL4 with Service_HTTP is shown as valid.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "ADC",
    "schemaVersion": "3.23.0",
    "id": "TEST_L4_Profile",
    "remark": "Test L4 profiles",
    "L4_Tenant": {
        "class": "Tenant",
        "L4_App": {
            "class": "Application",
            "service": {
                "class": "Service_HTTP",
                "virtualPort": 80,
                "virtualAddresses": ["1.2.3.4"],
                "profileL4": {
                    "use": "l4Profile"
                }
            },
            "l4Profile": {
                "class": "L4_Profile",
                "clientTimeout": 60,
                "idleTimeout": 600,
                "keepAliveInterval": 600,
                "looseClose": true,
                "looseInitialization": true,
                "maxSegmentSize": 4096,
                "resetOnTimeout": false,
                "tcpCloseTimeout": 43200,
                "tcpHandshakeTimeout": 43200
            }
        }
    }
}
```

2. Observe the following response:
```json
    "results": [
        {
            "code": 200,
            "message": "success",
            "lineCount": 23,
            "host": "localhost",
            "tenant": "L4_Tenant",
            "runTime": 2007
        }
    ]
```

### Expected Behavior
If profileL4 is allowed, then it should be attached to the virtual, but it should probably no be allowed.  Assuming it is not allowed, then AS3 should return a validation error.

### Actual Behavior
No error is thrown, but the profile is not attached.
```
ltm virtual /L4_Tenant/L4_App/service {
    creation-time 2021-08-17:07:36:32
    description L4_App
    destination /L4_Tenant/1.2.3.4:80
    ip-protocol tcp
    last-modified-time 2021-08-17:07:36:32
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    profiles {
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
```

**Comment by frslater** [comment]
This bug was originally reported by Aleksandra Zahajkiewicz.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have confirmed that a virtual server cannot have a tcp and an l4 profile. The example is being updated and I have added AUTOTOOL-2693 to our internal product backlog to address the lack of validation failure.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com in order to prioritize.
