### ISSUE TITLE
Error "can't get object count from mcpd" related to nodes

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-appsvcs-extension#495]
### Environment
 * Application Services Version:
```{"version":"3.30.0","release":"5","schemaCurrent":"3.30.0","schemaMinimum":"3.0.0"}```
```
{
  "burstHandlingEnabled": false,
  "asyncTaskStorage": "memory",
  "serviceDiscoveryEnabled": true
}
```
 * BIG-IP Version: 15.1.2.1

### Summary
Occasionally declarations fail on the BIG-IP with following error:
```
warning: [appsvcs] {"message":"unable to digest declaration. Error: GET http://admin:XXXXXX@localhost:8100/mgmt/tm/ltm/node?options=recursive query target BIG-IP current ltm node list response=400 body={\"code\":400,\"message\":\"can't get object count from mcpd\",\"errorStack\":[],\"apiError\":26214401}","level":"warning"}
```

I can't manually reproduce the error, it happens only rarely and I have no idea what could be the problem.
Declarations in our environment are coming in basically a constant stream from an Openstack orchestrator.

I did manage to recover from the condition by:
- saving config
- loading config with `tmsh load sys config`

We do not persist config to disk with AS3, it is done once a day through another method.
Devices are in HA and config is synchronized automatically via the Big-IP device group "auto-sync" setting, not from AS3.

Looking at existing and past reported issues, this may in some way be related to #238 and/or #152 I guess but I can't see a clear correlation. Can you please help me understand the cause of this failure?

**Comment by dstokesf5** [comment]
It looks like a GET request to the `mgmt/tm/ltm/node?options=recursive` iControl REST endpoint responded with a 400 status code and the "can't get object count from mcpd" message. I suspect there is some kind of problem with iControl REST or mcpd in this case. Please file a ticket with F5 support to determine why iControl REST is unable to communicate with mcpd.

I am not sure if it will help, but you can also try increasing the restjavad memory: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/best-practices.html#increase-the-restjavad-memory-allocation
