### ISSUE TITLE
Service Discovery for Openstack

### ISSUE THREAD

**Issue by jfreeland** [F5Networks/f5-appsvcs-extension#497]
### Is your feature request related to a problem? Please describe.

Yes and no.  There are 'workarounds' but not a native solution.

AS3 offers (from https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html):
Service_Discovery_AWS
Service_Discovery_Azure
Service_Discovery_Consul
Service_Discovery_GCE

I need and want:

Service_Discovery_Openstack
or
Service_Discovery_Nova

I don't want to use a third party system (Consul or DNS) for service discovery.  I want to use my 'cloud' provider's metadata services to discover my pool members.

### Describe the solution you'd like
Service_Discovery_Openstack
see for instance
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#openstack_sd_config
https://github.com/prometheus/prometheus/tree/main/discovery/openstack

### Describe alternatives you've considered
Consul or FQDN with an A record to each member.

**Comment by dstokesf5** [comment]
If you can query an HTTP endpoint that returns a JSON response for Openstack or Nova, you may be able to use the already available Consul service discovery. The AS3 Consul service discovery allows you to specify an arbitrary endpoint with the `uri` property and how to parse the results of that endpoint with the `jmesPathQuery` property.

Here is an example using both of those properties: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#using-service-discovery-with-the-consul-health-api

Additional information on JMESPath can be found here: https://jmespath.org/

Are you able to use this existing functionality to handle your use case?

**Comment by jfreeland** [comment]
> If you can query an HTTP endpoint that returns a JSON response for Openstack or Nova, you may be able to use the already available Consul service discovery. The AS3 Consul service discovery allows you to specify an arbitrary endpoint with the `uri` property and how to parse the results of that endpoint with the `jmesPathQuery` property.
> 
> Here is an example using both of those properties: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#using-service-discovery-with-the-consul-health-api
> 
> Additional information on JMESPath can be found here: https://jmespath.org/

I started playing with this the other day but other items have come up that have taken precedence.  That said, if the F5 development team doesn't have access to an Openstack environment (https://microstack.run/ ?) to test against, I don't know that this is going to work out well.

> Are you able to use this existing functionality to handle your use case?

I'd really rather not add a third system into the mix if I don't have to.  Openstack is a valid 'cloud provider', like Azure, AWS, and GCP.

**Comment by dstokesf5** [comment]
While this solution uses AS3's Consul service discovery, it does not actually require the use of Consul. The Consul service discovery feature has grown and become more flexible to the point that it is now capable of handling discovery from arbitrary JSON endpoints.

**Comment by delgadillo22** [comment]
Hello, adding Service Discovery for OpenStack is out of scope for AS3 as our resources, environments, and priorities are focused on AWS, Azure, and GCP. Use of AS3's Consul SD as a generic SD approach as discussed is likely to be the best option here.
