### ISSUE TITLE
Support for AFM SSH Proxy missing

### ISSUE THREAD

**Issue by ak-cw** [F5Networks/f5-appsvcs-extension#50]
##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION
3.7

##### BIGIP VERSION
13.1

##### SUMMARY
I'm working on a customers's project for SSH Proxy automation. Regarding SSH Proxy the schema contains no declaration for SSH Proxy Profile and assignment to Virtual (just Proxy Logging Profile is available).

Currently we have to use the Ansible bigip_command module to work around but we like to use a full declaration using AS3.

Please include SSH Proxy in the next version.

**Comment by dstokesf5** [comment]
Thank you for your feedback. We have opened an issue internally and are reviewing the feature request.

**Comment by kaustriaf5** [comment]
This is being tracked internally as 824.

**Comment by focrensh** [comment]
Added into AS3.10

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pointer-ssh-proxy-profile
