### ISSUE TITLE
GET request that includes HTTPS monitor adds space to receive attribute

### ISSUE THREAD

**Issue by kenfng** [F5Networks/f5-appsvcs-extension#503]
### Environment
 * Application Services Version: 3.30
 * BIG-IP Version: 15.1.3 build 0.0.11

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "schemaVersion": "3.30.0",
    "class": "ADC",
    "Tenant": {
        "class": "Tenant",
        "Application": {
             "HTTPS_MON": {
                "class": "Monitor",
                "monitorType": "https",
                "send": "GET /",
                "receive": "200 OK"
            }
        }
    }
}
```
Submitting the request works, and configuration is instantiated properly, with no errors.

### Expected Behavior
Doing a subsequent GET for the Tenant's declaration has a receive attribute that has no spaces in its name:
curl -ku admin https://f5bigip/mgmt/shared/appsvcs/declare/Tenant > decl.json
jq '.Tenant.Application.HTTPS_MON.receive' < decl.json

Should output:
"200 OK"

### Actual Behavior
Doing a subsequent GET on retrieves an invalid (AS3) declaration, since the receive attribute has a space in it:

curl -ku admin https://f5bigip/mgmt/shared/appsvcs/declare/Tenant > decl.json
jq '.Tenant.Application.HTTPS_MON."receive "' < decl.json

outputs:
"200 OK"

jq '.Tenant.Application.HTTPS_MON.receive' < decl.json

outputs:
null

**Comment by dstokesf5** [comment]
I was unable to reproduce this issue. Are you experiencing it on any other systems?

**Comment by kenfng** [comment]
I can't reproduce this either.  It looks like my LTM -> AS3 migration script was inserting spaces in the attribute names (receive) though, and these weren't causing an error when POST/PATCH'd via AS3.  That's what I was seeing in the GET's.

Please close, and sorry for the trouble.
-Ken.
