### ISSUE TITLE
error in 3.26.1: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by davebarry123** [F5Networks/f5-appsvcs-extension#509]
### Environment
 * Application Services Version: 3.26.1, Build 1
 * BIG-IP Version:
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.2.1
  Build       0.0.10
  Edition     Point Release 1
  Date        Fri Jan 15 13:43:15 PST 2021

### Summary
When submitting a declaration it fails in 3.26.1 with the error
 Cannot read property 'forEach' of undefined in tenant Common:
This looks like a repeat of issue #52 

### Steps To Reproduce
1. Submit the following declaration:
[3.26.1-forEach-error.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/7171898/3.26.1-forEach-error.txt)

### Expected Behavior
no error

### Actual Behavior
error

            {
                "message":"Cannot read property 'forEach' of undefined",
                "host":"localhost",
                "tenant":"Common",
                "code":422
            }

**Comment by dstokesf5** [comment]
I am unable to submit the provided declaration due to conflicting virtual servers:
```json
        {
            "code": 422,
            "message": "declaration failed",
            "response": "01070333:3: Virtual Server /Common/Shared/forwarder-0-ext-1101-tcp-ipv4 illegally shares destination address, source address, service port, ip-protocol, and vlan with Virtual Server /Common/Shared/forwarder-0-ext-1101s-tcp-ipv4.",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 6442
        },
```

Can you simplify the steps to reproduce this issue?

**Comment by davebarry123** [comment]
Looks like it works now after I removed the duplicate virtual servers
