### ISSUE TITLE
[RFE] - add support for executing tmsh on the BIG-IP, like Ansible's bigip_command

### ISSUE THREAD

**Issue by joelkeener** [F5Networks/f5-appsvcs-extension#510]
### Is your feature request related to a problem? Please describe.
Some settings and values are not yet available in AS3, but are in tmsh.

### Describe the solution you'd like
I would like to build that tmsh dynamically from user input and send it to the BIG-IP in my AS3 declaration, to be executed afterwards.

### Describe alternatives you've considered
For now there is no alternative. We just don't reference the setting.

### Additional context
In our case, AS3 does provide a way of updating the setting of interest (encoding on an ASM policy via text: json string assigned to the policy attribute on a WAF_Policy) but we suspect an ASM preventing this from working as encoding is always set to the default of utf-8 on the new asm policy. 

Here are a couple old Known Issues that I believe are related, though both were marked FUNCTIONS AS DESIGNED:
    http://go/ID707555/
    http://go/ID413009/

Here are the AS3 declarations that are not working when used with the following tmsh command after saving to /var/tmp/wafPolicy.json:
    Without modifications set in the policy text's json string --
```
{
  "class": "ADC",
  "schemaVersion": "3.0.0",
  "id": "urn:uuid:a858e55e-bbe6-42ce-a9b9-0f4ab33e3bf7",
  "a": {
    "class": "Tenant",
    "b": {
      "class": "Application",
      "template": "generic",
      "c_waf_policy": {
        "class": "WAF_Policy",
        "policy": {
          "text": "{ \"policy\": { \"encoding\": \"gbk\", \"template\": { \"name\": \"POLICY_TEMPLATE_RAPID_DEPLOYMENT\" } } }"
        },
        "ignoreChanges": true
      }
    }
  }
} 
```

    With modifications set in the policy text's json string --
```
{
  "class": "ADC",
  "schemaVersion": "3.0.0",
  "id": "urn:uuid:a858e55e-bbe6-42ce-a9b9-0f4ab33e3bf7",
  "a": {
    "class": "Tenant",
    "b": {
      "class": "Application",
      "template": "generic",
      "c_waf_policy": {
        "class": "WAF_Policy",
        "policy": {
          "text": "{ \"policy\": { \"encoding\": \"gbk\", \"template\": { \"name\": \"POLICY_TEMPLATE_RAPID_DEPLOYMENT\" }, \"modifications\": [ { \"encoding\": \"gbk\" } ] } }"
        },
        "ignoreChanges": true
      }
    }
  }
} 
```

Here is the tmsh that creates it [in /Common]:
    `tmsh load asm policy c_WAF_policy file /var/tmp/wafPolicy.json overwrite`

**Comment by dstokesf5** [comment]
Thank you for your feedback. However, allowing arbitrary tmsh could pose a security risk. For now will continue to expose settings as customers need them.
