### ISSUE TITLE
Invalid default setting for request/response chunking (sustain) on HTTP_Profile in v15.0+

### ISSUE THREAD

**Issue by joelkeener** [F5Networks/f5-appsvcs-extension#512]
### Is your feature request related to a problem? Please describe.
15.0 has a new default value for the HTTP_Profile's requestChunking and responseChunking values: sustain. If you use either the older preserve or selective or values in your declaration, it will convert that to sustain if run on v15.0+ but if you use sustain as the value it will fail with this error:
    {"code":422,"errors":["/tenant/app/vs_http/requestChunking: should be equal to one of the allowed values [\"selective\",\"preserve\",\"rechunk\"]"],"declarationFullId":"","message":"declaration is invalid"}

### Describe the solution you'd like
Will this work if you just add sustain as an option, and change it to the default value if run on <15.0?

### Describe alternatives you've considered
The alternative is to not specify the default value, so that the resulting setting is sustain.

### Additional context
The ACC sets the requestChunking and responseChunking values - even when they are default - so converting a v15.0+ config with an HTTP_Profile that has the default value for either key, will result in an invalid declaration.

**Comment by dstokesf5** [comment]
Based on your description, it sounds safe enough to remap `preserve` and `selective` to `sustain` on 15.0+. Do you have a suggestion on what to map `sustain` to for versions before 15.0?

**Comment by joelkeener** [comment]
Hello Daniel, sorry for not responding sooner. I suggest that you map the Request Chunking's sustain option to preserve, and the Response Chunking's sustain option to selective on pre-v15.0 versions of BIG-IP, since those are the default values, as is documented here:
    K40243113: Overview of the HTTP profile
    https://support.f5.com/csp/article/K40243113

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com in order to prioritize.
