### ISSUE TITLE
Allow base64 encoding of certificates and private keys

### ISSUE THREAD

**Issue by harmonjeff** [F5Networks/f5-appsvcs-extension#520]
It can be a little tricky to reformat the PKCS12 files (certificates and private keys) into a single line for use in AS3 JSON files. It would be much better to allow for both artifcats to be base 64 encoded and put into the JSON like can be done with device certificates in DO.

**Comment by NicodemeB** [comment]
Using Schema version 3.32.0 and f5-appsvcs-3.32.0-4.noarch, it looks like the base64 should be supported (at least for a CA_Bundle object), considering it is supposed to accept a F5string Object (https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json):

```json
"CA_Bundle": {
      "title": "CA_Bundle",
      "description": "Bundle of one or more PKI Certificate-Authority certificates",
      "type": "object",
      "properties": {
        "class": {
          "title": "Class",
          "type": "string",
          "const": "CA_Bundle"
        },
        "label": {
          "$ref": "#/definitions/Label"
        },
        "remark": {
          "$ref": "#/definitions/Remark"
        },
        "bundle": {
          "description": "Reference to a CA bundle or string of PEM encoded certificates",
          "allOf": [
            {
              "$ref": "#/definitions/F5string"
            }
          ],
          "f5fetch": "pki-cert",
          "f5bigComponent": "query sys file ssl-cert"
        }
      },
      "additionalProperties": false,
      "required": [
        "class",
        "bundle"
      ]
    },
```

```json
"F5base64": {
      "type": "string",
      "description": "Slightly over-matches both base64-orig and base64-url data",
      "pattern": "^([0-9A-Za-z/+_-]*|[0-9A-Za-z/+_-]+={1,2})$"
    },
    "F5string": {
      "title": "String value",
      "description": "String value optionally in base64 or from URL or AS3 pointer",
      "if": {
        "not": {
          "type": "object"
        }
      },
      "then": {
        "type": "string"
      },
      "else": {
        "$comment": "May add 'cryptogram' in future.",
        "properties": {
          "base64": {
            "title": "Base64",
            "description": "Base64-encoded value (in JSON string)",
            "type": "string",
            "allOf": [
              {
                "$ref": "#/definitions/F5base64"
              }
            ]
          },
          "text": {
            "title": "Text",
            "description": "UTF-8 text (in JSON string)",
            "type": "string"
          },
          "url": {
            "$ref": "#/definitions/Resource_URL"
          },
          "copyFrom": {
            "title": "Copy from",
            "description": "AS3 pointer to declaration object/property from which to copy value",
            "type": "string",
            "format": "f5pointer"
          },
          "bigip": {
            "title": "BIG-IP component pathname",
            "description": "Pathname of existing BIG-IP component",
            "type": "string",
            "format": "f5bigip"
          }
        },
        "additionalProperties": false,
        "minProperties": 1,
        "maxProperties": 1
      }
    },
```

However, I'm facing the same issue. I tried formatting the certificate into a single line with `\n` before or after PEM headers or without particular formatting, just encoding the certificate as_is in base64, but the result is the same in the logs: 
`Wed, 10 Nov 2021 16:39:28 GMT - severe: [appsvcs] {"message":"Declaration failed: 01070712:3: unable to validate certificate, invalid x509 file (<CA_Bundle_name>).","level":"error"}`

I'm not sure if it is due to a schema error, or just a bug?

**Comment by lisonlp** [comment]
Hi F5 Support

Facing the same issue here.
[The JSON schema supports [BASE64 encoded certificates](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/Certificate.schema.json.html) and [certificate bundles](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/CA_Bundle.schema.json.html).
however the BIG-IP API throws an error when using such format.


Kr,

**Comment by jmcalalang** [comment]
This still seems broken @dstokesf5. Even the master example of all still only has the pks version.

**Comment by dstokesf5** [comment]
This issue was not being tracked well since it did not follow one of the provided issue templates. I have created a new issue (#580) to address the fact that the schema allows this, but the BIG-IP configuration is invalid.

**Comment by jmcalalang** [comment]
awesome thanks, Daniel! so i will go back and say that the x509 isn't doable right now, but the pk12 format (bundled) should be
