### ISSUE TITLE
Adding lsn-legacy-mode & Destination Address/Port properties in Security_Log_Profile_Nat

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-appsvcs-extension#533]
### Is your feature request related to a problem? Please describe.
ISP customer Orange, would like the possibility to configure the lsn-legacy-mode & Destination Address/Port properties in Security_Log_Profile_Nat 

### Describe the solution you'd like
It can be configured either with GUI or tmsh as shown below:
security log profile logfirewallall {
    dos-network-publisher MyPublisher
    nat {                            
        end-inbound-session enabled  
        end-outbound-session {       
            action enabled           
            **elements { destination }** 
        }                            
        **lsn-legacy-mode enabled**      
    }  
}

### Additional context
tmsh modify security log profile logfirewallall nat { lsn-legacy-mode enabled }
tmsh modify security log profile logfirewallall nat { end-outbound-session { elements add { destination }}}

**Comment by sunitharonan** [comment]
This has been resolved with AUTOTOOL-3490 in As3 3.43.0. Thanks
