### ISSUE TITLE
Add proxy request as an event to more LTM policy items

### ISSUE THREAD

**Issue by grovesgroves** [F5Networks/f5-appsvcs-extension#539]
### Is your feature request related to a problem? Please describe.
When creating configuration via tmsh commands Vs. AS3, we have noticed that there an inconsistencies with the same configuration depending on the deployment method.

### Describe the solution you'd like
We need:
* Policy_Condition_HTTP_URI to work from an 'http proxy request' event - currently only 'request' is in the schema
* Policy_Action_Drop to work from an 'http proxy request' event - currently only 'request' is in the schema
* Policy_Action_TCL to support 'http proxy request' event

### Describe alternatives you've considered
n/a

### Additional context
 n/a

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as AUTOTOOL-2940.

**Comment by dstokesf5** [comment]
This is resolved in the 3.34.0 release that is now available.
