### ISSUE TITLE
422: Tenant Shared Partition not being created

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-appsvcs-extension#548]
### Environment
 * Application Services Version: 3.33.0
 * BIG-IP Version: 15.1.2

### Summary

Getting an intermittent error, about 1/5 times where AS3 declaration is not posting:

{"code":422,"message":"declaration failed","response":"01020036:3: The requested ASM policy (/Tenant_1/Shared/Custom_WAF_Policy) was not found.","host":"localhost","tenant":"Tenant_1","runTime":2426}],"declaration":{"class":"ADC","schemaVersion":"3.0.0","label":"Failover","remark":"Failover","id":"autogen_9b6828df-ea3e-4dff-aa33-111252caadbf","updateMode":"selective","controls":{"archiveTimestamp":"2022-01-14T21:35:20.779Z"}},"code":422

When the AS3 declaration should be actually be creating that partition for Tenant_1. When looking afterwards, can see partition has not been created and indeed missing:

admin@(failover01)(cfg-sync In Sync)(Active)(/)(tmos)# cd 
Folders:
  Common/       LOCAL_ONLY/   

### Steps To Reproduce

1. Submit the following declaration:
```json
{
  "class":"ADC",
  "schemaVersion":"3.0.0",
  "label":"Failover",
  "remark":"Failover",
  "Tenant_1":{
    "class":"Tenant",
    "Shared":{
      "class":"Application",
      "template":"shared",
      "Service_01_Pool":{
        "class":"Pool",
        "remark":"Service 1 shared pool",
        "members":[
          {
            "servicePort":80,
            "addressDiscovery":"aws",
            "region":"us-east-2",
            "updateInterval":60,
            "tagKey":"aws:cloudformation:logical-id",
            "tagValue":"AppInstance",
            "addressRealm":"private"
          }
        ],
        "monitors":[
          "http"
        ]
      },
      "Custom_HTTP_Profile":{
        "class":"HTTP_Profile",
        "xForwardedFor":true
      },
      "Custom_WAF_Policy":{
        "class":"WAF_Policy",
        "url":"https://XXXXXX.s3.amazonaws.com/Rapid_Deployment_Policy_13_1.xml",
        "enforcementMode":"blocking",
        "ignoreChanges":false
      },
      "Service_Address_01_A":{
        "class":"Service_Address",
        "virtualAddress":"10.0.10.101",
        "trafficGroup":"none"
      },
      "Service_Address_01_B":{
        "class":"Service_Address",
        "virtualAddress":"10.0.20.101",
        "trafficGroup":"none"
      }
    },
    "HTTP_Service_01_A":{
      "class":"Application",
      "template":"http",
      "serviceMain":{
        "class":"Service_HTTP",
        "virtualAddresses":[
          {
            "use":"/Tenant_1/Shared/Service_Address_01_A"
          }
        ],
        "snat":"auto",
        "pool":"/Tenant_1/Shared/Service_01_Pool",
        "profileHTTP":{
          "use":"/Tenant_1/Shared/Custom_HTTP_Profile"
        },
        "policyWAF":{
          "use":"/Tenant_1/Shared/Custom_WAF_Policy"
        }
      }
    },
    "HTTP_Service_01_B":{
      "class":"Application",
      "template":"http",
      "serviceMain":{
        "class":"Service_HTTP",
        "virtualAddresses":[
          {
            "use":"/Tenant_1/Shared/Service_Address_01_B"
          }
        ],
        "snat":"auto",
        "pool":"/Tenant_1/Shared/Service_01_Pool",
        "profileHTTP":{
          "use":"/Tenant_1/Shared/Custom_HTTP_Profile"
        },
        "policyWAF":{
          "use":"/Tenant_1/Shared/Custom_WAF_Policy"
        }
      }
    },
    "HTTPS_Service_01_A":{
      "class":"Application",
      "template":"https",
      "serviceMain":{
        "class":"Service_HTTPS",
        "virtualAddresses":[
          {
            "use":"/Tenant_1/Shared/Service_Address_01_A"
          }
        ],
        "snat":"auto",
        "pool":"/Tenant_1/Shared/Service_01_Pool",
        "serverTLS":{
          "bigip":"/Common/clientssl"
        },
        "redirect80":false,
        "profileHTTP":{
          "use":"/Tenant_1/Shared/Custom_HTTP_Profile"
        },
        "policyWAF":{
          "use":"/Tenant_1/Shared/Custom_WAF_Policy"
        }
      }
    },
    "HTTPS_Service_01_B":{
      "class":"Application",
      "template":"https",
      "serviceMain":{
        "class":"Service_HTTPS",
        "virtualAddresses":[
          {
            "use":"/Tenant_1/Shared/Service_Address_01_B"
          }
        ],
        "snat":"auto",
        "pool":"/Tenant_1/Shared/Service_01_Pool",
        "serverTLS":{
          "bigip":"/Common/clientssl"
        },
        "redirect80":false,
        "profileHTTP":{
          "use":"/Tenant_1/Shared/Custom_HTTP_Profile"
        },
        "policyWAF":{
          "use":"/Tenant_1/Shared/Custom_WAF_Policy"
        }
      }
    }
  }
}
```
On a device with an existing LOCAL_ONLY partition. 

2. Observe the following error response:
3. 
```json
{
  "code":422,
  "message":"declaration failed",
  "response":"01020036:3: The requested ASM policy (/Tenant_1/Shared/Custom_WAF_Policy) was not found.",
  "host":"localhost",
  "tenant":"Tenant_1",
  "runTime":2426
}
```

### Expected Behavior

The declaration should create the partition and policy as declared (per other successful times)

### Actual Behavior

The declaration only fails intermittently (about 1/5 times) so config appears generally valid. However, just for transparency, there are a couple of variables that might be unique to this deployment and possibly contributing:

1) This is an AWS instance w/ DO declaration which creates a default route in a LOCAL_ONLY partition with localOnly
```json

    "default":{
      "class":"Route",
      "gw":"10.0.10.1",
      "network":"default",
      "mtu":1500,
      "localOnly":true
    },

```

2) The devices are clustered/sync'd

Other Notes: 
  - As config is usually successful, tried a restart of restnoded/restjavad and repost in case was related to bad state but got same result.
  - Github Issues found with similar errors:
  - https://github.com/F5Networks/f5-appsvcs-extension/issues/340
  - https://github.com/F5Networks/f5-appsvcs-extension/issues/443

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this issue to our internal product backlog as AUTOTOOL-2968.

**Comment by mikeshimkus** [comment]
@dstokesf5 I'm experiencing similar sync issues but with the datagroup from this issue: https://github.com/F5Networks/f5-appsvcs-extension/issues/406

It looks like device 1 creates /Common/appsvcs/____appsvcs_lock, which then gets synced over to device 2 while it is in the middle of an AS3 declaration.  AS3 completes on device 1 and ____appsvcs_lock is deleted; that change is synced to device 2 before AS3 is finished. When AS3 tries to delete ____appsvcs_lock on device 2, it's already been removed and we see the error:

2022-01-26T20:42:32.559Z [9017]: error: {"code":500,"declarationFullId":"autogen_57c6e6bc-13d6-4269-904b-f49e3ce6f6be|Failover","message":"DELETE http://admin:XXXXXX@localhost:8100/mgmt/tm/ltm/data-group/internal/~Common~appsvcs~____appsvcs_lock Attempting to release global lock response=404 body=

{\"code\":404,\"message\":\"01020036:3: The requested value list (/Common/appsvcs/____appsvcs_lock) was not found.\",\"errorStack\":[],\"apiError\":3}
"}

(working on getting the full audit logs)

It looks like AS3 will only create ____appsvcs_lock if it doesn't already exist; would like to request that AS3 check that it exists before deleting as well. Let me know if I should create a new issue for this, reopen https://github.com/F5Networks/f5-appsvcs-extension/issues/406, or use this issue https://github.com/F5Networks/f5-appsvcs-extension/issues/548.

**Comment by sunitharonan** [comment]
Closing this issue as PD thinks it is not relevant anymore
