### ISSUE TITLE
cannot attach clone pool to virtual server

### ISSUE THREAD

**Issue by pmawan** [F5Networks/f5-appsvcs-extension#549]
when i try to attach a clone pool to a virtual server - i get the following 
where as the pool exists
 
egress/use: contains path to non-existent object ite1-clonePool"],"declarationFullId":"","message":"declaration is invalid"}

my clone pool definition 
"clonePools": {
                        "egress": {
                            "use": "/Common/Shared/ite1-clonePool"
                        }
                    },

**Comment by dstokesf5** [comment]
Please resubmit this issue and follow one of the provided templates. This will allow us to provide better feedback and assistance.

**Comment by pmawan** [comment]
how do i use a template - can you please guide me - thanks
