### ISSUE TITLE
Endpoint_Policy with asm setting could not bound to a Virtual Server.

### ISSUE THREAD

**Issue by jikui** [F5Networks/f5-appsvcs-extension#55]
##### Do you already have an issue opened with F5 support?
No. This is for internal development.

##### ISSUE TYPE

Bug Report

##### AS3 BUILD/ VERSION

```
3.7.0
```

##### BIGIP VERSION

```
13.1.1.4
```

##### SUMMARY
```
The Endpoint_policy could not be bound to Virtual Server if the Endpoint_policy contains WAF settings.

This should be related to the parition/path of the Endpoint_Policy created at bigip is not correct.
```

##### STEPS TO REPRODUCE

```
{
    "class": "AS3",
    "action": "deploy",
    "targetHost": "10.128.0.149",
    "targetUsername": "admin",
    "targetPassphrase": "admin",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.7.0",
        "id": "Service_HTTP",
        "Sample_container": {
            "class": "Tenant",
            "A1": {
                "class": "Application",
                "template": "generic",
                "testItem": {
                    "class": "Service_HTTP",
                    "pool": "web_pool",
                    "policyEndpoint": "endpointPolicy",
                    "virtualAddresses": ["10.0.1.10"]
                },

                "web_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [{
                        "servicePort": 80,
                        "serverAddresses": [
                            "192.0.1.10",
                            "192.0.1.11"
                        ]
                    }]
                },
                "endpointPolicy": {
                    "class": "Endpoint_Policy",
                    "rules": [
                        {
                            "name": "enableWAF",
                            "conditions": [{
                                "type": "httpUri",
                                "path": {
                                    "values": ["example.com"]
                                }
                            }
                            ],
                            "actions": [{
                                "type": "waf",
                                "policy": {
                                    "use": "wafPolicy"
                                }
                            }
                            ]
                        },
                       {
                            "name": "disable",
                            "conditions": [],
                            "actions": [{
                                "type": "waf",
                                "policy": {
                                	"use": "wafPolicy"
                                }
                            }
                            ]
                        }
                    ]
                },
                "wafPolicy": {
                    "class": "WAF_Policy",
                    "url": "http://10.145.106.100/asm-policy/asm-policy-linux-high.xml"
                }
            }
        }
    }
}
```

##### EXPECTED RESULTS

```
The above jason syntax file could be executed correctly.
```

##### ACTUAL RESULTS

```
We noticed that the Endpoint_policy endpointPolicy in above syntax file is created at /Sample_container/ instead of /Sample_container/A1/. At the same time, in the error logs, it complains that there is no endpointPolicy in /Sample_container/A1. 
Not sure if this is the root cause or not.

```

**Comment by kaustriaf5** [comment]
@jikui Looks like you're trying to disable WAF using 3.7 version. We have this supported in 3.8, have you tried that? https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.8.0
I know you're running on a container, which we have a known issue for, but this decl works for me on 3.8 (pointed to a diff waf policy file)

**Comment by jikui** [comment]
> @jikui Looks like you're trying to disable WAF using 3.7 version. We have this supported in 3.8, have you tried that? https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.8.0
> I know you're running on a container, which we have a known issue for, but this decl works for me on 3.8 (pointed to a diff waf policy file)

kaustria,

Thanks for your help. Actually, what we are trying to do is to define some ASM policies for some certain kinds of traffics in an Endpoint_Policy and then bind this Endpoint_Policy into a virtual server.


Thanks.

Jikui

**Comment by jikui** [comment]
> > @jikui Looks like you're trying to disable WAF using 3.7 version. We have this supported in 3.8, have you tried that? https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.8.0
> > I know you're running on a container, which we have a known issue for, but this decl works for me on 3.8 (pointed to a diff waf policy file)
> 
> kaustria,
> 
> Thanks for your help. Actually, what we are trying to do is to define some ASM policies for some certain kinds of traffics in an Endpoint_Policy and then bind this Endpoint_Policy into a virtual server.
> 
> Thanks.
> 
> Jikui

We verified that AS3 3.8.0 works for this. We think we could close this issue now. And we are also waiting for the AS3 3.8.0 container version available.

Thanks.

Jikui
