### ISSUE TITLE
SSL profile: add advanced settings

### ISSUE THREAD

**Issue by emmanuelcormier** [F5Networks/f5-appsvcs-extension#551]
### Is your feature request related to a problem? Please describe.
When creating a TLS profile in AS3 declaration, some advanced settings are not available, such as 0-RTT and Dynamic Record sizing.

### Describe the solution you'd like
Add advanced SSL parameters in TLS object class (ie TLS_server / TLS_client):

- 0-RTT: https://support.f5.com/csp/article/K54135010
- 'Allow Dynamic Record sizing': https://techdocs.f5.com/en-us/bigip-15-1-0/big-ip-system-ssl-administration/additional-ssl-profile-configuration-options.html#GUID-F80A18B3-1C88-465F-946B-9942D95399AE

### Describe alternatives you've considered
None.

### Additional context
N/A

**Comment by leondelyon3** [comment]
Hi,
same for the renegotiation part:
**renegotiate-max-record-delay
renegotiate-period
renegotiate-size
secure-renegotiation**
The only one that is taken in account is renegotiationEnabled.
The request is coming for ISP Orange.

**Comment by mdditt2000** [comment]
Created Jira AUTOTOOL-3488 and prioritized

**Comment by sunitharonan** [comment]
This has been resolved in the 3.41.0 release of AS3.
