### ISSUE TITLE
Update  Firewall_Address_List | The requested IP address list (/Common/Shared/mySharedAddressList) already exists in partition Common

### ISSUE THREAD

**Issue by bwearp** [F5Networks/f5-appsvcs-extension#557]
### Environment
 * Application Services Version: 3.34.0
 * BIG-IP Version: 16.1.0

### Summary
Trying to update/edit Firewall_address_List

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.34.0",
        "id": "container",
        "label": "SharedAddressList",
        "remark": "This is a shared address list",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "mySharedAddressList": {
                    "addresses": [
                        "1.1.1.1",
                        "2.2.2.2",
                        "3.3.3.3"
                    ],
                    "remark": "This is a description",
                    "class": "Firewall_Address_List"
                }
            }
        }
    }
}
```

2. Observe the following error response:
```json
{
    "id": "aa8fcc00-1693-454f-b340-806d7c562c56",
    "results": [
        {
            "code": 422,
            "message": "declaration failed",
            "response": "01020066:3: The requested IP address list (/Common/Shared/mySharedAddressList) already exists in partition Common.",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 1879
        },
        {
            "code": 422,
            "message": "declaration failed",
            "response": "01020066:3: The requested IP address list (/Common/Shared/mySharedAddressList) already exists in partition Common.",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 1789
        }
    ],
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.34.0",
        "id": "container",
        "label": "SharedAddressList",
        "remark": "This is a shared address list",
        "controls": {
            "class": "Controls",
            "userAgent": "vscode-f5/3.5.0",
            "archiveTimestamp": "2022-02-03T13:02:39.059Z"
        },
        "updateMode": "selective"
    }
}
```

### Expected Behavior
Declarative update should alter address list

### Actual Behavior
Error as above

**Comment by dstokesf5** [comment]
I posted the provided declaration multiple times, and all attempts were successful. Can you provide any additional information to reproduce this issue?

Trace information may help us narrow in on steps to reproduce this issue: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#using-traceresponse-to-enable-traces-in-as3-responses

**Comment by bwearp** [comment]
Hi - thanks for your help.

4 of us so far get the same result - what AS3 version are you using?

Please find trace below:

{
    "id": "2d2f1cad-c40a-4baa-b0fc-85baccb7e8be",
    "results": [
        {
            "code": 422,
            "message": "declaration failed",
            "response": "01020066:3: The requested IP address list (/Common/Shared/mySharedAddressList) already exists in partition Common.",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 1832
        },
        {
            "code": 422,
            "message": "declaration failed",
            "response": "01020066:3: The requested IP address list (/Common/Shared/mySharedAddressList) already exists in partition Common.",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 1834
        }
    ],
    "declaration": {
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
        "class": "ADC",
        "schemaVersion": "3.34.0",
        "id": "traceResponse",
        "controls": {
            "class": "Controls",
            "userAgent": "vscode-f5/3.5.0",
            "archiveTimestamp": "2022-02-08T05:25:11.890Z"
        },
        "updateMode": "selective"
    },
    "traces": {
        "CommonDesired": {
            "/Common/Shared/": {
                "command": "sys folder",
                "properties": {},
                "ignore": []
            },
            "/Common/Shared/mySharedAddressList": {
                "command": "security firewall address-list",
                "properties": {
                    "description": "\"This is a description\"",
                    "addresses": {
                        "1.1.1.1": {},
                        "2.2.2.2": {},
                        "3.3.3.3": {},
                        "4.4.4.4": {},
                        "50.50.50.50": {}
                    },
                    "fqdns": {},
                    "geo": {},
                    "address-lists": {}
                },
                "ignore": []
            }
        },
        "CommonCurrent": {
            "/Common/Shared/": {
                "command": "sys folder",
                "properties": {},
                "ignore": []
            }
        },
        "CommonDiff": [
            {
                "kind": "N",
                "path": [
                    "/Common/Shared/mySharedAddressList"
                ],
                "rhs": {
                    "command": "security firewall address-list",
                    "properties": {
                        "description": "\"This is a description\"",
                        "addresses": {
                            "1.1.1.1": {},
                            "2.2.2.2": {},
                            "3.3.3.3": {},
                            "4.4.4.4": {},
                            "50.50.50.50": {}
                        },
                        "fqdns": {},
                        "geo": {},
                        "address-lists": {}
                    },
                    "ignore": []
                },
                "tags": [
                    "tmsh"
                ],
                "command": "security firewall address-list",
                "lhsCommand": "",
                "rhsCommand": "security firewall address-list"
            }
        ],
        "CommonScript": "cli script __appsvcs_update {\nproc script::run {} {\nif {[catch {\ntmsh::modify ltm data-group internal __appsvcs_update records none\n} err]} {\ntmsh::create ltm data-group internal __appsvcs_update type string records none\n}\nif { [catch {\ntmsh::begin_transaction\ntmsh::create security firewall address-list /Common/Shared/mySharedAddressList description \\\"This is a description\\\" addresses replace-all-with \\{ 1.1.1.1 2.2.2.2 3.3.3.3 4.4.4.4 50.50.50.50 \\} fqdns none geo none address-lists none\ntmsh::modify auth partition Common description \\\"Updated by AS3 at [clock format [clock seconds] -gmt true -format {%a, %d %b %Y %T %Z}]\\\"\ntmsh::commit_transaction\n} err] } {\ncatch { tmsh::cancel_transaction } e\nregsub -all {\"} $err {\\\"} err\ntmsh::modify ltm data-group internal __appsvcs_update records add \\{ error \\{ data \\\"$err\\\" \\} \\}\n}}\n}"
    }
}

**Comment by dstokesf5** [comment]
This is strange. For some reason AS3 is unable to see existing firewall address list. Can you provide the tmsh output of the address-list?

If AS3 is somehow out of sync with BIG-IP, I suspect deleting the address-list and allowing AS3 to recreate it by resubmitting the request will work around this issue.

**Comment by dstokesf5** [comment]
We have discovered that this can happen when AFM is not provisioned. The Firewall_Address_List class currently relies on the AFM module being provisioned.
