### ISSUE TITLE
URL hosted iRules not updating

### ISSUE THREAD

**Issue by rafkruczkowski** [F5Networks/f5-appsvcs-extension#56]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.7.0-7.noarch
```

##### BIGIP VERSION

```
13.1.1
```

##### SUMMARY

```
When hosting a iRule on a URL, it looks like AS3 does not check if it is updated when reposting the deceleration.
```

##### STEPS TO REPRODUCE

```
I have this snip in my deceleration and on first post it works fine, but if I edit the file on Github then AS3 does not check the file again for updates:
"githosted": {
                "class": "iRule",
                "iRule": {
                    "url": "https://raw.githubusercontent.com/rafkruczkowski/irules/master/hosted_irule2.tcl"
                },
                "expand": true
            }
```

##### EXPECTED RESULTS

```
Would like a option or default that AS3 pulls hosted content and recompiled them into the config.
```

##### ACTUAL RESULTS

```
URL hosted content not updated.
```

**Comment by rafkruczkowski** [comment]
Hi @kaustriaf5 ,
Yes, that is what I'm experiencing.  The workaround would be to also update the filename, but that would be an extra step and I don't think it should be needed if there was just a flag to redownload and compile the iRule.

**Comment by kaustriaf5** [comment]
Thanks @rafkruczkowski we are tracking this internally as 874

**Comment by markchart** [comment]
I'm pretty sure the AS3 declaration parser will actually fetch the iRule from the server when the declaration is re-posted, so this is probably due to some kind of optimization error, failure to diff the iRule on the big-ip with the one imported into the declaration

**Comment by thomsonjames** [comment]
I'm running into this issue as well.  I get this response

{
    "results": [
        {
            "code": 200,
            "message": "no change",
            "host": "localhost",
            "tenant": "testrule",
            "runTime": 306


When, indeed the iRule on github has changed.
I don't view this a an enhancement, I view this as a bug because whatever it's doing, it's not realizing there's a change

To repro, you can use this basic declaration

https://github.com/thomsonjames/AttAzureBastion/tree/master/InProgress

post, then change the iRule in github, then post the same declaration without changing anything.  It may work the first time, but keep changing the port in the iRulke over and over again and you'll see "no change" in your response.

**Comment by thomsonjames** [comment]
I did some more testing. There is some timing aspect to this.  When I update the iRule the first couple times, it may take the change, then for another few minutes ,it will not update the iRule, then 5 minutes later, it will update the iRule.

I can't tell if it is timing from the last post or an absolute time.
