### ISSUE TITLE
WAF policy option is no longer available on FAST HTTP template

### ISSUE THREAD

**Issue by chungyu2** [F5Networks/f5-appsvcs-extension#560]
### Environment
 * Application Services Version: 3.34
 * BIG-IP Version: 15.1.2

### Summary

In the HTTP FAST template - I no longer see the option to deploy a WAF policy or pick the security logging option.  I recently removed some WAF iapps - I am not sure if the 2 are linked.

### Expected Behavior

when using the http fast template - i want to be able to pick WAF deployment and to pick the security logging profile

### Actual Behavior

The 2 options are no longer available to me know - I suspect it was because I removed the iapp WAF pluggins

**Comment by dstokesf5** [comment]
This looks like a ticket for the FAST project, which can be found here: https://github.com/F5Networks/f5-appsvcs-templates
