### ISSUE TITLE
Add support for "ltm monitor inband"

### ISSUE THREAD

**Issue by sschadwick** [F5Networks/f5-appsvcs-extension#562]
### Is your feature request related to a problem? Please describe.
AS3 should be able to create/edit/delete `ltm monitor inband` objects as part of AS3's `Monitor` class.

### Describe the solution you'd like
Add `monitorType: 'inband'` support to the existing `Monitor` class.

### Additional context
This is a request from the Journeys team.

**Comment by mdditt2000** [comment]
Added Jira AUTOTOOL-3448 for PM tracking

**Comment by sunitharonan** [comment]
This has been resolved in the 3.40.0 release of AS3.
