### ISSUE TITLE
GSLB Topology Record is lost after re-deploying a modified AS3 declaration

### ISSUE THREAD

**Issue by nobiac0922** [F5Networks/f5-appsvcs-extension#567]
### Environment
 * Application Services Version: 3.30.0 build 5
 * BIG-IP Version: 15.1.3.1

### Summary
1.  From initial state with an empty declaration, POSTing a valid attached declaration common_gslb.json.txt succeeds.
2. POSTing a valid attached declaration dns.json.txt succeeds. I can see the topology records deployed in BIG-IP
3. Modified dns.json like adding a new GSLB pool or wideIP, etc. POST the modified AS3 declaration dns.json.txt. It was successful and I can see the added gslb pool or wideip. However, GSLB topology records are lost from the BIG-IP configuration.
 
### Steps To Reproduce
1. From initial state without any previous declaration in Common, submit AS3 declaration common_gslb.json.txt.
2. Submit AS3 declaration dns.json.txt which contains GSLB pool, wideip and topology records.
3. Modify dns.json.txt like adding a new gslb pool or modifying the weight of existing topology record and submit the modified AS3 declaration dns.json.txt.
4. Observe topology record configuration previously deployed in Step 2.

### Expected Behavior
Topology records should remain in the BIG-IP configuration after step 3.

### Actual Behavior
It seems the topology records were erased. There are no more topology records in the configuration.

[common_gslb.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8127431/common_gslb.json.txt)
[dns.json.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8127432/dns.json.txt)

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this issue to our internal product backlog as AUTOTOOL-3034.

**Comment by dstokesf5** [comment]
This was resolved in the 3.36.0 release of AS3.
