### ISSUE TITLE
Adding log-profile & log-publisher properties in FTP_Profile

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-appsvcs-extension#570]
### Is your feature request related to a problem? Please describe.
ISP customer Orange, would like the possibility to configure the Log Settings parameters for FTP profile

### Describe the solution you'd like
It can be configured either with GUI or tmsh as shown below:
ltm profile ftp Orange_FTP {           
    allow-active-mode enabled          
    app-service none                   
    defaults-from ftp                  
    enforce-tls-session-reuse disabled 
    ftps-mode allow                    
    inherit-parent-profile disabled    
    **log-profile alg_log_profile        
    log-publisher MyPublisher**          
    port ftp-data                      
    translate-extended enabled         
}

### Describe alternatives you've considered
For the time being tmsh is used
(tmos)# create ltm profile ftp Orange_ALG_FTP log-publisher logFW log-profile alg_log_profile

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.

**Comment by sunitharonan** [comment]
This has been resolved with AUTOTOOL-3493 backlog item in As3 3.43.0. Thanks.
