### ISSUE TITLE
GSLB_Data_Center and GSLB_Server objects deleted by subsequent AS3 declarations

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-appsvcs-extension#571]
### Environment
 * Application Services Version: 3.34.0
 * BIG-IP Version: 16.1

### Summary
AS3 declaration that creates GSLB_Data_Center and GSLB_Server objects in /Common/Shared is deleting datacenters and servers that were created by an earlier AS3 declaration. Easily reproducible. Customer of @sahuddy initially reported.

### Steps To Reproduce
1. POST the declaration as3-declaration1.txt and notice that GSLB_Data_Center and GSLB_Server objects are created.
2. POST (or PATCH) the declaration as3-declaration2.txt.
3. Observe that objects from step 1 are now deleted, and objects from step 2 are created.
4. Optional, POST (or PATCH) as3-declaration1.txt again, and watch this overwrite behavior happen in reverse.

### Expected Behavior
I would expect 2 declarations that create objects in /Common/Shared not to overwrite eachother.

This customer has 2 teams that both want to deploy GSLB_Data_Center and GSLB_Server objects independently of eachother.

### Actual Behavior
* It appears that GSLB_Data_Center and GSLB_Server objects are deleted and overwritten by subsequent declarations, despite being declared in /Common/Shared.
* If a GSLB_Data_Center or GSLB_Server object was created by DO (not AS3) it appears unaffected by subsequent AS3 declarations.

[as3-declaration1.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8179360/as3-declaration1.txt)
[as3-declaration2.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8179361/as3-declaration2.txt)

**Comment by dstokesf5** [comment]
This is working as expected. You are asking AS3 to make the BIG-IP state match the second declaration, which excludes the GSLB objects from the first declaration.

You may be able to use PATCH operations to accommodate a multi-user workflow on the same tenant: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.htm#using-patch-to-add-a-new-application-to-a-tenant

**Comment by jmcalalang** [comment]
similar to here: https://github.com/F5Networks/f5-appsvcs-extension/issues/587

**Comment by mikeoleary** [comment]
@jmcalalang thanks for referencing this issue and @dstokesf5 thanks for explaining this for us. We haven't been successful in PATCHing /Common/Shared so for now we will live with the situation where a GSLB_Server objects created by an AS3 declaration must be known by subsequent AS3 declarations that create new GSLB_Server objects.

**Comment by dstokesf5** [comment]
@mikeoleary Have you created an issue for the PATCH issues you are seeing?

**Comment by mikeoleary** [comment]
@dstokesf5 no I have not. I've just checked with the SE @sahuddy and from my notes, what we were struggling with was how to PATCH the /Common/Shared application, since we need to add an additional GSLB_Server object to it. But at this point we're okay with the understanding that the GSLB_Server objects and DC's need to be coordinated between teams. We're happy to close the issue if you like.

**Comment by dstokesf5** [comment]
Thank you for your feedback. Closing.
