### ISSUE TITLE
Support RTSP profile

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-appsvcs-extension#575]
### Is your feature request related to a problem? Please describe.
ISP customer Orange, would like the possibility to configure profile RTSP

### Describe the solution you'd like
It can be configured either with GUI or tmsh as shown below:
ltm profile rtsp rtsp {
    app-service none
    check-source enabled
    defaults-from none
    description none
    idle-timeout 300
    log-profile none
    log-publisher none
    max-header-size 4096
    max-queued-data 32768
    multicast-redirect disabled
    partition Common
    proxy none
    proxy-header none
    real-http-persistence enabled
    rtcp-port any
    rtp-port any
    session-reconnect disabled
    unicast-redirect disabled
}

### Describe alternatives you've considered
For the time being tmsh is used
(tmos)# create ltm profile rtsp...

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.

**Comment by mdditt2000** [comment]
Jira AUTOTOOL-3492

**Comment by sunitharonan** [comment]
This has been resolved in As3 3.43.0. Thanks.
