### ISSUE TITLE
Support TFTP profile

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-appsvcs-extension#576]
### Is your feature request related to a problem? Please describe.
ISP customer Orange, would like the possibility to configure profile TFTP

### Describe the solution you'd like
It can be configured either with GUI or tmsh as shown below:
ltm profile tftp tftp {
    app-service none
    defaults-from none
    description none
    idle-timeout 30
    log-profile none
    log-publisher none
    partition Common
}

### Describe alternatives you've considered
For the time being tmsh is used
(tmos)# create ltm profile tftp ...

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.

**Comment by sunitharonan** [comment]
This has been resolved with AUTOTOOL-3494 backlog item in As3 3.43.0. Thanks.
