### ISSUE TITLE
Trying to deploy multiple VS in Common Partition but it's overwriting the config. Please advise

### ISSUE THREAD

**Issue by jainvijay1** [F5Networks/f5-appsvcs-extension#583]
This is my code . Please advise
{
    "class" : "AS3",
    "action" : "deploy",
    "persist" : true,
    "declaration" : {
            "class": "ADC",
            "schemaVersion": "3.34.0",
            "id": "test-alf-1",
            "label": "test_alf01",
            "remark": "Test_config",
            "Common": {
                "class": "Tenant",
                "Shared": {
                    "class": "Application",
                    "template": "shared",
                    "test-alf-01.xyz.com_http": {
                        "layer4": "tcp",
                        "pool": {"bigip":"/Common/test_pool"},
                        "iRules": [
                                {"bigip": "/Common/_sys_https_redirect"}
                        ],
                        "translateServerAddress": true,
                        "translateServerPort": true,
                        "remark": "test-alf-02.xyx.com",
                        "class": "Service_HTTP",
                        "profileHTTP": {
                            "bigip": "/Common/http"
                        },
                        "profileTCP": {
                            "bigip": "/Common/tcp"
                        },
                        "virtualAddresses": [
                            "10.218.10.0/23"
                        ],
                        "virtualPort": 4065,
                        "snat": "auto",
                        "allowVlans": [
                            {
                                "bigip": "/Common/External"
                            }
                        ]
                    },
                    "test-alf-01.xyz.com_https": {
                        "layer4": "tcp",
                        "pool": {"bigip":"/Common/test_pool"},
                        "iRules": [
                            {"bigip": "/Common/_sys_https_redirect"}
                    ],
                        "translateServerAddress": true,
                        "translateServerPort": true,
                        "remark": "test-alf-02.xyz.com",
                        "class": "Service_HTTPS",
                        "serverTLS": {"bigip":"/Common/WILDCARD-SSL-CLIENT-PROFILE"},
                        "profileHTTP": {
                            "bigip": "/Common/http"
                        },
                        "profileTCP": {
                            "bigip": "/Common/tcp"
                        },
                        "redirect80": false,
                        "virtualAddresses": [
                            "10.218.10.0/23"
                        ],
                        "virtualPort": 4066,
                        "snat": "auto",
                        "allowVlans": [
                            {
                                "bigip": "/Common/External"
                            }
                        ]
                    }
            }
        }
}
}

**Comment by dstokesf5** [comment]
AS3 is declarative. That means when you supply a second declaration for the Common tenant AS3 will replace the current configuration of the Common tenant. If you want to add a second virtual server to Common, you can update your configuration to contain to virtual servers or you can use a PATCH request to add a second virtual server to your declaration.
