### ISSUE TITLE
partition delete fails when there are monitor test results

### ISSUE THREAD

**Issue by thepowercoders** [F5Networks/f5-appsvcs-extension#585]
### Environment
 * Application Services Version: 3.35.0
 * BIG-IP Version: 16.1.2.1

### Summary
When a partition is attempted to be deleted, it returns a 202 Accepted with the task id. However, when the task status is checked with a GET to the /mgmt/shared/appsvcs/task endpoint, the replies states that the declaration has failed with the following:

`{
	"id": "00372ee2-d82e-4bc4-ac64-5a14cfe2a64d",
	"results": [
		{
			"code": 422,
			"message": "declaration failed",
			"response": "010713f9:3: The folder /ecospoc/dev cannot be deleted because it contains configuration item (monitor test results /ecospoc/dev/openshift_http31769 1)",
			"host": "localhost",
			"tenant": "ecospoc",
			"runTime": 25200
		}
	]`

The objects created in the declaration appear to have been all removed, but the partition is still present. It is assumed that the 'monitor test results' relate to a test ran against one of the defined health monitors in the 
Local Traffic  ››  Monitors  section. However, the pool and the monitor which were created have been successfully removed.

I am guessing that after the monitor was built, I may have ran a test via the GUI and this created a log file which is now stuck.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this issue to our internal product backlog as AUTOTOOL-3107.

**Comment by mdditt2000** [comment]
@antonywm I have added this issue to the next sprint. Please can you reach out to automation_toolchain_pm@f5.com so i can add a customer name to the Jira task.

**Comment by thepowercoders** [comment]
I think this has been fixed - certainly when I delete partitions now in latest AS3 (3.44.0) it does not cause this error.
