### ISSUE TITLE
Unable to delete tenants that contains a WAF policy.

### ISSUE THREAD

**Issue by devildog-tech** [F5Networks/f5-appsvcs-extension#589]
### Environment
Application Services Version: 3.35.0
BIG-IP Version: 16.1.2.1

### Summary
When deleting a tenant, if there is a WAF policy associated to the tenant it will fail delete.

### Steps To Reproduce

1. Post a declaration that contains a WAF policy. Doesn't need to be associated to a virtual or anything just its creation to the tenant is enough to cause the issue.

```
"test_asm_policy": {
    "class": "WAF_Policy",
    "ignoreChanges": true,
    "url": {
        "url": "https://removed/api/v4/projects/1048/repository/files/files%2Ftemplate_waf_policy.xml/raw?ref=main",
        "authentication": {
            "method": "bearer-token",
            "token": "removed"
        }
    }
}
```

2. Try and delete the tenant. Receive the following error every time. Only way around this is the manually delete the WAF policy from the F5 and then reissue the delete call.

```
"results": [
    {
        "host": "localhost",
        "code": 422,
        "message": "declaration failed",
        "runTime": 1564,
        "response": "010713f9:3: The folder /testApp/Shared cannot be deleted because it contains configuration item (ASM policy /testApp/Shared/test_asm_policy)",
        "tenant": "testApp"
    }
],
```

### Expected Behavior
It shouldn't matter what is associated to the tenant. If its able to be created. It should be able to be deleted without requiring manual intervention.

**Comment by G-gonzalezjimenez** [comment]
Thank you for reporting, tracking internally with Mystique-622

**Comment by dstokesf5** [comment]
I am unable to reproduce this issue with a declaration similar to the one below:
```json
{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "tenant": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "item": {
                "class": "WAF_Policy",
                "ignoreChanges": true,
                "url": {
                    "url": "https://removed/resources/asm-policy/wordpress_template_12.0.xml"
                }
            }
        }
    }
}
```

I was testing on 16.1.2.0. I will try again with 16.1.2.1. In the meantime, can you think of any additional information that may help in reproducing your issue?

**Comment by devildog-tech** [comment]
That should do it. The only other thing I can think of is the xml I am importing references a template policy and has everything inherited. When I try to delete the tenant, it errors out providing the above error. The interesting thing is it actually removes everything from the tenant besides the WAF profile, virtual servers and all. All that is left in the partition is a unassigned WAF profile. You go into the F5 and delete the WAF profile and rerun the job and it completes successful.

**Comment by devildog-tech** [comment]
> I am still unable to reproduce this. Do you have ASM provisioned when you try to delete the tenant?

ASM is provisioned and actively running 100's of other WAF profiles in production on the same box. If need be I would be happy to open a support case and provide the UCS. Just let me know.

**Comment by dstokesf5** [comment]
What we need to figure out, is why AS3 does not recognize that it needs to delete a WAF policy. The most helpful tool for debugging this would be trace output from the delete request. To get this trace data append `?controls.traceResponse=true` to your request URL.

If the results of that request are too sensitive to share here, please open an SR to share them.

**Comment by devildog-tech** [comment]
I haven't forgot about this. I'm going to have someone on my team get on this as soon as I have resources free up here in the next week or so. I will turn this one into an SR, that way we can exchange the needed information for troubleshooting. I provide the SR number on here once open. Thank you..

**Comment by dstokesf5** [comment]
Thank you. We will keep an eye out for that SR.
