### ISSUE TITLE
Support Security  Reporting Settings

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-appsvcs-extension#593]
### Is your feature request related to a problem? Please describe.
ISP customer Orange, require to configure Security Reporting Settings

### Describe the solution you'd like
It can be configured either with GUI or tmsh as shown below:
**(tmos)# list security analytics settings all-properties**
security analytics settings {
    acl-rules {
        collect-client-ip enabled
        collect-client-port disabled
        collect-dest-ip enabled
        collect-dest-port enabled
        collect-server-side-stats disabled
    }
    collect-all-dos-statistic disabled
    collected-stats-external-logging disabled
    collected-stats-internal-logging enabled
    dns {
        collect-client-ip enabled
    }
    dns-collect-stats enabled
    dos-l2-l4 {
        collect-client-ip enabled
        collect-dest-geo enabled
    }
    dosl3-collect-stats enabled
    fw-acl-collect-stats enabled
    fw-drops-collect-stats enabled
    ip-reputation-collect-stats enabled
    l3-l4-errors {
        collect-client-ip enabled
        collect-dest-ip enabled
    }
    partition Common
    publisher none
    sip-collect-stats enabled
    smtp-config none
    stale-rules {
        collect disabled
    }
}

### Describe alternatives you've considered
For the time being either tmsh:
**(tmos)# modify security analytics settings collect-all-dos-statistic enabled**
or GUI is used

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.

**Comment by dstokesf5** [comment]
AS3 is meant to configure per-application settings. Global settings like this one are more appropriate for Declarative Onboarding: https://github.com/F5Networks/f5-declarative-onboarding
