### ISSUE TITLE
Cannot specify GSLB pool ratio in GSLB_Domain AS3 configuration

### ISSUE THREAD

**Issue by antonywm** [F5Networks/f5-appsvcs-extension#594]
### Environment
 * Application Services Version: v3.35.0
 * BIG-IP Version: BIG-IP 16.1.2.1 Build 0.0.10 Point Release 1 (VE)

### Summary
When configuring GTM features via AS3, the WIP (Wide IP) configuration can be defined in GSLB_Domain object. This allows a WIP to be configured and assigned to 1 or more GSLB pools. GTM provides tiered global server load balancing where it distributes DNS name resolution requests, first to the best available pool in a wide IP, and then to the best available virtual server within that pool. This is described here: https://techdocs.f5.com/kb/en-us/products/big-ip_gtm/manuals/product/gtm-concepts-11-5-0/1.html

However, although you can specify the load balancing type in the [GSLB_Domain](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#gslb-domain) object, you cannot actually assign any value to the pools as the object [Pointer_GSLB_Pool](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pointer-gslb-pool) does not accept any additional values apart from the reference to the pool object.

Compare this with object [GSLB_Pool_Member_A](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#gslb-pool-member-a) which does allow specification of a ratio.

### Steps To Reproduce

1. Build Wide IP with 2 pools for UK South and UK West:

```json
			"example.com": {
				"class": "GSLB_Domain",
				"domainName": "wip.example.com",
				"resourceRecordType": "A",
				"poolLbMode": "ratio",
				"pools": [
					{
					"ratio": 50,
					"use": "pool-a"
					}]
				}
```

- this uses poolLBMode option to specify ratio load balancing between pools
- However, it errors as you cannot specify the ratio. Error returned is : 422 (Unprocessable Entity):

```json
{
	"code": 422,
	"errors": [
		"/test/test/example.com/pools/0: should NOT have more than 1 properties"
	],
	"declarationFullId": "",
	"message": "declaration is invalid"
}
```

Checking API spec, I cannot see any way to specify the ratio in AS3:
GSLB_Domain API reference: [GSLB_Domain](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#gslb-domain)

- within this object the pools property references: **array<Pointer_GSLB_Pool>**
[Pointer_GSLB_Pool](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pointer-gslb-pool)

In this object there is no property to specify ratio, and there does not seem to be any other way of specifying it.

**Comment by mdditt2000** [comment]
@antonywm specify you ratio in the members. Please see the following example https://github.com/F5Networks/f5-appsvcs-extension/issues/587

**Comment by antonywm** [comment]
@mdditt2000  - Hi Mark there is no example in issue 587 but regardless, I don't want to specify ratio in the pool members, I want to specify ratio between the pools themselves. GTM/DNS offers this tiered load balancing feature via GUI but cannot see it within AS3.

Below is how it works in the GUI - in example you can see against my WIP I am load balancing 50/50 across 2 pools:
![image](https://user-images.githubusercontent.com/32461620/163994393-7cf9e6f1-5933-4b93-b9f8-dbd21975e018.png)

**Comment by dstokesf5** [comment]
Adding support for a new property is a feature request, not a bug. Updating the labels.

**Comment by antonywm** [comment]
Can I assume by this terse reply that F5 haven't implemented this key feature of GTM config in AS3? And if this is the case, why does the GSLB_Domain object have the `poolLbMode` property which allows you to specify the load balancing method (quote from API reference: "...Specifies the load balancing method used to select a pool in this domain") - but then rejects any value against it? Adding support for a new property is a feature request - but an existing property in the schema which isn't functioning properly....surely is a bug?

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added AUTOTOOL-3141 to our internal product backlog to allow specifying a ratio value per pool member.
