### ISSUE TITLE
Unable to POST to Common/Shared using f5networks.f5_bigip.bigip_as3_deploy.

### ISSUE THREAD

**Issue by devildog-tech** [F5Networks/f5-appsvcs-extension#597]
### Environment

Application Services Version: 3.35.0
BIG-IP Version: 16.1.2.1

### Summary
Using Ansible F5 module f5networks.f5_bigip.bigip_as3_deploy. I am unable to POST to Common/Shared. No matter what I change in the JSON. It will report back Successful no change. If I take the same exact JSON and use ansible uri module to POST it or manually POST it from vscode etc.. It will make the change every-time. I can use the same ansible code and f5networks.f5_bigip.bigip_as3_deploy module to POST to any other tenant without issue.

**Comment by dstokesf5** [comment]
This looks like a problem with the Ansible module. Can you please file a ticket with F5 support to get this feedback to the team that works on the Ansible module?
