### ISSUE TITLE
Unable to add SMTPS profile to Virtual with AS3.

### ISSUE THREAD

**Issue by devildog-tech** [F5Networks/f5-appsvcs-extension#598]
### Is your feature request related to a problem? Please describe.
Please add support to add SMTPS profiles to Virtual Servers in AS3.

### Describe alternatives you've considered
Only alternative at the moment is to manually add it after the AS3 deploys. 

```
tmsh modify ltm virtual example_vs profiles add { smtps }
```

**Comment by devildog-tech** [comment]
Checking up on this one. Thanks..

**Comment by dstokesf5** [comment]
@devildog-tech Do you need AS3 to be able to create SMTPS profiles, or just reference existing ones from a virtual server?

**Comment by devildog-tech** [comment]
Just reference. I have not had a use case to create a custom SMTPS profile,

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added AUTOTOOL-3301 to our internal product backlog to support referencing SMTPS profiles.

**Comment by dstokesf5** [comment]
This has been resolved in the 3.38.0 of AS3.
