### ISSUE TITLE
TLS_Server & TLS_Client Features Missing -- Include all option such as "Proxy SSL" and "Proxy SSL Passthrough"

### ISSUE THREAD

**Issue by devildog-tech** [F5Networks/f5-appsvcs-extension#601]
TLS_Server & TLS_Client Features Missing -- Include all option such as "Proxy SSL" and "Proxy SSL Passthrough" to be configured. Missing features to objects makes it difficult to migrate to AS3. I have seen this in a few areas where all the features are just not included in the object being configured.

**Comment by mdditt2000** [comment]
@devildog-tech you correct, "Proxy SSL" and "Proxy SSL Passthrough" are currently missing from the schema. I can get these added so you able to migrate to AS3. 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#tls-server

Any additional objects that you need for migration? We cannot add every BIG-IP object.

**Comment by mdditt2000** [comment]
Add Jira AUTOTOOL-3293 for PM planning/tracking

**Comment by devildog-tech** [comment]
> @devildog-tech you correct, "Proxy SSL" and "Proxy SSL Passthrough" are currently missing from the schema. I can get these added so you able to migrate to AS3.
> 
> https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#tls-server
> 
> Any additional objects that you need for migration? We cannot add every BIG-IP object.

Thank you.. Please include the following. This should cover all my needs and allow me to move remaining profiles into AS3.

```
TLS_Server:
- Proxy SSL: Boolean
- Proxy SSL Passthrough: Boolean
- Non-SSL Connections: Boolean
- Secure Renegotiation: Request / Require / Require Strict ---> Note: You can enable Secure Renegotiation, but cannot set it to Request.
- Unclean Shutdown: Boolean
- Certificate Extensions List: Extended Key Usage
- Options: No DTLSv1.2

TLS_Client:
- Proxy SSL: Boolean
- Proxy SSL Passthrough: Boolean
- Secure Renegotiation: Request / Require / Require Strict ---> Note: You can enable Secure Renegotiation, but cannot set it to Request.
- Unclean Shutdown: Boolean
- Options: No DTLSv1.2
```

**Comment by dstokesf5** [comment]
There is already support for Proxy SSL and Proxy SSL Passthrough: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#configuring-explicit-forward-proxy-settings-in-ssl-tls-profiles

**Comment by dstokesf5** [comment]
Ah nevermind, I see that ssl-forward-proxy and ssl-proxy are separate settings.

**Comment by devildog-tech** [comment]
> There is already support for Proxy SSL and Proxy SSL Passthrough: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#configuring-explicit-forward-proxy-settings-in-ssl-tls-profiles

Forward Proxy is not the same as Proxy SSL and Proxy SSL Passthrough. There two separate use cases.

**Comment by devildog-tech** [comment]
It's also good to note that Proxy SSL and Proxy SSL Passthrough must be enabled and configured on both the TLS_Server and TLS_Client for the feature to work. Thank you..

**Comment by devildog-tech** [comment]
> @devildog-tech good morning. What BIG-IP version are you folks using? As some properties are added to newer BIG-IP versions, while others are deprecated

morning. We are 16.1.2.2 across the farm.

**Comment by dstokesf5** [comment]
This has been resolved in the 3.38.0 of AS3.

**Comment by devildog-tech** [comment]
It seems there is a but with the Proxy SSL feature.

**If you implement the below code you receive the following error.** 

```
{"changed": false, "msg": "declaration failed. 01071678:3: dont-insert-empty-fragments conflicts with Proxy SSL (both cannot be enabled) in profile /www.test.com/Shared/www.test.com_server_ssl."}
```

```
"www.test.com_server_ssl": {
    "clientCertificate": "www.test.com_certificate",
    "proxySslEnabled": true,
    "proxySslPassthroughEnabled": true,
    "remark": "TEST",
    "class": "TLS_Client"
},
```

If you implement the following code you receive even though "insertEmptyFragmentsEnabled" should be false by default the same error.

```
{"changed": false, "msg": "declaration failed. 01071678:3: dont-insert-empty-fragments conflicts with Proxy SSL (both cannot be enabled) in profile /www.test.com/Shared/www.test.com_server_ssl."}
```

```
"www.test.com_server_ssl": {
    "clientCertificate": "www.test.com_certificate",
    "proxySslEnabled": true,
    "proxySslPassthroughEnabled": true,
    "insertEmptyFragmentsEnabled": false,
    "remark": "TEST",
    "class": "TLS_Client"
},
```

The same issue appears in TLS_Server as well. I haven't found a way around it.

**Comment by dstokesf5** [comment]
@devildog-tech Thank you for your feedback. Can you create a new bug issue with these findings so we can track them properly?
