### ISSUE TITLE
Virtual Server AdminState

### ISSUE THREAD

**Issue by BarryHaines** [F5Networks/f5-appsvcs-extension#603]
### Is your feature request related to a problem? Please describe.
Current AS3 Service Classes have an "enable" property that can be set to true or false, when it is set to false the virtual server configuration in the tenant is removed and can no longer be viewed on the BIG-IP.

### Describe the solution you'd like
Using the BIG-IP webgui or API it is possible to set an Adminstate to enable or disable a virtual server and AS3 also has an AdminState for pool members, it would be nice to have this AdminState for the Services and leave the VS configuration without removing the configuration.

**Comment by mdditt2000** [comment]
@BarryHaines please review the following document i created using AdminState

https://github.com/mdditt2000/f5-appsvcs-extension/blob/master/github/603/as3.md

Please use enable or disable as shown below and in the link

```
            "Pool_1": {
                "class": "Pool",
                "members": [
                    {
                        "servicePort": 80,
                        "serverAddresses": [
                            "10.1.0.1",
                            "10.1.0.2"
                        ],
                        "adminState": "disable"
                    }
                ]
            }
```

**Comment by BarryHaines** [comment]
Please could merge this issue with https://github.com/F5Networks/f5-appsvcs-extension/issues/523, the issue 523 relates to my enhancement request.

**Comment by IkueMoto** [comment]
The use case is to disable the VIP without removing the config from BIG-IP, so that a BIG-IP admin can quickly re-enable the VIP if needed via the GUI. Re-adding the VIP using AS3 can potentially cause significant delay and unnecessary down time.

Can you provide an ETA for this RFE please?
