### ISSUE TITLE
Default values inside the replied declaration when using "dry-run" action

### ISSUE THREAD

**Issue by zongzw** [F5Networks/f5-appsvcs-extension#608]
### Is your feature request related to a problem? Please describe.

Hi,
When we POST the json declaration with action "dry-run", could we get the replied declaration with default values appended.

like: `virtualPort` `persistenceMethod` for `Service_HTTP`.

So that, I can know the very configuration(after as3 helps to validate and supplement) I'll post to BIG-IP.
Currently, AS3 just replies with the declaration user posts.

**Comment by dstokesf5** [comment]
The query parameter should be part of the URL:
`POST https://10.XX.XX.XX:8443/mgmt/shared/appsvcs/declare?show=full`

**Comment by zongzw** [comment]
Ops, apologize for noising. This can meet my requirement. Closed it.
