### ISSUE TITLE
Service Discovery / Consul and jmespathquery to configure priorityGroup for pool members

### ISSUE THREAD

**Issue by paolobeta71** [F5Networks/f5-appsvcs-extension#610]
Hi this request is to understand if I can use jmespathquery on Service Discovery working with Consul to parse additional information to set priorityGroup to pool members. We are currently supporting using jmespathquery the capability to configure custom ports on a pool member gathering this info from the jmespathquery. 
Consul can also provides additional parameters in the form of meta information to set for example priorityGroup in a pool member. This snippet is an example:
.......
"Meta":{"application-version":"v1.0","configuration-version":"v1.2","external-source":"nomad","priority":"20",..............

with  jmespathquery we can extract this information like SD does for ip or port, but I'm not sure if SD is also able to use a paramenter to configure the prorityGroup for a pool member. An example of my jmespathquery could be:
"jmesPathQuery": "[*].{id:Node.Address,ip:{private:Node.Address,public:Node.Address},port:Service.Port,priorityGroup:Service.Meta.priority}"
Can you please confirm if AS3-SD is able to configure priorityGroup for pool members or can only manage pool member name, ip and port?

**Comment by mdditt2000** [comment]
Created Jira AUTOTOOL-3335 for PM tracking

**Comment by sunitharonan** [comment]
This has been resolved in the 3.42.0 release of AS3.
