### ISSUE TITLE
Improved feature parity: ALG logging profiles

### ISSUE THREAD

**Issue by LaurentGravier** [F5Networks/f5-appsvcs-extension#619]
### Is your feature request related to a problem? Please describe.
It is not possible to create an ALG logging profile with AS3

### Describe the solution you'd like
I would like to create an ALG logging profile with AS3, as it is feasible with the CLI (create ltm alg-log-profile) or the GUI (Local Traffic / Profiles / Other / ALG Logging). 
The configurable parameters should be the same as with the CLI/GUI. 

### Describe alternatives you've considered
I create the ALG logging profiles out of AS3 (with non declarative commands).

**Comment by mdditt2000** [comment]
@LaurentGravier please can you reach out to me automation_toolchain_pm@f5.com

I would like to have a call/email/chat with you to understand better the use case. There may be other ways to look at this issue that could work better.

**Comment by mdditt2000** [comment]
@LaurentGravier @sunitharonan and I are looking at this issue. BTW we dont see the "tmsh" commands to create this profile

```
root@(ocp-02)(cfg-sync In Sync)(Standby)(/Common)(tmos)# create alg-log-profile ?
Syntax Error: "alg-log-profile" unexpected argument
root@(ocp-02)(cfg-sync In Sync)(Standby)(/Common)(tmos)# create alg-log-profile
```

**Comment by RobCupples** [comment]
@mdditt2000 @sunitharonan 

It looks like this profile requires the CGNAT module to be provisioned.

**Comment by LaurentGravier** [comment]
Yes, CGNAT module has to be provisioned to be able to use command `create alg-log-profile` in CLI mode. 

Theoretically, the AFM module is sufficient for making CGNAT, but because of the ALG log profiles, it remains necessary to provision the CGNAT module.  By the way, such provisioning is not necessary if you want to create ALG log profiles _with the GUI_. This is described in bug tracker ID 1097973.

**Comment by sunitharonan** [comment]
This has been resolved with AUTOTOOL-3491 backlog item  in As3 3.43.0. Thanks.
