### ISSUE TITLE
Add support SCTP_Profile for AS3

### ISSUE THREAD

**Issue by p-semenov-f5** [F5Networks/f5-appsvcs-extension#627]
We have sctp profile on BIG-IP what is not covered by AS3.

--
ltm profile sctp /Common/testSCTP {
    alternate-addresses {
        10.10.2.2
        10.10.2.3
    }
    app-service none
    client-side-multihoming enabled
    cookie-expiration 61
    defaults-from /Common/sctp
    heartbeat-interval 31
    heartbeat-max-burst 2
    idle-timeout 301
    in-streams 2
    init-max-retries 6
    ip-tos 3
    link-qos pass-through
    max-burst 5
    max-communication-paths 17
    max-path-retransmit-limit 6
    out-streams 3
    proxy-buffer-high 16385
    proxy-buffer-low 4000
    receive-chunks 258
    receive-ordered disabled
    receive-window-size 65534
    reset-on-timeout disabled
    rto-initial 3001
    rto-max 60001
    rto-min 1001
    sack-timeout 201
    secret $M$mQ$CBOzfbAMPgp81pPt+f1EEQ==
    send-buffer-size 65535
    send-max-retries 11
    send-partial enabled
    server-side-multihoming enabled
    tcp-shutdown enabled
    transmit-chunks 257
}
--

When I tried to post simple config:

{
    "class": "ADC",
    "schemaVersion": "3.38.0",
    "id": "urn:uuid:acfac9a0-49d9-4303-95bc-97bb90932b7e",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "testSCTP": {
                "class": "SCTP_Profile",
                "remark": "test description"
            }
        }
    }
}

I received:

{
    "code": 422,
    "message": "Invalid data property: SCTP_Profile"
}

**Comment by mdditt2000** [comment]
Created Jira AUTOTOOL-3394 for PM tracking.

**Comment by mdditt2000** [comment]
We have SCTP_Profile on BIG-IP what is not covered by AS3. Not a priority at this time. Closing
