### ISSUE TITLE
Patch objects removed after reboot

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#629]
### Environment
 * Application Services Version: 3:36.1
 * BIG-IP Version: 16.1.2.2

### Summary
A Post method with patch action doesn't persist a reboot. 

### Steps To Reproduce
1. Submit a full declaration (Post method with a full declaration)

2. Submit a Post declaration with a patch method and patch body

3. See the AS3 history that was created

3. Reboot the BIG-IP cluster (shutdown both nodes)

4. Pools created with Patch are removed

5. History for as3 is overwritten and the patch is missing.

### Expected Behavior
Patch objects should persist through a reboot.

@mdditt2000

**Comment by dstokesf5** [comment]
Step four suggests that this is an HA cluster. Do you see the same behavior with standalone devices?

**Comment by jmcalalang** [comment]
We've only tested on a HA cluster, since this is coming from the current CFT v1 HA>

**Comment by jmcalalang** [comment]
Internal case number is C3865623

**Comment by mdditt2000** [comment]
@jmcalalang messaged the ENE to ask if he has recreated the issue in standalone or HA.

**Comment by jmcalalang** [comment]
Customer just asked on this again. Internal case is still waiting on an update.

**Comment by mdditt2000** [comment]
Update from Support
--
I was only able to recreate this issue when the bigIP’s were in an HA pair.

After the initial creation of a pair of VEs, when the devices are powered off/on after an initial AS3 deployment, The Tenant is no longer visible in the GUI. During testing, only the Active device (I did not test POST'ing to the Standby) will still have the /config/partitions/<Tenant>/bigip.conf file. Running "tmsh load sys config" from the Active will reload the AS3 objects.
 
- This issue did not continue after the initial VE creation/AS3 deployment/power off - power on
- This issue did not impact a Standalone device
- This issue did not impact manually created Tenants and objects
---
Next steps are to review the testing with AS3 developers at the next SPRINT planning. 

Jira AutoTool-3401

**Comment by seattlevine** [comment]
Since you are using auto-sync, please configure the device group to save-on-auto-sync.

> save-on-auto-sync
     Specifies whether to save the configuration on the remote devices
     following an automatic configuration synchronization. A device
     group configured for manual synchronization will always save on
     the remote devices regardless of this setting.

I am only able to reproduce this behavior when save-on-auto-sync is disabled. When it is enabled, objects are persisting across reboot.
