### ISSUE TITLE
AS3 AWS service discovery not cleaning up nodes

### ISSUE THREAD

**Issue by shortenmark** [F5Networks/f5-appsvcs-extension#630]
### Environment

- Application Services Version: 3.38.0 (however issue persists with previous versions)
- Service Discovery Version: 1.10.13
- BIG-IP Version: BIG-IP 15.1.5.1

### Summary

AWS instances learned through service discovery are not removed from the list of nodes when destroyed in AWS. If an instance is recreated using an IP address of a previously destroyed instance the F5 adds the node to the pool with the instance ID of the destroyed instance. Number of nodes in partition continues to grow increasing chance of instance clash.

```
"{{ poolName }}": {
    "class": "Pool",
    "members": [
        {
             "addressDiscovery": true,
             "autoPopulate": true,
             "updateInterval": 30,
             "undetectableAction" "remove",
             "servicePort": {{ poolPort }},
             "tagKey": "aws:autoscaling:groupName",
             "tagValue": "{{ asgName }}",
             "region": "{{ awsRegion }}"
        }   
    ]
}
```

### Expected Behaviour

Destroyed instances should be removed from the list of nodes

**Comment by sunitharonan** [comment]
Please resubmit this issue using one of the provided templates in order to help us better track your issue.
