### ISSUE TITLE
HTTP monitor - we require Alias Service Port

### ISSUE THREAD

**Issue by alexgfullerton** [F5Networks/f5-appsvcs-extension#631]
### Is your feature request related to a problem? Please describe.
In HTTP monitor we require Alias Service Port but cannot see this in the AS3 schema. Is this an option we can use?

### Describe the solution you'd like
Alias Service Port to be an available option in http monitor

### Describe alternatives you've considered
No alternative as this is an option in the GUI but not in AS3. This is currently blocking a delivery

**Comment by RobCupples** [comment]
"Alias Address" and "Alias Service Port" should be the "targetAddress" and "targetPort" properties.

```json{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "controls": {
        "class": "Controls",
        "trace": true,
        "logLevel": "debug"
    },
    "TEST_MONITOR_HTTP": {
        "class": "Tenant",
        "TEST_Monitor_HTTP": {
            "class": "Application",
            "template": "generic",
            "mHttpNonDefault": {
                "class": "Monitor",
                "label": "mostly non-default values specified",
                "monitorType": "http",
                "send": "HEAD / HTTP/1.0\\r\\n\\r\\n",
                "receive": "HTTP/1.1",
                "receiveDown": "status=(quiesce|disabled|drain)",
                "transparent": true,
                "dscp": 20,
                "targetAddress": "198.19.192.15",
                "targetPort": 80,
                "interval": 10,
                "upInterval": 11,
                "timeUntilUp": 12,
                "timeout": 31
            }
        }
    }
}
```
![Screenshot 2022-07-26 154839](https://user-images.githubusercontent.com/29408153/181125364-0f6db27e-7ef9-46d8-b72b-553a8be7d66b.png)

**Comment by alexgfullerton** [comment]
Thanks Rob. I will give this a try.

Regards
Alex.

**Comment by alexgfullerton** [comment]
That worked thanks Rob.

**Comment by mdditt2000** [comment]
This can be closed as @RobCupples provided a resolution. Thanks
