### ISSUE TITLE
Question regarding parent policy support using declarative WAF

### ISSUE THREAD

**Issue by Eken92** [F5Networks/f5-appsvcs-extension#632]
### Is your feature request related to a problem? Please describe.
This is neither a request or a bug report - and not an AS3 issue (but no idea where to ask this if not here)

Anyway, this confused me a bit. Checking the schema for https://clouddocs.f5.com/products/waf-declarative-policy/declarative_policy_v16_0_0.html#urls it says you can either specify the type as "parent" or "security". 

However, checking the "support matrix" it says "Parent policy: no" (https://techdocs.f5.com/en-us/bigip-15-1-0/big-ip-declarative-security-policy/declarative-policy-additional-information.html)

And importing the policy with type: parent (using bigip 15.1.x) it fails with error message: Import declarative Parent Policy is not allowed.

So, I'm not surprised it doesn't work - but since the schema reference includes "parent" - is it supported in later versions of bigip (16+) or is it a coming feature, or what is the status for it?

Defining the parent policies in a declarative manner would be _extremely_ useful and make the declarative WAF functionality a lot more interesting.

Thanks, and sorry for placing the question here.

**Comment by dstokesf5** [comment]
@Eken92 Have  you tried opening a case with F5 support? Unfortunately, I do not have an answer to your question.

**Comment by Eken92** [comment]
I haven't, was hoping that the developers of AS3 and declarative WAF were the same (thus knowing the truth)

Anyway, will do so! Thank you for the quick reply :)

**Comment by dstokesf5** [comment]
Unfortunately, the developers for AS3 and Declarative WAF are not the same. Good luck on finding your answers. I am closing this issue.
