### ISSUE TITLE
GSLB Server and proberPool not created

### ISSUE THREAD

**Issue by paolobeta71** [F5Networks/f5-appsvcs-extension#637]
### Environment
 * Application Services Version: 3.38.0
 * BIG-IP Version: 15.1.5

### Summary
Trying to create using PATCH method a GSLB configuration that will create a GSLB Server with Prober Pool. The declaration also tries to create the prober pool itself but provides the following error: 
```json
{
    "code": 422,
    "errors": [
        "/Common/Shared/ACME-PAOLO-02: should NOT have additional properties"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

### Steps To Reproduce
1. Submit the following declaration using PATCH method to AS3:
```json
[      
  { 
    "op": "add",
    "path": "/Common/Shared/ACME-PAOLO-02",
    "value": { 
                "class": "GSLB_Server",
                "serverType": "bigip",
                "monitors": [
                        
                    ],
                "dataCenter": { 
                    "bigip": "/Common/testDataCenter"
                },
                "proberPreferred": "pool",
                "proberPool": {
                    "use": "prober_pool_02"
                },
                
                "devices":[
                    {
                        "label": "ACME-PAOLO-02",
                        "address": "1.2.9.20"
                    } 
                ],
                "virtualServers": [
                    {
                        "name": "ACME-PAOLO_VS2",
                        "address": "1.2.9.20",
                        "port": 0
                    }
                ],
                "prober_pool_02": {
                "class": "GSLB_Prober_Pool",
                    "members": [
                        {
                        "server": {
                        "bigip": "/Common/ACME-PAOLO"
                        },
                        "memberOrder": 0                        
                        }
                    ],
                    "lbMode": "global-availability"        
                }                
            }                              
    }
]
```

2. Observe the following error response:
```json
{
    "code": 422,
    "errors": [
        "/Common/Shared/ACME-PAOLO-02: should NOT have additional properties"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

### Expected Behavior
GSLB Server ACME-PAOLO-02 created with prober pool prober_pool_02 also created by the same declaration and referenced within the created GSLB Server

### Actual Behavior
The declaration doesn't create the objects and replies with the error provided.

**Comment by dstokesf5** [comment]
@paolobeta71 Can you provide the initial declaration before the PATCH request, or do a GET to the declare endpoint to get the state before the PATCH request?

**Comment by mdditt2000** [comment]
@paolobeta71 i believe this is resolved in AS3-40. Please reach out to automation_toolchain_pm@f5.com to get an early released image.

**Comment by paolobeta71** [comment]
In response to Daniel request. 
The first POST request is the following:
POST https://10.1.1.245/mgmt/shared/appsvcs/declare
{
    "class": "ADC",
    "schemaVersion": "3.25.0",
    "id": "GSLB_Sample",
        "Automation": { 
        "class": "Tenant",
        "Shared": { 
            "class": "Application",
            "template": "shared",
            "GSLB_testPool": { 
                "class": "GSLB_Pool",
                "resourceRecordType": "A",  
                "enabled": true,
                "fallbackIP": "127.0.0.1",
                "lbModeFallback": "drop-packet",
                "lbModeAlternate": "none",
                "lbModePreferred": "fallback-ip"
                }
            }
        }
    }


This is also the answer for the GET request to the declare endpoint:
{"Fast":{"class":"Tenant","nginx-http-70_vs":{"class":"Application","service":{"class":"Service_HTTP","virtualAddresses":["10.1.10.170"],"pool":"http_pool"},"http_pool":{"class":"Pool","monitors":["http"],"members":[{"servicePort":80,"addressDiscovery":"consul","updateInterval":10,"uri":"http://10.0.0.100:8500/v1/health/service/nginx?passing","jmesPathQuery":"[*].{id:Node.Address,ip:{private:Node.Address,public:Node.Address},port:Service.Port}"}]}},"nginx-http-71_vs":{"class":"Application","service":{"class":"Service_HTTP","virtualAddresses":["10.1.10.171"],"pool":"http_pool"},"http_pool":{"class":"Pool","monitors":["http"],"members":[{"servicePort":80,"addressDiscovery":"consul","updateInterval":10,"uri":"http://10.0.0.100:8500/v1/health/service/nginx?passing","jmesPathQuery":"[*].{id:Node.Address,ip:{private:Node.Address,public:Node.Address},port:Service.Port}"}]}}},"UDP_partition":{"class":"Tenant","DNS_Service":{"class":"Application","service":{"class":"Service_UDP","virtualPort":53,"virtualAddresses":["10.1.10.121"],"pool":"dns_pool"},"dns_pool":{"class":"Pool","monitors":[{"use":"udp_custom_53"},"icmp"],"minimumMonitors":"all","members":[{"servicePort":53,"serverAddresses":["172.16.10.239"]}]},"udp_custom_53":{"class":"Monitor","monitorType":"udp","adaptive":false}}},"Automation":{"class":"Tenant","Shared":{"class":"Application","template":"shared","GSLB_testPool":{"class":"GSLB_Pool","resourceRecordType":"A","enabled":true,"fallbackIP":"127.0.0.1","lbModeFallback":"drop-packet","lbModeAlternate":"none","lbModePreferred":"fallback-ip"},"record.info.it":{"class":"GSLB_Domain","domainName":"record.info.it","resourceRecordType":"A","poolLbMode":"global-availability","pools":[{"use":"/Automation/Shared/GSLB_testPool"}]},"testPoolCNAME":{"class":"GSLB_Pool","resourceRecordType":"CNAME","members":[{"domainName":"record.info.it","enabled":false}]},"testCNAME.it":{"class":"GSLB_Domain","domainName":"testCNAME.it","resourceRecordType":"CNAME","poolLbMode":"round-robin","pools":[{"use":"/Automation/Shared/testPoolCNAME"}]}}},"Common":{"class":"Tenant","Shared":{"class":"Application","template":"shared","Paolo-DC":{"class":"GSLB_Data_Center"},"pool_nomatch":{"class":"GSLB_Pool","resourceRecordType":"A","enabled":true,"fallbackIP":"127.0.0.1","lbModeFallback":"drop-packet","lbModeAlternate":"none","lbModePreferred":"fallback-ip"},"ACME-PAOLO":{"class":"GSLB_Server","serverType":"bigip","monitors":[],"dataCenter":{"use":"Paolo-DC"},"proberPreferred":"pool","proberPool":{"bigip":"/Common/prober_pool_01"},"devices":[{"label":"ACME-PAOLO","address":"1.2.9.19"}],"virtualServers":[{"name":"ACME-PAOLO_VS","address":"1.2.9.19","port":0}]},"prober_pool_02":{"class":"GSLB_Prober_Pool","members":[{"server":{"use":"/Common/ACME-PAOLO"},"memberOrder":0}],"lbMode":"global-availability"}}},"class":"ADC","updateMode":"selective","schemaVersion":"3.0.0","id":"DNS","DNS_Zones":{"class":"Tenant","TEST_DNS_Zone":{"class":"Application","dnsZone":{"class":"DNS_Zone","label":"dnsZone","remark":"DNS Zone test","dnsExpress":{"enabled":true,"nameserver":{"use":"dnsNameserverZone"},"notifyAction":"consume","allowNotifyFrom":["10.1.1.1"],"verifyNotifyTsig":false},"responsePolicyEnabled":true,"serverTsigKey":{"use":"tsigKeyZone"},"transferClients":[{"use":"dnsNameserverZone"}]},"dnsNameserverZone":{"class":"DNS_Nameserver","label":"dnsNameserverZone","address":"10.1.1.2","port":53,"routeDomain":{"bigip":"/Common/0"},"tsigKey":{"use":"tsigKeyZone"}},"tsigKeyZone":{"class":"DNS_TSIG_Key","label":"tsigKeyZone","remark":"TSIG Key test","algorithm":"hmacmd5","secret":{"ciphertext":"JE0kUVckWFJmSmhoYVc2SHFrTTlyVXpiRHI3Zz09","miniJWE":true,"protected":"eyJhbGciOiJkaXIiLCJlbmMiOiJmNXN2In0=","ignoreChanges":true,"allowReuse":false}}}},"controls":{"archiveTimestamp":"2022-08-05T23:16:32.433Z"}}

i'll also follow Mark suggestion and ask for testing with AS3-40.

Thanks
Paolo

**Comment by sunitharonan** [comment]
Please reach out to automation_toolchain_pm@f5.com to get an early released image to test it.

**Comment by paolobeta71** [comment]
Hi, tested with the preview of AS3-40...
I'm receiving the same error....
Declaration:
PATCH -> https://10.1.1.245/mgmt/shared/appsvcs/declare
[      
  { 
    "op": "add",
    "path": "/Common/Shared/ACME-PAOLO-02",
    "value": { 
                "class": "GSLB_Server",
                "serverType": "bigip",
                "monitors": [
                        
                    ],
                "dataCenter": { 
                    "bigip": "/Common/testDataCenter"
                },
                "proberPreferred": "pool",
                "proberPool": {
                    "use": "prober_pool_02"
                },
                
                "devices":[
                    {
                        "label": "ACME-PAOLO-02",
                        "address": "1.2.9.20"
                    } 
                ],
                "virtualServers": [
                    {
                        "name": "ACME-PAOLO_VS2",
                        "address": "1.2.9.20",
                        "port": 0
                    }
                ],
                "prober_pool_02": {
                "class": "GSLB_Prober_Pool",
                    "members": [
                        {
                        "server": {
                        "bigip": "/Common/ACME-PAOLO"
                        },
                        "memberOrder": 0                        
                        }
                    ],
                    "lbMode": "global-availability"        
                }                
            }                              
    }
]

Result with error:
{
    "code": 422,
    "errors": [
        "/Common/Shared/ACME-PAOLO-02: should NOT have additional properties"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}

**Comment by RobCupples** [comment]
It is also possible to combine the 2 PATCH operations into an array and post a single time.  This example assumes that the /Common/testDataCenter in my POST above is already on the bigip so it can be referenced with "bigip".  Once again, this will not work for you right now because I'm fixing the broken "proberPool" "use"-reference.

```
PATCH mgmt/shared/appsvcs/declare

[
    {
        "op": "add",
        "path": "/Common/Shared/prober_pool_02",
        "value": {
            "class": "GSLB_Prober_Pool",
            "members": [
                {
                    "server": {
                        "use": "/Common/ACME-PAOLO"
                    },
                    "memberOrder": 0
                }
            ],
            "lbMode": "global-availability"
        }
    },
    {
        "op": "add",
        "path": "/Common/Shared/ACME-PAOLO-02",
        "value": {
            "class": "GSLB_Server",
            "serverType": "bigip",
            "monitors": [],
            "dataCenter": {
                "bigip": "/Common/testDataCenter"
            },
            "proberPreferred": "pool",
            "proberPool": {
                "use": "prober_pool_02"
            },
            "devices": [
                {
                    "label": "ACME-PAOLO-02",
                    "address": "1.2.9.20"
                }
            ],
            "virtualServers": [
                {
                    "name": "ACME-PAOLO_VS2",
                    "address": "1.2.9.20",
                    "port": 0
                }
            ]
        }
    }
]
```
