### ISSUE TITLE
Cant create multiple websocket profiles, only one shared profile.

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-appsvcs-extension#638]
### Environment
 * Application Services Version:3.38.0
 * BIG-IP Version: 15.1.1

### Cant create multiple websocket profiles, only one shared profile.  
When separate HTTP profiles have websockets enabled, only one shared profile is created. 

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.38.0",
      "id": "123abc",
      "label": "Sample 1",
      "remark": "An HTTPS sample application",
      "controls": {
        "trace": true
      },
      "Common": {
        "class": "Tenant",
        "Shared": {
          "class": "Application",
          "template": "shared",
          "demo-app1": {
            "class": "Service_HTTP",
            "virtualPort": 80,
            "profileHTTP": {
            "use": "httpProfile-app1"
                },
            "virtualAddresses": [
              "10.5.20.242"
            ]
          },
            "demo-app2": {
            "class": "Service_HTTP",
            "virtualPort": 8080,
            "profileHTTP": {
            "use": "httpProfile-app2"
                },
            "virtualAddresses": [
              "10.5.20.242"
            ]
          },
         "httpProfile-app1": {
         "class": "HTTP_Profile",
         "webSocketsEnabled": true,
         "webSocketMasking": "selective"
            },
        "httpProfile-app2": {
         "class": "HTTP_Profile",
         "webSocketsEnabled": true,
         "webSocketMasking": "selective"
            }
          }
        }
      }
    }
```

2. Declaration succeeds. 

### Expected Behavior
Two websocket profiles attached to their respective VS. 

Example:
```
(tmos)# list ltm virtual recursive one-line 

ltm virtual Shared/demo-app1 { description Shared destination Shared/10.5.20.242:http ip-protocol tcp last-modified-time 2022-08-23:16:09:19 mask 255.255.255.255 persist { cookie { default yes } } profiles { Shared/httpProfile-app1_selective { } Shared/httpProfile-app1 { } f5-tcp-progressive { } } serverssl-use-sni disabled source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 18 }

ltm virtual Shared/demo-app2 { description Shared destination Shared/10.5.20.242:webcache ip-protocol tcp last-modified-time 2022-08-23:16:09:19 mask 255.255.255.255 persist { cookie { default yes } } profiles { Shared/httpProfile-app2_selective { } Shared/httpProfile-app2 { } f5-tcp-progressive { } } serverssl-use-sni disabled source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 19 }
```
### Actual Behavior
One system generated websocket profile `f5_appsvcs_selective` attached to each VS. 

Example:
```
(tmos)# list ltm virtual recursive one-line 

ltm virtual Shared/demo-app1 { description Shared destination Shared/10.5.20.242:http ip-protocol tcp last-modified-time 2022-08-23:16:09:19 mask 255.255.255.255 persist { cookie { default yes } } profiles { Shared/f5_appsvcs_selective { } Shared/httpProfile-app1 { } f5-tcp-progressive { } } serverssl-use-sni disabled source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 18 }

ltm virtual Shared/demo-app2 { description Shared destination Shared/10.5.20.242:webcache ip-protocol tcp last-modified-time 2022-08-23:16:09:19 mask 255.255.255.255 persist { cookie { default yes } } profiles { Shared/f5_appsvcs_selective { } Shared/httpProfile-app2 { } f5-tcp-progressive { } } serverssl-use-sni disabled source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 19 }
```

Having separate profiles allows for each websocket profile to be monitored for independent statistics.  
This is possible to do outside AS3 in LTM.

**Comment by megamattzilla** [comment]
Forgot to mention the separate WebSocket profiles should have predictable/configurable names.  

Alternatively, the existing web socket functionality can remain in the http profile schema and you could just add schema so that websocket profiles can be authored directly in  AS3 (like any other profile) and attached directly to the virtual server (like TMOS). The WebSocket profiles are very simple with only a few configurable options.

**Comment by megamattzilla** [comment]
It looks like the preference for a fix would be adding schema so that websocket profiles can be authored directly in AS3 (like any other profile) and attached directly to the virtual server (like TMOS can). The WebSocket profiles are very simple with only a few configurable options.

**Comment by RobCupples** [comment]
Thank you. This issue was added to our internal product backlog as AUTOTOOL-3435.

**Comment by mdditt2000** [comment]
Thanks @RobCupples for providing the Jira number.

**Comment by megamattzilla** [comment]
I see that we can now declare named websocket profiles in AS3 schema now, that's great!

It looks like we still can't attach websocket profiles to the virtual servers directly (like you can in TMOS). 

It looks like the reference to websocket profiles (profileWebSocket) was added to the HTTP profile class and not to the virtual server class. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#http-profile 

Was there a reason profileWebSocket was not added to service_http and service_https class so that we could associate websocket the profiles directly to virtual servers? 


Doing it this way, the customer would need to create duplicate HTTP profiles pointing to multiple different websocket profiles in order to assign different websocket profiles to different virtual servers.
