### ISSUE TITLE
HTTP_Profile: Add enforcement settings

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-appsvcs-extension#640]
### Is your feature request related to a problem? Please describe.
The `HTTP_Profile` is missing most to all settings listed in [K40243113](https://support.f5.com/csp/article/K40243113) under **Enforcement**. These are crucial settings, specifically `Enforce HTTP Compliance` and often require the creation of HTTP profiles outside the scope of AS3.

### Describe the solution you'd like
Expose all settings described in [K40243113](https://support.f5.com/csp/article/K40243113) under **Enforcement**.

### Describe alternatives you've considered
The only alternative is to create HTTP profiles outside the scope of AS3 and reference them in the AS3 declaration.

### Additional context
The settings are often required to mitigate or enhance security of the web applications delivered via F5 BIG-IP.

**Comment by mdditt2000** [comment]
@simonkowallik wouldn't it be best to use a pointer in AS3 to reference a custom HTTP profile. My concern today is the growth of the AS3 schema but adding every setting on BIG-IP.

**Comment by sunitharonan** [comment]
Thanks @simonkowallik. I have added this issue to our internal product backlog as AUTOTOOL-3441.

**Comment by RobCupples** [comment]
I have been investigating this.  I could only find 2 Enforcement properties that are missing: `Enforce RFC Compliance` and `Allow Space Header Name`.  There is also a TMOS property named `max-requests` that is not exposed to the GUI. 

For your assistance I have tried to map out the Enforcement properties from the GUI to AS3.  The set of properties available varies by proxy mode.  The set of properties for the reverse and explicit property modes are the same but some may have different defaults and minimum/maximum values.

Proxy Mode Reverse / Explicit (BIGIP GUI => AS3)
Enforcement RFC Compliance => not implemented
Allow Space Header Name => not implemented
Allow Truncated Redirect => truncatedRedirects
Maximum Header Size => maxHeaderSize
Maximum Header Count => maxHeaderCount
Pipeline Action => pipelineAction
Unknown Method => unknownMethodAction
Known Methods => knownMethods

Proxy Mode Transparent (BIGIP GUI => AS3)
Allow Truncated Redirect => truncatedRedircts
Maximum Header Size => maxHeaderSize
Oversize Client Headers => oversizeClientHeaders
Oversize Server Headers => oversizeServerHeaders
Maximum Header Count => maxHeaderCount
Excess Client Headers => excessClientHeaders
Excess Server Headers => excessServerHeaders
Pipeline Action => pipelineAction
Unknown Method => unknownMethodAction
Known Methods => knownMethods

I have also tried to create this example to illustrate the default Enforcement properties with each proxy mode.  The explicit proxy mode requires a DNS resolver.  I have used one that I think is on BIG-IP 15.1 and above.

```json
{
    "class": "ADC",
    "schemaVersion": "3.31.0",
    "id": "TEST",
    "Tenant": {
        "class": "Tenant",
        "App": {
            "class": "Application",
            "service": {
                "class": "Service_HTTP",
                "virtualPort": 80,
                "virtualAddresses": [
                    "1.2.3.4"
                ],
                "profileHTTP": {
                    "use": "httpProfileReverseProxy"
                }
            },
            "httpProfileReverseProxy": {
                "class": "HTTP_Profile",
                "proxyType": "reverse",
                "truncatedRedirects": false,
                "maxHeaderSize": 32768,
                "maxHeaderCount": 64,
                "pipelineAction": "allow",
                "unknownMethodAction": "allow",
                "knownMethods": [
                    "CONNECT",
                    "DELETE",
                    "GET",
                    "HEAD",
                    "LOCK",
                    "OPTIONS",
                    "POST",
                    "PROPFIND",
                    "PUT",
                    "TRACE",
                    "UNLOCK"
                ]
            },
            "httpProfileExplicitProxy": {
                "class": "HTTP_Profile",
                "proxyType": "explicit",
                "resolver": {
                    "bigip": "/Common/f5-aws-dns"
                },
                "truncatedRedirects": false,
                "maxHeaderSize": 32768,
                "maxHeaderCount": 64,
                "pipelineAction": "allow",
                "unknownMethodAction": "allow",
                "knownMethods": [
                    "CONNECT",
                    "DELETE",
                    "GET",
                    "HEAD",
                    "LOCK",
                    "OPTIONS",
                    "POST",
                    "PROPFIND",
                    "PUT",
                    "TRACE",
                    "UNLOCK"
                ]
            },
            "httpProfileTransparentProxy": {
                "class": "HTTP_Profile",
                "proxyType": "transparent",
                "truncatedRedirects": false,
                "maxHeaderSize": 16384,
                "oversizeClientHeaders": "pass-through",
                "oversizeServerHeaders": "pass-through",
                "maxHeaderCount": 32,
                "excessClientHeaders": "pass-through",
                "excessServerHeaders": "pass-through",
                "pipelineAction": "allow",
                "unknownMethodAction": "allow",
                "knownMethods": [
                    "CONNECT",
                    "DELETE",
                    "GET",
                    "HEAD",
                    "LOCK",
                    "OPTIONS",
                    "POST",
                    "PROPFIND",
                    "PUT",
                    "TRACE",
                    "UNLOCK"
                ]
            }
        }
    }
}
```
