### ISSUE TITLE
Feature Request: Support stateless udp service type

### ISSUE THREAD

**Issue by stboch** [F5Networks/f5-appsvcs-extension#642]
Currently we have wasted resources for UDP traffic due to AS3 not supporting the stateless service type. This allows much lower workloads on UDP traffic that does not require the extra features offered by the F5.
[F5 KB Article](https://support.f5.com/csp/article/K13675)

**Comment by sunitharonan** [comment]
Please resubmit this issue using one of the provided templates in order to help us better track your issue.
