### ISSUE TITLE
Support for stateless UDP service type

### ISSUE THREAD

**Issue by stboch** [F5Networks/f5-appsvcs-extension#643]
### Is your feature request related to a problem? Please describe.
Currently we have wasted resources for UDP traffic due to AS3 not supporting the stateless service type. This allows much lower workloads on UDP traffic that does not require the extra features offered by the F5.

### Describe the solution you'd like
Add support for choosing stateless similar to Service_l4

### Describe alternatives you've considered
Currently we have to manage the configuration manually for this virtual server, as and changes to the settings are overwritten when the AS3 is redployed

### Additional context
[F5 KB Article](https://support.f5.com/csp/article/K13675)

**Comment by mdditt2000** [comment]
@stboch please can you reach out to me at automation_toolchain_pm@f5.com so i can understand your use-case and prioritize.

**Comment by mdditt2000** [comment]
Jira Autotool 3444 has been created for PM tracking. Wonder if we could add a boolean property to the Service_UDP class for this.

**Comment by stboch** [comment]
I think the boolean make the most sense all its doing is adding stateless to the virtual server and some of the more advanced features are ignored... so at best case a little of information in the document that XYZ is ignored when defined as stateless.

**Comment by sunitharonan** [comment]
This has been resolved in the 3.40.0 release of AS3.

**Comment by stboch** [comment]
@sunitharonan I does not seem that the change is listed in the 3.40 schema can you please link a reference?

**Comment by RobCupples** [comment]
@stboch It appears this issue was mistakenly recorded in our changelog as being fixed for the 3.40 release instead of the 3.41 release.

@sunitharonan  @mdditt2000 Can you please reopen this issue?  I can fix the changelog but I don't seem to have permission to reopen an issue.

**Comment by sunitharonan** [comment]
Thanks @RobCupples, I have reopened the issue. @stboch once we have 3.41.0 release, we will let you know. Thanks

**Comment by sunitharonan** [comment]
This has been resolved in the 3.41.0 release of AS3.
