### ISSUE TITLE
routeDomain isn't honored-server is placed into default route-domain 

### ISSUE THREAD

**Issue by arturbarczewski** [F5Networks/f5-appsvcs-extension#645]
### Environment
 * Application Services Version: 3.33.0
 * BIG-IP Version:    BIG-IP 15.1.5

### Summary
When i set the routedomain to a route-domain value I expect that the route domain is attached to the pool-member. I use fqdn discovery. The server is placed into the default route-domain instead.

### Steps To Reproduce
Steps to reproduce the behavior: See Json
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "apphosting_commonservices_dev",
        "label": "label apphosting_commonservices_dev",
        "remark": "as3 config from Do 01 Sep 2022 17:06:25 CEST",
        "apphosting_commonservices_dev_git": {
            "class": "Tenant",
            "vip_apps.dev.xxxx.ch_443": {
                "class": "Application",
                "https_apps.dev.xxxx.ch_443": {
                    "class": "Service_HTTP",
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "profileHTTP": {
                        "use": "http_profile_x_forward"
                    },
                    "persistenceMethods": [],
                    "virtualPort": 443,
                    "virtualAddresses": [
                        {
                            "use": "bgpadvertise_apps.dev.xxxx.ch"
                        }
                    ],
                    "maxConnections": 2000000,
                    "rateLimit": 0,
                    "pool": "pool_ottbigscreen_apps.dev.xxxx.ch",
                    "snat": {
                        "bigip": "/Common/snatpool-traffic-group-21"
                    },
                    "iRules": [],
                    "addressTranslationEnabled": true,
                    "portTranslationEnabled": true,
                    "redirect80": false
                },
                "http_profile_x_forward": {
                    "class": "HTTP_Profile",
                    "xForwardedFor": true
                },
                "bgpadvertise_apps.dev.xxxx.ch": {
                    "class": "Service_Address",
                    "routeAdvertisement": "selective",
                    "virtualAddress": "1.1.1.1%2",
                    "trafficGroup": "traffic-group-2",
                    "arpEnabled": false
                },
                "pool_ottbigscreen_apps.dev.xxxx.ch": {
                    "class": "Pool",
                    "monitors": [
                        {
                            "use": "monitor_apps_dev_xxxx_ch_443_ottbigscreen_serverport_80"
                        }
                    ],
                    "loadBalancingMode": "least-connections-member",
                    "minimumMembersActive": 1,
                    "members": [
                        {
                            "addressDiscovery": "fqdn",
                            "hostname": "tvhdmc1-vaph00.stvd02.scstv",
                            "priorityGroup": 5,
                            "ratio": 71,
                            "routeDomain": 2,
                            "shareNodes": false,
                            "servicePort": 80
                        }
                    ]
                },
                "monitor_apps_dev_xxxx_ch_443_ottbigscreen_serverport_80": {
                    "class": "Monitor",
                    "monitorType": "http",
                    "receive": "test",
                    "send": "GET /PingService/Default.aspx"
                }
            }
        }
    }
}
```

2. Observe the following error response:
To proove that the pool member is really in the default partition i checked with tcpdump the self-ip used to monitor the member. And this self-IP belongs to the default route domain.
the screenshot doesn't show any percentage symbol to point to the route domain.
![github-secure](https://user-images.githubusercontent.com/73348645/188140776-cf7abb2f-01ab-44f2-90a0-fce0fde64441.png)

### Expected Behavior
The pool member should be in the route-domain 2.

### Actual Behavior
The pool member in the default  route-domain.

**Comment by dstokesf5** [comment]
Do you see the same behavior with static nodes?

**Comment by arturbarczewski** [comment]
hello 
when i change to static i see the correct route-domain. 
![image](https://user-images.githubusercontent.com/73348645/188809581-ea9d4d0b-e335-41bf-b2c5-fff21d726d16.png)
The reason for the fqdn is that we want to build a SSL connection from F5 to the pool members, so we need the pool-member name.
Artur
"members": [
                        {
                            "addressDiscovery": "static",
                            "priorityGroup": 5,
                            "ratio": 72,
                            "routeDomain": 2,
                            "shareNodes": false,
                            "servicePort": 80,
                            "serverAddresses": [
                                "10.63.234.200%2"
                            ]
                        }

**Comment by sunitharonan** [comment]
Hi @arturbarczewski, please contact us at  automation_toolchain_pm@f5.com so we can prioritize.

**Comment by arturbarczewski** [comment]
hi Suntiha
so can you confirm that this is a bug?
Artur

**Comment by sunitharonan** [comment]
Hi @arturbarczewski, yes it seems to be a bug. I have added this issue to our internal product backlog as AUTOTOOL-3443. Could you please contact us at automation_toolchain_pm@f5.com so we can prioritize.

**Comment by arturbarczewski** [comment]
hi any news on that topic? I blocks us from enhanving our automation
Regards Artur Barczewski

**Comment by sunitharonan** [comment]
Hi @arturbarczewski, this has been resolved in AS341.0 which will be released next week. Thanks.
