### ISSUE TITLE
Burst Handling for BIG-IQ AS3 Templates via API

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-extension#648]
AS3 Burst Handling has been added starting from v3.23 but only includes support for API "/mgmt/shared/appsvcs/declare" and to improve AS3 support for BIG-IQ it is needed for BIG-IQ AS3 Templates as well which uses API "/cm/global/appsvcs-templates".

In an automated environment it would be common to push multiple BIG-IQ AS3 templates via BIG-IQ to the related BIG-IPs. Not having this feature makes BIG-IQ AS3 templates less useful.

### Describe the solution you'd like
BIG-IQ AS3 Templates must have AS3 support for burst handling

### Describe alternatives you've considered
There are no alternatives and not having this feature will deliver failed AS3 deployments when declaring two declarations at the same time.

### Current behavior using API "/cm/global/appsvcs-templates"
1. Deploying two BIG-IQ AS3 templates at nearly the same time
2. BIG-IQ App is not deployed or gets deployed in "Unknown Applications"
3. BIG-IQ App gets deployed into the right "Global App", but the other gets deployed in "Unknown Applications"
4. Deploying a 2nd time things getting deployed correctly

**Comment by sunitharonan** [comment]
Please resubmit the issue using one of the provided issue templates. That helps us better understand and track your issue.

**Comment by gwolfis** [comment]
https://github.com/f5devcentral/f5-big-iq/issues/4
