### ISSUE TITLE
AS3 documentation error - TLS_Server

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-appsvcs-extension#653]
### Summary
Found an error in the AS3 documentation - Appendix A: Schema Reference, for `TLS_Server` object.
LINK: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#tls-server

Following parameters have wrong / misleading Description:
| Parameter | Description |
| ----------- | ------------- |
| tls1_0Enabled (boolean) | Allow TLS 1.0 Ciphers. |
| tls1_1Enabled (boolean) | Allow TLS 1.1 Ciphers. |
| tls1_2Enabled (boolean) | Allow TLS 1.2 Ciphers. |
| tls1_3Enabled (boolean) | Allow TLS 1.3 Ciphers. <omit> |

The correct Description should be:

Allow TLS 1.X **Protocol**.

The ciphers are disabled via different means, within the actual cipher string, with e.g. `!TLSv1:!TLSv1_1`
The above parameters correspond to the SSL protocol "Options" in Big-IP UI.

**Comment by sunitharonan** [comment]
Thank you for reaching out. I have added this issue to our internal product backlog as AUTOTOOL-3475.

**Comment by sunitharonan** [comment]
This has been resolved in the 3.41.0 release of AS3.
