### ISSUE TITLE
Redeploy the configuration of one specific tenant

### ISSUE THREAD

**Issue by cnicolorange** [F5Networks/f5-appsvcs-extension#666]
### Environment
 * Application Services Version: 3.39.0
 * BIG-IP Version: BIG-IP 15.1.5 Build 0.0.10 Final

### Summary
I want to redeploy the configuration of one specific tenant and not of all of them. When I post the redeploy declaration to the URI "<BIG-IP IP address>/mgmt/shared/appsvcs/declare/YLI" it redeploys the configuration of all tenants.

### Steps To Reproduce
1. Submit the following declaration:
I post the following declaration to the URI <BIG-IP IP address>/mgmt/shared/appsvcs/declare/YLI.
```json
{
    "class": "AS3",
    "action": "redeploy",
    "redeployAge": 0
}
```

3. Observe the following error response:
```json
{"results":[{"code":200,"message":"no change","host":"localhost","tenant":"CNI","runTime":509},{"code":200,"message":"success","lineCount":18,"host":"localhost","tenant":"TS2","runTime":1189},{"code":200,"message":"success","lineCount":21,"host":"localhost","tenant":"YLI","runTime":1742},{"code":200,"message":"success","lineCount":22,"host":"localhost","tenant":"US2","runTime":1266},{"code":200,"message":"no change","host":"localhost","tenant":"WS1","runTime":564}]
```

### Expected Behavior
I want to redeploy the configuration of one specific tenant and not of all of them. 

### Actual Behavior
When I post the redeploy declaration to the URI <BIG-IP IP address>/mgmt/shared/appsvcs/declare/YLI it redeploys the configuration of all tenants.
(YLI is the name of the tenant that I want to redeploy)
Is it possible to redeploy the configuration of one specific tenant only?

**Comment by sunitharonan** [comment]
Thank you @cnicolorange. In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com
