### ISSUE TITLE
F5 LTM REFERNCE PROBLEM FOR TLS CLIENT AND SERVER CLIENT

### ISSUE THREAD

**Issue by fekiy2aext** [F5Networks/f5-appsvcs-extension#672]
### Environment
 * Application Services Version: 3.36.0
 * BIG-IP Version: BIG-IP 15.1.0.5 Build 0.0.8 Point Release 5

### Summary
Hi, I am currently working on the automation of F5 LTM. I am having two issues with the TLS_Client and TLS_Server:
 1: I cannot reference an existing TLS_Client or TLS_Server.
 2:  I have to declare TLS_Client and TLS_Server whereas sometimes I only need one of them.

### Steps To Reproduce
1. Submit the following declaration:
{
    "class": "AS3",
    "action": "dry-run",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "controls": {
            "class": "Controls",
            "trace": true,
            "logLevel": "debug"
        },
        "id": "testid",
        "label": "test-label",
        "remark": "partition template",
        "updateMode": "selective",
        "xxxxxxxxxx": {
            "class": "Tenant",
            "xxxx": {
                "class": "Application",
                "template": "generic",
                "xxxxxxx": {
                    "class": "Service_HTTPS",
                    "virtualAddresses": [
                        "10.10.10.10"
                    ],
                    "virtualPort": 443,
                    "profileMultiplex": {
                        "bigip": "/Common/oneconnect"
                    },
                    "serverTLS": "responseadapt_1",
                    "clientTLS":  { "bigip": "/Common/clientssl_no-rc4" },
                    "profileTCP": "normal",
                    "adminState": "disabled",
                    "pool": "adnet_dev_http_pool"
                },
                "adnet_dev_http_pool": {
                    "class": "Pool",
                    "members": [
                        {
                            "servicePort": 80,
                            "addressDiscovery": "static",
                            "adminState": "disable",
                            "servers": [
                                {
                                    "name": "dev-clasuinfsy",
                                    "address": "10.10.10.10"
                                }
                            ]
                        }
                    ]
                },
                "responseadapt_1": {
                    "class": "TLS_Server",
                    "label": "simplest decl requires just cert",
                    "certificates": [
                        {
                            "certificate": "tlsserver_local_cert_1"
                        }
                    ]
                },
                "tlsserver_local_cert_1": {
                    "class": "Certificate",
                    "certificate": {"bigip":"/Common/default.crt"},
                    "privateKey": {"bigip":"/Common/default.key"}
                }
            }
        }
    }
}
```

2. Observe the following error response:
"code": 422,
    "declarationFullId": "",
    "message": "Unable to find /Common/clientssl_no-rc4 for /xxxxxxx/xxxx/xxxxxx/clientTLS"
```

### Expected Behavior
Reference an existing TLS_Client ("clientTLS":  { "bigip": "/Common/clientssl_no-rc4" },)

### Actual Behavior
Cannot find it.

**Comment by RobCupples** [comment]
In order to better match the industry the names TLS_Client and TLS_Server are the opposite of BIGIP terminology which is a common confusion.

TLS_Client is a 'ltm profile server-ssl' and TLS_Server is a 'ltm profile client-ssl'.  Check to see if your serverTLS and clientTLS values are reversed.
