### ISSUE TITLE
Support storageFormat "User-Defined" in Security_Log_Profile_Application_storageFormat

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-appsvcs-extension#673]
### Is your feature request related to a problem? Please describe.

AS3 does not support a user-defined storage format. An Example from the UI is shown in the below image:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1498073/211308243-55619867-b747-4ae5-aed1-7c2aac1c986e.png">

### Describe the solution you'd like

Add support for user-defined format.

### Describe alternatives you've considered

Configuration outside the scope of AS3 is a possible workaround.

### Additional context

User-Defined is a frequently used technique to format WAF logs, hence support would be appreciated.

**Comment by walterk82** [comment]
I think this duplicates #372

**Comment by walterk82** [comment]
I'm going to open an official support case on both of these requests.

**Comment by dstokesf5** [comment]
Have you tried specifying a string instead of an object for the storageFormat property? It looks like that is how it is handled for the Network section of the security log profile, and it might be the same case here.

**Comment by dstokesf5** [comment]
I would like to add that we are aware that the documentation is lacking here and I am trying to determine if any additional work beyond documentation improvements is needed.

**Comment by walterk82** [comment]
The schema indicates:
storageFormat (string | Security_Log_Profile_Application_storageFormat)

I don't think that I realized the "string" in this section of the docs before.

**Comment by walterk82** [comment]
I can confirm that the string option does work for "User-Defined" format.  The closing comments on #372 didn't provide any additional context as to the fix/solution required.  I tried to ask but no reply was sent.

**Comment by simonkowallik** [comment]
@walterk82 @dstokesf5 Thank you both, I can confirm this also!

Using the below in the AS3 declaration:

```json
"storageFormat": "F5-WAF-LOG:attack_type=\"%attack_type%\",date_time=\"%date_time%\"..."
```

results in the below tmconf, as expected:

```tcl
            format {
                type user-defined
                user-string F5-WAF-LOG:attack_type=\"%attack_type%\",date_time=\"%date_time%\"...
            }
```

As you mentioned this is rather a docs issue. The description of `storageFormat` could use a comment about the use of type `string` :-).
