### ISSUE TITLE
iFile creation adds -ifile to any ifile declaration

### ISSUE THREAD

**Issue by MicSkr** [F5Networks/f5-appsvcs-extension#676]
### Environment
 * Application Services Version: 3.36.1
 * BIG-IP Version: 14.1.4

### Summary
Object name is changed to include an undocumented suffix. Adds additional domain specific programming for declaration pipelines.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.36.0/as3-schema.json",
  "class": "AS3",
  "action": "deploy",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.36.0",
    "Common": {
      "class": "Tenant",
      "remark": "Shared Objects",
      "Shared": {
        "class": "Application",
        "template": "shared",
        "site_maintenance": {
          "class": "iFile",
          "iFile": {
            "base64": "U29ycnkhIFVuYXZhaWxhYmxlIGR1ZSB0byBtYWludGVuYW5jZS4gIFBsZWFzZSB0cnkgeW91ciByZXF1ZXN0IGxhdGVyLg=="
          }
        }
      }
    },
    "Site_Maint": {
      "class": "Tenant",
      "Maintenance": {
        "class": "Application",
        "template": "shared",
        "t_site_maintenance": {
          "class": "iFile",
          "iFile": {
            "base64": "U29ycnkhIFVuYXZhaWxhYmxlIGR1ZSB0byBtYWludGVuYW5jZS4gIFBsZWFzZSB0cnkgeW91ciByZXF1ZXN0IGxhdGVyLg=="
          }
        }
      }
    }
  }
}
```

2. Observe the following error response:
n/a

### Expected Behavior
Common Partition iFile should have an iFile in Common/Shared called site_maintenance-ifile
Site_Maint Partition iFile should have an iFile in Site_Maint/Maintenance called t_site_maintenance-ifile

### Actual Behavior
Common Partition iFile should have an iFile in Common/Shared called site_maintenance
Site_Maint Partition iFile should have an iFile in Site_Maint/Maintenance called t_site_maintenance

Please remote -ifile from the created files. Adding suffixes is not documented behavior and creates confusion when training people that the object name is the object name and that pointers in places like iRules should use the object name. 

Thank you

**Comment by MicSkr** [comment]
Causes this error Message without knowing the undocumented knowledge:

https://support.f5.com/csp/article/K75758551

**Comment by MicSkr** [comment]
ACTUALLY... upon further research it **does not** cause this issue:
https://support.f5.com/csp/article/K75758551

More research to understand how this ACTUALLY works...  the irule is referencing site_maintenance but the iFile shows under ifiles as site_maintenance-ifile

Clues?

**Comment by sunitharonan** [comment]
Hi @MicSkr, in order for us to prioritize and add to our backlog, please reach out to us at automation_toolchain_pm@f5.com if you are still looking for a fix.

**Comment by sunitharonan** [comment]
Closing as we haven't heard from you
