### ISSUE TITLE
Can't use x.x.1 schemaVersion accepted by schema that is x.x.1 codified

### ISSUE THREAD

**Issue by MicSkr** [F5Networks/f5-appsvcs-extension#677]
### Environment
 * Application Services Version: 3.36.1
 * BIG-IP Version: 14.1.4

### Summary
Can't use x.x.1 schemaVersion accepted by schema that is x.x.1 codified

Environments that have pipelines that are fed (choose?) the schemas that have a x.x.1 notation can be schema checked properly but can't be used as a consistent value for pipelines like:

1. Drop in the RPM or Monitor the latest AS3 release
2. Monitor device /info for matching schemaVersion or update the device
3. Assert $schema in json declarations
4. Use schemaVersion as fed/chosen in declaration which is accepted by Schema.

Difficult to stay programmatically up to date without codifying additional logic to handle mismatched schema tolerance.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.36.1/as3-schema.json",
  "class": "AS3",
  "action": "deploy",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.36.1",
    "Common": {
      "class": "Tenant",
      "remark": "Shared Objects",
      "Shared": {
        "class": "Application",
        "template": "shared",
        "site_maintenance": {
          "class": "iFile",
          "iFile": {
            "base64": "U29ycnkhIFVuYXZhaWxhYmxlIGR1ZSB0byBtYWludGVuYW5jZS4gIFBsZWFzZSB0cnkgeW91ciByZXF1ZXN0IGxhdGVyLg=="
          }
        }
      }
    }
  }
}
```

2. Observe the following error response:
```json
{
  "code": 422,
  "errors": [
    "/schemaVersion: should be equal to one of the allowed values [\"3.0.0\",\"3.1.0\",\"3.2.0\",\"3.3.0\",\"3.4.0\",\"3.5.0\",\"3.6.0\",\"3.7.0\",\"3.8.0\",\"3.9.0\",\"3.10.0\",\"3.11.0\",\"3.12.0\",\"3.13.0\",\"3.14.0\",\"3.15.0\",\"3.16.0\",\"3.17.0\",\"3.18.0\",\"3.19.0\",\"3.20.0\",\"3.21.0\",\"3.22.0\",\"3.23.0\",\"3.24.0\",\"3.25.0\",\"3.26.0\",\"3.27.0\",\"3.28.0\",\"3.29.0\",\"3.30.0\",\"3.31.0\",\"3.32.0\",\"3.33.0\",\"3.34.0\",\"3.35.0\",\"3.36.0\"]"
  ],
  "declarationFullId": "",
  "message": "declaration is invalid"
}
```

### Expected Behavior
Using a schema version that is accepted by the schema, AS3 engine should permit schemaVersion accepted by schema

### Actual Behavior
Error as noted. Declaration is not processed.

### Fix Idea
Adjust the schema tolerance in engine?
Don't use x.x.? version model?

**Comment by mdditt2000** [comment]
Resolved in AS3.49.0. Please review the release notes and upgrade. Thank you!
