### ISSUE TITLE
Unable to define port/service for VirtualAddresses property

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-appsvcs-extension#685]
### Environment
 * Application Services Version: 3.36.1 LTS
 * BIG-IP Version: 15.1.3

### Summary
I'm running into following issue. Under class `Service_Forwarding`, trying to configure the `VirtualAddresses` property with a destination IP address and `any` port (service). I also need to specify a source IP from which the virtual server will accept traffic.

According to the AS3 schema reference documentation for `VirtualAddresses` property:
*Virtual server will listen to each IP address in list. To accept connections only from certain subnet(s), replace IP address with array [IP-address, accept-from-subnet]. IP address can also be replaced by a reference to a Service_Address.*

I therefore constructed the `VirtualAddress` property as follows:
```
"virtualAddresses": [
    [
    "10.180.1.248%2147",
    "10.180.253.112%2147"
    ]
]
```

This should set the VS destination IP to `10.180.1.248%2147` and the VS source IP to `10.180.253.112%2147`.
The problem is, there is no way to define the destination port (service), which seems to be required by TMOS. So even though the declaration passes the 3.36.1 schema without issues, it produces following error:
```
msg": "declaration failed. \\\"10.180.1.248%2147:undefined\\\" contains invalid or ambiguous service undefined"}
```

There is no specific property under class `Service_Forwarding` for the service (dest port). And if I add the service (port) to the IP address, in the same format as it is done in tmsh and as the error message suggests - `10.180.1.248%2147:any`, declaration fails with this error instead:
```
"msg": "{'code': 422, 'errors': ['/tenant-test/lb-test/vs-test/virtualAddresses/0: should match format \"f5ip\"'], 'declarationFullId': '', 'message': 'declaration is invalid'}"
```

Can you please check and see if this is a bug, and if not, can you please advise how is the `VirtualAddresses` property then supposed to be defined in this case?

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "action": "deploy",
    "class": "AS3",
    "persist": false,
    "declaration": {
        "tenant-test": {
            "class": "Tenant",
            "lb-test": {
                "class": "Application",
                "vs-test": {
                    "class": "Service_Forwarding",
                    "forwardingType": "ip",
                    "addressStatus": false,
                    "profileL4": {
                        "use": "fastl4-test"
                    },
                    "virtualAddresses": [
                        [
                        "10.180.1.248%2147",
                        "10.180.253.112%2147"
                        ]
                    ]
                },
                "fastl4-test": {
                    "class": "L4_Profile",
                    "label": "test-profile"
                }
            }
        },
        "schemaVersion": "3.36.0",
        "updateMode": "selective",
        "id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",
        "label": "For testing",
        "class": "ADC"
    }
}
```

2. Observe the following error response:
```json
{
    "code": 422,
    "message": "declaration failed",
    "response": "10.180.1.248%2147:undefined contains invalid or ambiguous service undefined",
    "host": "localhost",
}
```

### Expected Behavior
The declaration should either accept `10.180.1.248%2147:any` IP:port syntax and the destination IP address should be configured on the Big-IP as such, with destination port "any", or even better, the "any" value should be implicit, if not defined differently. Or there should be explicit property to define the destination port under `Service_Forwarding` class.

### Actual Behavior
Declaration fails with above error.

Thank you very much for looking into this, it is currently a complete blocker for us to be able to go live with a new feature for our customers.

**Comment by m-kratochvil** [comment]
After several hours trying to make this declaration work, and of course after submitting the issue, I decided, I guess from desperation, to try to use the `"virtualPort": "any"` property, which I saw in another service class (`Service_L4`). And guess what, it worked like a charm.

So the only issue here seems to be the `virtualPort` property missing from the `Service_Forwarding` class schema documentation at https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/Service_Forwarding.schema.json.html

**Comment by sunitharonan** [comment]
Hi @m-kratochvil, glad to hear that worked and thank you for letting us know. I will request our team to add virtualPort to the schema documentation.
