### ISSUE TITLE
updated postman collections

### ISSUE THREAD

**Issue by dfs5** [F5Networks/f5-appsvcs-extension#69]
From the latest release notes:
"Renamed the example declarations in the Postman Collection posted to GitHub which makes identifying individual declarations easier"

Where can I find them?

**Comment by JosephPJordan** [comment]
Hi dfs5, the Postman collection is in the dist directory: https://github.com/F5Networks/f5-appsvcs-extension/tree/master/dist/latest.  I'll update the release notes with a link.  Thanks
