### ISSUE TITLE
AS3 configuration GTM sync issue

### ISSUE THREAD

**Issue by noracb** [F5Networks/f5-appsvcs-extension#694]
### Environment
 * Application Services Version: AS3 version 3.34.0 release 4
 * BIG-IP Version: 16.1.2.2

### Summary
Two Big-ip appliances are configured with autosync through sync-group. When using a POST or PATCH API on one of them with as3, the created objects are visible on the GUI of both. However, a GET API returns everything correctly only on the one used for the post/patch APIs, and returns 204 on the other one.

### Steps To Reproduce

1. Submit the following declaration on the first sync-group member:
POST https://xxx/mgmt/shared/appsvcs/declare
```json
{
    "class": "ADC",
    "schemaVersion": "3.25.0",
    "id": "GSLB_Sample",
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "testDataCenter": {
                "class": "GSLB_Data_Center"
            }
        }
    }
}
```

2. Submit the following declaration on both sync-group members:
GET https://xxx/mgmt/shared/appsvcs/declare?show=full

3. Observe different responses:
The API response is correct (200) on the first sync-group member, but it's 204 on the second one.
PATCH APIs only work on the first sync-group member.
All objects can be seen in the GUI of all sync-group members.

### Expected Behavior

It should be possible to use APIs on any of the sync-group members without any difference in the responses.
Objects visible on a member should be visible on all of them, both in the GUI and in the AS3 APIs responses.

### Actual Behavior

It is only possible to write on one member of the sync-group at a time without losing information.
POST APIs on other members overwrite everything on all members, while PATCH APIs only work on the one used for the last POST API.

**Comment by sunitharonan** [comment]
Hi @noracb, please contact us at  automation_toolchain_pm@f5.com so we can prioritize this issue. Thanks.

**Comment by sunitharonan** [comment]
Hi @noracb, thank you for reaching out. I have added this issue to our internal product backlog as AUTOTOOL-3695. We will notify you once it is resolved. Thanks.

**Comment by mdditt2000** [comment]
@noracb cannot reproduce. Awaiting declaration to compare.
