### ISSUE TITLE
Redeploying GSLB servers to add prober pool using as3 removed wide-ip pool members from existing declarations under that gslb servers.

### ISSUE THREAD

**Issue by Sravanthibollu1993** [F5Networks/f5-appsvcs-extension#695]
### Environment
 * Application Services Version:  v3.41.0
 * BIG-IP Version: 15.1.8 

### Summary
Converted existing manually created prober pool into As3 format by removing prober pool reference in gslbserver01 gslb servers. Instead, prober pool selected "inherit from datacenter" (default setting) and clicked on update.
	2. Deleted existing manually created prober pool 
	3. Deployed common-shared.json which creates prober-pool01 and references prober pool to gslbserver01  gslb server.
	
Doing this removed gtm pool members from existing wide-ip declarations. But we can see wide-ip pool members in mgmt/shared/appsvcs/declare/ as3 declaration. We tried Re-deploying the declaration, but even that didn't fix the issue.
	

### Steps To Reproduce
1. Submit the following declaration:
```json
{
"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.34.0/as3-schema.json",
"class": "AS3",
"action": "deploy",
"persist": true,
"declaration": {
  "class": "ADC",
  "schemaVersion": "3.34.0",
  "Common": {
    "class": "Tenant",
    "Shared": {
      "class": "Application",
      "template": "shared",
       "gslbserver01": {
            "class": "GSLB_Server",
                    "dataCenter": {
                      "bigip": "/Common/DC1"
                    },
                    "proberPreferred": "pool",
                    "proberPool": {
                      "use": "prober_pool01"
                    },
                    "devices": [
                      {
                        "label": "ltm-device-01",
                        "address": "x.x.x.x"
                      },
                      {
                        "label": "ltm-device-01",
                        "address": "X.X.X.X"
                      }
                    ],
                    "serverType": "bigip",
                    "virtualServerDiscoveryMode": "enabled-no-delete"
                },
                "prober_pool01": {
                    "class": "GSLB_Prober_Pool",
                    "enabled": true,
                    "members": [
                      {
                        "server": {
                          "use": "Probe-device01"
                        },
                        "memberOrder": 0
                      }
                    ],
                    "lbMode": "global-availability"
                  }  

            }
        }
    }
}
2. Observe the following error response:
```json
{
    "code": 200,
    "message": "success",
}
```

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by mdditt2000** [comment]
@Sravanthibollu1993 can we chat tomorrow or next week. Please contact me at automation_toolchain_pm@f5.com so we can schedule some time. Thanks AS3 PM

**Comment by Sravanthibollu1993** [comment]
@mdditt2000 
I work in split shift and my work timings are 09:30 AM IST to 4:00PM IST and then again 07:00PM IST to 09:30PM IST. Please share me your free slots for Monday. 
So, we can connect on this. 

I have sent an email as well.

**Comment by sunitharonan** [comment]
There is a case for the same issue by customer on salesforce: 00381831. I have created a internal backlog item to work on this issue: AUTOTOOL-3800
