### ISSUE TITLE
selftest folder location wrong

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-appsvcs-extension#7]
##### ISSUE TYPE
 - Documentation Report

##### AS3 BUILD/ VERSION
3.0.0-34

##### BIGIP VERSION
13.1.0.6

##### SUMMARY
http://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/userguide/self-test.html mentions that running selftest uses stuff in located in /var/config/rest/iapps/appsvcs/selftest. That folder doesn't exist on my F5. I show this...

[admin@jgf5-v13-1:Active:Standalone] selftest # pwd
/var/config/rest/iapps/f5-appsvcs/selftest

The difference being that appsvcs has f5- as a prefix.

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
update folder path

##### ACTUAL RESULTS
n/a

**Comment by JosephPJordan** [comment]
Thanks Jeff, this has been corrected as of [Doc Rev 1.3](http://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/revision-history.html)
