### ISSUE TITLE
Rate Class definition with AS3

### ISSUE THREAD

**Issue by bkittler** [F5Networks/f5-appsvcs-extension#700]
### Describe the solution you want
I would like to be able to define Rate Classes directly in my AS3 configuration and thus be able to update the Rate/Ceiling/Burst Size values of each rate class via AS3.

### Describe the alternatives you received
Currently I'm forced to use the GUI (or cli), network ›› Rate Shaping: Rate Class List part of my setup to set the Rate Class and Rate/Ceiling/Burst Size values

### Additional Context
We need to be able to adapt the Rate/Ceiling/Burst Size values of the rate class via AS3 calls in my automation processes.

Thank you for your help

**Comment by mdditt2000** [comment]
@bkittler Rate Shaping is networking and can only be created in /Common -- not /Common/Shared

As rate shaping is a network function it cannot be added to AS3. However we could add this to DO. Are you also using declarative onboarding? Or the alternative is continue to use the UI to determine the rate limiting for the network. Please advise
