### ISSUE TITLE
AS3 not able to configure serverType "generic-host"

### ISSUE THREAD

**Issue by Ronnie110755** [F5Networks/f5-appsvcs-extension#707]
### Environment
 * Application Services Version: 3.43.0
 * BIG-IP Version: 15.1.8

### Summary
I'm preparing an AS3 JSON script in VSCode to deploy a GSLB configuration.
I have taken a fully configured GTM and converted the ucs using ACC.
I ran into this issue while going through the configuration of a Server as a generic host.
It appears that the 'serverType' will not accept "generic-host' as a valid value.
 
### Steps To Reproduce
1. Submit the following declaration:
```json
"rtp-gtm-only-external": {
                    "dataCenter": {
                        "use": "/Common/Shared/RTP"
                    },
                    "devices": [
                        {
                            "address": "1.1.1.2"
                        }
                    ],

                    "proberPool": {
                        "use": "/Common/rtp-prober-pool-psuedo-external"
                    },
                    "proberPreferred": "pool",
                    "serverType": "generic-host",    **<<<---- Here**
```

2. Observe the following error response:

While running my cursor over the highlighted value the message states:  "value must be "bigip"

### Expected Behavior
The GTM configuration expects either 'generic-host" or "bigip" as valid values.  However the AS3 extension does not.
It Should accept "generic-host"
### Actual Behavior
n/a

**Comment by Ronnie110755** [comment]
AND I just noticed that when I change the value for serverType to "bigip" it displays 'value must be "generic-host"
 So, this is definitely a BUG

**Comment by Ronnie110755** [comment]
To further illustrate - the inconsistency appears on only two of the four servers that are reflected in the script.
Showing only two of the 4 - but the issue is illustrated. 


![image](https://user-images.githubusercontent.com/105079353/226990436-ccc00a7a-a359-4969-9db4-981da7b1606d.png)

**Comment by mdditt2000** [comment]
Working on this issue with @Ronnie110755

**Comment by mdditt2000** [comment]
**Note:**    
```
"pathProbeEnabled": false,
"serviceCheckProbeEnabled": false,
"snmpProbeEnabled": false,. 
```

Once removed its fine. Possible ACC logic issue when converting. Sending you a working JSON via email. Chat tomorrow.

**Comment by Ronnie110755** [comment]
> **Note:**
> 
> ```
> "pathProbeEnabled": false,
> "serviceCheckProbeEnabled": false,
> "snmpProbeEnabled": false,. 
> ```
> 
> Once removed its fine. Possible ACC logic issue when converting. Sending you a working JSON via email. Chat tomorrow.

Progressing through the updated JSON - dry runs look good with those parameters removed.

**Comment by mdditt2000** [comment]
Issue resolved and can be closed. Will make improvements in ACC. Defaults not getting converted correctly
