### ISSUE TITLE
High Swap usage and overall memory utilization increased for the management plane on the big-ip devices after upgrading AS3 to Version v3.43.0

### ISSUE THREAD

**Issue by Sravanthibollu1993** [F5Networks/f5-appsvcs-extension#708]
### Environment
 * Application Services Version: 3.43.0
 * BIG-IP Version: 15.1.8

### Summary
After upgrading the AS3 version to 3.43.0, we are seeing a sudden rise in Memory usage on all our Big-IP devices.

There are devices that we don't have traffic running through them, but their memory is suddenly going out of control after we installed this latest AS3 package.

Swap Usage and other subsequent memory utilization for the management plane increased steadily and still it is increasing for the past ten days.

We suspect that there is some sort of memory leak going on, that's why we are seeing this sudden increase in memory usage.

### Steps To Reproduce
1. Download "f5-appsvcs-3.43.0-2.noarch.rpm" file from https://github.com/F5Networks/f5-appsvcs-extension/releases and save it in local.
2. Login to the respective device and Go to iApps  ››  Package Management LX 
3. click on import and choose the rpm file from local and upload it.

2. Observe the following error response:
Swap Usage and other memory usage started increasing after upgrading AS3 to the latest version.

**Comment by mdditt2000** [comment]
@Sravanthibollu1993 was version of AS3 where you upgrading from?

**Comment by Sravanthibollu1993** [comment]
@mdditt2000 - upgraded from V3.38 and only gtm device we have upgraded from V3.41

**Comment by Sravanthibollu1993** [comment]
Raised case with F5. As per F5 -  Swap memory used is slowly increasing before AS3 upgrade. This is explained in the K article below:
K00040553: Swap memory usage keeps increasing after upgrade.

Coming to over all memory usage increment was around 1% which is relatively small and can be safely ignored. 

Hence, closing this issue.
