### ISSUE TITLE
SMTPs profile not created/assigned to virtual server when smtpsStartTLS is set to "require"

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/f5-appsvcs-extension#712]
### Environment
 * Application Services Version: 3.43
 * BIG-IP Version: 15.1.3.1

### Summary
SMTPs profile not created/assigned to virtual server when smtpsStartTLS is set to "require"

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.43.0",
      "id": "123abc",
      "label": "SMTPS Example",
      "remark": "",
 
      "Tenant_Acme": {
        "class": "Tenant",
 
        "acme_smtp_app": {
          "class": "Application",
 
          "acme_smtp_vs": {
            "class": "Service_TCP",
            "virtualAddresses": [
              "10.1.20.13"
            ],
            "virtualPort": 25,
            "pool": "acme_smtp_pool",
            "snat": "self",
            "smtpsStartTLS": "require",
            "serverTLS": {
              "bigip": "/Common/clientssl"
            },
            "clientTLS": {
              "bigip": "/Common/serverssl"
            },
            "persistenceMethods": []
          },
 
          "acme_smtp_pool": {
            "class": "Pool",
            "loadBalancingMode": "round-robin",
            "monitors": [{
              "use": "smtp_monitor"
            }],
 
            "members": [{
              "servicePort": 25,
              "shareNodes": false,
              "serverAddresses": [
                "10.1.10.5"
              ],
              "hostname": "foobar"
            }]
          },
          "smtp_monitor": {
            "class": "Monitor",
            "monitorType": "smtp",
            "interval": 30,
            "timeout": 91,
            "domain": "F5"
          }
        }
      }
    }
 }
```

2. Observe the following error response:
Application gets created, but with no SMTPS profile:
```json
{
    "id": "885d82d8-5e8d-4ef9-b336-703df0db6979",
    "results": [
        {
            "code": 200,
            "message": "success",
            "lineCount": 27,
            "host": "localhost",
            "tenant": "Tenant_Acme",
            "runTime": 890
        }
    ],
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.43.0",
        "id": "123abc",
        "label": "SMTPS Example",
        "remark": "",
        "Tenant_Acme": {
            "class": "Tenant",
            "acme_smtp_app": {
                "class": "Application",
                "acme_smtp_vs": {
                    "class": "Service_TCP",
                    "virtualAddresses": [
                        "10.1.20.13"
                    ],
                    "virtualPort": 25,
                    "pool": "acme_smtp_pool",
                    "snat": "self",
                    "smtpsStartTLS": "require",
                    "serverTLS": {
                        "bigip": "/Common/clientssl"
                    },
                    "clientTLS": {
                        "bigip": "/Common/serverssl"
                    },
                    "persistenceMethods": []
                },
                "acme_smtp_pool": {
                    "class": "Pool",
                    "loadBalancingMode": "round-robin",
                    "monitors": [
                        {
                            "use": "smtp_monitor"
                        }
                    ],
                    "members": [
                        {
                            "servicePort": 25,
                            "shareNodes": false,
                            "serverAddresses": [
                                "10.1.10.5"
                            ],
                            "hostname": "foobar"
                        }
                    ]
                },
                "smtp_monitor": {
                    "class": "Monitor",
                    "monitorType": "smtp",
                    "interval": 30,
                    "timeout": 91,
                    "domain": "F5"
                }
            }
        },
        "updateMode": "selective",
        "controls": {
            "archiveTimestamp": "2023-03-28T14:36:35.957Z"
        }
    }
}
```
BUT virtual server does not have SMTPs profile assigned:
tmsh list ltm virtual /Tenant_Acme/acme_smtp_app/acme_smtp_vs all-properties
ltm virtual /Tenant_Acme/acme_smtp_app/acme_smtp_vs {
    address-status yes
    app-cloud-security-services none
    app-service none
    auth none
    auto-lasthop default
    bwc-policy none
    clone-pools none
    cmp-enabled yes
    connection-limit 0
    creation-time 2023-03-28:07:36:35
    description acme_smtp_app
    destination /Tenant_Acme/10.1.20.13:smtp
    enabled
    ephemeral-auth-access-config none
    eviction-protected disabled
    fallback-persistence none
    flow-eviction-policy none
    gtm-score 0
    ip-protocol tcp
    last-hop-pool none
    last-modified-time 2023-03-28:07:36:35
    mask 255.255.255.255
    metadata none
    mirror disabled
    mobile-app-tunnel disabled
    nat64 disabled
    parent-name none
    partition Tenant_Acme
    per-flow-request-access-policy none
    persist none
    policies none
    pool /Tenant_Acme/acme_smtp_app/acme_smtp_pool
    profiles {
        clientssl {
            context clientside
        }
        f5-tcp-progressive {
            context all
        }
        serverssl {
            context serverside
        }
    }
    rate-class none
    rate-limit disabled
    rate-limit-dst-mask 0
    rate-limit-mode object
    rate-limit-src-mask 0
    related-rules none
    rules none
    security-log-profiles none
    serverssl-use-sni disabled
    service-down-immediate-action none
    service-policy none
    source 0.0.0.0/0
    source-address-translation {
        pool /Tenant_Acme/acme_smtp_app/acme_smtp_vs-self
        type snat
    }
    source-port preserve
    syn-cookie-status not-activated
    traffic-classes none
    traffic-matching-criteria none
    translate-address enabled
    translate-port enabled
    transparent-nexthop none
    urldb-feed-policy none
    vlans none
    vlans-disabled
    vs-index 34
}

### Expected Behavior
SMTPS profile with startTLS Action Mode = require

### Actual Behavior
SMTPS profile with startTLS Action Mode = require is not happening

**Comment by pedley-f5** [comment]
I realized that I really should not define a clientTLS (serverssl) for this configuration, so I resubmitted it without the clientTLS block, but got the same results (no smtps profile is assigned).
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.43.0",
      "id": "123abc",
      "label": "SMTPS Example",
      "remark": "",
 
      "Tenant_Acme": {
        "class": "Tenant",
 
        "acme_smtp_app": {
          "class": "Application",
 
          "acme_smtp_vs": {
            "class": "Service_TCP",
            "virtualAddresses": [
              "10.1.20.13"
            ],
            "virtualPort": 25,
            "pool": "acme_smtp_pool",
            "snat": "self",
            "smtpsStartTLS": "require",
            "serverTLS": {
              "bigip": "/Common/clientssl"
            },
            "persistenceMethods": []
          },
 
          "acme_smtp_pool": {
            "class": "Pool",
            "loadBalancingMode": "round-robin",
            "monitors": [{
              "use": "smtp_monitor"
            }],
 
            "members": [{
              "servicePort": 25,
              "shareNodes": false,
              "serverAddresses": [
                "10.1.10.5"
              ],
              "hostname": "foobar"
            }]
          },
          "smtp_monitor": {
            "class": "Monitor",
            "monitorType": "smtp",
            "interval": 30,
            "timeout": 91,
            "domain": "F5"
          }
        }
      }
    }
 }

**Comment by sunitharonan** [comment]
Thank you @pedley-f5. I have added this issue to our internal product backlog as AUTOTOOL-3789. In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com

**Comment by pedley-f5** [comment]
Apparently I was adding the "smtpsStartTLS": "require", in Service_TCP when it really should have been added in TLS_Server. That changes my declaration which apparently works. I'll need to dig more over the next couple days to see if this aligns with what the customer needs:

{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.43.0",
      "id": "123abc",
      "label": "SMTPS Example",
      "remark": "",
 
      "Tenant_Acme": {
        "class": "Tenant",
 
        "acme_smtp_app": {
          "class": "Application",
 
          "acme_smtp_vs": {
            "class": "Service_TCP",
            "virtualAddresses": [
              "10.1.20.13"
            ],
            "virtualPort": 25,
            "pool": "acme_smtp_pool",
            "snat": "self",
            "serverTLS": "acme_smtp_tls",
            "persistenceMethods": []
          },
          "acme_smtp_tls": {
            "class": "TLS_Server",
            "certificates": [
              {
                "certificate": "acme_smtp_cert"
              }
            ],
          "smtpsStartTLS": "require"
          },
          "acme_smtp_cert": {
            "class": "Certificate",
            "certificate": { "bigip": "/Common/default.crt"},
            "privateKey": { "bigip": "/Common/default.key"}
          },
          "acme_smtp_pool": {
            "class": "Pool",
            "loadBalancingMode": "round-robin",
            "monitors": [{
              "use": "smtp_monitor"
            }],
 
            "members": [{
              "servicePort": 25,
              "shareNodes": false,
              "serverAddresses": [
                "10.1.10.5"
              ],
              "hostname": "foobar"
            }]
          },
          "smtp_monitor": {
            "class": "Monitor",
            "monitorType": "smtp",
            "interval": 30,
            "timeout": 91,
            "domain": "F5"
          }
        }
      }
    }
 }
