### ISSUE TITLE
Cant associate websocket profiles directly to a virtual server 

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-appsvcs-extension#713]
# Environment
 * Application Services Version: 3.44.0
 * BIG-IP Version: 15.1.x

### Summary
In AS3 schema, you cannot attach a websocket profile directly to a virtual server. Instead, you must attach the websocket profile to the HTTP profile. 

### Steps To Reproduce
1. Websocket profile can be authored in AS3 schema with this class: 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#websocket-profile 

2. Virtual server class service_HTTPS cannot reference the authored websocket profile:  
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-https

### Expected Behavior
The ability to reference a websocket profile from a virtual server class service_HTTPS. This is how TMOS refers to websocket profiles. We requested this behavior in issue #638 but for some reason the websocket reference was added to HTTP profile instead. 

### Actual Behavior
Websocket profile is referenced by HTTP profile which then gets attached to a virtual server. 

Doing it this way, the customer would need to create duplicate HTTP profiles pointing to multiple different websocket profiles in order to assign different websocket profiles to different virtual servers.

**Comment by sunitharonan** [comment]
We already have a similar request and will be prioritizing it in upcoming sprints. Here is the internal product backlog jira id AUTOTOOL-3753

**Comment by sunitharonan** [comment]
This has been resolved in AS3 3.45.
