### ISSUE TITLE
DNS_Zone reverse zone names fails

### ISSUE THREAD

**Issue by schld** [F5Networks/f5-appsvcs-extension#719]
### Environment
 * Application Services Version: 3.44.0
 * BIG-IP Version: 16.1.3.4

### Summary
DNS_Zone reverse zone names (like 2.0.192.in-addr.arpa and 3.3.3.3.2.2.2.2.1.1.1.1.ip6.arpa) are considered invalid. Reproducibility is every time and it means we can't include any reverse zones in our declaration.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.44.0/as3-schema.json",
    "action": "dry-run",
    "declaration": {
        "class": "ADC",
        "updateMode": "selective",
        "schemaVersion": "3.44.0",
        "id": "DNS",
        "Sample_non_http_03": {
            "class": "Tenant",
            "TEST_DNS_Zone": {
                "class": "Application",
                "2.0.192.in-addr.arpa": {
                    "class": "DNS_Zone"
                },
                "3.3.3.3.2.2.2.2.1.1.1.1.ip6.arpa": {
                    "class": "DNS_Zone"
                }
            }
        }
    }
}
```

2. Observe the following error response:
```json
{
    "code": 422,
    "errors": [
        "/Sample_non_http_03/TEST_DNS_Zone: propertyName \"2.0.192.in-addr.arpa\" should match pattern \"^[A-Za-z]([0-9A-Za-z_.-]{0,188}[0-9A-Za-z_.])?$\""
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

### Expected Behavior
Create two DNS zones named 2.0.192.in-addr.arpa and 3.3.3.3.2.2.2.2.1.1.1.1.ip6.arpa

### Actual Behavior
Declaration is considered invalid since reverse zones don't match regexp ^[A-Za-z]([0-9A-Za-z_.-]{0,188}[0-9A-Za-z_.])?$

**Comment by sunitharonan** [comment]
Hi @schld,
AUTOTOOL-3816 has been created and added to our internal product backlog. In order to prioritize, please reach out to us at automation_toolchain_pm@f5.com so we can prioritize.
