### ISSUE TITLE
Additional property of pool member monitor logging

### ISSUE THREAD

**Issue by russellmilliner** [F5Networks/f5-appsvcs-extension#72]
##### ISSUE TYPE
 - Enhancement

##### AS3 BUILD/ VERSION
```
3.9.0
```

##### BIGIP VERSION
```
3.1.1.4
```

##### SUMMARY
```
Checkbox for "Monitor Logging" in a pool member settings is not available
```

##### EXPECTED RESULTS
```
Expect to be able to set this to true/false
```

##### ACTUAL RESULTS
```
Field currently unavailable
```

**Comment by kaustriaf5** [comment]
Thanks @russellmilliner, we are tracking this as 939

**Comment by dstokesf5** [comment]
This issue was lost in a tracker migration. I have re-added it to our internal product backlog as AUTOTOOL-1992.
