### ISSUE TITLE
Pool declared in /<Tenant name>/Shared can't be reused by other declarations in the same tenant. 

### ISSUE THREAD

**Issue by Nikoolayy1** [F5Networks/f5-appsvcs-extension#720]
Environment

    Application Services Version: 3.44.0-3
    BIG-IP Version: 15.1.8

Summary

Pool declared in /<Tenant name>/Shared can't be used by other declarations in the same tenant. The issue is similar to the one in https://github.com/F5Networks/f5-appsvcs-extension/issues/443 that is resolved when declaring the pool in /Common/Shared.

Steps To Reproduce

###    1. Declare pool in /<Partition>/Shared

{
    "class": "ADC",
    "schemaVersion": "3.24.0",
    "updateMode": "selective",
    "Partition1": {
        "class": "Tenant",
        "Shared": { 
            "class": "Application",
            "template": "shared",
            "my_pool": {
                "class": "Pool",
                "members": [
                    {
                        "servicePort": 80,
                        "serverAddresses": [
                            "10.10.10.11"
                        ]
                    }
                ]
            }
        }
    }
}

###      2. Try using the declared pool in another declaration in the same partition/tenant.

{
	"class": "ADC",
	"schemaVersion": "3.24.0",
	"updateMode": "selective",
	"Partition1": {
		"class": "Tenant",
		"my_app": {
			"class": "Application",
			"template": "generic",
			"my_vs": {
				"virtualAddresses": [
					"2.2.2.2"
				],
				"virtualPort": 80,
				"class": "Service_HTTP",
				"pool": {
					"use": "/Partition1/Shared/my_pool"
				}
			}
		}
	}
}

###    3. Observe the error

{
    "id": "a717f3f8-791f-4e3d-aced-a22832e40169",
    "results": [
        {
            "code": 422,
            "errors": [
                "/Partition1/A1/service/pool/use: contains path to non-existent object Shared"
            ],
            "declarationFullId": "",
            "message": "declaration is invalid"
        }
    ],
    "declaration": {}
}

_**Expected Behavior:**_

When declaring a pool in a tenant in the Shared folder, the pool should be available to use in other declarations that use the same Partition/Tenant. 

It is written "Normally you may only reference resources you define within any Application with other resources within the same Application. However, if you define an Application named Shared within any Tenant, then you can reference the resources it contains with objects in other Applications within the same Tenant. You may optionally define an Application named /Common/Shared and then you can reference resources it contains from all Applications in the declaration." in https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/declaration-purpose-function.html 

I think this will be really usefull when we create pools in tenant that don't use the default route domain of 0 ( "defaultRouteDomain": 0 as seen in https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html ) as then we will need to use the /tenant/Shared to reuse the pool not /Common/Shared

**Comment by sunitharonan** [comment]
HI @Nikoolayy1,
AUTOTOOL-3823 has been created and added to our internal product backlog. In order to prioritize and work, please reach out to us at automation_toolchain_pm@f5.com so we can prioritize.
