### ISSUE TITLE
member health monitor inherit from pool 

### ISSUE THREAD

**Issue by rduchez** [F5Networks/f5-appsvcs-extension#734]
Current behavior when creating an application is that the health monitor is assigned directly to the the pool member.  As a result any change (for testing or otf) of the pool monitoring has no effect on the pool members.  

Can a flag be set for the pool members to inherit the monitor from the pool instead? 

Thank you.

**Comment by sunitharonan** [comment]
Please resubmit this issue using one of the provided templates in order to help us better track your issue.
