### ISSUE TITLE
f5-service-discovery not cleaning up rpm-tmp files in /var/tmp

### ISSUE THREAD

**Issue by logicfoo** [F5Networks/f5-appsvcs-extension#735]
### Environment
 * Application Services Version: 3.43
 * BIG-IP Version: 15.1.8

### Summary
The f5-service-discovery component is placing rpm-tmp* files in the /var/tmp directory daily, consuming excessive disk space. We are not sure what triggers the rpm-tmp files to be generated.

### Steps To Reproduce
1. Install F5 AS3 on an LTM
2. Wait a day or so
3. Login to CLI
4. cd /var/tmp
5. ls -l rpm-tmp*
6. strings <rpm-tmp filename> to observe that these are associated with f5-service-discovery
#!/bin/sh
  RPM_SOURCE_DIR="/var/config/rest/node/tmp/SOURCES"
  RPM_BUILD_DIR="/var/config/rest/node/tmp/BUILD"
  RPM_OPT_FLAGS="-O2 -g"
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/local/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="f5-service-discovery"
  RPM_PACKAGE_VERSION="1.12.0"
  RPM_PACKAGE_RELEASE="1"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/var/config/rest/node/tmp/BUILDROOT/f5-service-discovery-1.12.0-1.x86_64"
  export RPM_BUILD_ROOT
  PKG_CONFIG_PATH="%{_PKG_CONFIG_PATH}:/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig"
  export PKG_CONFIG_PATH
  set -x
  umask 022
  cd "/var/config/rest/node/tmp/BUILD"
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/var/config/rest/iapps/f5-service-discovery
# install all resources
cp -rf $RPM_BUILD_DIR/f5-service-discovery/* $RPM_BUILD_ROOT/var/config/rest/iapps/f5-service-discovery
    
    
    
    /usr/local/lib/rpm/brp-compress 
    /usr/local/lib/rpm/brp-strip /usr/bin/strip 
    /usr/local/lib/rpm/brp-strip-static-archive /usr/bin/strip 
    /usr/local/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump 

### Expected Behavior
Internal processes should clean these files up on their own to ensure minimal disk usage.

### Actual Behavior
These seem to be generated daily and never cleaned up.

**Comment by logicfoo** [comment]
For additional context, I wanted to provide the case number that we had associated with this as well: F5 Case 00316609.

**Comment by sunitharonan** [comment]
Thanks @logicfoo for reaching out. In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com
