### ISSUE TITLE
Source Port option is limited to PEM - Needs to be available on service level

### ISSUE THREAD

**Issue by jrooty** [F5Networks/f5-appsvcs-extension#737]
On the VS object, the option `Source Port` seems to be not available on AS3, service level. 

The option appears only inside `Enforcement_Forwarding_Endpoint`, which requires the PEM module. 

According the schema reference :

```
sourcePortAction (string) | “preserve” | “change”, “preserve”, “preserve-strict” | Specifies whether the system preserves the source port of the connection
```

Could you please confirm that option (`Source Port`) is not available for regular VS/service (fastl4, ...) ? 

If not, is it possible to add the support of this option ?

Thank you.

**Comment by RobCupples** [comment]
The property "translateClientPort" might be what you are looking for which can hold the values of true, false or one of the string values "change", "preserve", or "preserve-strict".  This maps to the "source-port" property of a "ltm virtual".

**Comment by jrooty** [comment]
@RobCupples 
It was what I was looking for. Thank you for assistance.
