### ISSUE TITLE
Update example declarations to run directly

### ISSUE THREAD

**Issue by ansmithf5** [F5Networks/f5-appsvcs-extension#74]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE
 - Documentation Report

##### AS3 BUILD/ VERSION
N/A

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.3
  Build       0.0.1
  Edition     Point Release 3
  Date        Wed Nov 28 18:50:45 PST 2018
```

##### SUMMARY

Investigate and update the following examples in docs:

1.	example-endpoint-policy-ssl-sni-match-with-http-action.json
    * TASK: Update the example to create the shared pool sni1 and sni2.
    * See https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/http-services.html#two-applications-sharing-a-pool for example on sharing a pool. It 
2.	example-enable-disable-server-ssl-via-endpoint-policies.json
    * TASK: The example is using "type": "serverSsl" but it does not seem to be a correct value.
    * The response from Big-IQ/AS3 indicates that serverSsl is not an accepted value.
    * `{"status": 422, "response": {"message": "declaration is invalid", "code": 422, "errors": ["/Sample_cert_05/Application/testItem/rules/0/actions/0/type: should be equal to one of the allowed values [\"http\",\"httpCookie\",\"httpHeader\",\"httpRedirect\",\"httpUri\",\"waf\",\"forward\",\"drop\",\"clientSsl\"]"], "declarationFullId": ""}}`
3.	example-using-rewrite-profile.json
    * TASK: Update this declaration to make it work with a valid cert/key.
    * Similar example: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/http-services.html#http-and-https-virtual-services-in-one-declaration
4.	example-external-monitor.json
    * TASK: Create/find an external monitor script.
    * External monitors can use a script when running, in the example declaration. There is just a stand in script. I believe Big-IQ is looking for a script they can use/reference in their testing so the declaration passes.
5.	example-matchtosni-with-tls-server-profile.json
    * TASK: Update the VIP from from "192.**0**2.2.19" to  "192.2.2.19".
    * The 02 causes a failure in validation.
    * TASK 2: Update this declaration to make it work with a valid cert/key.
    * Similar example: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/http-services.html#http-and-https-virtual-services-in-one-declaration

6.	example-client-and-server-tls-profile-in-one-declaration.json
    * TASK: Review the declaration and the notes for #7 and #8 in docs/declarations/tls-encryption.rst. The .rst should reflect the values in the declaration.

##### EXPECTED RESULTS

It is expected that each of the declarations should be able to run as their own declarations.

##### ACTUAL RESULTS
Most of these tasks fail. See below:
1.
```json
{"status": 422, "response": {"results": [{"code": 422, "message": "Failed to send declaration: status:422, body:{\"code\":422,\"errors\":[\"/Sample_app_sec_04/Application/test1/rules/0/actions/0/select/pool: requested component /Common/sni1 does not exist\"],\"declarationFullId\":\"\",\"message\":\"declaration is invalid\"}", "runTime": 7560, "host": "localhost", "tenant": "Sample_app_sec_04"}], "declaration": {"updateMode": "selective", "target": {"hostname": "ranju1.f5net.com"}, "controls": {"archiveTimestamp": "2019-03-12T17:30:40.228Z"}, "class": "ADC", "schemaVersion": "3.8.0", "id": "Endpoint_Policy"}}}
```
2.
```json
{"status": 422, "response": {"message": "declaration is invalid", "code": 422, "errors": ["/Sample_cert_05/Application/testItem/rules/0/actions/0/type: should be equal to one of the allowed values [\"http\",\"httpCookie\",\"httpHeader\",\"httpRedirect\",\"httpUri\",\"waf\",\"forward\",\"drop\",\"clientSsl\"]"], "declarationFullId": ""}}
```
3.
```json
{"status": 422, "response": {"results": [{"code": 422, "message": "Failed to update BIG-IQ applications: cm/global/config-sets/a2024161-fbae-3d0b-88b3-d487c9bcd5af: cm/global/config-sets/a2024161-fbae-3d0b-88b3-d487c9bcd5af", "runTime": 548, "host": "localhost", "tenant": "Sample_profile_06"}], "declaration": {"updateMode": "selective", "target": {"hostname": "ranju1.f5net.com"}, "controls": {"archiveTimestamp": "2019-03-12T17:36:13.569Z"}, "id": "TEST_Rewrite_Profile", "Sample_profile_06": {"Application": {"testItem": {"insertAgeHeaderEnabled": false, "maximumAge": 100000, "agingRate": 5, "maximumEntries": 200000, "parentProfile": {"use": "/Sample_profile_06/Application/accel"}, "uriIncludeOverrideList": ["1.1.2.2", "1.2.3.4"], "maximumObjectSize": 300000, "class": "HTTP_Acceleration_Profile", "ignoreHeaders": "none", "metadataMaxSize": 30, "cacheSize": 200, "uriPinnedList": ["///"], "minimumObjectSize": 1000, "uriIncludeList": ["www.google.com"], "uriExcludeList": ["."]}, "http_accel": {"enable": true, "translateServerAddress": true, "persistenceMethods": ["cookie"], "profileHTTPAcceleration": {"use": "/Sample_profile_06/Application/testItem"}, "virtualAddresses": ["1.2.3.4"], "profileHTTP": "basic", "mirroring": "none", "translateClientPort": false, "lastHop": "default", "maxConnections": 0, "translateServerPort": true, "virtualPort": 80, "profileTCP": "normal", "layer4": "tcp", "snat": "auto", "class": "Service_HTTP", "addressStatus": true}, "accel": {"insertAgeHeaderEnabled": true, "maximumAge": 3600, "agingRate": 9, "maximumEntries": 10000, "parentProfile": {"bigip": "/Common/webacceleration"}, "maximumObjectSize": 50000, "ignoreHeaders": "all", "metadataMaxSize": 25, "cacheSize": 100, "minimumObjectSize": 500, "class": "HTTP_Acceleration_Profile"}, "schemaOverlay": "default", "enable": true, "template": "generic", "class": "Application"}, "optimisticLockKey": "", "enable": true, "defaultRouteDomain": 0, "class": "Tenant"}, "schemaVersion": "3.0.0", "class": "ADC"}}}
```
4.
```json
{"status": 422, "response": {"message": "declaration is invalid", "code": 422, "errors": ["/Sample_monitor_03/Monitors/mNewExternalMonitorFile/script: Unable to fetch value. GET https://example.com/monitor.sh for /Sample_monitor_03/Monitors/mNewExternalMonitorFile/script response=404 body=<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 50px;\n        background-color: #fff;\n        border-radius: 1em;\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        body {\n            background-color: #fff;\n        }\n        div {\n            width: auto;\n            margin: 0 auto;\n            border-radius: 0;\n            padding: 1em;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.</p>\n    <p><a href=\"http://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n"], "declarationFullId": ""}}
```
5. 
```json
{"status": 422, "response": {"message": "declaration is invalid", "code": 422, "errors": ["/Sample_cert_03/A1/serviceMain/virtualAddresses/0: should match format \"f5ip\""], "declarationFullId": ""}}
```

**Comment by kaustriaf5** [comment]
Tracked internally as 952.

**Comment by dstokesf5** [comment]
Re-added to our internal product backlog as AUTOTOOL-1993.
