### ISSUE TITLE
AS3 declarations can become incorrect and fail to function after an upgrade if a feature was deprecated

### ISSUE THREAD

**Issue by nwehrman** [F5Networks/f5-appsvcs-extension#748]
### Environment
 * Application Services Version: Any
 * BIG-IP Version: 13.X and then upgrade to 14.X or newer

### Summary
In this scenario SSLv2 was deprecated in v14+. So if you upgrade from v13.x to 14.x+ then run a GET to the /declare endpoint to pull the declaration it will contain whatever was posted in v13 even if those objects are no longer configured on the device or valid. I'm using SSLv2 as an example but it's not uncommon for features to become deprecated on upgrade and AS3 should clean things up so that the declaration matches the device configuration.

### Steps To Reproduce
1. Submit the following declaration on version 13.X
```json
{
 "class": "AS3",
 "action": "deploy",
 "persist": true,
 "trace": true,
 "traceResponse": true,
 "id": "InitialDeclare",
 "declaration": {
  "class": "ADC",
  "schemaVersion": "3.0.0",
  "label": "AS3 Declaration",
  "id": "autogen_56af37fe-ca5e-483c-abab-02778266044d",
  "Common": {
    "class": "Tenant",
    "Shared": {
      "class": "Application",
      "template": "shared",
      "NEW_CIPHER_RULE": {
        "class": "Cipher_Rule",
        "cipherSuites": [
          "!TLSv1_1",
          "!TLSv1_2",
          "ECDHE-RSA-AES256-GCM-SHA384",
          "!ADH",
          "!LOW",
          "!DES",
          "!SSlv2",
          "!MD5",
          "!EXP",
          "!DH"
        ],
        "label": "Desjardins N3 Server Cipher Rule"
      }
    }
  }
}
```

2. Run tmsh save sys config
3.  Upgrade the device to 14.X or newer
4. Run GET to /declare endpoint
5. Observe that !SSLv2 still exists
6. However, !SSLv2 will NOT exist within the configuration or bigip.conf file
7. Attempts to POST this configuration again will fail because SSLv2 isn't valid in v14.X or newer ( ID 811333 cleans it up because it was removed)

### Expected Behavior
AS3 declarations should function on the version they were requested from. Upgrading the configuration on the device shouldn't invalidate declarations without correcting them.

### Actual Behavior
Attempts to re-use the declaration attained from the device will fail.

**Comment by nwehrman** [comment]
Something to note: We do update declarations already. In this same example after upgrading to a newer version when you run a GET to pull down the declaration it adds "tsl1_3Enabled": false (default on newer versions that support it). However, we don't seem to remove the deprecated feature of SSLv2.

**Comment by sunitharonan** [comment]
Thanks @nwehrman, in order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com

**Comment by mdditt2000** [comment]
I raised this issue on github and someone asked me to drop an email here.  Let me know what I can do to help explain the situation
 
https://github.com/F5Networks/f5-appsvcs-extension/issues/748#issuecomment-1692067368
 
Thanks,
 
Nathan Wehrman – Sr ENE
F5 Networks

**Comment by sunitharonan** [comment]
We think it is not do-able at this moment and closing it. Sent more information to the customer.
