### ISSUE TITLE
Unable to set "SSL Handshake Timeout" for TLS_Server class AS3

### ISSUE THREAD

**Issue by grmenon** [F5Networks/f5-appsvcs-extension#756]
### Is your feature request related to a problem? Please describe.
In AS3, the "TLS_Server" class is missing the property "Handshake Timeout".  This property is available in the GUI. I need this property to increase the timeout.

### Describe the solution you'd like
Add property in the AS3 schema.

### Describe alternatives you've considered
No alternative available. Setting the parameter in GUI will get overwritten with the next run/deploy of AS3.

### Additional context
N/A

**Comment by sunitharonan** [comment]
Thank you for reaching out.  In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com

**Comment by sunitharonan** [comment]
AUTOTOOL-4059 is created for internal tracking.

**Comment by sunitharonan** [comment]
This has been done in AS3 3.49
