### ISSUE TITLE
Update Pool Schema to correctly describe Priority Group Activation attribute

### ISSUE THREAD

**Issue by retryW** [F5Networks/f5-appsvcs-extension#757]
### Is your feature request related to a problem? Please describe.
Currently the AS3 Schema has an underwhelming/misleading description for the `minimumMembersActive` attribute of the Pool object, as well as different defaults to the Big-IP UI, which is not mentioned.

As seen in the schema [here](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pool:~:text=minimumMembersActive), the Pool object attribute `minimumMembersActive` has a description that reads "Pool is down when fewer than this number of members are up". This description fails to mention that this is in fact the configuration for "Priority Group Activation", and that a setting of 0 disables the feature. 

This attribute also has a default value of `1` in AS3, but defaults to `disabled` when creating a pool in the Big-IP UI. In addition, the Pool_Member object still has a default value of `0` for attribute `priorityGroup` [link](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pool-member:~:text=priorityGroup) in AS3, which means it's not part of a priority group/has no priority.

### Describe the solution you'd like
The description for the `minimumMembersActive` attribute on the Pool object should correctly describe it's use in disabling or configuring Priority Group Activation.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by sunitharonan** [comment]
Thank you for reaching out.  In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com

**Comment by SScales** [comment]
I also find this misleading
