### ISSUE TITLE
Declaration can't reference /Common/serverssl object

### ISSUE THREAD

**Issue by bgekhtman** [F5Networks/f5-appsvcs-extension#76]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

12.1.4

##### SUMMARY

Sample declaration mention "ServerTLS" / Common/serverssl profile, however I am getting response that component does not exist. All other objects in /Common like /Common/clientssl processed fine. Other server ssl profiles are not working as well

##### STEPS TO REPRODUCE
Run the declaration
```json
{
	"class": "AS3",
	"action": "deploy",
	"persist": true,
	"declaration": {
		"class": "ADC",
		"schemaVersion": "3.9.0",
		"id": "Export_Date:_03-20-2019_09:32:12",
		"target": {
			"hostname": "10.1.1.4"
		},
		"AS3_Exports": {
			"class": "Tenant",
			"defaultRouteDomain": 0,
			"test1": {
				"class": "Application",
				"template": "https",
				"serviceMain": {
					"class": "Service_HTTPS",
					"remark": "test-1 - none",
					"virtualPort": 443,
					"virtualAddresses": ["1.1.1.1"],
					"redirect80": false,
					"pool": "test",
					"profileTCP": {
						"egress": "wan",
						"ingress": {
							"bigip": "/Common/tcp"
						}
					},
					"profileHTTP": {
						"bigip": "/Common/http"
					},
					"persistenceMethods": [],
					"clientTLS": {
						"bigip": "/Common/clientssl"
					},
					"serverTLS": {
						"bigip": "/Common/serverssl"
					},
					"snat": "none",
					"iRules": [],
					"policyWAF": {
						"bigip": "/Common/policy"
					},
					"securityLogProfiles": [{
							"bigip": "/Common/none"
						}
					]
				},
				"test": {
					"class": "Pool",
					"monitors": ["icmp"],
					"reselectTries": 0,
					"loadBalancingMode": "round-robin",
					"serviceDownAction": "none",
					"members": [{
							"servicePort": 3,
							"serverAddresses": ["5.5.5.5"]
						}
					]
				}
			}
		}
	}
}
```
##### EXPECTED RESULTS

```json
{
    "code": 422,
    "errors": [
        "/AS3_Exports/test1/serviceMain/serverTLS: requested component /Common/serverssl does not exist"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

##### ACTUAL RESULTS
```json
{
    "code": 422,
    "errors": [
        "/AS3_Exports/test1/serviceMain/serverTLS: requested component /Common/serverssl does not exist"
    ],
    "declarationFullId": "",
    "message": "declaration is invalid"
}
```

**Comment by JosephPJordan** [comment]
Hello bgekhtman,
  You are running into a difference between naming conventions in AS3 and BIG-IP configuration that can be a little confusing.  Essentially a "TLS_Server" in AS3 creates a "Client SSL" profile on the BIG-IP system (TLS server parameters are for connections arriving to BIG-IP).  TLS_Client creates a Server SSL profile (TLS client parameters are for connections leaving the BIG-IP).  

While this is briefly mentioned in the documentation in the examples section and in the schema reference (ie https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html?highlight=clienttls#service-http-clienttls), it is not very clear.  We will update the documentation to better explain these differences.

In the example declaration you posted above, if you swap ClientTLS and ServerTLS, your declaration will succeed.

**Comment by kaustriaf5** [comment]
Documentation update task tracked internally as 958.

**Comment by JosephPJordan** [comment]
Hello @bgekhtman, we added an FAQ entry for this issue: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html#tlsserver to help clarify this.  Going to close this issue, thanks for bringing it to our attention.
