### ISSUE TITLE
LTM Node Monitor configuration [case 00487862]

### ISSUE THREAD

**Issue by wncocz** [F5Networks/f5-appsvcs-extension#767]
### Is your feature request related to a problem? Please describe.
We need to be able to configure monitors at the LTM node level, but that does not appear to be available in AS3.

### Describe the solution you'd like
Perhaps something like this:
```json
"icmp_30sec": {
  "class": "Monitor",
  "monitorType": "icmp",
  "interval": 30,
  "timeout": 91
},
"pool_1": {
  "class": "Pool",
  "members": [
    {
      "servicePort": 2345,
      "serverAddresses": [
        "10.10.10.11"
      ],
      "nodeMonitor" { "bigip": "/Common/icmp" }
    },
    {
      "servicePort": 2345,
      "serverAddresses": [
        "10.10.10.12",
        "10.10.10.13"
      ],
      "nodeMonitor": { "use": "icmp_30sec" }
    }
  ]
```

### Describe alternatives you've considered
We could create nodes in `/Common` manually and reference them in our declaration.
We could use `"shareNodes": true` and manually set the monitor on the nodes in `/Common`.
We could set `ltm detault-node-monitor`, but that does not allow for customization of monitors on specific nodes.

None of these are desirable.

**Comment by wncocz** [comment]
> Keep in mind that by assigning node monitors to shared nodes, you may be inadvertently affecting another user's application. If you created an ICMP monitor for a node and a network admin blocked ICMP, it would take down all applications on that node even though app health is good.

Yep, another reason to implement this Feature!

**Comment by sunitharonan** [comment]
AUTOTOOL-4308 has been created and added to our internal product backlog.
