### ISSUE TITLE
Ability to enable Load-Balancing Decision Log for GSLB_Domain_A

### ISSUE THREAD

**Issue by sagor999** [F5Networks/f5-appsvcs-extension#772]
### Is your feature request related to a problem? Please describe.
Currently as of version 3.47.0 Load-Balancing Decision Log parameters are not exposed via GSLB_Domain class.

### Describe the solution you'd like
Ability to enable each log decision individually via AS3 declaration.

### Describe alternatives you've considered
The only alternative is to enable\disable them via UI.

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.

**Comment by mdditt2000** [comment]
Please reach out to automation_toolchain_pm@f5.com so i can prioritize this request

**Comment by sunitharonan** [comment]
Thank you for reaching out,k I have created AUTOTOOL-4118 and added to ourr internal product backlog.

**Comment by RobCupples** [comment]
This was recently implemented by AUTOTOOL-4078 and will be in our next release (3.49).  AUTOTOOL-4118 will probably be internally declared as a duplicate.

**Comment by sunitharonan** [comment]
This has been fixed in AS3 3.49
