### ISSUE TITLE
Unable to add double quotes to HTTPS monitor receive string

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/f5-appsvcs-extension#773]
### Environment
 * Application Services Version: 3.40
 * BIG-IP Version: 15.1.10

### Summary
Unable to add double quotes into monitor

### Steps To Reproduce
I have this declaration for a monitor:
  "check_monitor": {
     "class": "Monitor",
     "monitorType": "https"
     "interval": 5,
     "timeout": 16,
     "send": "GET /site/health HTTP/1.1\\r\\nHost: myhost.example.com\\r\\nConnection: Close: \\r\\n\\r\\n",
     "receive": "\"status\":\"UP\"",
     "clientTLS": {"bigip": "/Common/Shared/mysslprofile"}
   },

I am trying to set receive string to: "status": "UP"

If I try to single escape the quotes, I get: status: UP
If I try to double-escape the quotes, I get a 500 error from app svcs.

How do I properly escape the quotes in my declaration so I can have them appear in my monitor?

**Comment by RobCupples** [comment]
By the way I notice you are missing a comma after "monitorType": "https".

This example below seems to accomplish what you are looking for.

```
{
  "class": "ADC",
  "schemaVersion": "3.37.0",
  "controls": {
    "class": "Controls",
    "trace": true,
    "logLevel": "debug",
    "traceResponse": true
  },
  "Tenant": {
    "class": "Tenant",
    "Application": {
      "class": "Application",
      "check_monitor": {
        "class": "Monitor",
        "monitorType": "https",
        "interval": 5,
        "timeout": 16,
        "clientTLS": {
          "bigip": "/Common/serverssl"
        },
        "send": "GET /site/health HTTP/1.1\r\nHost: myhost.example.com\r\nConnection: Close: \r\n\r\n",
        "receive": "\\\"status\\\": \\\"UP\\\""
      }
    }
  }
}
```

**Comment by pedley-f5** [comment]
The triple-escape worked, thank you!

**Comment by dstokesf5** [comment]
@pedley-f5 While it is not ideal, if we change the current escaping behavior now, we are likely to break some user's configurations. Is the current behavior and workaround proposed by @RobCupples acceptable for you?

**Comment by pedley-f5** [comment]
Yes! Actually we deployed that workaround awhile ago and are in good shape.
