### ISSUE TITLE
Ability to create/reference SNI for DNS HTTPS monitors in GSLB declaration.

### ISSUE THREAD

**Issue by 6a6d** [F5Networks/f5-appsvcs-extension#778]
### Is your feature request related to a problem? Please describe.
This feature request would allow for the create of SNI monitors for GSLB objects.

### Describe the solution you'd like
Introduced in BIG-IP v16.x, the ability to use SNI for DNS HTTPS monitors.  More information can be found in the following KB.
[SNI for your DNS HTTPS monitor ](https://my.f5.com/manage/s/article/K30633554)
AS3 should support this feature and allow for the creation/reference of SNI based HTTPS monitors in a GSLB declaration.

### Describe alternatives you've considered
The alternative to using AS3 would be to leverage the imperative REST based API to either execute TMSH commands and/or create the monitor manually.

### Additional context
Equivalent TMSH command: 
tmsh create gtm monitor https sni-monitor \
cert /Common/default.crt \
key /Common/default.key \
sni-server-name test.example.com

**Comment by sunitharonan** [comment]
Thanks for reaching out, we have created a jira AUTOTOOL-4075 for our internal tracking and added to our next sprint.

**Comment by mdditt2000** [comment]
Will be added to AS3-49. Internal build available mid Dec
