### ISSUE TITLE
Ability to override pool member health monitor via AS3

### ISSUE THREAD

**Issue by sagor999** [F5Networks/f5-appsvcs-extension#782]
Hello,

currently there is no way to override pool's member health monitor via AS3, yet this is possible to do via UI.
This setting:
![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/18602811/08cdb04d-b8bf-43ef-a143-3855fd83123e)

It probably should be exposed via `GSLB_Pool_Member_A`, to add `healthmonitor` field to it that would allow to override pool's health monitors for that specific pool member.

**Comment by sunitharonan** [comment]
Thank you for reaching out,k I have created AUTOTOOL-4119 and added to ourr internal product backlog.

**Comment by mdditt2000** [comment]
EPIC AUTOTOOL-4141

**Comment by mdditt2000** [comment]
No update on this issue. Closing out
