### ISSUE TITLE
profileHTTP2: support setting both client and server http2 profile using AS3

### ISSUE THREAD

**Issue by lavanya-f5** [F5Networks/f5-appsvcs-extension#793]
### Is your feature request related to a problem? Please describe.
Setting ingress or egress http2 profile on virtualserver is allowed currently with AS3 but setting both in the declaration throws 422 ERROR
### Describe the solution you'd like
Option to define both ingress and egress on profileHTTP2
### Describe alternatives you've considered
None
### Additional context
Example declaration
`
{
    "class": "ADC",
    "schemaVersion": "3.44.0",
    "test": {
        "class": "Tenant",
        "APPLICATION_1": {
            "class": "Application",
            "webtls": {
                "class": "TLS_Server",
                "certificates": [
                    {
                        "certificate": "webcert"
                    }
                ],
                "renegotiationEnabled": false
            },
            "tlsClient": {
                "class": "TLS_Client",
                "clientCertificate": "webcert",
							  "renegotiationEnabled": false
            },
            "service": {
                "class": "Service_HTTPS",
                "httpMrfRoutingEnabled": true,
                "profileHTTP2": {
                	"egress": {
                		"bigip": "/Common/http2"	
                	},
									"ingress": {
										"bigip": "/Common/http2"
									}
                },
                "serverTLS": "webtls",
                "clientTLS": "tlsClient",
                "virtualAddresses": [
                    "10.0.1.10"
                ]
            },
            "webcert": {
                "class": "Certificate",
                "certificate": { "bigip": "/Common/default.crt" },
                "privateKey": { "bigip": "/Common/default.key" }
            }
        }
    }
}
`

**Comment by sunitharonan** [comment]
Thanks for reaching out, have created an internal backlog item AUTOTOOL-4264. In order to prioritize this issue, please reach out to us at automation_toolchain_pm@f5.com
