### ISSUE TITLE
Add Support for Local Traffic >> Profiles >> SSL >> Client :: Notify Certificate Status to Virtual Server

### ISSUE THREAD

**Issue by j-zehnder** [F5Networks/f5-appsvcs-extension#812]
### Is your feature request related to a problem? Please describe.
The GUI supports ClientSSL setting  for "Notify Certificate Status to Virtual Server", but this is not available in TLS_Server class in AS3.

**Comment by sunitharonan** [comment]
AUtootool-4306 has been created and added to our  internal product backlog.

**Comment by Spitfire1900** [comment]
Watching for this to be released 🤞 !

**Comment by mdditt2000** [comment]
AS3-52 will be posted on GitHub next Monday

**Comment by sunitharonan** [comment]
This issue has been resolved in AS3 53.0
