### ISSUE TITLE
Update AS3 on BIG-IQ

### ISSUE THREAD

**Issue by Sakorah** [F5Networks/f5-appsvcs-extension#82]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
AS is available in the latest version of 3.9 and I can use it on the BIG-IP and as docker container. On the BIG-IQ it is in 6.1 with AS 3.7. Can AS3 be updated on BIG-IQ independently?

Greetings,
Sako

**Comment by dstokesf5** [comment]
Unfortunately AS3 can not be updated on BIG-IQ independently, and this is outside of AS3's control.

**Comment by pzoloprotonmail** [comment]
https://support.f5.com/csp/article/K54909607

> Upgrading AS3 on the BIG-IQ system
