### ISSUE TITLE
Minimum Monitors for Members in Class Pool does not support "all"

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-appsvcs-extension#827]
### Environment
 * Application Services Version: 3.50.2
 * BIG-IP Version: 17.1.1.1

### Summary
Similar to issue [#106](https://github.com/F5Networks/f5-appsvcs-extension/issues/106) but for pool members (member-specific) monitor, it's not possible to achieve "Availability Requirement = All".
- "minimumMonitors": 0    <<< no effect-> Availability Requirement = At Least 1
- "minimumMonitors": "all"    <<< AS3 deploy error

### Steps To Reproduce
1. Submit the following declaration:
```json
      "mainICAP_pool": {
        "members": [
          {
            "addressDiscovery": "fqdn",
            "autoPopulate": true,
            "hostname": "example.com",
            "servicePort": 1344,
            "priorityGroup": 5,
            "minimumMonitors": "all",
            "monitors": [
              {
                "use": "mainICAP_stby_http"
              },
              {
                "use": "icap-STBY-MD-CORE-2_https"
              }
            ]
          }

```

2. Observe the following error response:
```json
{
  "code": 422,
  "errors": [
    "/Common/Shared/mainICAP_pool/members/3/minimumMonitors: should be integer"
  ],
  "declarationFullId": "",
  "message": "declaration is invalid",

```

### Expected Behavior
I would expect that the configuration property "minimumMonitors" to be exactly the same for pool monitor and pool member monitor.
Also, I think a string "all" is OK (probably added to have a wording parity with tmsh), but integer value of 0 should also provide the same result as "all".

### Actual Behavior
Not possible to configure the pool member monitor as required.

**Comment by sunitharonan** [comment]
We have a service request for the same, I have created a backlog item AUTOTOOL-4394 and added it to our upcoming sprint. Thanks

**Comment by mdditt2000** [comment]
Planing for AS3-53

**Comment by mdditt2000** [comment]
@amolari image is available for testing. Please reach out to automation_toolchain_pm@f5.com for pre-build.

**Comment by mdditt2000** [comment]
Closed Resolved in AS3-53
Release Notes | https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.53.0
