### ISSUE TITLE
Support for APM profile dependencies

### ISSUE THREAD

**Issue by emmanuelgirard** [F5Networks/f5-appsvcs-extension#83]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.9.0-3
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```

##### SUMMARY

```
It's not possible to attach any of the APM profile depencies like websso, rba, connectivity throught any of the properties in the current version of AS3 schema.
```

##### STEPS TO REPRODUCE

```
No Properties in the AS3 Declarations to refer existing profiles.
```

##### EXPECTED RESULTS

```
Ability to refer dependencies of existing APM profile throught different AS3 Properties.
```

##### ACTUAL RESULTS

```
Failed to deploy an AS3 declaration with a policyIAM property refering an existing APM Profiles with websso, rba or connectivity dependencies.
```

**Comment by dstokesf5** [comment]
@emmanuelgirard Thank you for your feedback. I have passed along your request to the decision makers (tracked internally as 979).

**Comment by zivvel** [comment]
We also need this, and I have opened a case with F5 support.

**Comment by focrensh** [comment]
@emmanuelgirard , are you able to provide examples of a service that has the websso and rba dependency? We have connectivity coming up but I want to make sure we cover the exact use-case you have. Are you wanting to be able to reference a websso/rba (profile?) from a service before apply IAM to it?

**Comment by focrensh** [comment]
@zivvel do you have the examples/answers to the question above?

**Comment by emmanuelgirard** [comment]
@focrensh , in AS2 we were able to link APM Profiles via vs__ProfileAccess, and all dependencies via the vs__AdvProfiles properties to deliver the service.  

If I can reference existing websso/rba, rewrite, stream, profiles along the APM profile on service deployment using AS3, at least we could move from AS2 to AS3,  it would be great start.

Then we could look to build all required profiles for the services in the AS3 declaration itself in a second phase.

**Comment by focrensh** [comment]
Ok thank you for clarifying. The list of dependencies keeps growing :)

**Comment by zivvel** [comment]
I finally got around to testing this, and I don't actually see a problem.  Adding the policyIAM item to the service effectively adds the required rba/websso profiles to the virtual server.  No need to reference them directly.

**Comment by focrensh** [comment]
Interesting, so as long as the RBA/websso profiles are on the box you are able to associate an IAM policy to a service?

**Comment by zivvel** [comment]
In our case, we have a Security team that manages all things APM, and they create policies in /Common and apply them to virtuals created with AS3.  If I add policyIAM: { "bigip": "/Common/policyname" } after they apply it, it all "just works": I can remove it, re-deploy, and the APM policy and rba/websso are gone from the virtual.  I can re-add policyIAM, re-deploy, and they are back as desired.

I know we are living in the ideal world here: our source of truth is not my AS3 declaration repo.  I am trying to build playbooks to prevent our AS3 automation from colliding with their manual configuration.  Such is the real world.

**Comment by simonkowallik** [comment]
The source of Truth for your APM policy isn't AS3 anyway. So you would continue to configure the APM policy and relevant configuration objects using the WebUI. You can use the policy export+import functionality to transport them between devices or use sync only device groups. Then refer the (new) APM policy using AS3. Rba+sso profiles don't need to be configured by you. This is different for the connectivity profile, which has to be pre-configured and added to the virtual Server when the APM policy is referenced. v3.14 provides this feature.

**Comment by dstokesf5** [comment]
@emmanuelgirard and @zivvel, it sounds like there is no further work needed on this issue. I am closing this issue. If you are still encountering an issue with a specific APM policy, please create a new issue for that specific dependency. Thank you.
