### ISSUE TITLE
Declaration deployment produces an non-descriptive error message "betaOptions"!

### ISSUE THREAD

**Issue by jewettg** [F5Networks/f5-appsvcs-extension#830]
### Environment
 * Application Services Version: 3.50.2
 * f5-appsvcs				3.50.2 	Build: 3		f5-appsvcs-3.50.2-3.noarch
 * f5-service-discovery 	1.19.0 	Build: 1 		f5-service-discovery-1.19.0-1.noarch
 * BIG-IP Version: BIG-IP 17.1.1.1 Build 0.0.2 Point Release 1 

### Summary
I have F5 support also looking into this with case 00601595.  Strange "betaOptions" error presented with no other context to indicate what the failure is, when submitting the declaration.  I am using the Ansible module to deploy the declaration as follows:

```
- name: "Deploy AS3 configuration to tenant"
  f5networks.f5_bigip.bigip_as3_deploy:
    content: "{{ gh_content }}"
    tenant: Common
```

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "ADC",
    "schemaVersion": "3.37.0",
    "id": "urn:uuid:e8721eba-8d92-4b3d-a8fa-04effbcc7bc3",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "five_alive_80_vs": {
                "remark": "fivealive-n",
                "layer4": "tcp",
                "iRules": [
                    {
                        "use": "/Common/Shared/five_alive_ir"
                    }
                ],
                "translateServerAddress": true,
                "translateServerPort": true,
                "class": "Service_HTTP",
                "profileHTTP": {
                    "use": "/Common/Shared/std_http_prof",
                    "bigip": "/Common/tcp"
                },
                "profileTCP": {
                    "bigip": "/Common/tcp"
                },
                "virtualAddresses": [
                    "146.6.219.130"
                ],
                "virtualPort": 80,
                "snat": "none"
            },
            "std_http_prof": {
                "unknownMethodAction": "allow",
                "insertHeader": {
                    "name": "nsclientip",
                    "value": "[IP::remote_addr]"
                },
                "xForwardedFor": true,
                "proxyType": "reverse",
                "class": "HTTP_Profile"
            },
            "five_alive_ir": {
                "class": "iRule",
                "iRule": {
                    "base64": "d2hlbiBIVFRQX1JFUVVFU1QgewogICAgSFRUUDo6cmVzcG9uZCAyMDAgLXZlcnNpb24gYXV0byBjb250ZW50IHsKICAgICAgICA8aHRtbD4KICAgICAgICAgICAgPGhlYWQ+CiAgICAgICAgICAgICAgICA8dGl0bGU+CiAgICAgICAgICAgICAgICAgICAgU3VjY2VzcyEKICAgICAgICAgICAgICAgIDwvdGl0bGU+CiAgICAgICAgICAgIDwvaGVhZD4KICAgICAgICAgICAgPGJvZHk+CiAgICAgICAgICAgICAgICBZb3UgZm91bmQgdXMhCiAgICAgICAgICAgIDwvYm9keT4KICAgICAgICA8L2h0bWw+CiAgICB9Cn0="
                }
            }
        }
    }
}

```

2. Observe the following error response:
```json
fatal: [f5-r5900-test-a.its.utexas.edu]: FAILED! => {
    "changed": false,
    "module_stderr": "'betaOptions'",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

### Expected Behavior
Deployment of configuration to succeed.

### Actual Behavior
An odd and and very non-descriptive error message "betaOptions" is presented upon declaration deployment attempt.

**Comment by jewettg** [comment]
UPDATE:  This appears to be behavior introduced in 3.50.x versions.  I downgraded the AS3 package on my F5 to version (f5-appsvcs-3.49.0-6.noarch.rpm), and now the error message is "declaration is invalid".  
`
"msg": "{'code': 422, 'errors': ['/Common/Shared/five_alive_80_vs/profileHTTP: should be string'], 'declarationFullId': '', 'message': 'declaration is invalid'}"`

Which at least gives me a little more context, but not sure why the declaration is invalid, but will continue to troubleshoot.  

QUESTION remains, what does "betaOptions" mean, and why is that a valid error message?

**Comment by mdditt2000** [comment]
@jewettg we introduced beta options for Per-APP-API. However Per-App API went GA is version 50.

If you GET https://10.192.75.63:443/mgmt/shared/appsvcs/settings using pre as3-50 you will see betaOptions. Post 3-50 you now see

`{
    "asyncTaskStorage": "data-group",
    "perAppDeploymentAllowed": true, ----- GA "BETA-OPTIONS REMOVED
    "burstHandlingEnabled": false,
    "performanceTracingEnabled": false,
    "performanceTracingEndpoint": "",
    "serializeFileUploads": false,
    "serviceDiscoveryEnabled": true,
    "webhook": ""
}`

**Comment by mdditt2000** [comment]
@jewettg remove line 25 "bigip": "/Common/tcp" from HTTP Profile. Works fine on AS3 50. 

![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/12733938/47081477-99af-451e-a8b3-a3d2fa308b78)

Closing issue
