### ISSUE TITLE
AS3 codebase to import sys level objects

### ISSUE THREAD

**Issue by Ajit-satapathy** [F5Networks/f5-appsvcs-extension#831]
### Environment

- Application Services Version: f5-appsvcs-3.46.0-5.noarch
- BIG-IP Version: Hotfix-BIGIP-15.1.10.4.0.37.5

### ISSUE TYPE

- Feature Idea

### Summary:
We are looking for ways to import sys level iFile objects to BIGIP Devices through AS3 codebase.

We have followed below document and did not find any example in as3 format in F5 docs where iFile is getting deployed to devices. 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#ifile

**Comment by mdditt2000** [comment]
@Ajit-satapathy here is an example https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html?highlight=ifile#referencing-an-ifile-in-an-irule-declaration

**Comment by mdditt2000** [comment]
Closing this out!
