### ISSUE TITLE
A descriptive error message is needed when the delete operation for a VLAN fails.

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-appsvcs-extension#834]
### Environment
 * Product Name: rSeries 5800 / VELOS CX410
 * Base OS: F5OS
 * Base OS Version: 1.5.0-5781 / 1.6.1-19136
![Screenshot 2024-04-24 132312](https://github.com/F5Networks/f5-appsvcs-extension/assets/88710971/b3efab3f-2588-4fd6-bbd9-759d0e85964b)

### Is your feature request related to a problem? Please describe.
A VLAN is created on the F5OS device and assigned to a Tenant device. When this VLAN is deleted from the Host device, the delete operation fails and the following error is retrieved **"illegal reference 'fdb mac-table entries entry XX:XX:XX:XX:XX:XX XX tag_type_vid vlan'"**. This error is expected however the error message here does not describe the actual cause of the issue. Hence, a more descriptive error message would help the user identify and resolve the issue further. 

### Describe the solution you'd like
To have a more descriptive error message would help the user identify and resolve the issue further.

**Comment by mdditt2000** [comment]
@selinaarokiaswamy-GSLAB how is this a AS3 on Classic issue? Please submit a issue to the F5OS group. Closing
