### ISSUE TITLE
GLSB_Server Class - Allow no or NULL value for Monitor type, and not select default 'bigip' type.

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-appsvcs-extension#836]
When using the “GSLB_Server” class in an AS3 declaration, if I don’t define a monitor, the system defaults to the ‘bigip’ monitor type. But when you set the “serverType” to “generic-host”, you can’t have the ‘bigip’ monitor (since it’s not a BIG-IP device). Based on T-Mobile's config, they leave that value blank, but if I leave it blank in my declaration, we try to fill in ‘bigip’ since it's a 'default', which errors. Is there a way to define no monitors so that it doesn’t try to select the default value? I’ve tried creating the monitors sections, and leaving it blank or using NULL, but that doesn’t seem to work either, as it says the value can’t be empty. In my reference example, I had to put in a value just to get it to deploy, but ideally, I want there to be no value (and not have it use the default for when that key/value doesn’t exist).

![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/92110540/0d0cffa4-af48-46da-9235-57ec1264b7a0)

**Comment by mdditt2000** [comment]
Created AUTOTOOL-4389. Once assigned can provide timeframe for delivery

**Comment by sunitharonan** [comment]
This has been released in As3 53.0
