### ISSUE TITLE
minimumMonitors support in GSLB_Servers and GLSB_Virtual_Server classes

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-appsvcs-extension#837]
In the UI, we can set the Availability Requirements for Health Monitors at either the GSLB Server Level, or from within the Virtual Servers tab, inside the GSLB Server setup. In AS3, when trying to use the "minimumMonitors" key, AS3 errors as that is not part of the schema. Please add a way to set the Availability Requirements setting for GSLB configurations. In the BIG-IP conf file, it looks like this (in Bold):

gtm server /Common/ADMPUPT150 {
    datacenter /Common/Titan
    devices {
        /Common/ADMPUPT150 {
            addresses {
                10.148.25.44 { }
            }
        }
    }
    product generic-host
    virtual-servers {
        ADMPUPT150_VIP(10_148_25_44-8140) {
            destination 10.148.25.44:8140
            **monitor min 1 of { /Common/tcp_half_open }**
        }
    }
}

**Comment by mdditt2000** [comment]
Created AUTOTOOL-4389. Once assigned can provide timeframe for delivery

**Comment by mdditt2000** [comment]
Added AUTOTOOL-4390. Once assigned will provide ETA for release and early build

**Comment by mdditt2000** [comment]
Closed Resolved in AS3-53
Release Notes | https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.53.0
