### ISSUE TITLE
GSLB_Server - Error trying to create multiple devices

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-appsvcs-extension#839]
Referencing this page: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/GSLB_Server.schema.json.html, I am trying to create a more complex GSLB_Server configuration that has multiple devices. Basically, it looks like I have to use an array, but when I try to submit, I am having some issues.

First, If I use the following, I receive an error that it can only contain one object:

                                             "ADMPLUNIX0005": {
                                                            "class": "GSLB_Server",
                                                            "devices": [
                                                                           {
                                                                                          "address": "192.168.3.31"
                                                                           },
                                                                           {
                                                                                          “address”: “192.168.3.32”
                                                                           }
                                                            ],

{
    "id": "07145baf-c553-4246-a7e4-83714cfc3182",
    "results": [
        {
            "code": 422,
            "errors": [
                "/Common/Shared/ADMPLUNIX0005/devices: should NOT have more than 1 items"
            ],
            "declarationFullId": "",
            "message": "declaration is invalid",
            "declarationId": "TMO_GTMPOL01"
        }
    ],
    "declaration": {}
}

So, if I change the config, and put them both into the same segment, which looks like the following, I do not receive any errors on the deployment, but it will only put the last entry into my device list.

                                             "ADMPLUNIX0005": {
                                                            "class": "GSLB_Server",
                                                            "devices": [
                                                                           {
                                                                                          "address": "192.168.3.31",
                                                                                          "address": "192.168.3.32"
                                                                           }
                                                            ],

![image](https://github.com/F5Networks/f5-appsvcs-extension/assets/92110540/ae05c912-642e-4f8f-bc2e-aa2197b7fe31)

**Comment by sunitharonan** [comment]
Created AUTOTOOL-4395 and added to our backlog.

**Comment by mdditt2000** [comment]
Closed Resolved in AS3-53
Release Notes | https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.53.0
