### ISSUE TITLE
RFE: return logs of service discovery on AS3 declaration

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-appsvcs-extension#84]
##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
```
3.9.0
```

##### BIGIP VERSION
```
NA
```

##### SUMMARY
```
Currently there is API way to troubleshoot Service Discovery as deployed by AS3
```

##### EXPECTED RESULTS

We should have an option to test Service Discovery for each member group individually, to allow other members group to be actively providing pool members to the service.

I would add a an attribute to which would indicate to run the service discovery once for that given member group and return the result of the service discovery process. The log level should also be allowed to be set. It could look something like:

```
                        {
                            "servicePort": 443,
                            "addressDiscovery": "aws",
                            "updateInterval": 15,
                            "tagKey": "green",
                            "tagValue": "enabled",
                        },
                        {
                            "servicePort": 443,
                            "addressDiscovery": "aws",
                            "updateInterval": 15,
                            "tagKey": "blue",
                            "tagValue": "enabled",
                            "addressDiscoveryTest": "enabled",
                            "addressDiscoveryTestLogLevel": "info"
                        },

```

The log results should be returned with the response to the declaration.

**Comment by ansmithf5** [comment]
Good afternoon @alonsocamaro,

Thank you for your feedback. I have passed along your request to the decision makers (tracked internally as #987).

**Comment by dstokesf5** [comment]
If you query the endpoint `mgmt/shared/service-discovery/task` you should be able to see additional information about the running service discovery tasks. This includes a `lastRun` and `lastDiscoveryResult` property that provide additional information about the last attempt service discovery made to find nodes. Is this additional information sufficient for your needs?
