### ISSUE TITLE
GSLB_Monitor - Add TCP Half Open Monitor Type

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-appsvcs-extension#841]
I am currently working on a configuration that requires the use of TCP Half Open GSLB Monitor type. Currently, on our docs page https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/GSLB_Monitor.schema.json.html, it looks like our schema only includes 7 of the 29 options available in the UI, including TCP Half Open. Could this monitor type be added to the schema please.

Config from bigip.conf file:
gtm monitor tcp-half-open /Common/tcp-half-open_jirapolqat_ext {
    defaults-from /Common/tcp_half_open
    destination 10.5.14.65:443
    interval 10
    probe-attempts 3
    probe-interval 1
    probe-timeout 5
    timeout 120
}

Attempted AS3 configuration:
			"tcp-half-open_jirapolqat_ext": {
				"class": "GSLB_Monitor",
				"monitorType": "tcp-half-open",
				"target": "10.74.154.168:443",
				"interval": 30,
				"probeAttempts": 3,
				"probeInterval": 1,
				"probeTimeout": 5,
				"timeout": 120
			},

Error message received:
{
    "id": "dc4bc8c8-28ec-4fcc-8010-4f8ff1b70e9b",
    "results": [
        {
            "code": 422,
            "errors": [
                "/Common/Shared/alias-208_54_138_101-443/monitorType: should be equal to one of the allowed values [\"http\",\"https\",\"gateway-icmp\",\"tcp\",\"udp\",\"external\"]"
            ],
            "declarationFullId": "",
            "message": "declaration is invalid",
            "declarationId": "TMO_GTMPOL01"
        }
    ],
    "declaration": {}
}

**Comment by mdditt2000** [comment]
@KyleTwenty here is the Jire AUTOTOOL-4402

Issue got added to the current sprint. Will provide you with a build for testing when ready!!

**Comment by sunitharonan** [comment]
This issue has been resolved in AS3 53.0
