### ISSUE TITLE
GSLB_Monitor - Add Additional Monitor Types

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-appsvcs-extension#843]
While working to convert a configuration to AS3, I came across some additional GSLB Monitors that are not exposed in the current schema. Could the following monitors be added in a future release please:

mysql
sip
ldap
smtp

Thank you.

**Comment by sunitharonan** [comment]
Thanks for reaching out, I have added to our backlog as AUTOTOOL-4414
