### ISSUE TITLE
Can't attach PingAccess Profile to service_HTTP(S)

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-appsvcs-extension#860]
### Describe the solution you'd like
Add AS3 schema `profilePingAccess` for service_HTTP(S) classes similar to existing schema `profileAccess` that would allow customers the ability to associate Ping Access Profiles with an AS3 created virtual server. 

### Additional context
Big-IP GUI has the configuration to do this: 
<img width="638" alt="2024-07-26_10-58-02" src="https://github.com/user-attachments/assets/2b9d9d14-39db-4153-8788-99fa0241332d">

**Comment by mdditt2000** [comment]
Created AUTOTOOL-4463. Added to sprint 43-1 scheduled for end of September

**Comment by mdditt2000** [comment]
@megamattzilla AS3 3.53.0 build 2 is now available which has this fix. Reach out to me for the download

**Comment by sunitharonan** [comment]
Closing as it is fixed in AS3 3.53.0, please reach out to us for fix

**Comment by megamattzilla** [comment]
@mdditt2000 @sunitharonan  testing the schema added for this and there might be a problem. 

100% of the time AS3 authors a virtual server with `profilePingAccess` referenced the Ping Access profile doesnt work until it is manually removed/reattached to the virtual server in the F5 GUI. After that, it works fine. 

the error in the problem state: 
HTTP requests are TCP reset with reason `Internal error (APM::RBA requested abort (Failed to parse meta Header))` which goes away when we detach/attach the same profile manually in the GUI.

**Comment by mdditt2000** [comment]
Resolved in AS3-53
Release Notes | https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.53.0
