### ISSUE TITLE
Schema hosted on Github is stuck on 3.45.0 as the lastest

### ISSUE THREAD

**Issue by kyleklabunde** [F5Networks/f5-appsvcs-extension#861]
None

### Environment
 * Application Services Version: 3.51.0
 * BIG-IP Version: 16.1.3.3

### Summary
Scheme hosted on https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json is not updated to the latest release of AS3 Services extension

### Steps To Reproduce
1. Submit the following declaration:
None, 
schemaVersion": {
          "title": "Schema version",
          "description": "Version of ADC Declaration schema this declaration uses",
          "type": "string",
          "$comment": "IMPORTANT: In enum array, please put current schema version first, oldest-supported version last.  Keep enum array sorted most-recent-first.",
          "enum": [
            "3.45.0",
            "3.44.0",
            "3.43.0",
            "3.42.0",
            "3.41.0",
            "3.40.0",
            "3.39.0",
            "3.38.0",
            "3.37.0",
            "3.36.0",
            "3.35.0",
            "3.34.0",
            "3.33.0",
            "3.32.0",
            "3.31.0",
```

2. Observe the following error response:
if attempting to change the scheme version in as3 in VS code, you get brow squiggles.
```

### Expected Behavior
that i shouls be able to match up when deploying declarations to the newest i have uploaded to the LTMs

### Actual Behavior
can not use the latesr version of the schema

**Comment by JuergenMang** [comment]
I stumbled across it too. The link has changed - replace master with main.
Correct is: https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json
