### ISSUE TITLE
AS3 processing is now very long 

### ISSUE THREAD

**Issue by jrooty** [F5Networks/f5-appsvcs-extension#877]
### Environment
 * Application Services Version: 3.50
 * BIG-IP Version: 15.1

### Summary
Upgrading the AS3 version coming from 3.36 to 3.50 increases significantly the time to process the AS3 declaration.
The difference is spectacular and breaks automation.

### Steps To Reproduce
Using AS3 3.36, we have enabled the debug mode and observe the time to achieve the declaration.
We have measured the time between the validation of the declaration and the success of the parsing.

AS3 TENANT 1 (118 pools deployed)

Tue, 24 Sep 2024 08:25:12 GMT - fine: [appsvcs] {"message":"declaration is valid","level":"debug"}
Tue, 24 Sep 2024 08:25:28 GMT - fine: [appsvcs] {"message":"success parsing declaration id 141042ae-cb27-43fb-84f9-666ebf5a2066","level":"debug"}
Tue, 24 Sep 2024 08:25:28 GMT - info: [appsvcs] {"message":"parsed declaration id 141042ae-cb27-43fb-84f9-666ebf5a2066","level":"info"}

 -> 16 seconds

AS3 TENANT 2 (61 pools deployed)

Tue, 24 Sep 2024 08:21:35 GMT - fine: [appsvcs] {"message":"declaration is valid","level":"debug"}
Tue, 24 Sep 2024 08:21:49 GMT - fine: [appsvcs] {"message":"success parsing declaration id 141042ae-cb27-43fb-84f9-666ebf5a2066","level":"debug"}
Tue, 24 Sep 2024 08:21:49 GMT - info: [appsvcs] {"message":"parsed declaration id 141042ae-cb27-43fb-84f9-666ebf5a2066","level":"info"}

-> 14 seconds

2. Observe the following error response:  
Now, upgrade to AS3 3.50 and do the same operation (GET and POST the declaration)

AS3 TENANT 1 (118 pools deployed)

Mon, 23 Sep 2024 10:01:03 GMT - fine: [appsvcs] {"message":"declaration is valid","level":"debug"}
Mon, 23 Sep 2024 10:17:56 GMT - fine: [appsvcs] {"message":"success parsing declaration","level":"debug"}

 -> 16 minutes and 53 seconds

AS3 TENANT 2 (61 pools deployed)

Mon, 23 Sep 2024 14:09:09 GMT - fine: [appsvcs] {"message":"declaration is valid","level":"debug"}
Mon, 23 Sep 2024 14:17:53 GMT - fine: [appsvcs] {"message":"success parsing declaration","level":"debug"}

-> 8 minutes and 44 seconds

### Expected Behavior  
A similar time processing

All VS has an ASM policy attached (LTM + ASM)

**Comment by mkyrc** [comment]
Did you try v3.52? I'm using latest 16.x/17.x with 3.52 (previously 3.49 LTS) and in my case is everything running up to 90 seconds (I'm using python-based orchestration as AS3 generator with ansible for AS3 deployment - there's a bit of overhead).

**Comment by jrooty** [comment]
AS3 3.53 has the same behavior.  
Easy to reproduce, attach a policyWAF for each service and the AS3 processing increases a lot.  
Maybe, processing  may vary depending the hardware

**Comment by mdditt2000** [comment]
@jrooty please can you open a Service Request and set the priority

**Comment by mdditt2000** [comment]
Closing Github issue. Requesting Service Request
