### ISSUE TITLE
 adminState offline : declaration cannot be POSTed when upgrading AS3

### ISSUE THREAD

**Issue by jrooty** [F5Networks/f5-appsvcs-extension#882]
### Environment
 * Application Services Version: 3.50
 * BIG-IP Version: 15.1

### Summary
A declaration containing a poolMember configured in `offline` state using AS3 3.36 cannot be POSTed when upgrading AS3 version (e.g. 3.50).

### Steps To Reproduce
1. Install 3.36 and include this portion : 
```json

                     {
                        "servicePort": 443,
                        "adminState": "offline",
                        "ratio": 1,
                        "priorityGroup": 1,
                        "serverAddresses": [
                            "1.2.3.4"
                        ],
                        "shareNodes": true
                    },
```

2. Install AS3 3.50 and GET and POST the declaration
```json
[
    {
        "code": 422,
        "message": "declaration failed",
        "response": "01020036:3: The requested Pool Member (/TENANT1/APP_ac270b9a1e1b_fastl4_tcp_443/P_tmypool_443 /Common/1.2.3.4 443) was not found.",
        "host": "localhost",
        "tenant": "TENANT1",
        "runTime": 17188,
        "declarationId": "2ae564c4-cf02-4d18-b1db-687d3bcec0a7"
    }
]
```

### Expected Behavior
Declaration should succeed

### Actual Behavior
Break all existing declarations for all devices using offline state

**Comment by mdditt2000** [comment]
#882 has already been completed in AS3 3.52. Closing issue out
