### ISSUE TITLE
Support minus character in AS3 property name

### ISSUE THREAD

**Issue by zhaoqin-github** [F5Networks/f5-appsvcs-extension#89]
No

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION
```
N/A
```

##### BIGIP VERSION
```
N/A
```

##### SUMMARY
Can we make AS3 to support minus character '-' in its property name? We will need to use 36 characters UUID as a part of AS3 property name (eg. Pool-2e091c62-020f-49f0-a1eb-392645724a45), in order to reference to objects in other systems. If AS3 can support '-', it will be great.

```

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Please use "_"(underscore) in this case. "-"(dash) was purposefully excluded for parsing and schema reasons.

**Comment by kaustriaf5** [comment]
Hi @zhaoqin-github this is also noted in our cloud docs page. Please see https://cloudsolutions.pages.gitswarm.f5net.com/f5-appsvcs/userguide/tips-warnings.html?highlight=dash/hyphen%20(-)#notes-and-tips 

Closing this issue.
