### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-appsvcs-extension#9]
##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
n/a
```

##### BIGIP VERSION

```
n/a
```

##### SUMMARY

No source code is in this repository but there are references to source that should exist here

http://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/understanding-the-json-schema.html

specifically the schema files
```

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

Source code would be available

##### ACTUAL RESULTS

It's not available, and this makes the documentation incorrect

```

```

**Comment by JosephPJordan** [comment]
We have removed references to the location of the schema files from the reference material in the documentation on clouddocs.f5.com, As you pointed out, these files are not on GitHub.  Thanks for bringing this to our attention.
