### ISSUE TITLE
adding mblb profile to declaration

### ISSUE THREAD

**Issue by rduchez** [F5Networks/f5-appsvcs-extension#94]
##### Do you already have an issue opened with F5 support? 
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.5.1-5.noarch.rpm

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### SUMMARY

```
I want to add and MBLB profile to an application built on top of the TCP template

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```
I want to be able to create custom MBLB profiles and add them to the virtual server that is being created. 
Resulting configuration should look like (with a different partition): 
ltm profile mblb /Common/mblb_smpp {
    defaults-from /Common/mblb
    ingress-high 10000
    ingress-low 9000
    isolate-abort enabled
    isolate-client disabled
    isolate-expire enabled
    isolate-server enabled
    min-conn 0
    tag-ttl 60
}

```

##### ACTUAL RESULTS

```

```

**Comment by delgadillo22** [comment]
Added AT-251 for internal tracking.

**Comment by rduchez** [comment]
It appears that MBLB is no longer supported after the introduction of the message routing framework (MRF) - please disregard this request. I will open a new request for MRF support. 

Regards

**Comment by focrensh** [comment]
Closing in preference for #101
