### ISSUE TITLE
Feature request: Service discovery based on multiple tags

### ISSUE THREAD

**Issue by cybershoe** [F5Networks/f5-appsvcs-extension#95]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
AS3 should be able to discover pool members based on multiple tags. For instance, I should be able to define a pool that contains all instances tagged as both "webserver" AND "east-region".

Use case is for integrating AS3 into an existing environment where developers do not wish to perform a wide-scale re-tagging to support AS3.

**Comment by focrensh** [comment]
AT-263 opened internally for review.

**Comment by focrensh** [comment]
This is only looking for AND logic? Is OR needed as well?

**Comment by cybershoe** [comment]
The specific use case prompting this is AND only.

**Comment by Virenta** [comment]
We're currently looking into switching to auto-discovery pools in AWS.

This feature would really help us. Any ETA on delivery, since it's been over a year with no updates?
