### ISSUE TITLE
Cannot patch new app inside existing tenant

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-appsvcs-extension#96]
##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
```
3.10 build 5
```

##### BIGIP VERSION
```
14.1.0.3
bigiq 6.1.0
```

##### SUMMARY

```
I'm trying to use the patch method with bigiq to add another app to an existing tenant already containing a previously deployed generic template app.

I get this error when sending the PATCH: InvalidPatchOperationError: path does not exist /tenant_1/myapp2
```

##### STEPS TO REPRODUCE

```
PATCH json looks like this :

{
  "class": "AS3",
  "action": "patch",
  "target": {
    "hostname": "bigip1"
  },
  "patchBody": [
    {
      "path": "/tenant_1/myapp2",
      "op": "add",
      "value": {
        "class": "Application",
        "template": "generic",
        "statsProfile": {
          "class": "Analytics_Profile",
          "collectedStatsInternalLogging": true,
          "collectedStatsExternalLogging": false,
          "capturedTrafficInternalLogging": false,
          "capturedTrafficExternalLogging": false,
          "collectPageLoadTime": true,
          "collectMaxTpsAndThroughput": true,
          "collectClientSideStatistics": true,
          "collectResponseCode": true,
          "collectMethod": true,
          "collectOsAndBrowser": true,
          "collectUrl": true,
          "collectUserAgent": true,
          "collectUserSession": true,
          "sessionCookieSecurity": "ssl-only"
        },
        "vs_myapp2": {
          "class": "Service_HTTP",
          "virtualAddresses": [
            "10.42.10.113"
          ],
          "snat": "auto",
          "pool": "pool_myapp2"
        },
        "pool_myapp2": {
          "class": "Pool",
          "monitors": [
            "http"
          ],
          "members": [
            {
              "servicePort": 8090,
              "serverAddresses": [
                "10.1.20.130",
                "10.1.20.131",
                "10.1.20.132"
              ]
            }
          ]
        }
      }
    }
  ]
}

GET of existing app in the tenant : 

{
    "class": "ADC",
    "schemaVersion": "3.5.0",
    "id": "id_tenant_1_init",
    "target": {
        "address": "1.2.3.4"
    },
    "tenant_1": {
        "class": "Tenant",
        "defaultRouteDomain": 0,
        "init_app": {
            "class": "Application",
            "template": "generic",
            "vs_init_app": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "10.42.1.10"
                ],
                "virtualPort": 1024,
                "persistenceMethods": [
                    "cookie"
                ],
                "profileHTTP": "basic",
                "layer4": "tcp",
                "profileTCP": "normal",
                "enable": true,
                "maxConnections": 0,
                "snat": "auto",
                "addressStatus": true,
                "mirroring": "none",
                "lastHop": "default",
                "translateClientPort": false,
                "translateServerAddress": true,
                "translateServerPort": true
            },
            "schemaOverlay": "default",
            "enable": true
        },
        "enable": true
    },
    "updateMode": "selective"
}

```

##### EXPECTED RESULTS

```
I want 2 VS in one partition
```

##### ACTUAL RESULTS

```
Error, not working
```

**Comment by xbill42** [comment]
It works when using the tenant name in the declare url :
/mgmt/shared/appsvcs/declare/tenant_1?async=true

Otherwise, I think it's trying to find the first tenant already configured.
If I do a GET without specifying the tenant /mgmt/shared/appsvcs/declare, it returns the first tenant that I  created via bigiq before tenant_1.

**Comment by xbill42** [comment]
Actually, it only works for one PATCH to add an app.
If I try to patch again to add one more app I get this error :

"response": "customRule111.call(...).then is not a function",
                "status": 500

Content of the second patch json :

{
  "class": "AS3",
  "action": "patch",
  "target": {
    "hostname": "bigip1"
  },
  "patchBody": [
    {
      "path": "/tenant_1/myapp3",
      "op": "add",
      "value": {
        "class": "Application",
        "template": "generic",
        "statsProfile": {
          "class": "Analytics_Profile",
          "collectedStatsInternalLogging": true,
          "collectedStatsExternalLogging": false,
          "capturedTrafficInternalLogging": false,
          "capturedTrafficExternalLogging": false,
          "collectPageLoadTime": true,
          "collectMaxTpsAndThroughput": true,
          "collectClientSideStatistics": true,
          "collectResponseCode": true,
          "collectMethod": true,
          "collectOsAndBrowser": true,
          "collectUrl": true,
          "collectUserAgent": true,
          "collectUserSession": true,
          "sessionCookieSecurity": "ssl-only"
        },
        "vs_myapp3": {
          "class": "Service_HTTP",
          "virtualAddresses": [
            "10.42.10.213"
          ],
          "snat": "auto",
          "profileAnalytics": {
            "use": "statsProfile"
          },
          "pool": "pool_myapp3"
        },
        "pool_myapp3": {
          "class": "Pool",
          "monitors": [
            "http"
          ],
          "members": [
            {
              "servicePort": 8090,
              "serverAddresses": [
                "10.42.1.200"
              ]
            }
          ]
        }
      }
    }
  ]
}

**Comment by xbill42** [comment]
I've done more research and it looks like it's when I use service discovery with Azure.
I can only add one appsvc with a service discovery pool inside the existing tenant. After that I cannot any other app (with or without service discovery) inside the tenant with the patch method.
I get a "customRule111.call(...).then is not a function" from the bigiq.

There is no problem without service discovery, I can patch multiple times to add VS in the same tenant.

**Comment by focrensh** [comment]
Currently reviewing patch action under AT-235 internally. We will review if this solves the Service Discovery issue and follow up.

**Comment by dstokesf5** [comment]
It looks like AT-235 was completed some time ago. Closing this issue. If you are till experiencing a problem, please create a new GitHub issue.
