### ISSUE TITLE
Cannot delete appsvc deployed via bigiq when corresponding bigip is no more available

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-appsvcs-extension#97]
##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION

```
3.10.0 on bigip

```

##### BIGIP VERSION

```
14.1.0.3
bigiq 6.1.0 (as3 3.7.0)

```

##### SUMMARY

```
I had deployed some as3 app on a bigip via bigiq.
Then I deleted the bigip (test device), but I did not remove the application before, so they are still present in bigiq.

The problem is that I cannot delete these application.
The DELETE rest call returns :
 "Failed to install AppSvcs on 1 device: 1".
Cannot query package f5-appsvcs-3.7.0-6.noarch.rpm on device 10.1.2.3  (the erased bigip)

I think that's because the bigip does not exist anymore, so it cannot contact it.

Please note, that the bigip is still discovered in bigiq (but in red status), and that I cannot remove it because it says that it's used by some deployed applications (that I am trying to delete).

I'm also not able to delete the app via the bigiq GUI.

```

##### EXPECTED RESULTS

```

Is there a way to force the delete even when the bigip is not reachable from bigiq ?

```

##### ACTUAL RESULTS

```

Cannot remove existing as3 app from bigiq when the corresponding bigip is no more reachable.
Cannot remove the bigip from the discovered device in bigiq without removing deployed as3 app before.

```

**Comment by ansmithf5** [comment]
Hello @xbill42,

Currently, as far as I am aware a Big-IQ is not able to delete or remove something that it cannot currently connect to. This has been an issue I've experienced, I'll see about submitting a feature request for this.

**Comment by focrensh** [comment]
The supported/correct workflow is:
1. Delete AS3 app
2. Un-manage BIG-IP in BIG-IQ
3. Delete BIG-IP

Please loop back with with your account manager for BIG-IQ related features/requests.

**Comment by focrensh** [comment]
BIG-IQ is working on a flow to get out of this state once objects are orphaned.

**Comment by rjouhann** [comment]
For the record, BIG-IQ offer a Force-Delete API to remove the orphan objects on BIG-IQ only.

https://clouddocs.f5.com/products/big-iq/mgmt-api/v7.1.0/ApiReferences/bigiq_public_api_ref/r_as3_force_delete.html
