### ISSUE TITLE
restnoded repeatly crash in AS3 container

### ISSUE THREAD

**Issue by zhaoqin-github** [F5Networks/f5-appsvcs-extension#98]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION

```
f5devcentral/f5-as3-container          3.10.0
```

##### BIGIP VERSION

```
N/A
```

##### SUMMARY

After I starting AS3 container, its REST API never works. When I entered into the container, I noticed there were many many core files under /etc/service/restnoded, and their number was growing. The disk consumption of my container host machine was growing quickly, too. I think restnoded was repeatly crashing and restarting in AS3 container.

```
bash-4.4# ls restnoded/
core.13    core.188   core.238   core.284   core.331   core.377   core.423   core.468   core.513   core.559   core.604   core.649   core.694   core.742   core.787   core.834   core.879   core.926   finish
core.145   core.197   core.247   core.294   core.340   core.386   core.432   core.477   core.522   core.568   core.613   core.658   core.704   core.751   core.797   core.843   core.888   core.935   log
core.160   core.206   core.256   core.303   core.349   core.395   core.441   core.486   core.531   core.577   core.622   core.667   core.713   core.760   core.806   core.852   core.898   core.945   run
core.169   core.215   core.266   core.312   core.358   core.404   core.450   core.495   core.540   core.586   core.631   core.676   core.723   core.769   core.815   core.861   core.907   core.954   supervise
core.179   core.224   core.275   core.321   core.368   core.413   core.459   core.504   core.549   core.595   core.640   core.685   core.733   core.778   core.824   core.870   core.916   core.963
```

This problem occurs in some of my servers and VMs. Some others servers do not have this problem.

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

```

```

##### ACTUAL RESULTS

```

```

**Comment by zhaoqin-github** [comment]
One of restnoded core file is uploaded.

[core.13.zip](https://github.com/F5Networks/f5-appsvcs-extension/files/3165909/core.13.zip)

**Comment by zhaoqin-github** [comment]
I think the root cause should be https://github.com/nodejs/docker-node/issues/813

In my container restnoded crashes immediately after ```process.setgid(options.group);``` in /usr/share/rest/node/src/restWorkerHost.js

**Comment by focrensh** [comment]
Tracking with AT-314

**Comment by zhaoqin-github** [comment]
The latest image of f5devcentral/f5-api-services-gateway (version 1.0.11) fixes the crashing problem. Wait for AS3 to publish a new image.

**Comment by zhaoqin-github** [comment]
The iControl LX in ASG 1.0.11 can not work. Need to use ASG 1.0.12

**Comment by dstokesf5** [comment]
Since AS3 is using the latest version of ASG, I am closing this issue.
