### ISSUE TITLE
Can't create generic GSLB servers without monitor

### ISSUE THREAD

**Issue by DaanOlbrechts** [F5Networks/f5-appsvcs-extension#99]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.11.0-3
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.184.4
  Edition     Engineering Hotfix
  Date        Wed May  8 09:25:06 PDT 2019

Hotfix List
ID740228-1    ID715923-1
```

##### SUMMARY

I want to be able to declare a generic GSLB server without a monitor. When omitting the monitor attribute (or including it with an empty array as value) AS3 reverts to a default value which appears to be /Common/bigip (incompatible with the generic server type).

##### STEPS TO REPRODUCE

Deploy a new GSLB server with a basic set of parameters (including an empty array as value for the monitor attribute).

```
"generic_server":{"dataCenter":{"use":"dc1"},"serverType":"generic-host","devices":[{"address":"10.0.0.11"}],"monitors":[],"virtualServers":[{"port":9700,"address":"10.0.0.11"}],"class":"GSLB_Server"}
```

##### EXPECTED RESULTS

The generic GSLB server should be created without any monitors

##### ACTUAL RESULTS

The declaration fails due to an error with the generic GSLB server

```
        {
            "message": "declaration failed",
            "response": "01071033:3: Server (/Common/generic_server) contains monitor (/Common/bigip) which is an invalid type.",
            "code": 422,
            "host": "localhost",
            "tenant": "Common",
            "runTime": 1884
        }
```

**Comment by focrensh** [comment]
Tracking with AT-315

**Comment by DaanOlbrechts** [comment]
This was listed as fixed in the releasenotes so I tried again after upgrading. It works now! Thank you!
